### ISSUE TITLE
Packages list

### ISSUE THREAD

**Issue by TeHashX** [Entware-ng/Entware-ng#1]
There is a list of compiled packages like for optware-ng http://optware-ng.zyxmon.org/buildroot-mipsel/Packages.html or we have to build them?
Thanks

**Comment by zyxmon** [comment]
It will be ready next week.
I can upload packages without "installer" or "updater". With nearly no testing.
(armv7, armv5, x86-32, x86-64).

**Comment by ryzhovau** [comment]
HTML indexes will be available for any target, I've made all necessary scripts to build it automatically. Only two of them are available at this moment.

* http://entware.zyxmon.org/binaries/mipsel/Packages.html
* http://entware.zyxmon.org/binaries/x86-64/Packages.html

Stay tuned.
