### ISSUE TITLE
Package-request: gettext

### ISSUE THREAD

**Issue by clsalva** [Entware-ng/Entware-ng#100]
Hello, i'd need GNU gettext to compile third parties programs.

url: https://www.gnu.org/software/gettext/

src: http://ftp.gnu.org/pub/gnu/gettext/gettext-latest.tar.gz

Thank you
claudio

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-%28native-compilation%29
