### ISSUE TITLE
Problem package: unrar 5.3.8-1

### ISSUE THREAD

**Issue by sgtsquiggs** [Entware-ng/Entware-ng#103]
unrar 5.3.8-1 seems to install unrar 3.60:

```
[~] # opkg install unrar
Installing unrar (5.3.8-1) to root...
Downloading http://pkg.entware.net/binaries/x86-64/unrar_5.3.8-1_x86-64.ipk.
Configuring unrar.
[~] # which unrar
/opt/bin/unrar
[~] # unrar

UNRAR 3.60 freeware      Copyright (c) 1993-2006 Alexander Roshal
```
snipped the verbose help

**Comment by sgtsquiggs** [comment]
Hmm seems even though `which unrar` reports `/opt/bin/unrar`, it's actually calling `/usr/local/sbin/unrar`

**Comment by ryzhovau** [comment]
There is two variants of GPL `unrar`unility, but non of them are good enough. 

As for `unrar` form Entware, I've checked about dozen of different RAR archives and caught `Out of memory` message twice.:(
