### ISSUE TITLE
gcc -- wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by wiesel25** [Entware-ng/Entware-ng#105]
Hello,
Wrong ELF class ELFCLASS32 means that the libraries it has found are,
 32 bit and it is expecting 64 bit.
What is the solution ?

Thanks

uname -a
Linux QNAP 3.19.8 #1 SMP Thu Dec 24 05:52:15 CST 2015 x86_64 GNU/Linux
[/opt/simplebuild] # gcc --version
gcc (OpenWrt GCC 4.8.5) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+-------------------------------------------------------------------------------
| OSCam ver: 1.20-unstable_svn rev: 11209 target: x86_64-openwrt-linux-gnu-libusb-pcsc
| Tools:
|  CROSS    = 
|  CC       = gcc
| Settings:
|  CONF_DIR = /usr/local/etc
|  CC_OPTS  = -Os -ggdb -pipe -ffunction-sections -fdata-sections
|  CC_WARN  = -w
|  CFLAGS   = -DWITH_LIBUSB=1 -DWITH_PCSC=1 -I/opt/include/PCSC -I/opt/include/../local/include/PCSC
|  LDFLAGS  = -Wl,--gc-sections -DWITH_LIBUSB=1 -DWITH_PCSC=1 -I/opt/include/PCSC -I/opt/include/../local/include/PCSC -lz -Wl,-rpath,/opt/lib
|  LIBS     = -Wl,-Bstatic -lusb-1.0 -lrt -Wl,-Bdynamic -lpcsclite -lpthread -ldl -lrt
|  UseFlags = USE_LIBUSB=1 USE_PCSC=1
| Config:
|  Addons   : WEBIF WEBIF_LIVELOG WEBIF_JQUERY TOUCH HAVE_DVBAPI READ_SDT_CHARSETS IRDETO_GUESSING CS_ANTICASC WITH_DEBUG MODULE_MONITOR WITH_LB CS_CACHEEX CW_CYCLE
|  Protocols: CAMD35 CAMD35_TCP NEWCAMD CCCAM CCCSHARE GBOX RADEGAST SCAM SERIAL CONSTCW PANDORA GHTTP
|  Readers  : NAGRA IRDETO CONAX CRYPTOWORKS SECA VIACCESS VIDEOGUARD DRE TONGFANG BULCRYPT GRIFFIN DGCRYPT
|  CardRdrs : PHOENIX INTERNAL SC8IN1 MP35 SMARGO DB2COM STAPI STAPI5 STINGER SMART PCSC
|  Compiler : gcc (OpenWrt GCC 4.8.5) 4.8.5
|  Config   : build/x86_64-openwrt-linux-gnu-libusb-pcsc/config.mak
|  Binary   : ../archiv/oscam-svn11209-QNAP-x86_64-webif-libusb_st-pcsc
+-------------------------------------------------------------------------------
HOSTCC<>webif/pages_gen
GEN<--->webif/pages.c
./pages_gen: error while loading shared libraries: libgcc_s.so.1: wrong ELF class: ELFCLASS32
Makefile:18: recipe for target 'pages.c' failed
make[1]: *** [pages.c] Error 127
Makefile:361: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zyxmon** [comment]
Have you read wiki
https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-%28native-compilation%29
Have you set needed environment variables?

**Comment by wiesel25** [comment]
thanks

**Comment by wiesel25** [comment]
Hello ,
I have set the environment variables on a QNAP NAS andcan compile and run a simple "Hello World".
Have the same with my oscam Makefile made with the environment variables but make does not pass through.
I try it for several hours but did not find the error ...
Maybe you can give me a hint.


[/share/CS/OS] # gcc $CFLAGS $LDFLAGS helloworld.c -o helloworld
[/share/CS/OS] # ./helloworld 
Hello, World
[/share/CS/OS] # 




[/share/CS/OS/oscam-svn] # make libusb
make --no-print-directory \
	USE_LIBUSB=1 \
	EXTRA_LDFLAGS="-Wl,-rpath=/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-linux-x86-64.so.2 -L/opt/lib" \
	EXTRA_CFLAGS="-O2 -pipe -fomit-frame-pointer -fno-caller-saves" \
	
+-------------------------------------------------------------------------------
| OSCam ver: 1.20-unstable_svn rev: 11209 target: x86_64-openwrt-linux-gnu-libusb
| Tools:
|  CROSS    = 
|  CC       = gcc
| Settings:
|  CONF_DIR = /usr/local/etc
|  CC_OPTS  = -O2 -ggdb -pipe -ffunction-sections -fdata-sections
|  CC_WARN  = -W -Wall -Wshadow -Wredundant-decls -Wstrict-prototypes -Wold-style-definition
|  CFLAGS   = -O2 -pipe -fomit-frame-pointer -fno-caller-saves -DWITH_LIBUSB=1 -O2 -pipe -fomit-frame-pointer -fno-caller-saves
|  LDFLAGS  = -Wl,--gc-sections -DWITH_LIBUSB=1 -Wl,-rpath=/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-linux-x86-64.so.2 -L/opt/lib
|  LIBS     = -lusb-1.0 -lrt -lpthread -ldl
|  UseFlags = USE_LIBUSB=1
| Config:
|  Addons   : WEBIF WEBIF_LIVELOG WEBIF_JQUERY IRDETO_GUESSING CS_ANTICASC WITH_DEBUG MODULE_MONITOR WITH_LB CS_CACHEEX CW_CYCLE_CHECK
|  Protocols: CCCAM CCCSHARE
|  Readers  : NAGRA IRDETO CONAX CRYPTOWORKS SECA VIACCESS VIDEOGUARD DRE TONGFANG BULCRYPT GRIFFIN DGCRYPT
|  CardRdrs : SMART
|  Compiler : gcc (OpenWrt GCC 4.8.5) 4.8.5
|  Config   : build/x86_64-openwrt-linux-gnu-libusb/config.mak
|  Binary   : Distribution/oscam-1.20-unstable_svn11209-x86_64-openwrt-linux-gnu-libusb
+-------------------------------------------------------------------------------
GEN	webif/pages.c
./pages_gen: error while loading shared libraries: libgcc_s.so.1: wrong ELF class: ELFCLASS32
Makefile:18: recipe for target 'pages.c' failed
make[2]: *** [pages.c] Error 127
Makefile:361: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile.extra:32: recipe for target 'libusb' failed
make: *** [libusb] Error 2
[/share/CS/OS/oscam-svn] #

**Comment by zyxmon** [comment]
The recipe in wiki is not universal. You may need to modify Makefile or environment variables for some projects.
You may also need to make extra patches for sources - look here
https://github.com/Entware-ng/rtndev/blob/master/oscam/patches/001-opt_path.patch

If you do not like oscam from repo - try to crosscompile it on a linux computer. Just modify the supplied Makefile and patches. As I can see wee use cmake to compile oscam that is absent in Entware.

PS You will find an article on building packages in the wiki here.
