### ISSUE TITLE
Package Request: bacula with mysql/postgres and TLS support

### ISSUE THREAD

**Issue by Steltek** [Entware-ng/Entware-ng#106]
The existing bacula package is using sqlite (which per http://www.bacula.org/5.2.x-manuals/en/main/main/Installing_Configuring_SQLi.html isn't recommended for production).

It would be nice if there was a bacula-mysql and a bacula-postgres package (ideally also with TLS support build-in).

Alternatively: If there were source packages for mysql/postgres and openssl, one could compile these easily by installing the source pkgs.

**Comment by zyxmon** [comment]
Yes. You can build it yourself
https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources
You will need to edit Makefile for bacula - https://github.com/Entware-ng/rtndev/blob/master/bacula/Makefile
You will find it in feeds/rtndev folder
