### ISSUE TITLE
Irssi scripting support?

### ISSUE THREAD

**Issue by pagga** [Entware-ng/Entware-ng#109]
Does the Irssi build for entware-ng support scripts? I ask because the build for the older entware project did not include the perl scripting support which is usually built into Irssi,

**Comment by ryzhovau** [comment]
Looks like OpenWrt buildroot is not the finest tool for target perl dependencies, there's no other packages with perl integration. I've managed to compile new [irssi with perl support](https://github.com/Entware-ng/graveyard/commit/9f105a7df128b2ec32cfcd9315c25317574c39b1) but it's not worth of including into main feed.

I hope OpenWrt guys will find good perl package maintainer. As well as python maintainer they're got now.

Closing for now, sorry.
