### ISSUE TITLE
search egrep fgrep (Package Request?)

### ISSUE THREAD

**Issue by Mister-XY** [Entware-ng/Entware-ng#110]
Hello, i search the tools egrep and fgrep. only grep is in the grep package.

**Comment by zyxmon** [comment]
You can install busybox with grep, egrep, fgrep applets if you do not have them in your system.

**Comment by Mister-XY** [comment]
This is right, but the busybox did not run exactly like the bin files.

**Comment by zyxmon** [comment]
egrep is in fact a script, that call grep

```
#!/bin/sh
exec grep -E "$@"
```

and fgrep is

```
#!/bin/sh
exec grep -F "$@"
```

We will consider adding this scripts to grep package or making separate packages.
