### ISSUE TITLE
Error reboot/halt busybox

### ISSUE THREAD

**Issue by Mister-XY** [Entware-ng/Entware-ng#112]
Hello, i have installed Busybox but have problems with it. If i type reboot or halt via putty nothing is happen. If i uninstall the busybox, reboot/halt get good. If i remove the symlink from /opt/sbin/reboot
and /opt/sbin/halt, the commands runs very well.

**Comment by zyxmon** [comment]
I have tried to reboot one of my devices with reboot from Entware-ng busybox and it worked.
Probably there can be some sort of incompatibility in your case.
Try to install strace and run 
`strace /opt/bin/busybox reboot -d 3` - may be it will give some info on the problem

**Comment by Mister-XY** [comment]
Ok, here is the error log
-bash-4.3# strace /opt/bin/busybox reboot -d 3
execve("/opt/bin/busybox", ["/opt/bin/busybox", "reboot", "-d", "3"], [/* 18 vars */]) = 0
brk(0)                                  = 0x87000
uname({sysname="Linux", nodename="NAS540", ...}) = 0
mmap2(NULL, 409600, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x2ab43000
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x2ac94000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/opt/lib/tls/v7l/neon/vfp/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/tls/v7l/neon/vfp", 0x7ec0f690) = -1 ENOENT (No such file or directory)
open("/opt/lib/tls/v7l/neon/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/tls/v7l/neon", 0x7ec0f690) = -1 ENOENT (No such file or directory)
open("/opt/lib/tls/v7l/vfp/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/tls/v7l/vfp", 0x7ec0f690) = -1 ENOENT (No such file or directory)
open("/opt/lib/tls/v7l/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/tls/v7l", 0x7ec0f690)  = -1 ENOENT (No such file or directory)
open("/opt/lib/tls/neon/vfp/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/tls/neon/vfp", 0x7ec0f690) = -1 ENOENT (No such file or directory)
open("/opt/lib/tls/neon/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/tls/neon", 0x7ec0f690) = -1 ENOENT (No such file or directory)
open("/opt/lib/tls/vfp/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/tls/vfp", 0x7ec0f690)  = -1 ENOENT (No such file or directory)
open("/opt/lib/tls/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/tls", 0x7ec0f690)      = -1 ENOENT (No such file or directory)
open("/opt/lib/v7l/neon/vfp/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/v7l/neon/vfp", 0x7ec0f690) = -1 ENOENT (No such file or directory)
open("/opt/lib/v7l/neon/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/v7l/neon", 0x7ec0f690) = -1 ENOENT (No such file or directory)
open("/opt/lib/v7l/vfp/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/v7l/vfp", 0x7ec0f690)  = -1 ENOENT (No such file or directory)
open("/opt/lib/v7l/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/v7l", 0x7ec0f690)      = -1 ENOENT (No such file or directory)
open("/opt/lib/neon/vfp/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/neon/vfp", 0x7ec0f690) = -1 ENOENT (No such file or directory)
open("/opt/lib/neon/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/neon", 0x7ec0f690)     = -1 ENOENT (No such file or directory)
open("/opt/lib/vfp/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/vfp", 0x7ec0f690)      = -1 ENOENT (No such file or directory)
open("/opt/lib/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0,<\0\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0755, st_size=624076, ...}) = 0
mmap2(NULL, 655504, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x2ad88000
mprotect(0x2ae20000, 28672, PROT_NONE)  = 0
mmap2(0x2ae27000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x97000) = 0x2ae27000
close(3)                                = 0
open("/opt/lib/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0d=\0\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0644, st_size=49120, ...}) = 0
mmap2(NULL, 80592, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x2ab12000
mprotect(0x2ab1e000, 28672, PROT_NONE)  = 0
mmap2(0x2ab25000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xb000) = 0x2ab25000
close(3)                                = 0
open("/opt/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\370n\1\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0755, st_size=1231444, ...}) = 0
mmap2(NULL, 1234280, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x2ae29000
mmap2(0x2af51000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x128000) = 0x2af51000
mmap2(0x2af54000, 9576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x2af54000
close(3)                                = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x2aaea000
set_tls(0x2aaea4c0, 0x2aaeaba8, 0x2aaf2050, 0x2aaea4c0, 0x2aaf2050) = 0
mprotect(0x2af51000, 8192, PROT_READ)   = 0
mprotect(0x2ae27000, 4096, PROT_READ)   = 0
mprotect(0x2aaf1000, 4096, PROT_READ)   = 0
getuid32()                              = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
nanosleep({3, 0}, 0x7ec0f9d4)           = 0
sync()                                  = 0
kill(1, SIGTERM)                        = 0
exit_group(0)                           = ?
+++ exited with 0 +++

**Comment by zyxmon** [comment]
I have moved your log to pastebin. Please use pastebin for logs.
What NAS do you have? I can guess from the log
line 4 -> nodename="NAS540"
it is Zyxel NAS540. Please write here.
I have check reboot on another device and it works.
I am closing the issue. Probably it is some incompatibility. I'll reopen it if somebody confirms the problem.

**Comment by Mister-XY** [comment]
Hello, yes it's a Zyxel Nas 540.

**Comment by Mister-XY** [comment]
I have compile my own busybox and the halt reboot function are ok.

**Comment by zyxmon** [comment]
What is the difference with entware compilation - options, patches, version, kernel sources?

**Comment by Mister-XY** [comment]
i use the same compilation, i only used the start-stop-daemon patch. I Use the oficial Busybox 1.24.1 files.
Currently defined functions:
        [, [[, addgroup, adduser, arping, ash, awk, base64, basename, blkid,
        brctl, bunzip2, bzcat, cat, chgrp, chmod, chown, chroot, clear, cmp,
        cp, crond, crontab, cryptpw, cut, date, dd, delgroup, deluser, devmem,
        df, diff, dirname, dmesg, dnsdomainname, dos2unix, du, echo, egrep,
        env, expr, false, fgrep, find, flock, free, fsync, getty, grep, gunzip,
        gzip, halt, head, hexdump, hostid, hostname, hwclock, id, ifconfig,
        init, insmod, iostat, ipcalc, kill, killall, klogd, less, linuxrc, ln,
        logger, login, losetup, ls, lsmod, lsusb, lzcat, md5sum, mkdir, mkfifo,
        mknod, mkpasswd, mkswap, mktemp, more, mount, mv, nc, netstat, nice,
        nslookup, ntpd, od, passwd, patch, pgrep, pidof, ping, ping6,
        pivot_root, poweroff, ps, pwd, readlink, reboot, renice, reset, rm,
        rmdir, route, run-parts, sed, seq, setconsole, setserial, sh, sha1sum,
        sha256sum, sha3sum, sha512sum, sleep, sort, start-stop-daemon, stat,
        strings, svlogd, swapoff, swapon, switch_root, sync, syslogd, tail,
        tar, tee, test, time, top, touch, tr, traceroute, true, tty, uname,
        uniq, unix2dos, unlink, unlzma, unzip, uptime, usleep, vconfig, vi,
        watchdog, wc, wget, which, xargs, yes, zcat

**Comment by zyxmon** [comment]
What  start-stop-daemon you are speaking about?

**Comment by Mister-XY** [comment]
the patch can you find here
http://lists.busybox.net/pipermail/busybox-cvs/2014-September/034739.html

**Comment by ryzhovau** [comment]
> Hello, i have installed Busybox but have problems with it. If i type reboot or halt via putty nothing is happen. If i uninstall the busybox, reboot/halt get good. If i remove the symlink from /opt/sbin/reboot
and /opt/sbin/halt, the commands runs very well.

`Reboot`/`halt` will never be good for all embedded devices as long as they have different init systems. We won't change busybox in a favor of some NAS/router model, sorry.

**Comment by zyxmon** [comment]
@Mister-XY - I do not see any connection between patching debianutils/start_stop_daemon.c and reboot. Do you have any explanation to it?

**Comment by Mister-XY** [comment]
There is nor problem between start stop daemon and the halt error problem. 
That have i never say, that start stop daemon make any problem with reboot.

**Comment by zyxmon** [comment]
Code patch of start-stop-daemon.c does not effect reboot (halt.c)!

**Comment by zyxmon** [comment]
>> i use the same compilation, i only used the start-stop-daemon patch. I Use the oficial Busybox 1.24.1 files.
I your words are - reboot works on bustbox you've compiled.

**Comment by Mister-XY** [comment]
Thats correct but i have never say that in handle with start stop daemon.
And i say i have also patch the start-stop-daemon to use "umask" via busybox.

**Comment by zyxmon** [comment]
What is the difference between  your compilation and my compilation?
Why do you think reboot for your device works in your version of busybox? If it will not ruin reboot in other cases we can use your method for everybody.

**Comment by Mister-XY** [comment]
I don't know why my buybox get with reboot and halt. Is it possible that init is needed?

**Comment by Mister-XY** [comment]
If it possible that you compile busybox it with "Init", an "ash history" and "unlink"?
Best regard?

**Comment by zyxmon** [comment]
You can use wiki to compile it yourself. I cannot find any reasons to add init. As for ash history - it is a good idea to add - I'll try. May be unlink will be added also.
You can install `coreutils-unlink` package instead.

**Comment by Mister-XY** [comment]
I have compiled for my self. And i found that i need init fir the reboot/halt error.
And that i found in busybox

> The reboot/halt applets in busybox normally rely on the init applet being
turned on, as they just send a signal to it to trigger the reboot/halt.

> http://lists.busybox.net/pipermail/busybox/2001-November/005109.html
