### ISSUE TITLE
Packet Request: Perl Modules for PlexWatch

### ISSUE THREAD

**Issue by LennyM8472** [Entware-ng/Entware-ng#113]
Hi,

it would be great if following Perl modules can be added:
p5-libwww p5-XML-Simple p5-Time-Duration p5-Time-modules p5-DBD-SQLite p5-JSON

They are required for plexWatch (for more information http://www.sololegends.com/linux/2015/10/02/install-plex-watch-and-plex-watch-web-to-freenas-plex-plugin-jail/)

thanks
Lenny

**Comment by zyxmon** [comment]
I have written a short instruction on QNAP forum with an example showing how to install perl modules, that may require compilation.
It will be faster for you to install needed perl modules yourself.

**Comment by zyxmon** [comment]
Another solution to the problem was posted on QNAP forum. Closing.
