### ISSUE TITLE
Package Request: File::RsyncP

### ISSUE THREAD

**Issue by enko** [Entware-ng/Entware-ng#116]
Please add Perls [`File::RsyncP`](http://search.cpan.org/~cbarratt/File-RsyncP-0.52/lib/File/RsyncP.pm) because I need it to get [backuppc](http://backuppc.sourceforge.net/) running.

Thanks in Advance.

**Comment by zyxmon** [comment]
I am going to write an instruction - how to install perl modules using CPAN. I have successfully added modules that require compilation.
Compilation requires some files and packages on your device that depend on architecture. If you feel yourself experienced enough to follow it - please contact me <my_nic>@gmail.com and write your feed/architecture. I'll try to help you.

**Comment by ryzhovau** [comment]
No response.

**Comment by yoru74** [comment]
Roughly, the procedure to compile RsyncP is the following (I tested it several times in QNAPs with Intel x64 CPUs):

opkg install perl tar rsync make zip unzip samba36-client sudo
opkg install openssh-client openssh-client-utils openssh-keygen
opkg install perlbase-cpan perlbase-utf8 perlbase-cpan perlbase-universal
opkg install perlbase-unicore perlbase-term perlbase-file perlbase-archive
opkg install perl-compress-bzip2 perl-http-date perlbase-devel
opkg install perlbase-extutils perlbase-encode perlbase-json-pp perlbase-pod
opkg install perlbase-digest perlbase-perlio perlbase-dumpvalue
opkg install perlbase-filter perlbase-data perlbase-less perl-cgi
opkg install perlbase-blib perlbase-threads perlbase-mro perlbase-findbin
opkg install perlbase-compress perl-dev gcc
opkg install lighttpd lighttpd-mod-cgi lighttpd-mod-access lighttpd-mod-auth
opkg install lighttpd-mod-accesslog

mkdir /share/homes/admin/cpan
ln -s /share/homes/admin/cpan .cpan
perl -MCPAN -e shell

cpan> install File::Listing
cpan> install File::RsyncP
cpan> install CGI
cpan> exit

Verify that each install finishes with "OK". 

What follows is the installation procedure to run BackupPC's Web interface on port 81 with lighttpd running as backuppc user.

useradduseradd -m -d /share/homes/backuppc backuppc
cd ~backuppc
mkdir build
cd build
wget 'http://freefr.dl.sourceforge.net/project/backuppc/backuppc/3.3.1/BackupPC-3.3.1.tar.gz'
tar zxvf BackupPC-3.3.1.tar.gz
cd BackupPC-3.3.1
perl configure.pl --config-dir=/opt/etc/BackupPC --log-dir=/opt/var/log/backuppc

    Full path to existing main config.pl []?  Leave empty
    par2  path is EMPTY
    --> Install directory (full path)  /opt/local/BackupPC
    --> Data directory (full path)     /share/homes/backuppc/BackupPC
    --> CGI bin directory (full path)  /opt/share/www/cgi-bin
    --> Apache image directory         /opt/share/www/BackupPC
    --> URL for image directory        /BackupPC


 -m -d /share/homes/backuppc backuppc
cd ~backuppc
mkdir build
cd build
wget 'http://freefr.dl.sourceforge.net/project/backuppc/backuppc/3.3.1/BackupPC-3.3.1.tar.gz'
tar zxvf BackupPC-3.3.1.tar.gz
cd BackupPC-3.3.1
perl configure.pl --config-dir=/opt/etc/BackupPC --log-dir=/opt/var/log/backuppc

    Full path to existing main config.pl []?  Leave empty
    par2  path is EMPTY
    --> Install directory (full path)  /opt/local/BackupPC
    --> Data directory (full path)     /share/homes/backuppc/BackupPC
    --> CGI bin directory (full path)  /opt/share/www/cgi-bin
    --> Apache image directory         /opt/share/www/BackupPC
    --> URL for image directory        /BackupPC
visudo
    admin ALL=(ALL) ALL
    backuppc ALL=(admin) NOPASSWD: /bin/ping

Edit /opt/etc/BackupPC/config.pl and set:
    $Conf{PingCmd} = '/opt/bin/sudo -u admin $pingPath -c 1 -w 3 $host';

Edit /etc/group and set:
    administrators:x:0:admin,backuppc

chmod 775 /opt/var/log/backuppc/
chown backuppc:backuppc /opt/var/log/backuppc/ /opt/share/www/

Test
====
sudo -i -u backuppc
    /opt/local/BackupPC/bin/BackupPC -d
    (should be running)
    ps axuww | grep Backup
    kill xxxx yyyy  (kill BackupPC_trash and BackupPC)

If this error is shown:

Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE (\w+)}(\+?)/ at /opt/local/BackupPC/lib/BackupPC/Lib.pm line 1268.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(.*)\${ <-- HERE (\w+)}(\+?)(.*)/ at /opt/local/BackupPC/lib/BackupPC/Lib.pm line 1273.

Edit /opt/local/BackupPC/lib/BackupPC/Lib.pm as:

    Line 1264:   $arg =~ s[\$\{(\w+)}(\+?)]{
                             ^
    Line 1273:   if ( $arg =~ m[(.*)\$\{(\w+)}(\+?)(.*)] && ...
                                      ^
------------------------------------------------------------------------
Startup script (/opt/sbin/backuppc)
(after edit do: cd /opt/etc/init.d; ln -s ../../sbin/backuppc S79backuppc)
==============
------------------------------------------------------------------------
#!/bin/sh

# PROVIDE: backuppc
# REQUIRE: DAEMON
# BEFORE:  LOGIN

name="backuppc"
USER="backuppc"
MYSELF=$0

function isRunning() {
    if [ "$(ps ax | grep perl | grep BackupPC/bin/Back)" = "" ] ; then
        echo 0
    else
        echo 1
    fi
}

case "$1" in
start)
    sudo -u ${USER} /opt/local/BackupPC/bin/BackupPC -d
    echo "${name} started"
    ;;
restart)
    if [ $(isRunning) = 1 ]; then
        "$MYSELF" stop
        sleep 1
    fi
    "$MYSELF" start
    ;;
stop)
    killall BackupPC
    echo "${name} stopped"
    ;;
status)
    if [ $(isRunning) = 1 ]; then
        echo "${name} running"
    else
        echo "${name} not running"
    fi
    ;;
*)
    printf "Usage: %q {start|stop|restart|status}\n" "$0" >&2
    exit 1
    ;;
esac

exit 0
------------------------------------------------------------------------

Startup script (/opt/etc/init.d/S80lighttpd)
==============
------------------------------------------------------------------------
#!/bin/sh

ENABLED=yes
PROCS=lighttpd
ARGS="-f /opt/etc/lighttpd/lighttpd.conf"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
USER=backuppc

# . /opt/etc/init.d/rc.func

function isRunning() {
    if [ "`ps ax | grep ${PROCS}`" = "" ]; then
        echo 0
    else
        echo 1
    fi
}

case "$1" in
start)
#   sudo -u ${USER} ${PROCS} ${ARGS}
    ${PROCS} ${ARGS}
    echo "${DESC} started"
    ;;

stop)
    killall ${PROCS}
    echo "${DESC} stopped"
    ;;
restart)
    if [ $(isRunning) = 1 ]; then
        "$0" stop
        sleep 1
    fi
    "$0" start
    ;;
status)
    if [ $(isRunning) = 1 ]; then
        echo "${DESC} running"
    else
        echo "${DESC} not running"
    fi
    ;;
*)
    printf "Usage: %q {start|stop|restart|status}\n" "$0" >&2
    exit 1
    ;;
esac

exit 0
------------------------------------------------------------------------

index.html (/opt/share/www/index.html) Readable by backuppc:backuppc
==============
------------------------------------------------------------------------
<!DOCTYPE html>
<html>
<head>
<title>Backup PC</title>
<meta http-equiv="refresh" content="0; url=/cgi-bin/BackupPC_Admin.pl" />
</head>
</html>
------------------------------------------------------------------------

# Rename BackupPc_Admin to *.pl
mv /opt/share/www/cgi-bin/BackupPC_Admin /opt/share/www/cgi-bin/BackupPC_Admin.pl

# Create htdigest users
sudo -i -u backuppc
/usr/local/apache/bin/htdigest -c BackupPC.users BackupPC admin

------------------------------------------------------------------------

/opt/etc/lighttpd/lighttpd.conf
===============================
server.modules = (
    "mod_auth"
)

server.document-root        = "/opt/share/www"
server.upload-dirs          = ( "/tmp" )
server.errorlog             = "/opt/var/log/lighttpd/error.log"
server.pid-file             = "/opt/var/run/lighttpd.pid"
server.username             = "backuppc"
server.groupname            = "backuppc"

auth.backend = "htdigest"
auth.backend.htdigest.userfile = "/share/homes/backuppc/BackupPC.users"
auth.require = ( "/cgi-bin/"  => (
            "method"  => "digest",
            "realm"   => "BackupPC",
            "require" => "valid-user" ))


## enable debugging
# debug.log-request-header   = "enable"
# debug.log-response-header  = "enable"
# debug.log-request-handling = "enable"
# debug.log-file-not-found   = "enable"

index-file.names            = ( "index.php", "index.html",
                                "index.htm", "default.htm",
                                "index.lighttpd.html" )

static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
server.port                 = 81
$HTTP["url"] =~ "/cgi-bin/" {
    cgi.assign = ( ".pl" => "/opt/bin/perl" )
}

include       "/opt/etc/lighttpd/mime.conf"
include_shell "cat /opt/etc/lighttpd/conf.d/*.conf"
