### ISSUE TITLE
NUT Package - pid file can't be changed on upsd executable

### ISSUE THREAD

**Issue by davigre** [Entware-ng/Entware-ng#118]
The `pid` file can't be changed from command or .conf file but can be done through [compile](http://old.networkupstools.org/doc/1.4.1/configure.html) with 

```
--with-pidpath=PATH

   Changes the directory where pid files are stored.  By default this is
   /var/run.  Certain programs like upsmon will leave files here.
```
option.

Can be done to be `/var/run`?

This is the log of running the command:
```
/opt/etc/init.d # upsd
Network UPS Tools upsd 2.7.3
fopen /opt/var/run/upsd.pid: No such file or directory
listening on 192.168.1.1 port 3493
listening on 127.0.0.1 port 3493
/opt/var/run is world readable
Connected to UPS [jawan]: blazer_usb-jawan
/opt/etc/init.d #
```
Also if is posible in the `/opt/lib/nut/`driver-packages* also in the NUT repository.

This is the `ls` of this path:
```
/opt/var/run # ls -la
drwxr-xr-x    5 admin    root          4096 Jan 26 19:26 .
drwxr-xr-x    8 admin    root          4096 Jan  9 09:27 ..
drwxr-xr-x    2 nobody   nogroup       4096 Jan 23 09:56 avahi-daemon
srw-rw----    1 admin    root             0 Jan 26 18:44 blazer_usb-jawan
-rw-r--r--    1 admin    root             5 Jan 26 18:44 blazer_usb-jawan.pid
drwxr-xr-x    3 admin    nogroup       4096 Jan  8 11:00 cups
drwxr-xr-x    2 admin    root          4096 Jan 23 09:56 dbus
-rw-r--r--    1 admin    root             5 Jan 23 09:56 dbus.pid
-rw-r--r--    1 admin    root             5 Jan 26 19:26 upsd.pid
/opt/var/run #
```

`blazer_usb-jawan.pid` is the pid from one of the NUT-drivers-package.
`dbus.pid` is the pid from `dbus` package.

Thanks.

**Comment by ryzhovau** [comment]
> Can be done to be `/var/run`?

Why it should be changed? `/opt/var/run` is a place of pid-files for all other services.


> Also if is posible in the `/opt/lib/nut/`driver-packages* also in the NUT repository.

Is `\opt\lib\nut` path is wrong?

**Comment by ryzhovau** [comment]
No response.
