### ISSUE TITLE
Could not install entware arm on android TV clone

### ISSUE THREAD

**Issue by rodoviario** [Entware-ng/Entware-ng#120]
Followed the wiki and found some caveats:

It didn't worked for me out of the box on a google tv clone, a RK3188 based one.
I added to the steps su to gain Super User access (accepted on the TV) and all worked before the script.

In the script part, it says 2 errors about Bad File Mode. Both of them corresponds to chmod +x 2 files.

When I try to do it myself step by step following the script, it says that in the chmod part.

But if I use /usr/xbin/chmod (the one from the busybox that I installed), it apparently succedes... but even doing so by hand, I am not able to run opkg.

I will try in other (older) google TV clone, also based on the RK chip and report.
¿any suggestions? - I am very eager to install entware there, because it is always on, it has a screen and audio (vs the one that I have on the ASUS Router), and it has a bigger and faster procesor.

Sorry if it looks more like a forum post, may be it is not a bug at all in the installer nor the entware-ng. Please, if there is an english forum for entware-ng... arm feed, I happly go there to research and to write about the testing I do with it.

**Comment by zyxmon** [comment]
I have install Entware (not Entware-ng) on  RK3188 based TV stick.
Here is my old instruction in Russian - http://www.zyxmon.org/2015/03/21/ustanavlivaem-entware-arm-na-android/ (try google translator).

**Comment by rodoviario** [comment]
Thanks man, I actually remember seeing that post on XDA (or a similar one) so I think that there is a good place to report and ask instead of here in the bug section of github repo, so I will move there and report. I will mix and match data on your post with the info on the wiki and the arm script itself to see if it goes thru. I also will research about using dropbear instead of SSHDroid.

Thank for the quick response. I will close mi inquiry here for the moment.
