### ISSUE TITLE
rutorrent: Hash check on download completion found bad chunks, consider using "safe_sync

### ISSUE THREAD

**Issue by Criton** [Entware-ng/Entware-ng#121]
I get the following error message on entware-ng rutorrent : " Hash check on download completion found bad chunks, consider using "safe_sync"." If I enable safe_sync then the same issue. Router is AC87U with 380.57.2_HGG-FINAL firmware.

Any idea?

**Comment by ryzhovau** [comment]
IMHO, better to start from f\s checking.

**Comment by Criton** [comment]
?

**Comment by ryzhovau** [comment]
Check file system on USB storage for errors.

**Comment by Criton** [comment]
No error could,  file system is ext4

**Comment by zyxmon** [comment]
I have checked rutorrent on tomato (broadcom arm based router similar to AC87U + ext2 usb) and found no issues. So it is not a problem with entware/rutorrent, it is a problem with your system. Try other usb storage with ext2/3.
Closing.

**Comment by Criton** [comment]
If somebody has the same issue on AC87U with entware-ng, then the solution is desabling usb 3.0 reduce and the issue is gone. So this issue is now solved.
