### ISSUE TITLE
Samba utils

### ISSUE THREAD

**Issue by shunjou** [Entware-ng/Entware-ng#122]
Coming from optware, I was used to having the command `smbstatus` to check on the status of my samba server. After installing the latest samba36-server package using entware on my armv5 device, I noticed that it is slimmed down to where commands are linked to a single samba_multicall binary. This multicall however only includes the commands `smbd nmbd smbpasswd` and omits the very useful utilities of the full package. Is it possible to have the missing functionality restored to the samba36 server package or perhaps have an additional utility package made available? I found [this patch](https://github.com/tobiaswaldvogel/openwrt-addpack/blob/master/samba4/patches/110-multicall.patch) for multicall but it seems to pertain to samba4 so I am not sure how useful it would be.

**Comment by ryzhovau** [comment]
Not sure we going to change OpenWrt SAMBA package without serious reasons.

**Comment by zyxmon** [comment]
All needed utils are compiled, but not installed (standard owrt policy). They can be found in source3/bin folder.
@shunjou - please test if this works for you - http://pkg.entware.net/binaries/armv5/test/smbstatus and report back. Do not forget chmod +x.

**Comment by shunjou** [comment]
@ryzhovau Would a complimentary samba36-utils package then not be possible?

@zyxmon It works great. Thanks.

**Comment by ryzhovau** [comment]
`smbstatus` is a part of `samba36-server` now. MIPSEL binaries will arrive in the next few days.
