### ISSUE TITLE
Package Request: minidlna-rescan-thumbnail

### ISSUE THREAD

**Issue by Criton** [Entware-ng/Entware-ng#123]
Please add minidlna-rescan-thumbnail

**Comment by zyxmon** [comment]
Minidlna with fast rescan, thumbnail generator, custom icon and other goodies is in the repo from October 2015.

**Comment by esousra** [comment]
Somehow I can't seem to find this in the repo. Maybe I'm looking in wrong place? :) http://pkg.entware.net/binaries/mipsel/Packages.html

**Comment by ryzhovau** [comment]
http://pkg.entware.net/binaries/mipsel/minidlna_1.1.5-1a_mipselsf.ipk is what you are searching for:)

**Comment by esousra** [comment]
Ah I see, thanks!
