### ISSUE TITLE
Package Request: Unison

### ISSUE THREAD

**Issue by allaboutsec** [Entware-ng/Entware-ng#124]
Hi,

can anyone add: http://www.cis.upenn.edu/~bcpierce/unison/

Source package: http://www.seas.upenn.edu/~bcpierce/unison//download/releases/stable/unison-2.48.3.tar.gz

thx

**Comment by ryzhovau** [comment]
As long as `golang` is not ready for cross-compiltaion, I'm afraid, no.
You may try a static version from [here](http://files.lancethepants.com/Binaries/unison/).

**Comment by dugwood** [comment]
See: https://github.com/Entware-ng/Entware-ng/issues/477#issuecomment-316628740
