### ISSUE TITLE
Entware-ng and OpenWRT

### ISSUE THREAD

**Issue by mattheweli** [Entware-ng/Entware-ng#126]
This is not an issue but a question really:is it possible to install Entware-NG in OpenWRT? The rwason is the not manteined packages on OpenWRT I instead found on Entware-NG

**Comment by zyxmon** [comment]
I think it is possible. You must create a script in openwrt that symlinks or mount-binds /opt to the folder on usb strorage ant runs the script /opt/etc/init.d/rc.unslung
