### ISSUE TITLE
Package Upgrade: shadowsocks-libev from 2.4.1 to 2.4.5

### ISSUE THREAD

**Issue by steve3d** [Entware-ng/Entware-ng#127]
Recently entware-ng upgraded libsodium, but shadowsocks-libev depends on it, so current version of 2.4.1 won't work because no libsodium.so.17 (current version of libsodium has libsodium.so.18)

So please upgrade shadowsocks-libev to latest version.

**Comment by zyxmon** [comment]
done - https://github.com/Entware-ng/entware-packages/commit/5d4702ca0b129ddf0babf9c9dd7eef281670745f

will be in binary repos in a couple of days
