### ISSUE TITLE
Package upgrade request - Mosquitto client

### ISSUE THREAD

**Issue by kalo8450** [Entware-ng/Entware-ng#129]
The default setting for compiling mosquitto disables the websockets protocol.  Lots of applications use websockets for MQTT so it would be very helpful the have a version with websockets enabled.

kalo

**Comment by ryzhovau** [comment]
Done. Please, reinstall package to take effect.

https://github.com/Entware-ng/entware-packages/commit/453ec94134e7f365501dde1af076c9b37c0500b9
https://github.com/Entware-ng/Entware-ng/commit/2eac45c0b190beded11c84ab0bd470770f0b5e59
