### ISSUE TITLE
No root with OpenSSH

### ISSUE THREAD

**Issue by Mister-XY** [Entware-ng/Entware-ng#131]
Hello, i'm using on my NAS540 from Zyxel Openssh (ssh and SFTP server) via OPKG. If i want to Login, i have access. But i have only access via "admin"  But i wan't login via root. 
But i i do this, Openssh ask for my passwort. I enter my root passwort and it's say, it is wrong. I have also changed my root password via Admin access "sudo passwd root" but is has no effect. he also ask for the password.
i have also change the Line PermitRootLogin without-password to #PermitRootLogin without-password.
Is has also no effect.

**Comment by zyxmon** [comment]
On QNAP you can login as admin (with root rights) only with `PermitRootLogin yes` in configuration. It is device specific. The only thing that can be theoretically implemented is to separate Entware and device users (Entware users have no connection with device users and have there own logins/passwords). I have checked this approach with previous Entware.arm repo and android and with some mipsel devices. I am not sure it is needed for your device.

**Comment by Mister-XY** [comment]
I Think, thats's wars the solution
PermitRootLogin yes
