### ISSUE TITLE
Package Request: vblade (AoE Target)

### ISSUE THREAD

**Issue by lars18th** [Entware-ng/Entware-ng#132]
Hi,

In the old days of optware, the VBLADE tool is present: http://manpages.ubuntu.com/manpages/oneiric/man8/vblade.8.html
If you found AoE a quite old protocol think on this:

* For running the Target, you only need a user-space target tool (vblade). _This tool don't have any requirement about kernel support or third party libraries_.

* For running the Initiator, you only need to use the kernel driver already included in kernel from 2.x. If your current kernel don't have the driver compiled, then you can compile an standalone version.

* This protocol can be very useful for exporting ANY block device (HD, partition, etc.) from a system booted with a Linux LiveCD.

So, I found it very useful for HD recovery and other admin tasks.

I suggest to include it. All the info you need for creating the package is here:

- Sources homepage (original): http://sourceforge.net/projects/aoetools/files/vblade/
- Sources homepage (github): http://github.com/OpenAoE/vblade
- Old Optware page: http://www.nslu2-linux.org/wiki/Optware/Vblade
- Opwate Makefile: http://github.com/keestux/optware/blob/master/make/vblade.mk

So, I hope someone likes to create the package.
Thank you!

PD: Additional info (not required by vblade, it's only for run the INITIATOR AoE):
- Kernel driver (backported): http://github.com/OpenAoE/aoe

**Comment by zyxmon** [comment]
Kernel drivers cannot be part of entware. Entware is device independent.
Can vblade be launched without kernel driver?

**Comment by lars18th** [comment]
Sure! Vblade is **completly** kernel free. This is the reason for ask to include it in entware.

**Comment by zyxmon** [comment]
Why have you included sources to kernel module that cannot be part of Entware?

**Comment by lars18th** [comment]
Hi @zyxmon ,

> Why have you included sources to kernel module that cannot be part of Entware?

To comment that if you like to use the INITIATOR side, then you can compile the kernel module if you don't have the module in your stock kernel. This is only _additional information_. The vBlade tool is the TARGET part of the tool, and it's completly standalone.

I feel you never have working with AoE. It's like iSCSI, but more simple. The vBlade tool is very powerful because is: user-level, don't need any kernel support, not depends on external libraries. Then is perfect to put in inside "entware".

Please, review the MAKEFILE for Optware. I feel will be easy for you port it.
Regards!

**Comment by ryzhovau** [comment]
Done.

**Comment by lars18th** [comment]
Thank you! ;)
