### ISSUE TITLE
znc & adb

### ISSUE THREAD

**Issue by MrDini123** [Entware-ng/Entware-ng#134]
Hi!

I've just installed the entware to my zyxel nas. It works nice, but I Can't start the znc. When I try to start it, with /opt/etc/init.d/S99zncs start it says started, but when i check it no znc proccess will show up...

It also says _chmod 666 error missing options_.

What's wrong?

Second:

Can you compile the adb package to entware?

Thanks for UR answer!

Ps: I have an arm5 based nas.

**Comment by zyxmon** [comment]
Try to start znc without a script to get some error reports/logs.

**Comment by MrDini123** [comment]
It works manually.

**Comment by zyxmon** [comment]
Try to modify the strartup script and write here - what was the problem.
Closing - it works!
