### ISSUE TITLE
unfs3 & NFS kernel server

### ISSUE THREAD

**Issue by Mister-XY** [Entware-ng/Entware-ng#135]
Hello, i have a small Problem with these two tools. With unfs3 i don't see my NAS in my kodi system and with the NFS kernel server i see my NAS in my Kodi System. But in both cases i can't connect to the shared folder.
with the Original Firmware from Zyxel (NAS 540) i have these in my exports file.
"/i-data/3976460a/video *(ro,sync,no_subtree_check,wdelay,no_root_squash) # Video"
and if i copy it to the /opt/etc/exports it did not help. I have also no access to the NFS mount.

**Comment by zyxmon** [comment]
We do not have Zyxel (NAS 540) to test. As for unfs3 - it does have compatibility problems. As for kernel server - try other options to mount and export, change startup script to something like
https://github.com/zyxmon/zyxel-keenetic-packages/blob/master/package/built/nfs-kernel-server/files/K20nfsd - I have tested nfs kernel server with this type of script recently - it worked for me,

**Comment by Mister-XY** [comment]
Ok, how look your line in unfs3?

**Comment by zyxmon** [comment]
If some client does not "see" unfs3 - it cannot be fixed. Try nfs kernel server if you have appropriate kernel modules. Google for solution.

**Comment by Mister-XY** [comment]
Hello, a short feedback back from me. Is it possible, that your nfs kernel server look in /etc/services ?
Because some devices did not have this file. 
But there is a small solution. 
I have create a directory called "nfs" in /opt/etc and make a file "services" with following content
`nfs        2049/tcp
nfs        2049/udp`
After that, i edit my S57nfs-kernel-server in /opt/etc/init.d
and add following lines in that script
`	# look for services file in /etc
	if [ ! -d /etc/services ] ; then
		ln -s /opt/etc/nfs/services /etc/services
	fi`
under
`func_start()
{`

**Comment by ryzhovau** [comment]
> Hello, a short feedback back from me. Is it possible, that your nfs kernel server look in /etc/services ?
Because some devices did not have this file. 

This is a part of POSIX specification.

Even with r/o `/etc` there is a way to `mount -o bind /opt/something /opt/etc` to fix it.
