### ISSUE TITLE
libfuse compile ... no rules

### ISSUE THREAD

**Issue by father-mande** [Entware-ng/Entware-ng#136]
Hi,

To integrate some program as new package (working in Entware when just savagely patched ... )
I need libfuse ...
I have for test create a x64 Entware dev. under a VM Ubuntu 14.04 64 bits (up to date)
... all is OK including making compile for some tools (tmux like in your wiki page for ex.)
BUT libfuse seem to be unknown ... no rules to compile ... no sources ...
libfuse ipkg is present in x86_64 feeds when we install it in a client system ?

So what I have to do to get the corresponding source and rules ... BUT perhaps I have not understand something ... I am new in Entware ... even if before (long time ago) I have work to do change in Optware
Philippe.

**Comment by zyxmon** [comment]
libfuse is part of Entware and is already in the binary repo.
It is here - https://github.com/Entware-ng/Entware-ng/tree/master/package/utils/fuse

PLS note - the Entware is in the stage of monthly updates - it may fail to compile (only few days).
