### ISSUE TITLE
Package Request: python3

### ISSUE THREAD

**Issue by shantanugoel** [Entware-ng/Entware-ng#137]
It seems that the package exists in the repo but is not compiled (at least for mips routers). Is it possible to make python3 available?

**Comment by thunfischbrot** [comment]
I am interested in the python3-package as well, regarding https://github.com/Entware-ng/Entware-ng/issues/142

**Comment by tolbard** [comment]
Also interested

**Comment by kolyagora** [comment]
+1

**Comment by nkotak1** [comment]
+1

**Comment by zyxmon** [comment]
Done - https://github.com/Entware-ng/entware-packages/commit/1b54f224b0e5a40fa8812c808f724f66dc831c8c
