### ISSUE TITLE
Package Request: hplip-3.15.9

### ISSUE THREAD

**Issue by chanchaktong** [Entware-ng/Entware-ng#139]
There is a problem(mdns_probe_nw_scanners) in hplip-3.15.11 so that I can not use it with "scanimage -L". 
Could you please provide hplip-3.15.9?

https://bugs.launchpad.net/ubuntu/+source/xsane/+bug/1521694

**Comment by zyxmon** [comment]
@chanchaktong - what is your feed (architecture)? I can build 3.15.11 with a patch for you to test.

**Comment by chanchaktong** [comment]
@zyxmon mipsel

**Comment by zyxmon** [comment]
@chanchaktong - please try this one and report
http://pkg.entware.net/binaries/mipsel/test/hplip_3.15.11-2_mipselsf.ipk

**Comment by chanchaktong** [comment]
@zyxmon Thanks. It works now!

/opt/home/admin # scanimage -L
device `hpaio:/usb/Deskjet_F2400_series?serial=CN97B1S2GQ05H4' is a Hewlett-Packard Deskjet_F2400_series all-in-one

**Comment by zyxmon** [comment]
Fixed in https://github.com/Entware-ng/entware-oldpackages-ports/commit/6c56180fe2b2fc7ad73d5edca9642e89c84bb9e9
closing
