### ISSUE TITLE
aufs or unionfs

### ISSUE THREAD

**Issue by francesco2013** [Entware-ng/Entware-ng#140]
Hello guys,

Would you be able to provide me the package aufs or any other implementation of Unionfs ? I would need to export with NFS a single share  containing the sum of the drives I have in my Zyxel NAS540.

Thank you very much in advance.

Francesco Fazio

**Comment by zyxmon** [comment]
Entware does not have kernel drivers in repo that are specific for devices.

**Comment by francesco2013** [comment]
I understand thanks.
