### ISSUE TITLE
fuse.mhddfs 

### ISSUE THREAD

**Issue by francesco2013** [Entware-ng/Entware-ng#141]
Hello,

Would you be able to provide fuse.mhddfs for Entware ?

I understand you dont have kernel drivers specific for the devices but this is fuse mhddfs.

It would be really amazing if I could have it running. 

Thanks in advance.

Francesco Fazio

**Comment by ryzhovau** [comment]
What device are you using?

**Comment by francesco2013** [comment]
Zyxel NAS540

**Comment by francesco2013** [comment]
hello ? any news ?

**Comment by ryzhovau** [comment]
I see no sense to add it for MIPS devices,sorry.
 Now it's up to @zyxmon.

**Comment by ryzhovau** [comment]
No plans to add it, sorry.
