### ISSUE TITLE
Package Request: Borg Backup

### ISSUE THREAD

**Issue by thunfischbrot** [Entware-ng/Entware-ng#142]
Is anyone else interested in having [Borg Backup ](https://github.com/borgbackup) as a package?

It offers deduplicated, encrypted backups and is very quick in doing incremental updates-it only send actually changed data blocks. It deals well even with low bandwidth and repeated changes to large files.

**Comment by ryzhovau** [comment]
Not sure it's necessary to add another backup solution to repo. There is `rsnapshot`, `rdiff-backup` and `bacula` (last on is for Intel/ARM only).

**Comment by zyxmon** [comment]
Let us wait for more requests on this package. I am also not sure it is needed.
Closing.

**Comment by vandendal** [comment]
Bacula is closed source in the interesting parts. Bareos is fully AGPL.

**Comment by ikog** [comment]
I would like to put another request for the borgbackup. Some people call it "the holly grail of backup solutions". I also like it very much.

**Comment by zyxmon** [comment]
borgbackup needs python3. There is no python3 now in entware!

**Comment by thunfischbrot** [comment]
Borg Backup (and attic) fulfill some needs which the existing packages don't. Incremental, encrypted (also at rest), de-duplicated, chunk-based remote backups are what Borg Backup offers in one simple package. Backups can be easily mounted and used as a simple filesystem. It would really be great if we could include it.

Would it be possible to employ Python freeze in order to create a Borg Backup package without depending on an entware python3-package?

See e.g. https://wiki.archlinux.org/index.php/Synchronization_and_backup_programs#Single_machine https://borgbackup.readthedocs.org/en/stable/ http://librelist.com/browser/attic/2014/1/31/attic-vs-obnam/ and https://www.reddit.com/r/linux/comments/42feqz/i_asked_here_for_the_optimal_backup_solution_and/czbeuby for more detailed pros and cons.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/Entware-ng/issues/851
