### ISSUE TITLE
Package request: Exim

### ISSUE THREAD

**Issue by sieghardGitHub** [Entware-ng/Entware-ng#144]
Would be nice to the opportunity to set up a Exim-Dovecot mailserver on a ARMv5 Qnap NAS.

**Comment by zyxmon** [comment]
Two variants of dovecote (with/without mysql support) are in repo fro a long time. I have made exim package for testing a year ago and go no response. Probably I'll try to build exim once more later.

**Comment by ryzhovau** [comment]
We kept it open for several months, there is no other request nether here, nor on forums. Closing for now.
