### ISSUE TITLE
Support request: postfix 3.0.1-2

### ISSUE THREAD

**Issue by sieghardGitHub** [Entware-ng/Entware-ng#145]
Recently I installed the postfix package 3.0.1-2 on my Qnap NAS (ARMv5, TS-119P+). Starting postfix raises a lot of errors about missing directories and files. Some issues could be fixed with a symlink, but a 1:1 comparision with a vanilla postfix installation on a current Linux Mint showed am great number of files that are missed in the entware-ng package (e.g. divers 'libpostfix-...' shared libraries).

Could you please check if the package postfix_3.0.1-2_armv5soft.ipk is brocken?

Thanks for your help!
Sieghard

**Comment by zyxmon** [comment]
This is normal (number of files can be less) - openwrt minimizes the size of the package putting only essential files in ipk and using special compilation options. Entware follows openwrt approach.
As of errors on missing directories and files - I have started posfix on ARMv5 QNAP TS-121 and do not have such errors. Put I have not configured postfix.

```
[~] # /opt/etc/init.d/S69postfix start
starting service postfix
postfix: warning: smtputf8_enable is true, but EAI support is not compiled in
postfix: fatal: file /opt/etc/postfix/main.cf: parameter mail_owner: unknown user name value: postfix
```

I guess postfix user must be added to the system by adduser in console ore in web gui. Configuration files must be changed for further tests.
