### ISSUE TITLE
Issue using Oscam

### ISSUE THREAD

**Issue by ksya** [Entware-ng/Entware-ng#146]
I have a Asus AC66U and a TBS3102 card reader which I want to use with Oscam on the router. Oscam works, but it does not read the reader correctly. I constantly get these log entries:
```
2016/01/30 15:58:03 4D0AA093 r (reader) Ziggo [mouse] Flush readed byte Nr 75 value 01 time_us 19725
2016/01/30 15:58:03 4D0AA093 r (reader) Ziggo [mouse] Flush readed byte Nr 76 value 60 time_us 47
2016/01/30 15:58:03 4D0AA093 r (reader) Ziggo [mouse] Flush readed byte Nr 77 value 01 time_us 9691
2016/01/30 15:58:03 4D0AA093 r (reader) Ziggo [mouse] Flush readed byte Nr 78 value 60 time_us 46
2016/01/30 15:58:03 4D0AA093 r (reader) Ziggo [mouse] Flush readed byte Nr 79 value 01 time_us 19712
2016/01/30 15:58:03 4D0AA093 r (reader) Ziggo [mouse] Flush readed byte Nr 80 value 60 time_us 49
2016/01/30 15:58:03 4D0AA093 r (reader) Ziggo [mouse] Flush readed byte Nr 81 value 01 time_us 9756
2016/01/30 15:58:03 4D0AA093 r (reader) Ziggo [mouse] Flush readed byte Nr 82 value 60 time_us 47
2016/01/30 15:58:03 4D0AA093 r (reader) Ziggo [mouse] Flush readed byte Nr 83 value 01 time_us
```

It goes on from Nr 1 to Nr 255 and starts again, infinitely. I tried rebuilding Oscam, but this version also failed the same way. I used to run Oscam on OpenWRT with the same card reader, which worked great!

Someone knows what's wrong?

I already tried other AsusWRT-Merlin version, no success. By the way, the TBS3102 reader is a FTDI device

**Comment by ryzhovau** [comment]
I have neither card reader nor subscription to reproduce that, sorry.
All I know is oscam package was proven as working by some number of users. There's nothing I can do about this issue, so I'm closing this for now.
