### ISSUE TITLE
Package Request: Grive2

### ISSUE THREAD

**Issue by mithron** [Entware-ng/Entware-ng#147]
Hello. Grive is google drive command-line app. Grive is currently abandoned, but there is a maintained fork https://github.com/vitalif/grive2 .

I think having it in wrt routers is very good for off-site backup purposes. Can its dependencies be compiled for wrts?

yajl 2.x
libcurl
libstdc++
libgcrypt
Boost (Boost filesystem, program_options, regex, unit_test_framework and system are required)
expat

There are also some optional dependencies:

CppUnit (for unit tests)
libbfd (for backtrace)
binutils (for libiberty, required for compilation in OpenSUSE, Ubuntu, Arch and etc)

**Comment by monosoul** [comment]
+1

**Comment by zyxmon** [comment]
Done. Only for glibc (arm & intel) because of https://github.com/vitalif/grive2/issues/78
https://github.com/Entware-ng/rtndev/commit/98d13899a867ffc3e4a37e3bd74cf2e01475ecaf

Binaries will arrive soon.

**Comment by zyxmon** [comment]
Mipsel is also added.

**Comment by monosoul** [comment]
Awesome, thanks!
