### ISSUE TITLE
Restore asterisk18-chan-gtalk and asterisk11-chan-motif packages

### ISSUE THREAD

**Issue by fktpa813** [Entware-ng/Entware-ng#149]
Please enable packages asterisk18-chan-gtalk and asterisk11-chan-motif to be built by default.
They are disabled in Entware (since this commit: https://github.com/Entware/entware/commit/69eedcd99b94a55a37879c1fe45c04f8c75788e8), but they have been since restored in upstream a while ago: openwrt/telephony@7fb39ad.

To restore packages in Entware, the following settings should be changed in all configs/*.config files:
CONFIG_PACKAGE_asterisk11-chan-motif=m
CONFIG_PACKAGE_asterisk11-res-xmpp=m
CONFIG_PACKAGE_asterisk18-chan-gtalk=m

Thank you!

**Comment by zyxmon** [comment]
Done:
https://github.com/Entware-ng/Entware-ng/commit/2f879067e146ab36cb45880448ad681c01b2c577
Binaries will be available soon.
