### ISSUE TITLE
Restore asterisk18-chan-gtalk and asterisk11-chan-motif packages for MIPS

### ISSUE THREAD

**Issue by fktpa813** [Entware-ng/Entware-ng#151]
The asterisk18-chan-gtalk and asterisk11-chan-motif packages were re-enabled for ARM and Intel platforms ( 2f87906 ) in response to issue #149. Please make the same change for MIPS as well in configs/mipselsf.config:
CONFIG_PACKAGE_libiksemel=m
CONFIG_PACKAGE_asterisk11-chan-motif=m
CONFIG_PACKAGE_asterisk11-res-xmpp=m
CONFIG_PACKAGE_asterisk18-chan-gtalk=m

Thanks!

**Comment by ryzhovau** [comment]
Dup of https://github.com/Entware-ng/Entware-ng/issues/149
