### ISSUE TITLE
Some problem about start and package

### ISSUE THREAD

**Issue by Jorman** [Entware-ng/Entware-ng#154]
Hi, until yesterday I used optware, but I want to move on and I removed optware and installed entware-ng, but first I exported the old ipkg list and the requiment from python. I've one qnap TS-269L and my arch is x86_64

But I've some "problem", maybe are not problem and it's normal but, better to ask to some more expert that me!

1st problem:
I removed optware, but after a restart I've again the optware folder under .qpkg but no app optware installed via the app center. I've more that one app installed but I don't think that one of those app can make the almost full structure of optware folder.

2nd problem:
I use Qmono, Jacket, Qsonarr ... and before entware all the symbolic link for the folder was placed under /opt that point under .qpkg/optware.
Now with entware, seems that Qmono and others run before the entware and I found all the symbolic links not under /opt but under .qpkg/optware, but I think that is wrong because the right opt folder must be .qpkg/entware. This explain better the situation
Now with entware, after a restart, I found the Qmono links under
/share/CACHEDEV1_DATA/.qpkg/Optware
and not under
/share/CACHEDEV1_DATA/.qpkg/Entware-ng

3rd problem:
I need to install python cffi package, but the *dev package are not on the repo, so I cant install cffi or cryptography package, there is any way to have the stuff to compile with the nas? I tried to follow this, https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-%28native-compilation%29, but I don't know what I've to put under Environment, because I've one x86_64 and I'm not so expert to know how I've to put in the script

4th problem:
Some my old script don't works anymore and I don't know why, for example I've a simple pushover script that don't works, seems that don't recognize some command but the script is always the same use getopts and curl functions but don't works anymore.

Do you've some idea?

J

**Comment by zyxmon** [comment]
I do not think it is a good idea to ask a lot of questions here. Use qnap forum instead. There is an Entware subforum.
Issues are used mainly for requests and bug reports.
Please beware I cannot answer your questions on third party packages like Qmono etc etc.

**Comment by Jorman** [comment]
Ok tnx, but just for info, Qmono etc, before entware all was ok, I checked the script of qmono and report
ln -sf $QPKG_ROOT /opt/Qmono

So I expect that the symbolic link was created under the Entware-ng dir, but won't.
Btw, I open the thread on qnap forum, tnx.
