### ISSUE TITLE
entware lighttpd conflict with built-in one

### ISSUE THREAD

**Issue by monosoul** [Entware-ng/Entware-ng#155]
Hi! I'm using merlin's firmware on my Asus RT-n66u. It has built-in lighttpd for serving content streaming of AiCloud. So, if I install lighttpd from entware and would try to start it - it'd say that it's already running and wouldn't start. As far as I can understand it happens because you're using pidof to determine process pid in "rc.func".
I suggest 2 possible solutions:
1) Rename entware's lighttpd binary to something else, for example: "lighttpdmn" or maybe "entlighttpd";
2) Use another way of process pid determination that would consider binary path. (more preferable)
Something like this maybe: https://github.com/monosoul/rc.func/commit/fec69f9a7b3be2d2ef1e3aacb60b6aea099db311

**Comment by zyxmon** [comment]
You can write your own startup script in this case. Entware scripts should be modified in many cases.

**Comment by monosoul** [comment]
@zyxmon @ryzhovau anyway, could someone take a look at rc.func patch I suggested? It could be useful in many cases.

**Comment by ryzhovau** [comment]
No, sorry. We keep this scripts as simple as possible.
`readlink` is absent on number of systems.

**Comment by monosoul** [comment]
@ryzhovau ok, got it.
