### ISSUE TITLE
Package Request: ruTorrent mobile plugin

### ISSUE THREAD

**Issue by monosoul** [Entware-ng/Entware-ng#156]
Hi!
Could you please add this plugin https://github.com/xombiemp/rutorrentMobile to repo? I know that we're already have iPad plugin, but in ruTorrent wiki it's recommended to use mobile plugin instead.
Thanks in advance!

**Comment by ryzhovau** [comment]
No need to wait new package, just [download](https://github.com/xombiemp/rutorrentMobile/archive/master.zip) it and unpack into `plugins` dir.
