### ISSUE TITLE
Package Request: whowatch

### ISSUE THREAD

**Issue by tuxy** [Entware-ng/Entware-ng#157]
Displays information about the users currently logged on to the machine in real time.

http://wizard.ae.krakow.pl/~mike/#whowatch

Requires "ncurses" package.

**Comment by zyxmon** [comment]
It was abandoned in 2000. Try to use coreutils-who instead.

**Comment by zyxmon** [comment]
One more remark - all binaries w,who,whowatch use /var/run/utmp file that is absent on most embedded systems.
