### ISSUE TITLE
rsnapshot dependency missing "perlbase-ipc"

### ISSUE THREAD

**Issue by pkim22** [Entware-ng/Entware-ng#16]
rsnapshot needs perlbase-ipc, but on my first install of rsnapshot, perlbase-ipc was not installed as part of dependency fulfillment. I installed perlbase-ipc manually and then rsnapshot worked.

- Peter

**Comment by ryzhovau** [comment]
Fixed in https://github.com/Entware-ng/entware-oldpackages-ports/commit/bdc327d1568e01320c36cf0e4ed0d6247fc1429d
Thanks for report!
