### ISSUE TITLE
Package Request: python24 py-pgsql py24-mx-base

### ISSUE THREAD

**Issue by mureev** [Entware-ng/Entware-ng#161]
Hello,

I am looking for the option to use Synlogy Downloadstation CLI interface
http://downloadstation.jroene.de/

But for some reason this script uses py2.4 and can't be runned on 2.7. So can you add python24 py-pgsql py24-mx-base packages?

**Comment by ryzhovau** [comment]
No plans to add old python versions to repo, sorry.
