### ISSUE TITLE
Package Request: hashdeep/md5deep (and related asst hashing programs)

### ISSUE THREAD

**Issue by sethcohn** [Entware-ng/Entware-ng#162]
https://github.com/jessek/hashdeep
(used to be known as md5deep, and was/is an optware package, but missing from ent)
very fast hashing in many flavors, including md5, sha256, tiger, whirlpool and more.

**Comment by ryzhovau** [comment]
"Many" [is](https://github.com/jessek/hashdeep#hash-algorithm-references): MD5, SHA1, SHA256, Tiger and Whirlpool. Is there any reasons against using coreutils utilities?
* `opkg install coreutils-md5sum` 
* `opkg install coreutils-sha1sum` 
* `opkg install coreutils-sha256sum`

**Comment by sethcohn** [comment]
Hashdeep does much more functionally and is faster. 

I use it on my NAS for duplicate checking, and security scans.

**Comment by zyxmon** [comment]
Done - https://github.com/Entware-ng/rtndev/commit/98b17f5df7063ac812806e0048f0b9bf7ffaf95c
I have compared the speed of md5sum/sha256sum (from busybox) with md5deep binaries. There is no big difference. md5deep package has additional usefull digest that can be usefull.
Binaries will arrive soon.

**Comment by ryzhovau** [comment]
Done. Binaries will arrive soon.
