### ISSUE TITLE
Package upgrade request - Nginx --with-http_upstream_zone_module

### ISSUE THREAD

**Issue by kalo8450** [Entware-ng/Entware-ng#163]
One of the main reasons for using Nginx is as a proxy server.  This build has been compiled --without-http_upstream_zone_module.  This module allows amongst other things the proxying of websocket servers which is where my interest lies.

kalo8450

**Comment by idcrisis** [comment]
How about this patch?

https://engineering.opendns.com/2015/11/03/lets-talk-about-proxies-pt-2-nginx-as-a-forward-http-proxy/

https://gist.github.com/aramg/4540f0f8cfb8922e89bd

The server guys may not need this ( read may not pay heed ) as they run
some big machines. But may be relevant for devices.

Cheers,
ID

**Comment by kalo8450** [comment]
Thanks for the reply but I am already successfully using nginx as a reverse proxy for several http servers.  My problem is that I am now attempting to proxy a websocket server for which http_upstream_zone_module is required and the current version is compiled without it (nginx -V for details). 

kalo8450

**Comment by ryzhovau** [comment]
This feature requires gcc builtin atomic operations which is absent in Entware toolchain.
