### ISSUE TITLE
Package Request: mysql 5.7.x

### ISSUE THREAD

**Issue by quidam** [Entware-ng/Entware-ng#165]
As mysql 5.1.73 is quite old now, I would highly appreciate a newer version, preferably 5.7.x. I tried to compile it natively, but g++ hangs at one file, so a ready-made package would be great.

Thanks
Ulrich

**Comment by ryzhovau** [comment]
No plans to update mysql before OpenWrt guys. Please, make a PR and/or issue for them [here](https://github.com/openwrt/packages).
