### ISSUE TITLE
nzbget - configuration file appending entries geometricaly

### ISSUE THREAD

**Issue by kalo8450** [Entware-ng/Entware-ng#166]
Each time I save nzbget's configuration from the webui the following is cumulatively added to nzbget.config.  I have saved a username/password change and a news-server change - nothing to do with categories.  I originally noticed that nzbget.conf had grown by several thousand lines each of which was in a block which duplicated repeatedly and also included feed config details as I had set up RSS feeds.
I have uninstalled nzbget and deleted those parts which were not removed by opkg remove (e.g. nzbget.conf) I have done a fresh install and made the two saves as above. The quoted block now appears twice at the end of nzbget.conf.  I have now done a save without making any changes and the block repeats 4 times, saved again and it repeats 8 times.
"Category2.DestDir=
Category2.Unpack=yes
Category2.PostScript=
Category2.Aliases=
Category3.DestDir=
Category3.Unpack=yes
Category3.PostScript=
Category3.Aliases=
Category4.DestDir=
Category4.Unpack=yes
Category4.PostScript=
Category4.Aliases=
"

**Comment by ryzhovau** [comment]
There is no special patches or other changes we made to original code.
https://github.com/Entware-ng/entware-oldpackages-ports/tree/master/nzbget

So it's up to `nzbget` itself. Please, send this issue to `nzbget` devs.

**Comment by kalo8450** [comment]
Known issue, line 112 of nzbget.conf should be changed to

ConfigTemplate=/opt/share/nzbget/nzbget.conf-opkg

otherwise nzbget.conf is its own template which confuses it!

**Comment by ryzhovau** [comment]
Thanks for the info.

**Comment by moneytoo** [comment]
Latest 17.0-1 still contains misconfigured path so I sent a PR.
