### ISSUE TITLE
uclibc support for posix.fallocate()

### ISSUE THREAD

**Issue by Dixxy** [Entware-ng/Entware-ng#167]
Hi guys,

I tried using an entware package to work around a small issue I have with Padavan Firmware for my Asus RT-N56U B1 Router. I am using the Router as a Samba server and would need to use the posix.fallocate() function for fast allocation on ext4 HDDs with boolean 'fast allocate = yes' enabled in Samba config. 

Even though the Entware Package "Samba3.6-server" should support this call, it did not appear to be working and instead the old and slow allocation method is used for "strict allocate = yes" which results in approx 18-20 seconds of delay before a 1.2gb file can be written and respectively longer for bigger files; so long in fact it causes a timeout with the smb-share.

It seems that the problem lies within the uclibc used for entware, because it does not seem to support the posix.fallocate call. 

https://wiki.samba.org/index.php/Linux_Performance
(See "How do I know this is working?")

Can anyone confirm this and can the posix.fallocate call be added to the library?

Original issue post on padavan's Bitbucket: https://bitbucket.org/padavan/rt-n56u/issues/272/posix_fallocate-for-smb-strict-allocate#comment-25599616

**Comment by ryzhovau** [comment]
Tried `posix.fallocate()` on rtorrent before. Works fine.

**Comment by Dixxy** [comment]
What Hard/Software are you using and would you care to try it with samba36-server?

I will try and see how my router performs with rtorrent.

**Comment by ryzhovau** [comment]
Tried on Asus RT-N16 with [Oleg's f\w](https://github.com/wl500g/wl500g) on EXT4 formatted HDD ([russian thread](http://wl500g.info/showthread.php?28036&p=242048#post242048)).

Now I'm on RT-N66U with no EXT4 support, so I can't reproduce it, sorry.
