### ISSUE TITLE
nano: bring back "-w" option

### ISSUE THREAD

**Issue by ryzhovau** [Entware-ng/Entware-ng#17]

**Comment by TeHashX** [comment]
Error with nano Entware-NG installed on AsusWRT Merlin firmware, mipsel version:

```admin@RT-AC66U:/tmp# nano entware-ng-setup.sh
Error opening terminal: xterm.
admin@RT-AC66U:/tmp#
```

**Comment by zyxmon** [comment]
opkg install terminfo
(terminfo is preinstalled on x86 & arm)

**Comment by zyxmon** [comment]
fixed - https://github.com/Entware-ng/entware-packages/commit/058544ef4a1546f9b53b8461a634c7b625dbb03c
