### ISSUE TITLE
oldports\cups is missing doc and ipptool folders

### ISSUE THREAD

**Issue by futurechild** [Entware-ng/Entware-ng#171]
cups is missing the following folders:
-doc  containing cups.css, index.html etc.
ipptool containing a few testfiles. 

The below changes to the Makefile solve this.

changing this:
```
	$(INSTALL_DIR) $(1)/opt/share/cups
	$(CP) $(PKG_INSTALL_DIR)/opt/share/cups/templates \
		$(1)/opt/share/cups/
```

into this:
```
	$(INSTALL_DIR) $(1)/opt/share/cups
	$(CP) $(PKG_INSTALL_DIR)/opt/share/cups/templates \
		$(1)/opt/share/cups/
	$(CP) $(PKG_INSTALL_DIR)/opt/share/cups/ipptool \
		$(1)/opt/share/cups/
	$(INSTALL_DIR) $(1)/opt/share/doc
	$(CP) $(PKG_INSTALL_DIR)/opt/share/doc/cups \
		$(1)/opt/share/doc/
```

Have these folders been ommited intentionally ?

**Comment by ryzhovau** [comment]
This package came from OpenWrt. So better to ask them for their reasons.
CUPS package doesn't include WebUI, so I see no sense to add CSS, HTML e.t.c.

**Comment by futurechild** [comment]
Actually the WebUi is active and functioning, apart from the missing homepage.
I''l go and ask at OpenWrt.
Will changes at their packages be picked up in entware-ng ?

**Comment by ryzhovau** [comment]
Yes, we sync with OpenWrt packages approx. once per months, so we'll update CUPS if it will be changed there.

**Comment by davygravy** [comment]
Is there currently a maintainer of CUPS at OpenWRT?  My reading has led me to believe that there is not one that the moment.  It might be a while until this gets fixed.

**Comment by ryzhovau** [comment]
Sorry for the late answer. I'll promise to answer all questions you mailed before.

**Comment by davygravy** [comment]
NP, Alexander. Enjoy the weekend. 

(Sent from my iPhone)

Dave Purdy
