### ISSUE TITLE
Package request bareos

### ISSUE THREAD

**Issue by vandendal** [Entware-ng/Entware-ng#172]
Please add the Backup Archiving https://www.bareos.org/en/.
Bareos is a fork and successor of bacula.

There should be package for client only "bareos-fd" and full Backupserver.

**Comment by ryzhovau** [comment]
We won't add another backup solution to repo. There is `rsnapshot`, `rdiff-backup` and `bacula` (last on is for Intel/ARM only). 

I'm closing this as https://github.com/Entware-ng/Entware-ng/issues/142. Sorry.

**Comment by vandendal** [comment]
#https://github.com/Entware-ng/Entware-ng/issues/185

**Comment by guillemlc** [comment]
I would also like to support Bareos as a package, per the reasons given by @vandendal . Also, bareos seems to be in better health than Bacula, and is easier to integrate with different clients.
