### ISSUE TITLE
Include Pixelserv-tls

### ISSUE THREAD

**Issue by swetoast** [Entware-ng/Entware-ng#176]
Supports both arm and mipsel great for adblocking

https://github.com/kvic-z/pixelserv-tls

**Comment by ryzhovau** [comment]
Done.

Thanks to @kvic-z.

**Comment by swetoast** [comment]
mind adding the arm package too and not just the mipsel

**Comment by ryzhovau** [comment]
That's normal, non-mipsel binaries will arrive soon.

**Comment by swetoast** [comment]
not sure if you included a init script  so here is mine thats tested and working
```
#!/bin/sh

ENABLED=yes
PROCS=pixelserv
ARGS="`ifconfig br0 | awk '/inet addr/{print substr($2,6)}'` -p 80 -p 8080 -k 443 -k 2443 -u $USER"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
```

**Comment by ryzhovau** [comment]
> not sure if you included a init script ...

Please, check first. Then write.

> so here is mine thats tested and working

This is firmware-independed repo, we can't take interface names form asuswrt-merlin.
