### ISSUE TITLE
pkg.entware.net is down,please fixed it.

### ISSUE THREAD

**Issue by imagelife** [Entware-ng/Entware-ng#177]
Hi 

pkg.entware.net is down,please fixed it.

ping  pkg.entware.net
PING pkg.entware.net (81.4.123.217): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
^C
--- pkg.entware.net ping statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss

who can solved? thx.

**Comment by ryzhovau** [comment]
It's closed for some Chinese subnets which was source of recent DDOS attacks.

For every other IP addresses it remains open.

**Comment by imagelife** [comment]
I am  Chinese Normal User，so sad.

**Comment by zyxmon** [comment]
You can use proxy - https://wiki.openwrt.org/doc/techref/opkg#proxy_support

**Comment by imagelife** [comment]
thx

**Comment by imagelife** [comment]
@ryzhovau please add 119.9.108.54 to white list, I use 119.9.108.54 as my proxy,thx.

**Comment by loopism** [comment]
Same thing for .au addresses as well (101.176.x.x)

@imagelife - What you can do is google open proxy lists, and use a (for example) UK proxy in your .wgetrc
