### ISSUE TITLE
Package Request "fping"

### ISSUE THREAD

**Issue by p4l4din** [Entware-ng/Entware-ng#180]
Requesting a package for "fping" please

http://fping.org/
fping is a program to send ICMP echo probes to network hosts, similar to ping, but much better performing when pinging multiple hosts. fping has a very long history: Roland Schemers did publish a first version of it in 1992 and it has established itself since then as a standard tool for network diagnostics and statistics.

Thanks in advance!

**Comment by ryzhovau** [comment]
I see no advantages of `fping` when `nping` is already available, sorry.
