### ISSUE TITLE
Please, update the freeradius2 package!

### ISSUE THREAD

**Issue by SimpleCold** [Entware-ng/Entware-ng#184]
I can't connect to my router with EAP-TTLS, because of this bug in freeradius 2.2.8, posts 29 180 186 : 
https://code.google.com/p/android/issues/detail?id=188867
The router rejects the connection because of it, and authentication fails.

**Comment by ryzhovau** [comment]
There is no person here who will maintain updated package. 
The `freeradius2` came from OpenWrt upstream. You may [send](https://github.com/openwrt/packages/issues) this issue to OpenWrt guys. We sync with them once per months, so if `freeradius2` will be updated there, new version will arrive to Entware.
