### ISSUE TITLE
Package request "bareos"

### ISSUE THREAD

**Issue by mdallastella** [Entware-ng/Entware-ng#185]
Hi,

it would be nice to have the [bareos](http://bareos.org) suite among with bacula (bareos is a fork of it).
Unfortunately recent bacula client has some issues to communicate with bareos director, so it would be great to have its native client.

If you need further information, I'm at your disposal.

Thank you.

**Comment by ryzhovau** [comment]
Duplicate of https://github.com/Entware-ng/Entware-ng/issues/172

**Comment by vandendal** [comment]
That's nice. Another vote for bareos :)
ryzhovau: What's the point against another backup solution in the repo?
