### ISSUE TITLE
pyload broken

### ISSUE THREAD

**Issue by exclamationgm** [Entware-ng/Entware-ng#186]
As I found out today the pyload-v0.4.9.tar.gz we are fetching from their github-releases page is kinda broken. What has to be done has GammaC0de pointed out here: 

https://github.com/pyload/pyload/issues/2000#issuecomment-147120512

The UpdateManager.py in the tar.gz is not updating itself so it has to get replaced at least once to a newer version manually.

Thx
!gm

**Comment by ryzhovau** [comment]
It's up to maintainers. 
I've updated pyload to last rev, but I have no time to catch all their UpdateManager tricks, sorry.
