### ISSUE TITLE
Locale naming mismatch in /opt/etc/profile?

### ISSUE THREAD

**Issue by curby** [Entware-ng/Entware-ng#187]
Hi folks, I'm not sure if this is a problem, but it seems a bit odd:

`/opt/etc/profile` have lines like:

```
# You may define localization
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
```

However, Synology locales have slightly different names:

```
# locale -a
C
cs_CZ.utf8
da_DK.utf8
de_DE.utf8
en_US.utf8
es_ES.utf8
fr_FR.utf8
hu_HU.utf8
it_IT.utf8
ja_JP.utf8
ko_KR.utf8
nb_NO.utf8
nl_NL.utf8
pl_PL.utf8
POSIX
pt_BR.utf8
pt_PT.utf8
ru_RU.utf8
sv_SE.utf8
tr_TR.utf8
zh_CN.utf8
zh_TW.utf8
# /opt/bin/locale.new -a
C
en_US.utf8
POSIX
ru_RU.utf8
```

Is this a problem?  (If not, why not?) Should `/opt/etc/profile` be changed to reflect the 'utf8' naming convention used by Synology?

**Comment by ryzhovau** [comment]
Host locales has no any relations to Entware locales.

**Comment by zyxmon** [comment]
@curby - you can add new locales in Entware this way:
1. Download http://pkg.entware.net/sources/i18n_glib222.tar.gz and unpack to /opt/usr/share
2. Run `/opt/bin/localedef.new -c -f UTF-8 -i pl_PL pl_PL.UTF-8` to add needed locale (polish, for example).
Please note - locale generation requires a lot or RAM.
