### ISSUE TITLE
rtorrent / rutorrent - private tracker errors

### ISSUE THREAD

**Issue by ckisgen** [Entware-ng/Entware-ng#188]
Currently running Entware-NG on an Asus RT-AC66U (MIPSEL) router.

I installed rtorrent/rutorrent using the rtorrent-easy-install - 0.2-2 package. However, rtorrent is apparently incorrectly identifying itself to some fairly popular private trackers.

Client is calling in to the trackers as (-DE / libtorrent/1.0.6.0). This is either unrecognized or simply not on the client/approved white list for several private trackers. 

So I either get an error from the tracker in rutorrent on some trackers or torrents simply don't seed. I'm guessing this is also because of how the client is reporting itself to other peers (with an unknown or not mainstream user peer ID/string).

I'm guessing that the issue lies somewhere with the initial libtorrent or rtorrent configs when compiling and configuring via the rtorrent-easy-install - 0.2-2 script. 

Can someone please help me get rutorrent / rtorrent compiled and running correctly on my AC66U please so that it's calling in correctly to the private trackers (should be calling in as rtorrent / x.x.x.x)?

**Comment by ryzhovau** [comment]
This issue is not related to Entware. Please, send it to `rtorrent` devs.
