### ISSUE TITLE
Package Request: redis

### ISSUE THREAD

**Issue by bmanfield** [Entware-ng/Entware-ng#189]
Personally I would like redis to use as the memcache service for owncloud. I would specifically like redis for its support for transactional file locking.

Thanks.

**Comment by ryzhovau** [comment]
Please, tell us how you going to use it?

**Comment by bmanfield** [comment]
Hi Alex,
I require it for use on my QNAP NAS with owncloud.

Cheers
Ben
On 20 May 2016 9:23 pm, "Alexander Ryzhov" <notifications@github.com> wrote:

Please, tell us how you going to use it?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Entware-ng/Entware-ng/issues/189#issuecomment-220586400>

**Comment by argakon** [comment]
+1 for redis package.
Now i build him myself using files from [this](https://github.com/pdf/openwrt-14.07-x86_64-packages/tree/master/net/redis) repository and changed them for entware compatibility.
Redis working very fast and 128Mb of my RT-N16 RAM is enough.

**Comment by ryzhovau** [comment]
Done, binaries will arrive soon.

**Comment by TeHashX** [comment]
Are you using redis with owncloud through entware-ng? I think php5-mod-redis is required too.
