### ISSUE TITLE
opkg illegal instruction on Asus WL-500W due to MIPS r2 instruction.

### ISSUE THREAD

**Issue by dreamlayers** [Entware-ng/Entware-ng#19]
It seems opkg is built for MIPS r2:

> $ file opkg.new 
> opkg.new: ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), statically linked, stripped

On Asus WL-500W I can get the opkg help text output, but attempts to perform any operations result in ". Here's what happens in gdb:

> (gdb) run
> Starting program: /opt/dl/opkg.new list-installed
>
> Program received signal SIGILL, Illegal instruction.
> 0x004226e4 in ?? ()

> (gdb) x/10i 0x4226e4
> => 0x4226e4:	ins	v0,zero,0x7,0x1
>   0x4226e8:	sb	v0,28(s0)
>   0x4226ec:	lbu	v0,28(s0)
>   0x4226f0:	lw	t9,-32580(gp)
>   0x4226f4:	ext	s2,s2,0x3,0x1
>   0x4226f8:	ins	v0,s2,0x4,0x1

This seems like valid MIPS code, but the ins instruction requires MIPS r2, and the WL-500W is r1.

Was opkg accidentally built for MIPS r2 or will Entware-ng be unusable on MIPS r1 routers?

**Comment by sy-uname** [comment]
http://wl500g.info/showthread.php?28036-Entware-%ED%EE%E2%FB%E9-%F0%E5%EF%EE%E7%E8%F2%EE%F0%E8%E9-%E4%EB%FF-%F0%EE%F3%F2%E5%F0%EE%E2-(MIPS)&p=269154#post269154
MIPS R2. Old men like D-Link DIR-320 or Asus wl500gpv2 will be put in order on pension,

**Comment by ryzhovau** [comment]
Yes, we dropped MIPS R1 devices support, ASUS WL-500gP and older (WL-500gPv2, WL-500W, WL-500gX, WL-520gU, WL-550gE, WL-330gE, WL-320gE, WL-320gP, D-Link DIR-320 and so on) are out of boat, sorry.

You still can use other repos, including previous Entware feeds:
```
wget -O - http://entware.wl500g.info/binaries/mipselsf/installer.orig/entware_install.sh | sh
```

Asus [dropped it's support 7+ years ago](https://www.asus.com/ru/Networking/WL500g_Premium/HelpDesk_Download/), so, there is no sense to support it here too.

**Comment by dreamlayers** [comment]
Could you at least make the installer script warn about this, so others don't waste their time finding this out on their own?

**Comment by ryzhovau** [comment]
Unfortunately, there is no simple way to detect MIPSr1 devices from BB console. All I can do is to add some warnings to upgrade script:
```
# wget -qO - http://entware.zyxmon.org/binaries/mipsel/installer/upgrade.sh | sh
This script will upgrade existing Entware packages to Entware-ng.
Please keep in mind:

* Entware-ng is not compatible with MIPSr1 devices (7+ years old). Please,
    refer to this list if you are not sure about your device
    http://tomatousb.org/doc:build-types

* Upgrade will be aborted if you are logged on to this console via ssh/telnet
    daemon from Entware,

* Some of packages may need to be re-configured after upgrade.

Upgrade will be continued in 30 seconds. Press Ctrl+c to abort
...............................starting upgrade!
[1/4] Trying to stop running services...
The following packages will be reinstalled after upgrade:
findutils ldconfig libc libgcc libssp
[2/4] Uninstalling existing packages...
Removing package findutils from root...
Removing package ldconfig from root...
Removing package libc from root...
Removing package libgcc from root...
Removing package libssp from root...
[3/4] Deploying Entware-ng opkg package manager...
Downloading /opt/bin/opkg... success!
Downloading /opt/etc/opkg.conf... success!
Downloading /opt/etc/profile... success!
Downloading /opt/etc/init.d/rc.func... success!
Downloading /opt/etc/init.d/rc.unslung... success!
[4/4] Installing new versions of packages...
Downloading http://entware.zyxmon.org/binaries/mipsel/Packages.gz.
Updated list of available packages in /opt/var/opkg-lists/entware-ng.
No packages removed.
Installing ldconfig (1.0.8-1) to root...
Downloading http://entware.zyxmon.org/binaries/mipsel/ldconfig_1.0.8-1_mipselsf.ipk.
Installing findutils (4.5.14-1) to root...
Downloading http://entware.zyxmon.org/binaries/mipsel/findutils_4.5.14-1_mipselsf.ipk.
Installing libc (1.0.8-1) to root...
Downloading http://entware.zyxmon.org/binaries/mipsel/libc_1.0.8-1_mipselsf.ipk.
Installing libgcc (4.8.5-1) to root...
Downloading http://entware.zyxmon.org/binaries/mipsel/libgcc_4.8.5-1_mipselsf.ipk.
Installing libssp (4.8.5-1) to root...
Downloading http://entware.zyxmon.org/binaries/mipsel/libssp_4.8.5-1_mipselsf.ipk.
Package findutils (4.5.14-1) installed in root is up to date.
Package ldconfig (1.0.8-1) installed in root is up to date.
Package libc (1.0.8-1) installed in root is up to date.
Package libgcc (4.8.5-1) installed in root is up to date.
Package libssp (4.8.5-1) installed in root is up to date.
Configuring ldconfig.
Configuring libgcc.
Configuring libc.
Configuring libssp.
Configuring findutils.
Done. Found a bug? Please report us at
https://github.com/Entware-ng/Entware-ng/issues
```
