### ISSUE TITLE
Useless runtime dependencies ob libsoxr

### ISSUE THREAD

**Issue by alllexx88** [Entware-ng/Entware-ng#190]
Package libsoxr currently contains static libraries only, so runtime dependencies on it are meaningless. As of now, these packages depend on it for no real reason (grepped through armv7):
shairport-sync-openssl
shairport-sync-polarssl
squeezelite-full

**Comment by ryzhovau** [comment]
Thanks for report!

**Comment by alllexx88** [comment]
You're welcome. If Entware-ng switches to shared libsoxr, I remember I had to add some more linker flags to cmake, apart from the standard OpenWRT ones, to get RPATH passed properly (https://github.com/Optware/Optware-ng/blob/master/make/libsoxr.mk):

```
		-DCMAKE_EXE_LINKER_FLAGS:STRING="$(STAGING_LDFLAGS) $(LIBSOXR_LDFLAGS)" \
		-DCMAKE_MODULE_LINKER_FLAGS:STRING="$(STAGING_LDFLAGS) $(LIBSOXR_LDFLAGS)" \
		-DCMAKE_SHARED_LINKER_FLAGS:STRING="$(STAGING_LDFLAGS) $(LIBSOXR_LDFLAGS)" \
		-DCMAKE_C_LINK_FLAGS:STRING="$(STAGING_LDFLAGS) $(LIBSOXR_LDFLAGS)" \
		-DCMAKE_CXX_LINK_FLAGS:STRING="$(STAGING_LDFLAGS) $(LIBSOXR_LDFLAGS)" \
		-DCMAKE_SHARED_LIBRARY_C_FLAGS:STRING="$(STAGING_LDFLAGS) $(LIBSOXR_LDFLAGS))" \
```

Sorry, don't remember which of these are automatically added by OpenWRT build system.
