### ISSUE TITLE
Entware problem with Router installation

### ISSUE THREAD

**Issue by webnet918** [Entware-ng/Entware-ng#193]
I have successfully installed Entware.NG on a USB stick, but I want to get it to be mounted directly on the router, what should I do? My router is AC88U

**Comment by ryzhovau** [comment]
This is f\w specific question. Every firmware got it's own start up sequence (including `/opt` mount). Better to find out details on f'\w forum.

Entware is firmware-independent repo, we can't provide start up details for every f\w, sorry.

**Comment by webnet918** [comment]
Thanks a lot
