### ISSUE TITLE
gdb is missing?

### ISSUE THREAD

**Issue by HunterZ** [Entware-ng/Entware-ng#195]
I had gdb installed in Entware, and the upgrade script said it couldn't reinstall it.

It looks like there's a "gdb_legacy" package. What is the story?

Thanks.

Edit: This probably doesn't matter, as it looks like I have gdb from tomatoware.

**Comment by zyxmon** [comment]
Entware-ng is compiled for many artitectures, using differnet kernel versions. mipsel version is compiled with an old 2.6.22 kernel and need a differnt gdb version that works. gdb_leagcy is gdb equivalent for the old Entware.
