### ISSUE TITLE
openssh-sftp-client dependencies

### ISSUE THREAD

**Issue by HunterZ** [Entware-ng/Entware-ng#196]
I installed openssh-sftp-client, and when I tried to run sftp it said that it couldn't find /opt/bin/ssh.

Looks like maybe a package dependency on openssh-client needs to be added?

**Comment by zyxmon** [comment]
Do you have any sshd (dropbear, openssh-server) working?
The ssh server on your device should expect to find /opt/libexec/sftp-server
If it does not - use dropbear or openssh-server from optware.

**Comment by HunterZ** [comment]
I'm using TomatoUSB, but openssh-sftp-client's sftp wouldn't use it. It reported that it needed to find one at /opt/bin/ssh.

**Comment by HunterZ** [comment]
Please see bug #197, which was closed out of hand. Frustrating that this wasn't taken seriously

**Comment by zyxmon** [comment]
@HunterZ - if you need more technical details - please ask to make a patch before building firmware - http://www.linksysinfo.org/index.php?threads/tomato-shibbys-releases.33858/page-31#post-243986

The tomato on my ws-880 has this patch and sft-server is working without installing any additional servers.

**Comment by HunterZ** [comment]
Who said anything about servers? I'm talking about clients!

**Comment by zyxmon** [comment]
>>  I'm talking about clients!

In this case you have a lot of solutions. The simplest one is `ln -s /usr/bin/dropbear /opt/bin/ssh` in case you have /usr/bin/dropbear. Here is the output

```
root@ws880:/tmp/home/root# /opt/bin/sftp admin@10.0.0.26:/etc/TZ
WARNING: Ignoring unknown argument '-oForwardX11 no'
WARNING: Ignoring unknown argument '-oForwardAgent no'
WARNING: Ignoring unknown argument '-oPermitLocalCommand no'
WARNING: Ignoring unknown argument '-oClearAllForwardings yes'
WARNING: Ignoring unknown argument '-oProtocol 2'
WARNING: Ignoring unknown argument '--'

Host '10.0.0.26' is not in the trusted hosts file.
(ssh-rsa fingerprint md5 44:48:f4:e8:fb:65:7f:a7:05:c8:72:f8:15:fc:32:ca)
Do you want to continue connecting? (y/n) y
admin@10.0.0.26's password:
Connected to 10.0.0.26.
Fetching /etc/TZ to TZ
/etc/TZ                                                                                     100%    6     0.0KB/s   00:00
```
```

**Comment by HunterZ** [comment]
Okay, so it's not intended to work out of the box. I just wanted to be sure of that.

It looks like openssh SFTP tries to send a lot of arguments to SSH that dropbear doesn't support.

**Comment by ryzhovau** [comment]
`/opt/bin/ssh` can be any of SSH server (including SSH server from Tomato). That why `openssh-sftp-client` has no hard dependency.
