### ISSUE TITLE
entware.zyxmon.org, pkg.entware.net not reachable from China

### ISSUE THREAD

**Issue by stephanfuchs** [Entware-ng/Entware-ng#198]
I've tried to install entware-ng on my qnap and it never finished. It turns out that the above mentioned domains can not connect to `81.4.123.217`. Is there anything that can be done from your side about this?

**Comment by zyxmon** [comment]
You can find and use proxy. For installing use proxy for wget (through http_proxy environment variable).
After installing you can specify proxy in /opt/etc/opkg.conf file: https://wiki.openwrt.org/doc/techref/opkg#proxy_support
