### ISSUE TITLE
Package Upgrade Request: I2pd

### ISSUE THREAD

**Issue by Lichtenshtein** [Entware-ng/Entware-ng#199]
Hi, please update i2pd package for Mipsel. Latest version is 2.5.1, and version in repository is 2.2.0.

**Comment by ryzhovau** [comment]
Done. The new version will arrive to repo in the next week, but there is some version number issue. The previous one was `2.20`, the new one is `2.5.1`, so you have to update it manually by:
```
opkg remove i2pd
opkg update
opkg install i2pd
```
