### ISSUE TITLE
Postfix searches config outside of /opt

### ISSUE THREAD

**Issue by ryzhovau** [Entware-ng/Entware-ng#2]
https://github.com/Entware/entware/issues/5 to be continued.
```
/opt/root # sendmail.postfix
sendmail.postfix: fatal: open /etc/postfix/main.cf: No such file or directory
```

**Comment by zyxmon** [comment]
fixed in https://github.com/Entware-ng/entware-packages/commit/a00e02ff1935740de2f0d0871ead8913edaab766
