### ISSUE TITLE
New Generation Entware folder name

### ISSUE THREAD

**Issue by TeHashX** [Entware-ng/Entware-ng#20]
I want to create a script to install entware-ng which will backup first any entware, optware, optware-ng installation and will also create a swap file but I'm not sure how to name entware folder, entware or entware-ng (entware-ng.arm respectively)? something like optware-ng install script http://goo.gl/NhZz9U

**Comment by zyxmon** [comment]
It makes little difference, sinсe the folder is symlinked to /opt. The packages tor QNAP nases name it entware-ng for any architecture.
The entware-ng binaries (armv7)  are not binary compatible with entware. I'm just writing a script for upgrade - http://entware.zyxmon.org/binaries/armv7/installer/upgrade.sh

Probably some comments will help you. It does not backup old installation. It removes all previously installed packages (this leaves all configuration files) and installs entware-ng and all the old packages. In entware the last package installed overwrites the binaries of the previously installed packages. To make shure find is used from findutils - it is installed in the end.

**Comment by zyxmon** [comment]
As I can see from optware-ng install script - it backups the old installation folder and installs optware-ng in the new one.
I think the folder name in arm version and mipsel version should be the same. Let us ask @ryzhovau the folder name for mipsel entware-ng.

**Comment by zyxmon** [comment]
Merlin uses entware.arm for the arm version - https://github.com/RMerl/asuswrt-merlin/blob/master/release/src/router/others/entware.arm/entware-setup.sh
and entware for mipsel version - https://github.com/RMerl/asuswrt-merlin/blob/master/release/src/router/others/entware.mips/entware-setup.sh

Is your script for asuswrt only?

**Comment by TeHashX** [comment]
Yes, the script is for asuswrt Merlin based firmwares but may be modified to match other firmwares too, I decided to name it entware-ng & entware-ng.arm, I will publish it this weekend, thanks

**Comment by TeHashX** [comment]
Done :)

https://www.hqt.ro/how-to-install-new-generation-entware/

**Comment by ryzhovau** [comment]
@TeHashX please edit how-to, I'm [referring](https://github.com/Entware-ng/Entware-ng/wiki/Install-on-RMerlin-firmware) to нщг from local wiki.

* On ARM devices:
```
wget -O - http://entware.zyxmon.org/binaries/armv7/installer/entware_install.sh | sh
```
* On MIPS devices:
```
wget -O - http://entware.zyxmon.org/binaries/mipsel/installer/installer.sh | sh
```

**Comment by TeHashX** [comment]
Sorry, I don't understand, I only created mipsel installer and url is the same, please be more specific

**Comment by ryzhovau** [comment]
That it, ARM installation is the same as MIPS, just one URL is different. 
Could you edit your article to make universal HOW-TO for ARM and MIPS devices?

I've made universal installation script which will be a part of asuswrt-merlin soon. You can see how to determine ARM or MIPS platform here. 

https://github.com/RMerl/asuswrt-merlin/pull/905

**Comment by TeHashX** [comment]
I started working on universal installer from yesterday but a little bit different, I get router model from `cat "/proc/sys/kernel/hostname"` :) which is wrong from start :(
I will do it your way: (uname -m) it's much better.
Thanks
