### ISSUE TITLE
Package Request: mono

### ISSUE THREAD

**Issue by BarakaAka1Only** [Entware-ng/Entware-ng#200]
I was wondering if the package mono could be added, I've tried to compile it myself only gotten 2.11 to work, 3.0 and above failed due to glibc version not above 2.16 (even tho i am using a 2.23)
but anyhow here is the package source http://download.mono-project.com/sources/mono/

looking for it to be compiled on ARMv7 would be a great addition, thank you in advanced.

If it is decided not to be added then i fully understand.

**Comment by ryzhovau** [comment]
Please, tell us how are you going to use mono? It will be useful just for few console closed-source apps.

**Comment by ryzhovau** [comment]
No response.

**Comment by moonman** [comment]
Sonarr and radarr use mono and work fine in headless mode. Just an example.

**Comment by zyxmon** [comment]
https://github.com/mono/mono#build-status

It looks like it will not be stable for most Entware feeds.

**Comment by moonman** [comment]
I have been running it (mono + Sonarr + Jackerr) for over a year on Odroid XU4 and SolidRun Clearfog, borth are ARMv7 devies (albeit with VFP). Don't know if mono will work well without VFP
