### ISSUE TITLE
Package Request: pcal

### ISSUE THREAD

**Issue by linuxnutzer** [Entware-ng/Entware-ng#203]
Hi!

Can you add pcal on entware-ng from optware-ng.

Homepage:
http://pcal.sourceforge.net/

Background:
PCAL is a multi-platform program which generates annotated PostScript or HTML calendars in a monthly or yearly format.

I use it for automatic printing my calendar events from google-calendar by a weekly cron job. This is pretty good solution for a NAS/server.
Short summary:
1) Get google calendar file in ical format with wget <Private-Link>
2) Convert it to pcal-text-file with ical2pcal.sh (https://github.com/pmarin/ical2pcal)
3) generate a postscript calendar page for the current/next month
4) print it with cups

Thank you,
linuxnutzer

**Comment by zyxmon** [comment]
Done - https://github.com/Entware-ng/rtndev/commit/1533341621a85c72f15d1c1229848e4b6b29afa6
Binaries will arrive soon.

**Comment by linuxnutzer** [comment]
Thank you very much for that fast handling!!

linuxnutzer
