### ISSUE TITLE
New package request: Par2cmdline

### ISSUE THREAD

**Issue by burbulence** [Entware-ng/Entware-ng#205]
A command line implementation of the PAR v2.0 specification. Currently compiles under Win32, cygwin, and various unix flavors with gcc. It is hosted here at the Parchive Project  https://sourceforge.net/projects/parchive/

**Comment by ryzhovau** [comment]
It's abandoned 12 years ago. Please, find some alternative if it's really needed.

**Comment by burbulence** [comment]
Yet still essential for the repair of downloaded Usenet files and a fork still being maintained on GitHub
https://github.com/Parchive/par2cmdline

**Comment by ryzhovau** [comment]
Done.
