### ISSUE TITLE
Package Request: Perl Module SOAP::Lite

### ISSUE THREAD

**Issue by GUHU0433** [Entware-ng/Entware-ng#206]
Hello,
is it possible to package the perl module SOAP::Lite? I cannot make it by myself because openssl-dev is needed. 

Target is arm-openwrt-linux-gnueabi

Thank you very much in advance.

**Comment by ryzhovau** [comment]
> I cannot make it by myself because openssl-dev is needed. 

Please, [download headers](https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-%28native-compilation%29#headers-installation) first.
