### ISSUE TITLE
perl path hardcode to /usr/bin/perl break thing in some NAS (ie qnap synology)

### ISSUE THREAD

**Issue by mike-pt** [Entware-ng/Entware-ng#209]
I noticed this using git submodule, it tries to use /usr/bin/perl, but the box doesn't have it, perl is however installed from entware.

Ideally it should use "perl" and let PATH do its thing.

This is ofc not a major issue since a ln can work around it

**Comment by zyxmon** [comment]
Do you have a patch for git sources?
You can always create a symlink on qnap /usr/bin/perl -> /opt/bin/perl
