### ISSUE TITLE
/opt/share/dbus-1 missing

### ISSUE THREAD

**Issue by tonyarnold** [Entware-ng/Entware-ng#21]
After installing both `dbus` and `dbus-utils`, the server won't start stating:

```
Failed to start message bus: Failed to open "/opt/share/dbus-1/system.conf": No such file or directory
```

**Comment by ryzhovau** [comment]
Fixed https://github.com/Entware-ng/entware-packages/commit/5c9039c17b7d3fb74fd9015c6b71f25409826816
