### ISSUE TITLE
cups and python-cloudprint issues

### ISSUE THREAD

**Issue by pgera** [Entware-ng/Entware-ng#210]
Tried to install cups first. I see the following issues:

In cups-files.conf
SystemGroup sys root
throws an error because there's no group called sys presumably. Removing sys supresses the error.

MaxPrinterHistory in cupsd.conf throws an error. Commenting it suppresses it.

BrowseProtocols cups  in cupsd.conf throws an error.

After some workarounds, cups starts, but the cups webpage says not found. Interestingly, the admin page still shows details. However, there are no graphics. This is related to:

cupsdLoadBanners: Unable to open banner directory "/opt/share/cups/banners": No such file or directory

Next, I tried the python-cloudprint package.

There's a comma missing at the end of line 483.

After fixing that, I get ImportError: cannot import name xmpp. I couldn't find any related package in the repository. 

Edit: Trying this on N66U with asus-merlin

**Comment by futurechild** [comment]
The webgui is incomplete due to the missing docroot folder, see #171 
I have tried to get this package updated but gave up.

**Comment by pgera** [comment]
That's certainly one of the problems. However, even without the webui, I don't think it's in a usable form right now.

**Comment by futurechild** [comment]
I agree the cupsd.conf file could use an update, but as configuration has be done by the user after installing it i can sort of understand why it is left as is.
For me cups is working as intended, i did however have to create a cups-filter, poppler, qpdf and libijs package ( #81 ).
I did have a quick go at getting airprint working but got stuck getting avahi to communicate, as i did not need it i just left is at that.

**Comment by ryzhovau** [comment]
No CUPS Web configuration by design.
No predictable users\groups are present on different embedded system.

If you wish to see some changes in cups config, make a PR.

**Comment by Crazy-Hopper** [comment]
Well, cups problems aside, but this thread also describes cloupdrint problems.
How should those problems be solved?

**Comment by feranick** [comment]
For reference this is what I did to fix the above listed issues:
1. "cannot import name xmpp. I couldn't find any related package in the repository."

Replace the line: 
`from cloudprint import xmpp`
with:
`from xmpp import *`

This should be pushed as an update.

2. The issues with cups not starting can be fixes in /opt/etc/cups/cups-files.conf by replacing:
`SystemGroup lpadmin sys root`
with:
`SystemGroup root`

**Comment by pgera** [comment]
It's good that some progress has been made since this issue was opened. Since no one has been able to get cloudprint to work yet, I would request this issue (or a different one) be opened again so that it gets visibility. Clearly people are regularly trying to get this feature to work.
