### ISSUE TITLE
Package request: tsocks

### ISSUE THREAD

**Issue by mzhboy** [Entware-ng/Entware-ng#214]
tsocks is a library to allow transparent SOCKS proxying. It wraps the normal connect() function. When a connection is attempted, it consults the configuration file (which is defined at configure time but defaults to /etc/tsocks.conf) and determines if the IP address specified is local. If it is not, the library redirects the connection to a SOCKS server specified in the configuration file. It then negotiates that connection with the SOCKS server and passes the connection back to the calling program.

tsocks is designed for use in machines which are firewalled from then internet. It avoids the need to recompile applications like lynx or telnet so they can use SOCKS to reach the internet. It behaves much like the SOCKSified TCP/IP stacks seen on other platforms.

--------------------------

[http://tsocks.sourceforge.net/](http://tsocks.sourceforge.net/)
[https://github.com/lironghuang/openwrt-old-packages-mirror/tree/master/net/tsocks](https://github.com/lironghuang/openwrt-old-packages-mirror/tree/master/net/tsocks)

**Comment by ryzhovau** [comment]
There is several SOCK proxies in repo. You can always use them with iptables instead of using `LD_PRELOAD` hack.

Also, `tsock` is abandoned 13 years ago. 

Not sure it will be handy for this repo.
