### ISSUE TITLE
Package request: python-twisted

### ISSUE THREAD

**Issue by credo22** [Entware-ng/Entware-ng#217]
Hello, is it possible to package the python-twisted?
Target - MIPS.
Thank you very much in advance.

**Comment by ryzhovau** [comment]
How you going to use it?

**Comment by credo22** [comment]
To run hls-proxy (https://github.com/juanfont/hls-proxy) to avoid mediatomb transcoding hls->ts via ffpmeg on ASUS RT-N66U.

**Comment by ryzhovau** [comment]
Done.
```
opkg install twisted python-crypto
```
Looks like last `pycrypto` [is missing](https://github.com/juanfont/hls-proxy/issues/1) in dependency list.

**Comment by credo22** [comment]
Ok, tnx!
