### ISSUE TITLE
Package Request: LXML

### ISSUE THREAD

**Issue by flametrees** [Entware-ng/Entware-ng#218]
Hi Team,  I am hoping you can please create an LXML Package that I can use on my QNAP TS-419P II.

I get this error log when using a program:
LXML not available, please install for better/faster scraping support: `http://lxml.de/installation.html`

Thanks & Regards,
Flametrees

**Comment by zyxmon** [comment]
Yave you tried to build it yourself 
https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-python-modules

**Comment by ryzhovau** [comment]
No response.
