### ISSUE TITLE
Package Upgrade: pyopenssl

### ISSUE THREAD

**Issue by flametrees** [Entware-ng/Entware-ng#219]
Hi Team,  I am hoping you can please provide an updated version of  the pyopenssl Package that I can use on my QNAP TS-419P II.

I get this error log when using a program:
OpenSSL installed but 0.15 is needed while 0.13.1 is installed. Run `pip install pyopenssl --upgrade`

I've tried upgrading via pip but I can't get this to work.

Thanks & Regards,
Flametrees

**Comment by zyxmon** [comment]
Binaries will arrive soon: https://github.com/Entware-ng/entware-oldpackages-ports/commit/d42d9ecbd98691a8800bd1e682ea5296dddc6d89

**Comment by flametrees** [comment]
Thanks @zyxmon.  Just confirming (sorry for the n00b question) that I will be able to soon do:

opkg update

..Which will include a new package called python-pyopenssl for armv5 architecutre?

Thanks again for your very quick response to my original request.

**Comment by zyxmon** [comment]
Yes. If the old package pyopenssl was installed, you will need to uninstall it.

**Comment by flametrees** [comment]
@zyxmon Just wanted to say Thank You.  This package is working like a dream.  I really appreciate your efforts! :)
