### ISSUE TITLE
Please supply perl module perl-usb-serial (Device::SerialPort) for armv7

### ISSUE THREAD

**Issue by BerlinSnoop** [Entware-ng/Entware-ng#22]
Hello,
I have tried it many many days to create it by my own but without success. Many people are looking for it or trying to create it. Nobody has had success. For unawares it is to complicated to create a running toolchain.

For many people this will be the solution to run the home automation software FHEM on a Synology or QNAP NAS with a CUL stick.

So please supply a compiled version of the cpan/perl module Device::SerialPort (Device-SerialPort-1.04)

Many thanks in advance
Andreas

**Comment by ryzhovau** [comment]
Just added https://github.com/Entware-ng/Entware-ng/commit/6c31328f1e52d1b6b8476500844b536b02f9d88d
Binaries will be available a bit later.

**Comment by zyxmon** [comment]
perl-device-serialport package is in the repository for all feeds including armv7.
Th install run

```
opkg update
opkg install perl-device-serialport
```
