### ISSUE TITLE
Lost libgcc.a

### ISSUE THREAD

**Issue by tasict** [Entware-ng/Entware-ng#221]
GCC lost libgcc.a in x86_64 after upgrade gcc from 4.8.5 to 5.3.0

**Comment by zyxmon** [comment]
libgcc.a was not part of gcc package. You can always use old ipk from archive subfolder.
I have just checked the ipk file from this subfolder.

**Comment by zyxmon** [comment]
FYI. If you look gcc package Makefile libgcc.a is added to package only in the case when libgcc_s.so is a linker script. There is no libgcc.a (x86_64) in the toolchain libs.

**Comment by tasict** [comment]
I build ruby 2.3.0 from source with gcc 4.8.5 and libgcc everything is ok. But I upgrade gcc to 5.3.0 by opkg update, rebuild build ruby 2.3.0 form source will show "-lgcc not found" error.I think new toolchain libs maybe lost some libs.

**Comment by zyxmon** [comment]
I do confirm the bus with new gcc on x64. I'll try to fix it or rollback to gcc 4.8.5

**Comment by Mister-XY** [comment]
there must also an error with armv7 version. i cannot build anything. I will build an oscam and i get gcc error and i will build busybox and also get error. with my old gcc i build it without error.

**Comment by zyxmon** [comment]
@Mister-XY - armv7 version works for me.
I've fixed x64 version. Binaries for all feeds will arrive after more tests.

**Comment by Mister-XY** [comment]
i have installed 4.8.5 and it's build very good but with 5.3.0 not.

**Comment by zyxmon** [comment]
@Mister-XY you are very informative in your bug description )))

I have just uploaded new gcc 5.3 packages for x64 and armv7. I have added gcc static libraries (libgcc*.a) to the package.
I have compiled busybox 1.24.2 on armv7 and it works. The only thing you need to do before building is to make so Makefile modification. Without it host binaries (for meny display) will not honor cflags and ldflags and will not work.

**Comment by Mister-XY** [comment]
Ok, with the new build its compiled. Can you tell, wich makefile do you have changed and what do you have changed.

**Comment by zyxmon** [comment]
**4 All**
My guess is:
gcc4.8.5 always used -shared-libgcc mode and it worked.
gcc 5.3.0 tries to select between -shared-libgcc and -static-libgcc but the previous version cannot use -static-libgcc (no libgcc*.a found). Now it is fixed.

**Mister-XY** The fast and dirty way: add contents of LDFLAGS to the end of the line `HOSTCC  = gcc -Wl,-rpath....` in the Makefile

**Comment by georgeef** [comment]
same/similar problem for x86-32 (installed on qnap). there is no libgcc.a after upgrade. i can create shared libs using "gcc -shared-libgcc -shared ...", but cannot create a binaries using "gcc -o prog file.o", either with or without -shared-libgcc. is there any shortcut until gcc is fixed?

**Comment by zyxmon** [comment]
gcc ipk is now updated for all architectures.
