### ISSUE TITLE
Package-Request: ruby-dev or ruby-devel

### ISSUE THREAD

**Issue by manoloonline** [Entware-ng/Entware-ng#223]
Thank you for your work!

I think it could be very usefull for ruby developers to have the package "ruby-dev" in the repository, it is necesary for installing a lot of gems of ruby and one of the most important gems Rails Framework. Without this package the log of installation it is always the same:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
...
mkmf.rb can't find header files for ruby at /opt/lib/ruby/include/ruby.h
```

I will be very gratefull and also lots of people.

**Comment by ryzhovau** [comment]
It's already here. Please, take a look at wiki.
https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources

**Comment by manuelmeurer** [comment]
@ryzhovau Should these steps work to get `ruby-dev` installed?

```
git clone https://github.com/Entware-ng/Entware-ng.git
cd Entware-ng
make package/symlinks
cp configs/armv7.config .config # for ARMv7 system
make
make package/ruby-dev/compile
```

Haven't tried it yet, just making sure this is what you meant by linking to the wiki entry. 😄 
Thanks!

**Comment by zyxmon** [comment]
>> Should these steps work to get ruby-dev installed?
NO! You can get all ruby headers as described in the wiki!

```
[~] # ls /opt/include/ruby-2.3/
ruby/             ruby.h            x86_64-linux-gnu/
```

This is an example for x64 feed.

**Comment by manuelmeurer** [comment]
Thanks for the quick answer, @zyxmon!
Could you explain a bit more please?
In which wiki entry is this described?
I installed Entware-ng on my Synology DS216j (ARMv7) and lots of Ruby packages:

´´´
# opkg list-installed | grep ruby
libruby - 2.3.1-1
ruby - 2.3.1-1
ruby-bigdecimal - 2.3.1-1
ruby-cgi - 2.3.1-1
ruby-datetime - 2.3.1-1
ruby-dbm - 2.3.1-1
ruby-debuglib - 2.3.1-1
ruby-digest - 2.3.1-1
ruby-enc - 2.3.1-1
ruby-enc-extra - 2.3.1-1
ruby-erb - 2.3.1-1
ruby-filelib - 2.3.1-1
ruby-gems - 2.3.1-1
ruby-irb - 2.3.1-1
ruby-json - 2.3.1-1
ruby-math - 2.3.1-1
ruby-misc - 2.3.1-1
ruby-mkmf - 2.3.1-1
ruby-multithread - 2.3.1-1
ruby-net - 2.3.1-1
ruby-openssl - 2.3.1-1
ruby-optparse - 2.3.1-1
ruby-patterns - 2.3.1-1
ruby-prettyprint - 2.3.1-1
ruby-pstore - 2.3.1-1
ruby-psych - 2.3.1-1
ruby-racc - 2.3.1-1
ruby-rake - 2.3.1-1
ruby-rbconfig - 2.3.1-1
ruby-rdoc - 2.3.1-1
ruby-socket - 2.3.1-1
ruby-uri - 2.3.1-1
ruby-yaml - 2.3.1-1
ruby-zlib - 2.3.1-1
```

Still, when I try to install certain gems (`io-console` for example), it complains that the Ruby header files cannot be found: `mkmf.rb can't find header files for ruby at /opt/lib/ruby/include/ruby.h`

There is no `ruby` or `ruby-2.3` folder in `/opt/include/`

What can I do to get the Ruby header files?
Thanks!

**Comment by zyxmon** [comment]
>> In which wiki entry is this described?

The link is in the second post on this page.

**Comment by manuelmeurer** [comment]
As far as I can see, that wiki entry doesn't describe how to get the Ruby headers. The word "headers" is only mentioned once in the last sentence.
In my first post in this thread I listed the commands as described in the wiki entry and you said they are not correct. What are the correct ones?

**Comment by zyxmon** [comment]
Issues is for bug reporting and feature requests. Please reread thу wiki!

**Comment by manuelmeurer** [comment]
Ah, *that* wiki entry explains it! 😄 
Thanks so much for your help!

If anyone else happens upon this issue with the same question - this command installs the heads to `/opt/include`:

```
wget -qO- http://pkg.entware.net/binaries/armv7/include/include.tar.gz | tar xvz -C /opt/include
```

Replace `armv7` if your architecture differs.

**Comment by manuelmeurer** [comment]
For anyone else stumbling over this question, I solved my issue!
http://stackoverflow.com/questions/40572453/trying-to-install-ruby-gems-on-synology-diskstation-ds216j-cannot-find-ruby-hea

**Comment by manoloonline** [comment]
Hello Manuel,


Thank you very much for your efforts, solving the problem and keeping me informed. I will try the solution as soon as I can. It will be very useful to me.


Thanks again


Manuel Ibáñez




________________________________
De: Manuel Meurer <notifications@github.com>
Enviado: lunes, 14 de noviembre de 2016 9:19
Para: Entware-ng/Entware-ng
Cc: manoloonline; Author
Asunto: Re: [Entware-ng/Entware-ng] Package-Request: ruby-dev or ruby-devel (#223)


For anyone else stumbling over this question, I solved my issue!
http://stackoverflow.com/questions/40572453/trying-to-install-ruby-gems-on-synology-diskstation-ds216j-cannot-find-ruby-hea

-
