### ISSUE TITLE
3proxy 0.8.6-1 Library Dependencies Broken

### ISSUE THREAD

**Issue by MathewCNichols** [Entware-ng/Entware-ng#225]
3proxy package dependencies are borked for version 0.8.6-1. "ldd" cli command reports "Not found" for libdl.so.1, libpthread.so.1, libc.so.1, and also ld-uClibc.so.0 doesn't point to the /opt directory either. 

Doing a forced downgrade to 0.7.1.3-1 reports correct dependencies with root directories located in the /opt directory.

See here: http://screencast.com/t/4a5moPNHz5He 

Let me know if you need anything else from me!

Have a good eve!

**Comment by zyxmon** [comment]
Fixed: https://github.com/Entware-ng/rtndev/commit/bc2d0e257f98b83761a4f5513df9d34a279b8141
Binaries will arrive soon.

**Comment by MathewCNichols** [comment]
You rock! Thanks for all your work! Everything you do is greatly appreciated!
