### ISSUE TITLE
missing header files in libsqlite3

### ISSUE THREAD

**Issue by georgeef** [Entware-ng/Entware-ng#227]
libsqlite3 contains libs but not the associated header files. i had to copy sqlite3ext.h, sqlite3.h from a another installation in order to be able to use libsqlite3. but this is not convenient and i am not sure if the old headers are consistent with the latest lib. is it possible to add the header files in the package? they are small anyway.

**Comment by zyxmon** [comment]
Please read the wiki - https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-%28native-compilation%29
