### ISSUE TITLE
Package Request: GNU Emacs

### ISSUE THREAD

**Issue by sk8ingdom** [Entware-ng/Entware-ng#229]
It was previously available under Optware, although pretty outdated (version 22 vs. the current 25). Is it possible to include it in Entware? Thanks for all your hard work!

**Comment by zyxmon** [comment]
Emacs was not designed to be cross-compiled.
Cross-compilation is not straight forward. For example Emacs 23.4: https://github.com/kyak/openwrt-packages/tree/master/emacs requires host build (for lisp compilation) and qemu for other steps.
May be later we will try to build Emacs, not now.
