### ISSUE TITLE
Package request: rar2fs

### ISSUE THREAD

**Issue by kolyagora** [Entware-ng/Entware-ng#23]
Please add [rar2fs](https://github.com/hasse69/rar2fs) package.

**Comment by kolyagora** [comment]
I'm trying to make the package myself but I have no experience so I stuck at the beginning and hope to get some assistance here.

At first, I added my custom feed to `feeds.conf`:
```
...
src-link custom /opt/myfeed
```
Then I created `/opt/myfeed/rar2fs/Makefile` and added the package to the repo:
```
./scripts/feeds update custom
./scripts/feeds install rar2fs
```
The feed and the package appeared in corresponding `feeds` and `package/feeds` directories.
But it looks like `make package/rar2fs/compile` doesn't even start fetching the package's source code, however it builds the package's dependencies just fine (and all other packages I've tried). This is the output I get:
```
builder@1b9d5d40dc1f:/opt/entware/Entware-ng$ make package/rar2fs/compile
Collecting package info: done
 make[1] package/rar2fs/compile
 make[2] -C package/libs/toolchain compile
 make[2] -C feeds/packages/utils/unrar compile
 make[2] -C package/utils/fuse compile
 make[2] -C /opt/myfeed/rar2fs compile
```
`V=s` doesn't show any errors either. Sources are only get downloaded and extracted to `build_dir` as a result of explicit `make package/rar2fs/prepare` command. But even when source code is in the place, subsequent `make package/rar2fs/compile` doesn't try to do something with it.

I'm attaching the Makefile (added .txt extension just to be able to attach it here). Of course it's far from being complete but for now I just want to make it start doing something with the package's sources.

[Makefile](https://github.com/Entware-ng/Entware-ng/files/47795/Makefile.txt)

So what can be a reason for such strange behavior?

**Comment by ryzhovau** [comment]
This is normal behavior, after installing all packages from your feed, you have to mark it with `[m]` from `make menuconfig`. Some packages are marked to be compiled, some not. For more details, please refer OpenWrt Buildroot docs.

**Comment by kolyagora** [comment]
Thanks, it helped indeed. I've successfully built the package and been able to run it on my x86-64 NAS. However, it requires some manual tuning which I'd like to avoid. As stated in [rar2fs wiki](https://github.com/hasse69/rar2fs/wiki#q-15-why-do-i-need-the-complete-unrar-source-to-build-rar2fs), it requires complete unrar source and libunrar.so during the build. I'm using the following code in the Makefile to reference both:
```
CONFIGURE_ARGS += \
        --with-unrar=$(BUILD_DIR)/unrar-5.3.7/unrar \
        --with-unrar-lib=$(BUILD_DIR)/unrar-5.3.7/unrar
```
But, as you can see, it relies on unrar package version and its PKG_BUILD_ROOT format. Is there a way to achieve the same in a more appropriate manner?

[Makefile](https://github.com/Entware-ng/Entware-ng/files/48294/Makefile.txt)

**Comment by ryzhovau** [comment]
So what's performance of this binaries? I'm afraid it'll be painfully slow on MIPS or ARM routers.

**Comment by zyxmon** [comment]
>> Is there a way to achieve the same in a more appropriate manner?

Openwrt unrar package should be fixed. It is missing InstallDev section!

**Comment by kolyagora** [comment]
> So what's performance of this binaries? I'm afraid it'll be painfully slow on MIPS or ARM routers.

```
[~] # dd if=/share/CACHEDEV1_DATA/unrar/file.mkv of=/dev/null
769+1 records in
769+1 records out
12916117931 bytes (13 GB) copied, 132.067 s, 97.8 MB/s
```
I'm running QNAP TS-253 Pro powered by Celeron J1900 with 2 WD Red's in RAID1. Average CPU load was about 10% during the test.

**Comment by kolyagora** [comment]
> Openwrt unrar package should be fixed. It is missing InstallDev section!

It makes sense with the libunrar.so reference but what about requirement of having complete unrar source tree referenced by `--with-unrar`? I don't know which files rar2fs actually uses from it.

**Comment by kolyagora** [comment]
Ok, so I've modified unrar Makefile adding the folowing:
```
define Build/InstallDev
        $(INSTALL_DIR) $(STAGING_DIR)/opt/include/unrar
        $(CP) $(PKG_BUILD_DIR)/*.hpp $(STAGING_DIR)/opt/include/unrar
        $(INSTALL_DIR) $(STAGING_DIR)/opt/lib
        $(CP) $(PKG_BUILD_DIR)/libunrar.so $(STAGING_DIR)/opt/lib
endef
```
It allowed me to to change `CONFIGURE_ARGS` in the rar2fs Makefile to this:
```
CONFIGURE_ARGS += \
        --with-unrar=$(STAGING_DIR)/opt/include/unrar
```
It works and definitely looks better but does it looks good by openwrt/entware standards? I'd like to omit `--with-unrar` but rar2fs will only look for unrar subdir inside it's own directory in that case:
```
withval=
AC_ARG_WITH([unrar],
   [AS_HELP_STRING([--with-unrar=PATH],
               [search PATH to unrar source [PATH=./unrar]]
   )],
   [], [])
if test x"$withval" != x; then
    if test x"$withval" != x"no"; then
        if test x"$withval" != x"yes"; then
           UNRAR_CPPFLAGS="-I"$with_unrar
        fi
    fi
else
    with_unrar="./unrar"
    UNRAR_CPPFLAGS="-I./unrar"
fi
```
And modifying configure script doesn't look like a right decision.

**Comment by kolyagora** [comment]
I've sent a pull request openwrt/packages#2060 in order to get `Build/InstallDev` define added to unrar package.

**Comment by Noltari** [comment]
Hi @kolyagora,

I've fixed unrar in the following commit: https://github.com/openwrt/packages/commit/082314c49de900bf685b0016f353aa2594bab554

Now you should be able to build rar2fs without further issues.
I modified your rar2fs Makefile in order to get it working:
https://gist.github.com/Noltari/cb796028a7083d5d9b17

Regards,
Álvaro.

**Comment by kolyagora** [comment]
I've made a package and sent a PR to Openwrt: https://github.com/openwrt/packages/pull/2133. I've got no response still and since I don't use Openwrt itself I'd like to get the package added to Entware-ng. Should I send a PR to this repo or maybe https://github.com/Entware-ng/rtndev will be a better place?

**Comment by kolyagora** [comment]
@ryzhovau @zyxmon 
Any advice?

**Comment by ryzhovau** [comment]
I see no obstacles to add it, I think we can do it in next few days.
@zyxmon?

**Comment by zyxmon** [comment]
Why not?

**Comment by ryzhovau** [comment]
Done. Please, provide a feedback.
https://github.com/Entware-ng/rtndev/commit/5bf990785bdeadf131c29b0b613b12f4f2acb633

**Comment by kolyagora** [comment]
Thanks! I've successfully built it for x86-64 target, will test later.
One question though: what is the reason for adding `--with-libiconv-prefix=$(ICONV_PREFIX)` to `CONFIGURE_ARGS`?

**Comment by ryzhovau** [comment]
We've faced some troubles with different `iconv` implementations before. They are very different in `Glibc` and `uClibc`, so we relying on full blown external `libiconv` which is proven as working. Please, test this package with some non-ascii file names inside archives, it should work on UTF-8 systems.

**Comment by kolyagora** [comment]
I confirm it works well with Cyrillic file names inside archives.
