### ISSUE TITLE
Nethogs 

### ISSUE THREAD

**Issue by ded-al** [Entware-ng/Entware-ng#232]
Having an issue with nethogs running on entware-ng mispel, it is complaining about being root, when it's already root

creating socket failed while establishing local IP - are you root?

Any ideas to why this could be happening?

**Comment by zyxmon** [comment]
It works for my router )))

```NetHogs version 0.8.2-SNAPSHOT

    PID USER     PROGRAM       DEV        SENT      RECEIVED
  25490 root     dropbear      vlan1       0.884       0.135 KB/sec
      ? root     unknown TCP               0.000       0.000 KB/sec

  TOTAL                                    0.884       0.135 KB/sec```

**Comment by ded-al** [comment]
what could be preventing me from running it?  I have the updated version, running as root and I still get a kick back saying I am not root...

Linux version 3.10.101 (root@nmndev) (gcc version 5.1.0 (OpenWrt GCC 5.1.0 r45933) ) #12043 Fri Mar 25 09:25:25 CET 2016

**Comment by ded-al** [comment]
update to version 8.2 works
