### ISSUE TITLE
Package request: Spideroak

### ISSUE THREAD

**Issue by RoxKilly** [Entware-ng/Entware-ng#234]
Please add the SpiderOakONE client to enable NAS devices to perform cloud backups.  It's available for both 32 and 64bit architectures for Debian, Fedora and Slackware based Linux distributions.  https://spideroak.com/opendownload/ .

**Comment by ryzhovau** [comment]
There is no commercial services in this repo. Not sure SpiderOak client should be an exception, sorry.

**Comment by RoxKilly** [comment]
I did not know about the restriction. Thank you for your consideration.
