### ISSUE TITLE
CouchPotatoServer

### ISSUE THREAD

**Issue by marcosvrs** [Entware-ng/Entware-ng#237]
I instaled python2.7 and clone CouchPotato repository to my device, I made the init.d script for run the CouchPotatoServer, but it only runs when I execute it manually (_/opt/etc/init.d/S75couchpotato start_)...
The S75couchpotato script:
```
#!/bin/sh

ENABLED=yes
PROCS=/data/opt/etc/CouchPotatoServer/CouchPotato.py
ARGS="--daemon --quiet"
PREARGS=/data/opt/bin/python2.7
DESC=CouchPotato
PATH=/data/opt/sbin:/data/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
```
> /data/opt/etc/init.d # l
> total 8634
> -rwxr-xr-x    1 root     root         192 Jan 21 15:57 S52inadyn
> -rwxr-xr-x    1 root     root         180 Jan  9 14:27 S55portmap
> -rwxr-xr-x    1 root     root        1.8K Jan  9 14:27 S57nfs-kernel-server
> -rwxr-xr-x    1 root     root         192 Mar 24 07:03 S70mysqld
> -rwxr-xr-x    1 root     root         271 Apr  2 01:29 S75couchpotato
> -rwxr-xr-x    1 root     root         256 Mar 27 15:53 S76sickrage
> -rwxr-xr-x    1 root     root         297 Jan  9 14:27 S77ntpd
> -rwxr-xr-x    1 root     root         268 Feb 23 01:36 S88transmission
> -rw-------    1 root     root        8.4M Feb 19 02:49 core
> -rw-rw-rw-    1 root     root        2.7K Feb  3 09:28 rc.func
> -rwxrwxrwx    1 root     root         888 Feb  3 09:28 rc.unslung

> /data/opt/etc/CouchPotatoServer # l
> total 99
> -rw-rw-rw-    1 root     root         124 Feb  3 09:38 .coveragerc
> -rw-rw-rw-    1 root     root         240 Feb  3 09:38 .editorconfig
> drwxrwxrwx    1 root     root        8.0K Apr  2 17:21 .git
> drwxrwxrwx    1 root     root        8.0K Apr  2 17:14 .github
> -rw-rw-rw-    1 root     root         126 Feb  3 09:38 .gitignore
> -rw-rw-rw-    1 root     root          30 Feb  3 09:38 .nosetestsrc
> -rw-rw-rw-    1 root     root         635 Feb  3 09:38 .travis.yml
> -rwxrwxrwx    1 root     root        4.5K Feb  3 09:38 CouchPotato.py
> -rw-rw-rw-    1 root     root        5.6K Feb  3 09:38 Gruntfile.js
> -rw-rw-rw-    1 root     root        6.0K Apr  2 17:14 README.md
> -rw-rw-rw-    1 root     root        1.5K Feb  3 09:38 config.rb
> drwxrwxrwx    1 root     root        8.0K Apr  2 17:22 couchpotato
> drwxrwxrwx    1 root     root        8.0K Apr  2 17:14 init
> drwxrwxrwx    1 root     root        8.0K Apr  2 17:22 libs
> -rw-rw-rw-    1 root     root       34.3K Feb  3 09:38 license.txt
> -rw-rw-rw-    1 root     root         730 Feb  3 09:38 package.json
> -rw-rw-rw-    1 root     root          48 Feb  3 09:38 py-dev-requirements.txt
> -rw-rw-rw-    1 root     root          33 Feb  3 09:38 version.py

Any ideas?

Obs.: /opt are symlink from /data/opt

**Comment by zyxmon** [comment]
Startup scripts for python binaries are different. Something like (real example)

```
#!/bin/sh

prefix="/opt"
PATH=${prefix}/bin:${prefix}/sbin:/sbin:/bin:/usr/sbin:/usr/bin

daemon_status ()
{
        [ -n "`pidof deluge-web`" ]
}


start() {
	echo "starting deluge-web"
	deluge-web -f -p 888
	}

stop() {
	echo "stopping deluge-web"
	killall deluge-web
	}

case "$1" in
	start)
		if daemon_status
		then
			echo "deluge-web already running"
		else
			start
		fi
		;;
	stop)
		if daemon_status
		then
			stop
		else
			echo "deluge-web is not running"
		fi
		;;
	restart)
		if daemon_status
		then
			stop
		fi
		sleep 4
		if ! daemon_status
		then
			start
		fi
		;;
	status) 
		if daemon_status
		then
			echo "deluge-web is running"
		else
			echo "deluge-web is not running"
		fi
		;;
	*)
		echo "Usage: $0 (start|stop|restart|status)"
		exit 1
		;;
esac

```
