### ISSUE TITLE
joe (file editor) package does not work

### ISSUE THREAD

**Issue by bubbleguuum** [Entware-ng/Entware-ng#239]
Platform: Synology DS115J.

It installs fine:

opkg install joe

But running it results in this error:

$joe blargh.txt
Processing '/opt/etc/joe/joerc'...
Finished processing /opt/etc/joe/joerc
Missing or empty :querya keymap
rc file has no :main key binding section or no bindings.  Bye.

**Comment by zyxmon** [comment]
Fixed - https://github.com/Entware-ng/entware-packages/commit/dbc4f14b70ee23ead9dfdf5160ab93beddcc91d1

**Comment by bubbleguuum** [comment]
Thank you
