### ISSUE TITLE
request: libzen

### ISSUE THREAD

**Issue by Jorman** [Entware-ng/Entware-ng#242]
Hi, tnx for your works, it's possible to have also the libzen compiled?

**Comment by ryzhovau** [comment]
Please, describe your task. What are you trying to do?

**Comment by Jorman** [comment]
Hi, I'm trying to use the full functionality of filebot, I installed it manually, and I installed the mediainfo package from this repo, but filebot also use libzen, in order to do some action, so I've this error

```
filebot -script fn:sysinfo
Using persistent disk cache /share/CACHEDEV1_DATA/.qpkg/Entware-ng/share/filebot/data/admin/cache/0
FileBot 4.6.1 (r3718)
JNA Native: 4.0.1
MediaInfo: java.lang.UnsatisfiedLinkError: Unable to load library 'zen': Native library (linux-x86/libzen.so) not found in resource path ([file:/share/CACHEDEV1_DATA/.qpkg/Entware-ng/share/filebot/FileBot.jar])
Apache Commons VFS: [zip, ftps, rar, ftp, tar, tgz, tbz2, sftp]
Chromaprint: java.io.IOException: Cannot run program "fpcalc": error=2, No such file or directory
Extended Attributes: OK
Groovy Engine: 2.4.6
JRE: Java(TM) SE Embedded Runtime Environment 1.8.0_65 (headless)
JVM: 32-bit Java HotSpot(TM) Embedded Server VM
CPU/MEM: 4 Core / 668 MB Max Memory / 17 MB Used Memory
OS: Linux (i386)
Package: IPKG
Data: /opt/share/filebot/data/admin
uname: Linux Qnap 3.4.6 #1 SMP Mon Feb 1 00:49:49 CST 2016 x86_64 GNU/Linux
Done ヾ(＠⌒ー⌒＠)ノ
```

With the oldest optware I was able compile libzen for my machine (nas TS-269L) but with this entware I 'm not able to do that.

So I ask if is possible to add the libzen package in order to have also the libzen functionality

Tnx

**Comment by ryzhovau** [comment]
I see no sense to add some library into repo if it will not be used by any other package, so it's up to you. [Static libzen](https://github.com/Entware-ng/rtndev/blob/master/libzen/Makefile) is compiled for `mediainfo`, so you can [build](https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources) it and transfer to NAS.

Closing for now, sorry.

**Comment by Jorman** [comment]
Ok tnx. So if I understand well I need the shared library and I can use with the mediainfo that came from this repo.
Unfortunately I don't know how to use the info that you gave me.

**Comment by gravelld** [comment]
Looks like you're also missing `fp_calc`, for which you'll need #758 .
