### ISSUE TITLE
Можно добавить пакет kmod-usb-serial-ftdi

### ISSUE THREAD

**Issue by ASKOE** [Entware-ng/Entware-ng#249]
Можно добавить пакет kmod-usb-serial-ftdi?
Пробовал ставить с OpenWRT https://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/mt7620/packages/base/kmod-usb-serial-ftdi_3.18.23-1_ramips_24kec.ipk 
pkg_hash_fetch_best_installation_candidate: Packages for kmod-usb-serial-ftdi found, but incompatible with the architectures configured - не та версия я так понимаю.
Я использую Xiaomi Mi Mini c прошивкой Padavan (XRMWRT) собрана PROMETHEUS
Linux ASUS 3.4.111 #1 Sun Apr 17 22:04:35 MSK 2016 mips GNU/Linux 
Хочу подключить Arduino но нет модуля. Спасибо.

**Comment by ryzhovau** [comment]
Entware — прошивконезависимый проект  ядерных модулей в нём быть не может.

Ищите модули там же, где взяли прошивку.
