### ISSUE TITLE
rc.unslung find path

### ISSUE THREAD

**Issue by IL2** [Entware-ng/Entware-ng#25]
Please correct in
http://entware.zyxmon.org/binaries/mipsel/installer/rc.unslung
line
for i in $(find /opt/etc/init.d/ -perm '-u+x' -name 'S*' | sort $ORDER ) ;
to
for i in $(/opt/bin/find /opt/etc/init.d/ -perm '-u+x' -name 'S*' | sort $ORDER ) ;
due /usr/bin/find is
BusyBox v1.20.2 (2015-11-15 11:21:55 MST) multi-call binary
in john9527's firmware and doesn't recognize **-perm** switch.

**Comment by ryzhovau** [comment]
Thanks for the report. I've added:
```
. /opt/etc/profile
```
as the second string in `/opt/etc/init.d/rc.unslung` to make sure `$PATH` var is set as expected.

**Comment by IL2** [comment]
Thank you.

**Comment by ryzhovau** [comment]
`. /opt/etc/profile` appears not a good idea for most of NAS users, where full blown core utilities are available. So I added back a full path to `find` binary as you mentioned before.
