### ISSUE TITLE
Package request: seafile-server 5.1.1

### ISSUE THREAD

**Issue by jult** [Entware-ng/Entware-ng#252]
Has some crucial upgrades and patches included this time.
It's saying
"A new server version 5.0.4 is available."
and at the bottom it says
"Server Version: 5.0.0"

Don't know much about the packaging you did, or how seafile does that, but apparently I've not installed actual 5.0.6, but some mixture of seafile-server version files from your entware-ng package?

Seafile-server is now at 5.1.1, could you upgrade the -server -seahub -ccnet packages for entware-ng ? TIA!

**Comment by jult** [comment]
Or give me some hints on how to add them, or update the entware-ng package, and I will do what I can..

**Comment by zyxmon** [comment]
Package are updated once a month. Just wait. Monthly sync with owrt and updating is in progress now.

**Comment by zyxmon** [comment]
@jult - I have built seafile 5.1.1 but the seahub does not start and leaves no logs.
I can upload packages for your further investigations. What platform/feed I need to build for you.

**Comment by jult** [comment]
I can test it on an asustor ST604 nas, this is, I believe, just plain x86_64 for Intel Atom (2.13 GHz, Dual-Core).. In the near future I'll put it on a raspberry pi3B though.

**Comment by zyxmon** [comment]
You are to fix, not to test seafile. seahub does not start. It is a python application - so you do not need to compile anything to fix seahub.
Here are packages for fixing - http://pkg.entware.net/binaries/x86-64/test/

**Comment by jult** [comment]
I'll go check this out tomorrow, I think I know what causes seahub not to start. I had it before, even with the current release.

**Comment by zyxmon** [comment]
No fix found. Closing

**Comment by zyxmon** [comment]
Seafile 5.1.4 is in the repo. Teste and working.
Test were done with clean entware installation!
