### ISSUE TITLE
Package request: bluez5, sbc

### ISSUE THREAD

**Issue by jpap** [Entware-ng/Entware-ng#253]
I'm looking to set up a bluetooth audio sink on my R7000, coexisting with an AirPlay (shairport-sync) server, which plays out of a USB audio device.  (The AirPlay part is working well.)

I've got a CSR bluetooth USB dongle up and running on my R7000 with kernel modules
```
btusb                   8804  1 
hidp                   11083  0 
rfcomm                 32113  0 
l2cap                  38413  4 hidp,rfcomm
bluetooth              49660  4 btusb,hidp,rfcomm,l2cap
```
and am trying to follow [this OpenWRT guide](https://wiki.openwrt.org/doc/howto/bluetooth.audio), that depends on **bluez5** and **sbc**.

**Comment by ryzhovau** [comment]
The newer version of bluez is incompatible with k2.6.22 based toolchain, so there's no chance to add it.

**Comment by zyxmon** [comment]
@jpap bluez(5) is now in Entware-3x repository (a fork for newer kernels)
https://github.com/Entware-for-kernel-3x
