### ISSUE TITLE
Package Request: lua-zlib

### ISSUE THREAD

**Issue by Loader23** [Entware-ng/Entware-ng#254]
I need the lua-zlib module for Prosody. Can u provide a package for that or is there any other way of installing it?

**Comment by zyxmon** [comment]
May be lua-lzlib  - https://github.com/openwrt/packages/tree/master/lang/lua-lzlib

**Comment by Loader23** [comment]
Prosdy says, it has to be brimworks zlib: https://github.com/brimworks/lua-zlib 
But i would test the other one, if you can tell me how i can install it ;-)

**Comment by zyxmon** [comment]
It is not in the repo. You cannot test it.

**Comment by Loader23** [comment]
Ok, please create a Packacke for Entware then, would be great :-)

**Comment by zyxmon** [comment]
Closing for now.
