### ISSUE TITLE
znc won't run

### ISSUE THREAD

**Issue by jongray** [Entware-ng/Entware-ng#255]
I've installed Entware-ng 0.97 on a QNAP TS-119P+ using the auto-detecting installer.

I then installed znc using opkg and then installed all of the znc-mod-* module packages (the majority of which I can see in /opt/share/znc/modules

All of the init.d scripts appear to be in place and run correctly.  However, when I run the same znc command manually I get the following error.  I presume this is why the init.d script runs to completion but after which znc is not running.

`[~] # znc -d /opt/share/znc`
`[ .. ] Checking for list of available modules...`
`[ !! ] failed`
`[ ** ] No modules found. Perhaps you didn't install ZNC properly?`
`[ ** ] Read http://wiki.znc.in/Installation for instructions.`
`[ ?? ] Do you really want to run ZNC without any modules? (yes/no) [no]: `

**Comment by zyxmon** [comment]
I think the script in init.d is obsolete. Please try to google for the solution. May be some initial setup is required. I thing znc should not be run from admin/root.

**Comment by jongray** [comment]
After some more digging it appears that everything is in the right place and should work.  However, running strace on the znc executable yields the following results.  For some reason it finds the module libraries, opens them but then still returns failure.

```
open("/opt/lib/znc/webadmin.so", O_RDONLY|O_CLOEXEC) = 5
read(5, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0000e\0\0004\0\0\0"..., 512) = 512
fstat64(5, {st_mode=S_IFREG|0755, st_size=211984, ...}) = 0
mmap2(NULL, 276136, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 5, 0) = 0xb69fa000
mprotect(0xb6a2d000, 65536, PROT_NONE)  = 0
mmap2(0xb6a3d000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 5, 0x33000) = 0xb6a3d000
close(5)                                = 0
munmap(0xb69fa000, 276136)              = 0
open("/opt/lib/znc/fail2ban.so", O_RDONLY|O_CLOEXEC) = 5
read(5, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\270)\0\0004\0\0\0"..., 512) = 512
fstat64(5, {st_mode=S_IFREG|0755, st_size=23472, ...}) = 0
mmap2(NULL, 87624, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 5, 0) = 0xb6a28000
mprotect(0xb6a2e000, 61440, PROT_NONE)  = 0
mmap2(0xb6a3d000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 5, 0x5000) = 0xb6a3d000
close(5)                                = 0
munmap(0xb6a28000, 87624)               = 0
write(1, "\33[1m\33[34m[\33[31m !! \33[34m]\33[39m\33["..., 62[ !! ] failed
) = 62
write(1, "\33[1m\33[34m[\33[31m ** \33[34m]\33[39m\33["..., 95[ ** ] No modules found. Perhaps you didn't install ZNC properly?
) = 95
write(1, "\33[1m\33[34m[\33[31m ** \33[34m]\33[39m\33["..., 91[ ** ] Read http://wiki.znc.in/Installation for instructions.
) = 91
write(1, "\33[1m\33[34m[\33[33m ?? \33[34m]\33[39m\33["..., 102[ ?? ] Do you really want to run ZNC without any modules? (yes/no) [no]:
```

If these module libraries were successful to open then by default the first time it's run it would create a configuration file.  This means the command needs to be run successfully once but after that would presumably work as part of init.

**Comment by zyxmon** [comment]
Just as a guess. May be one should create config first (with -c -r) and edit it to enable libraries.
The config is created - I have checked it.

**Comment by jongray** [comment]
I did that and edited to load one of the modules (webadmin - I think the most common).  I then get the failure below.  Is this something to do with compilation or me missing a library?

```
[/opt/share/znc/configs] # znc --datadir=/opt/share/znc -r
[ .. ] Checking for list of available modules...
[ !! ] failed
[ ** ] No modules found. Perhaps you didn't install ZNC properly?
[ ** ] Read http://wiki.znc.in/Installation for instructions.
[ ?? ] Do you really want to run ZNC without any modules? (yes/no) [no]: yes
[ >> ] ok
[ .. ] Opening config [/opt/share/znc/configs/znc.conf]...
[ >> ] ok
[ .. ] Loading global module [webadmin]...
[ !! ] Unable to open module [webadmin] [/opt/lib/znc/webadmin.so: undefined symbol: __sync_fetch_and_add_4]
[ ** ] Unrecoverable config error.
```

**Comment by zyxmon** [comment]
It looks like this bug is in armv5 version only. I'll have time for more investigations in a week.

**Comment by zyxmon** [comment]
You can try to use these ipk - http://pkg.entware.net/binaries/armv5/test/

It looks like everything is ok:

```
[~] # znc -r -c
[ .. ] Checking for list of available modules...
[ >> ] ok
...
```

**Comment by jongray** [comment]
Installed all of those packages and running znc (including modules webadmin, chansaver, controlpanel and simple_away), all running fine.

Thank you!

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/entware-packages/commit/427221dd88e435ba4c346a2c894c020e046e7ce8
