### ISSUE TITLE
freeradius with mysql not works

### ISSUE THREAD

**Issue by MrDini123** [Entware-ng/Entware-ng#256]
Hi!

I have just installed the entware-ng to my tomato based asus router. (Mipsel) My router's memory is too small, So I had to install it to an nfs share, but it works nice.

And I decided to install the freeradius package. It works nice if I put the users into the "users" file, but I have a mysql server when I store the account's, So I installed the freeradius2-mod-sql and the freeradius2-mod-sql-mysql package, and I set up the sql.conf and in the sites/default I uncommented the sqls. After it I tried to run it as debugger, but it says this if I start it:

```
/opt/etc/freeradius2/sites/default[177]: Failed to find "sql" in the "modules" section.
/opt/etc/freeradius2/sites/default[69]: Errors parsing authorize section.
```

What's wrong?

And one more thing... I Can't find the radtest binary in the freeradius packages. So please include it to the freeradius package, because (I think) it is a very useful thing for tests.

Thanks!

Ps: sorry for my bad English...

**Comment by MrDini123** [comment]
Nobody Can help me?

**Comment by ryzhovau** [comment]
We have no time to reproduce it as we can't be guru in every existing package.

So, freeradius2 configuration is up to you or other users. Freeradius2 built exactly as in OpenWrt, so you may find some useful info on their forum.

Closing for now.

**Comment by MrDini123** [comment]
Ok. After that try, I compiled freeradius 2.2.8 for myself and it works perfectly.
