### ISSUE TITLE
make tools with gccgo failed

### ISSUE THREAD

**Issue by hshh** [Entware-ng/Entware-ng#257]
Hi
I can't make tools if include gccgo.
I have to comment out CONFIG_INSTALL_GCCGO and Go packages to build tools.

System: Ubuntu 16.04 x86_64
Here is build log,

/opt/entware-ng-arm/Entware-ng/staging_dir/host/go/pkg/tool/linux_amd64/6l -o ego -L $WORK -extld=gcc $WORK/_/opt/entware-ng-arm/Entware-ng/build_dir/host/go.1.4.2/src/cmd/go.a
_/opt/entware-ng-arm/Entware-ng/build_dir/host/go.1.4.2/src/cmd/go
/tmp/go-build715716247/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
/tmp/go-build715716247/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 298
runtime/cgo(.text): unexpected relocation type 298
Makefile:33: recipe for target '/opt/entware-ng-arm/Entware-ng/build_dir/host/go.1.4.2/.built' failed
make[2]: *** [/opt/entware-ng-arm/Entware-ng/build_dir/host/go.1.4.2/.built] Error 2
make[2]: Leaving directory '/opt/entware-ng-arm/Entware-ng/tools/go-src'
tools/Makefile:135: recipe for target 'tools/go-src/compile' failed
make[1]: *** [tools/go-src/compile] Error 2
make[1]: Leaving directory '/opt/entware-ng-arm/Entware-ng'
/opt/entware-ng-arm/Entware-ng/include/toplevel.mk:192: recipe for target 'tools/install' failed
make: *** [tools/install] Error 2

**Comment by zyxmon** [comment]
You can use another linux distro (debian jessie does not have this problem) or try to upgrade go sources - that do no have this problem. If you do not need go - just disable go in `make menuconfig`.

**Comment by evs38** [comment]
Fixed in go 1.5.3+, please update.
 #https://github.com/golang/go/issues/13114
 #https://github.com/golang/go/issues/13896
