### ISSUE TITLE
Package Request: Chromaprint (fpcalc)

### ISSUE THREAD

**Issue by giopas** [Entware-ng/Entware-ng#258]
Would it be possible to have Chromaprint [1], and relating fpcalc tool, added to Entware-ng repository?

> Chromaprint is the core component of the AcoustID project [2]. It's a client-side library that implements a custom algorithm for extracting fingerprints from any audio source.

> Acoustic fingerprinting is a technique for identifying songs from the way they “sound” rather from their existing metadata. That means that beets’ autotagger can theoretically use fingerprinting to tag files that don’t have any ID3 information at all (or have completely incorrect data).

This will be very useful as currently if you try to use Chromaprint/Acoustid plugin of Beets [3], which you can install using pip through Entware-ng with a simple "pip install pyacoustid", you should still compile Chromaprint to make the plugin working.

By the way fpcalc is also used by filebot.

Thank you!

giopas

[1] https://acoustid.org/chromaprint
[2] http://beets.readthedocs.org/en/latest/plugins/chroma.html
[3] http://beets.readthedocs.org/en/latest/index.html

**Comment by ryzhovau** [comment]
No plans to add it, sorry.
