### ISSUE TITLE
Please add uvcdynctrl to available packages

### ISSUE THREAD

**Issue by dgalimov** [Entware-ng/Entware-ng#259]
uvcdynctrl - is a command line tool to control webcam parameters on the fly.

It is small, so there shouldn't be a problem to use them in routers.

​http://packages.ubuntu.com/precise/libs/uvcdynctrl

openwrt alredy has it https://github.com/openwrt/packages/blob/master/utils/uvcdynctrl/Makefile

**Comment by ryzhovau** [comment]
It's incompatible with our MIPS k2.6.22 based toolchain, some of UVC controls is V4L2 here, some other is still ancient V4L1.

**Comment by dgalimov** [comment]
Hmm, is it possible to upgrade to V4L2 then?

**Comment by dgalimov** [comment]
It seems that it is a small package - http://packages.ubuntu.com/precise/uvcdynctrl-data - just 55 kb

**Comment by ryzhovau** [comment]
> Hmm, is it possible to upgrade to V4L2 then?
No, we'll throw off support of too many devices then.

**Comment by dgalimov** [comment]
Maybe creating a separate branch will help?

**Comment by ryzhovau** [comment]
If so, who's going to support it?

**Comment by dgalimov** [comment]
What is required to support the branch? ;-)

**Comment by dgalimov** [comment]
I can try but I'm not sure what is required to support it. I have Asus RT-N56U router and can test the new branch on it.

**Comment by ryzhovau** [comment]
> What is required to support the branch? ;-)

* Fork Entware project,
* Modify toolchain,
* Host compiled *.ipk package somewhere.

Entware used widely on very different devices, that's why k2.6.22 based toolchain here. We can't support several MIPS feeds for different devices, so it's up to you.

**Comment by dgalimov** [comment]
Could you please provide more info and how-to? Can you contact me on skype? danila.galimov

**Comment by ryzhovau** [comment]
Not sure I'm ready to provide personal support, sorry.

**Comment by zyxmon** [comment]
@dgalimov uvcdynctrl is added to Entware-3x
https://github.com/Entware-for-kernel-3x

**Comment by dgalimov** [comment]
Cool, thank you! How can I use it on Asus RT-N56U router ( mipsel) ?

**Comment by dgalimov** [comment]
It seems to be still missing on mipsel branch 
```
/opt/home/admin # opkg install uvcdynctrl
Unknown package 'uvcdynctrl'.
Collected errors:
 * opkg_install_cmd: Cannot install package uvcdynctrl.

```

**Comment by zyxmon** [comment]
>> It seems to be still missing on mipsel branch

It is present in Entware-3x only.
