### ISSUE TITLE
mjpg-streamer doesn't return control when started in daemon mode

### ISSUE THREAD

**Issue by dgalimov** [Entware-ng/Entware-ng#260]
Startup script should return control to the caller, however, it seems that mjpg-streamer doesn't do that even when started with -b switch - it requires any key to be pressed afterwards.

I solved this by editing /opt/etc/init.d/S96mjpg-streamer by piping yes to it:

yes | mjpg_streamer -b ...

However, I believe that this is a problem with mjpg-streamer itself - maybe extra getch() call or something like that in the sources.

Please fix.

**Comment by ryzhovau** [comment]
We can't upgrade mjpg-streamer, because our MIPS toolchain is based on old 2.6.22 kernel. Some of kernel interfaces is still belongs to legacy V4L, some other interfaces already belongs to newer V4L2. That's why I'n not sure `uvcdynctrl` or other utilities will work as expected.

**Comment by dgalimov** [comment]
Then, at least, you can implement my workaround - I think it wouldn't hurt much.

As for  uvcdynctrl - I can try it if you give me the binary

**Comment by ryzhovau** [comment]
I'm still no idea what feed you are using.

**Comment by dgalimov** [comment]
I'm using  http://entware.wl500g.info/binaries/entware/Packages.gz.
My hardware is ASUS RT-N56U, so I assume I'm on mipsel

**Comment by ryzhovau** [comment]
This is obsolete feed from Entware, which is abandoned in October 2015. Please, consider [upgrade to Entware-ng](https://github.com/Entware-ng/Entware-ng/wiki/Upgrade-from-Entware).

**Comment by dgalimov** [comment]
I upgraded successfully, but still have to pipe yes to mjpg_streamer

**Comment by ryzhovau** [comment]
Not sure `yes` binary is present on any system but `yes | ...` will work in any case. Thanks for workaround, now it's in repo.
