### ISSUE TITLE
Incorrect motion.conf file location

### ISSUE THREAD

**Issue by dgalimov** [Entware-ng/Entware-ng#261]
When I'm adding motion package, motion.conf file is placed as /opt/etc/motion.conf.

However, it is not working: if you execute motion -h, it will say:

_Motion is configured using a config file only. If none is supplied,
it will read motion.conf from current directory, ~/.motion or /opt/etc/motion._

I moved motion.conf to **/opt/etc/motion/motion.conf** and now it is working as expected.

Please update installer so it will create the motion.conf file in the correct directory (or adjust /opt/etc/init.d/S99motion to use -c parameter for current file location)

**Comment by zyxmon** [comment]
fixed - https://github.com/Entware-ng/entware-packages/commit/5820c6b23a35e0be7c2963ee61769c5107463160
