### ISSUE TITLE
How to safely remove busybox

### ISSUE THREAD

**Issue by dgalimov** [Entware-ng/Entware-ng#262]
I installed busybox package and now some of the build-in scripts does not work correctly.

I'm trying to remove busybox but getting this message:

_/opt/home/admin # opkg remove busybox
Refusing to remove essential package busybox.
        Removing an essential package may lead to an unusable system, but if
        you enjoy that kind of pain, you can force opkg to proceed against
        its will with the option: --force-removal-of-essential-packages
No packages removed.
/opt/home/admin #_

How can I safely remove busybox from entware and revert to router build-in busybox implementation?

**Comment by zyxmon** [comment]
What hardware is used? What build-in scripts fail?

**Comment by dgalimov** [comment]
I'm using ASUS RT-N56U router

This command doesn't work:

/opt/bin # mtd_storage.sh save
touch: invalid option -- h
BusyBox v1.23.2 (2015-09-22 16:45:13 MSK) multi-call binary.

Usage: touch [-c] FILE...

Update the last-modified date on the given FILE[s]

        -c      Don't create files

Save storage files to MTD partition "/dev/mtdblock5"
Error! Invalid storage final data size:

**Comment by dgalimov** [comment]
the source of this file is here - https://cloud.mail.ru/public/DciG/qL4cKzb1y

**Comment by dgalimov** [comment]
It seems that endware busybox is compiled with different options:

/opt/home/admin # /bin/touch
BusyBox v1.23.2 (2015-06-01 13:27:33 KRAT) multi-call binary.

Usage: touch [-c] [-d DATE] [-t DATE] [-r FILE] FILE...

Update the last-modified date on the given FILE[s]

        -c      Don't create files
        -h      Don't follow links
        -d DT   Date/time to use
        -t DT   Date/time to use
        -r FILE Use FILE's date/time

/opt/home/admin # /opt/bin/touch
BusyBox v1.23.2 (2015-09-22 16:45:13 MSK) multi-call binary.

Usage: touch [-c] FILE...

Update the last-modified date on the given FILE[s]

        -c      Don't create files

**Comment by zyxmon** [comment]
You have a lot of solutions: manually remove symlink /opt/bin/touch, install coreutils-touch package, remove busybox with -force..... flag.

**Comment by dgalimov** [comment]
Yes, this works for me, thank you!
