### ISSUE TITLE
Package Update Request: Libsodium 1.0.10

### ISSUE THREAD

**Issue by AtAM1** [Entware-ng/Entware-ng#264]
Please update libsodium as the current available entware package is outdated. Thanks

**Comment by ryzhovau** [comment]
May I ask: which killer feature appeared between 1.0.8 and 1.0.10 for you needs? Which bug was fixed, that bother you now?

**Comment by AtAM1** [comment]
Not necessarily killer features but security-based packages should always be updated
- Countermeasures for Ed25519 signatures malleability have been added
to match the irtf-cfrg-eddsa draft (note that malleability is irrelevant to
the standard definition of signature security). Signatures with a small-order
`R` point are now also rejected.
- The HChaCha20 core function was implemented (`crypto_core_hchacha20()`)

**Comment by ryzhovau** [comment]
Done.
