### ISSUE TITLE
Package Update Request: xl2tpd v1.3.7

### ISSUE THREAD

**Issue by hellblue** [Entware-ng/Entware-ng#265]
Please update xl2tpd as the current available entware package is outdated. Thanks

https://github.com/xelerance/xl2tpd/releases/tag/v1.3.7

i have some trouble with xl2tpd - devel-20151125-1b on my asus rtn-66u with different shibby tomato firmware versions 1.32-1.36
i have to restart the service often and can not connect to my ipsec vpn 
sometimes the service xl2tpd seems to be running but nothing happens when i look into the logfile an tries to connect

**Comment by zyxmon** [comment]
done
https://github.com/Entware-ng/entware-packages/commit/ea498a1fe58a2622e73f44a8a0da338f90162605
binaries will arrive soon

**Comment by hellblue** [comment]
thank you, now it works like a charm,
i have not to restart xl2tpd since i updated the package
