### ISSUE TITLE
Package request: djbdns for mips

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-ng/Entware-ng#267]
Including the dependency packages: 
1. daemontools 0.70 or above
2. ucspi-tcp

**Comment by ProBackup-nl** [comment]
There are already OpenWrt packages at http://milksnot.com/stuff/openwrt/ for:
1. daemontools 0.76
2. djbdns-axfrdns
3. djbdns-base
4. djbdns-dnscache
5. djbdns-rbldns
6. djbdns-tinydns
7. djbdns-tools
8. djbdns-walldns
9. ucspi-tcp
And there is some stuff at https://dev.openwrt.org/browser/packages/net/djbdns?order=name

**Comment by ryzhovau** [comment]
I see no sense to add DNS server which is abandoned 15 years ago.

**Comment by ProBackup-nl** [comment]
Djbdns has a low memory footprint, it doesn't read the whole zone file into memory. And djbdns requires less steps to configure new zones. Djbdns is patched for ipv6 and dnssec.
In case you don't want to invest time, let me do the puzzling. I am already configuring a development environment like described in https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources. A hello-world example to add a new package is welcome.

**Comment by ProBackup-nl** [comment]
I see less sense now I have learned that the included dnsmasq should be able to run an authoritative dns server.

**Comment by ProBackup-nl** [comment]
Apparently Padavan 3.0.3.7 is not able to run dnsmasq authoritative:
```
Dec  8 18:29:52 dnsmasq[4964]: unsupported option (check that dnsmasq was compiled with DHCP/TFTP/DBus support) at line 5 of /etc/storage/dnsmasq/dnsmasq.conf
Dec  8 18:29:52 dnsmasq[4964]: FAILED to start up
```
Line number 5:
`auth-server=domain.tld,eth3`

Neither does auth. dnsmasq work with recent Padavan 3.4.3.9-099 firmware version.
