### ISSUE TITLE
Package request: megatools

### ISSUE THREAD

**Issue by thomkaufmann** [Entware-ng/Entware-ng#269]
Can you please add the command line tool for Mega, [megatools](https://github.com/megous/megatools)?

I see it was [recently added to optware-ng](https://github.com/Optware/Optware-ng/issues/19).

Thanks!

**Comment by ryzhovau** [comment]
We won't put half-working package to repo, that's why `megatools` is [still in our graveyard](https://github.com/Entware-ng/graveyard/tree/master/megatools):)

**Comment by diman82** [comment]
Why do you call it a 'half-working package'? It's a fukky operational project ongoing more than 3 years, and as an evidence Optware added this package..
