### ISSUE TITLE
Can't stop XMail 1.27

### ISSUE THREAD

**Issue by aromuk** [Entware-ng/Entware-ng#27]
Hi,
i can't stop or killall xmail (1.27) process on 2 RT-N65U routers. Removal of pid file is also without result. Therefore can't safe remove USB disk.
While xmail continues to send and receive emails, as if nothing had happened.
I hope You will check it.

**Comment by zyxmon** [comment]
Have you tried `kill -INT <pid>` or `kill -2 <pid>` as google suggests?

**Comment by aromuk** [comment]
Thank You for answer.
with pid numbers xmail terminates well, with both commands.
Well, something wrong with supplied xmail's init.d startup script, but my skills not enough to check it out.

Old xmail versions works well with rc.func script, but 1.27 don't want to turn off even through script supplied... Lost automation of reboot/safe disk removing from padavan's router interface...

**Comment by zyxmon** [comment]
There is no startup script for xmail. We will add such a script to the package when the users of xmail will give us a script they have tested.
