### ISSUE TITLE
Mosh connection from mac to rt-n56u fails with "Did not find mosh server startup message."

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-ng/Entware-ng#270]
I did install Mosh on both a Mac OS X (10.9.5) machine, a Debian 8 VM, and as Entware-ng package on a RT-N56U_3.4.3.9-099_base.trx. Mosh version on the Mac is 1.2.5. All machines are configured to ssh login with certificates. Mac OS X shell is zsh.

Connecting Mosh from Mac to Debian in a 10.x pvm_nat LAN (parallels virtual machine shared networking) works **ok**: $ mosh username@10.x.x.x

Connecting Mosh from Mac to the rt-n56u at 192.168.x using a cabled LAN, fails with "**/usr/local/bin/mosh: Did not find mosh server startup message.**" after running command: $ mosh username@192.168.x.x

_Regression_
1. I did try to disable the firewall on the Mac with no improvement, still: **/usr/local/bin/mosh: Did not find mosh server startup message.**

2. I did also try to start a debug session using: 
```
$ ssh -S none -o ProxyCommand='mosh --fake-proxy -- %h %p' -n -tt user@192.168.x.x -- 'mosh-server new'
MOSH IP 192.168.x.x
Connection to 192.168.x.x closed.
```
3. I commented out SendEnv on the Mac:
$ cat /etc/ssh_config | grep SendEnv
#   SendEnv LANG LC_*

The rt-n56u log displays this:
```
May  3 00:42:15 dropbear[819]: Child connection from 192.168.x.y:50824
May  3 00:42:17 dropbear[819]: Pubkey auth succeeded for 'username' with key md5 2c:...:94 from 192.168.x.y:50824
May  3 00:42:18 dropbear[820]: ioctl(TIOCSCTTY): Input/output error
May  3 00:42:18 dropbear[820]: /dev/pts/0: No such file or directory
May  3 00:42:18 dropbear[820]: open /dev/tty failed - could not set controlling tty: No such device or address
May  3 00:42:18 dropbear[819]: Exit (username): Disconnect received
```
On the rt-n56u:
```
# ls -l /dev/pts/*
crw--w--w-    1 username   root      136,   0 May  3 00:45 /dev/pts/0
# ls -l /dev/tty
crw-rw----    1 username   root        5,   0 Jan  1  2015 /dev/tty
```
What to improve to mosh connect my Mac to rt-n56u?

**Comment by ryzhovau** [comment]
Just tried to connect to RT-N14U with OpenSSH from Padavan's firmware with no issues:
```
mosh --ssh="ssh -i ~/private.key" --server=/opt/bin/mosh-server admin@my.router
```
Closing this, works for me.
