### ISSUE TITLE
iptables miss match `account`and`TRIGGER'

### ISSUE THREAD

**Issue by houzi-** [Entware-ng/Entware-ng#271]
use `iptables-save` in tomato-shibby
error:
```
Can't find library for match `account'
```
In the DD-WRT is under
```
Can't find library for target `TRIGGER'
```

What should I do to solve this problem？

**Comment by zyxmon** [comment]
iptables is not fully functional. it was compiled for systems missing iptables in firmware.
use tomato or dd-wrt versions of iptables.

**Comment by Xentrk** [comment]
I find issues with iptables in dd-wrt.  What has worked for me sometimes, is replacing iptables-save with iptables -L.
