### ISSUE TITLE
Package Update Request: Aria2 1.23

### ISSUE THREAD

**Issue by MacQwerty** [Entware-ng/Entware-ng#272]
I would like to have Aria2 updated from 1.20.0-1 to 1.23 as there are several bugs fixed and added features. See changes in the links below. Thanks in advance!

[Aria2 1.23 Release Note, Changes and Download Links](https://github.com/aria2/aria2/releases/tag/release-1.23.0)
[Aria2 1.22 Release Note, Changes and Download Links](https://github.com/aria2/aria2/releases/tag/release-1.22.0)
[Aria2 1.21 Release Note, Changes and Download Links](https://github.com/aria2/aria2/releases/tag/release-1.21.0)

**Comment by zyxmon** [comment]
done - https://github.com/Entware-ng/entware-packages/commit/717798880d94d902005e068ebdfcf7cb23e2d268
