### ISSUE TITLE
Package request: rdist 6.1.5

### ISSUE THREAD

**Issue by protogen** [Entware-ng/Entware-ng#274]
I use rdist to manage a bunch of machines from a central config repository.  I would like to be able to do the same with my new shiny Asuswrt-Merlin router.  Thanks.

```
[937] root@server:~ # /usr/local/bin/rdist -V
Version 6.1.5 (RELEASE) - Protocol Version 6, Release 6.1, Patch level 5
[938] root@server:~ #
```

**Comment by ryzhovau** [comment]
I see no sense to add utility, which is abandoned eight years ago, sorry.
