### ISSUE TITLE
freeradius2 packages are EOL upstream

### ISSUE THREAD

**Issue by graysky2** [Entware-ng/Entware-ng#277]
Is it feasible to supply the version 3.0.x series of freeradius since upstream has [deprecated](http://freeradius.org/download.html) the version 2.2.x series in 12-2014?

**Comment by ryzhovau** [comment]
Please, see https://github.com/Entware-ng/Entware-ng/issues/248

**Comment by graysky2** [comment]
Sorry, didn't search all issues, just open ones... is an update to 2.2.9 possible?

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/entware-packages/blob/master/net/freeradius2/Makefile

**Comment by graysky2** [comment]
Thanks!  Upstream is still providing security fixes to the 2.2.x series so this is a value-added update for sure.
