### ISSUE TITLE
Custom package 'make' results in error #2 on /opt/Entware-ng/include/toplevel.mk:192: recipe for target 'package/xyz' failed

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-ng/Entware-ng#278]
Trying to enhance Padavan firmware with an Entware-ng package, I am trying to add a package myself.
I have read [OpenWRT Creating packages](https://wiki.openwrt.org/doc/devel/packages).

To not have all issues the first attempt is to "port" an OpenWRT package. In this attempt I use: [ucscp-tcp](https://dev.openwrt.org/browser/packages/net/ucspi-tcp).

Some files/directories have been created on the build system:
1. /opt/Entware-ng/package/network/utils/ucspi-tcp
2. /opt/Entware-ng/package/network/utils/ucspi-tcp/Makefile
3. /opt/Entware-ng/package/network/utils/ucspi-tcp/patches
4. /opt/Entware-ng/package/network/utils/ucspi-tcp/patches/100-cross_compile.patch

The Makefile has one adaptation for the submenu "Utils":
```
define Package/ucspi-tcp
  SECTION:=net
  CATEGORY:=Network
  SUBMENU:=Utils
  DEPENDS:=
  TITLE:=UNIX Client-Server Program Interface for TCP
  URL:=http://cr.yp.to/ucspi-tcp.html
endef

define Package/PKG_NAME/description.
        tcpserver and tcpclient are command-line tools for building
        TCP client-server applications.
endef
```
I did ran a `make oldconfig` after receiving the warning that "my configuration is out of sync", and choose <kbd>m</kbd> for the newly detected package.
Now to package make command returns an error:
```
$ make -j1 package/ucspi-tcp V=s
make[1]: Entering directory '/opt/Entware-ng'
make[1]: *** No rule to make target 'package/ucspi-tcp'.  Stop.
make[1]: Leaving directory '/opt/Entware-ng'
/opt/Entware-ng/include/toplevel.mk:192: recipe for target 'package/ucspi-tcp' failed
make: *** [package/ucspi-tcp] Error 2
```
The offending line is:
```
$ sed -n -e 192p /opt/Entware-ng/include/toplevel.mk
	@+$(PREP_MK) $(NO_TRACE_MAKE) -r -s prereq
```
Could you offer any help what might go wrong in the make process of this new package?

**Comment by zyxmon** [comment]
Read the wiki - https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources
Investigate existing packages.

**Comment by zyxmon** [comment]
no responce. closing
