### ISSUE TITLE
Package update request: erlang/otp 18.3

### ISSUE THREAD

**Issue by aglyzov** [Entware-ng/Entware-ng#279]
Please update Erlang/OTP to the latest (18.3 at the moment).
It was quite a major update to the language and the runtime.
I need this to run Elixir programs (a language using the Erlang VM).

**Comment by zyxmon** [comment]
We update our packages after openwrt. It has still 17.5 version - https://github.com/openwrt/packages/blob/master/lang/erlang/Makefile
