### ISSUE TITLE
Request: rblibtorrent New Build

### ISSUE THREAD

**Issue by mscaff** [Entware-ng/Entware-ng#28]
Hi All,

Seems the entware implementation of the rblibtorrent/deluge lacks working proxy support.

According to Deluge developers, this is most likely in relation to rblibtorrent not being the latest - however I lack the skills or know how in order to build the latest version for entware.
If anyone can spare the time, I would really appreciate it if someone could port the latest build of rblibtorrent for Deluge.

Thanks!
Matt

**Comment by zyxmon** [comment]
rblibtorrent in Entware is 1.0.5 (released in may 2015). I can try to build the latest 1.0.7 version for you for testing. But I do not know your feed/architecture (armv5, arvmv7, x86-??).

**Comment by mscaff** [comment]
Thanks Zyxmon!

I am currently using a QNAP TS-453 Pro x86 - it's running QNAPWARE but as advised here http://qnap.community/viewtopic.php?t=119 - you will be providing a guide to upgrade to entware-ng shortly, so I will upgrade to that once available.

If you need any further information please let me know, thanks heaps!
Matt

**Comment by zyxmon** [comment]
The instructions a here (in wiki) and here - http://forum.qnap.com/viewtopic.php?f=351&t=116737

**Comment by mscaff** [comment]
Awesome! Thanks Zyx, I'll be upgrading tonight.

I'd like to do a fresh install however, what is the best way to completely
remove QNAPware and ALL packages and configuration files as well?

Cheers!
Matt

**Comment by zyxmon** [comment]
Just uninstall qnapwere from App Center - that is all!

**Comment by mscaff** [comment]
Awesome thanks Zyx I appreciate it, please keep me updated on the
rblibtorrent build!

Matt

**Comment by zyxmon** [comment]
In case your NAS has a 64-bit kernel - here is the version
http://entware.zyxmon.org/binaries/x86-64/test/rblibtorrent_1.0.7-1_x86-64.ipk

Please test that deluge is starting and running with the old rblibtorrent version, before you install this one.

**Comment by mscaff** [comment]
Awesome! Thanks man, will test within the hour and get back to you :D

**Comment by mscaff** [comment]
Hi again Zyx - I have installed the QPKG, was there anything else I needed to go to get Entware up and running? Also are commands still "opkg install packagename" etc?

**Comment by zyxmon** [comment]
Re: [Entware-ng] Request: rblibtorrent New Build (#28)



Nothing more. Logout & login from ssh.
What qpkg do you try to install?
If the installation does not work. Try to uninstall from app center and install from ssh.
Download qpkg to any folder and run `sh ./xxx.qpkg`
There are sometimes some strange errors (with unpacking) - there is a bug in QDK (the tool to make qpkg).
I think it is better to discuss installation problems (if any) on qnap or qnap.community forum. Please answer on the forum.

**Comment by mscaff** [comment]
QKPG installed fine, forgot to login and out of SSH!

Only problem I have now then is just installing the latest build of rblibtorrent that you linked here:
http://entware.zyxmon.org/binaries/x86-64/test/rblibtorrent_1.0.7-1_x86-64.ipk

I'm assuming: wget http://entware.zyxmon.org/binaries/x86-64/test/rblibtorrent_1.0.7-1_x86-64.ipk...........and something else?

I'm assuming this latest build is not on your repo correct?

**Comment by zyxmon** [comment]
Your questions are not for the github issues.
You should dot install rblibtorrent. Just install deluge and test that it works.
After the test run 
```

**Comment by mscaff** [comment]
Deluge up and running on Entware-ng now - I will remove 1.05 rblibtorrent
and install the new version.
I'm sorry I understand this isn't the section for it but could you please
clarify how to install the new rblibtorrent from your link? (my final
question).

Thanks!!
Matt

**Comment by mscaff** [comment]
Disregard - worked it out :D testing now

**Comment by mscaff** [comment]
Awesome! works perfectly, routes through proxy perfectly!
Thanks heaps Zyx! really appreciate it!
