### ISSUE TITLE
Package request: fslint

### ISSUE THREAD

**Issue by stanstrup** [Entware-ng/Entware-ng#281]
I am trying to make all duplicates into hardlinks on my synology nas.
fslint seems like a good option for that, but I found no way to get it on my synology. Apparently it used to be available with optware.

**Comment by zyxmon** [comment]
fslint (cmdline tools) is a set of shell and python scripts. You can install them manually and edit shebang `/bin/bash` --> `/opt/bin/bash`

**Comment by michailf** [comment]
I second the request.

I tried building fslint but it failed with msgfmt: command not found.

The whole point of packages is so we do not have to deal with these problems on different systems.

**Comment by zyxmon** [comment]
You do not need to build anything. Just download scripts, Put them in you PATH. Edit shebang (if needed).

**Comment by ryzhovau** [comment]
No response.
