### ISSUE TITLE
Package Update Request: stunnel 5.32

### ISSUE THREAD

**Issue by Lesotho** [Entware-ng/Entware-ng#282]
I would like to have stunnel updated from 5.20-1 to 5.32 as there are several bugs fixed and added features. See changes in the links below. Thanks in advance!

https://www.stunnel.org/sdf_ChangeLog.html

**Comment by zyxmon** [comment]
Done - https://github.com/Entware-ng/entware-packages/commit/53b6614c6e87a045b850600b44b0293b9198de1b
please not - I had to change threading model from fork to pthreads for this version to compile.
