### ISSUE TITLE
There is no file named "/etc/rc.local" on Synology NAS

### ISSUE THREAD

**Issue by mrwd2005** [Entware-ng/Entware-ng#283]
When I install in entware-ng on my Synology NAS, I found there is no file named ` /etc/rc.local ` on Synology NAS, but only `/etc/rc`, and is it right?

**Comment by zyxmon** [comment]
All Entware-ng files are installed in /opt folder. Different devices and firmwares need different methods to start Entware and Entware services. Try to create rc.local with `touch rc.local` or consult synology  forums for your issue.

**Comment by mrwd2005** [comment]
got it, but I add the lines:

> /bin/ln -sf /volume1/@entware-ng/opt /opt
/opt/etc/init.d/rc.unslung start

in `/etc/rc` and it works well.
