### ISSUE TITLE
armv5 build obstacles

### ISSUE THREAD

**Issue by bzapwe** [Entware-ng/Entware-ng#288]
Hi,

first I would like to thank you for providing the entware-ng package and the repository.
While building armv5 (QNAP TS 110 & TS 210) I ran into some minor obstacles and solved them as described. This worked for me but needs to be fixed in the repository.

Config used: arnv5.config
LastSync: May 9th
commit: a4953d94d3a5...35849a6e31
Buildsystem: Ubuntu 16.04, amd64-Architecture
Targetsystem: QNAP TS 110 & TS210, QTS 4.2, entware-ng_097

make menuconfig
-> Adv. conf options -> Toolchain Opt. -> disable gccgo compiler
-> Multimedia -> disable xupnpd

Packages libvobisidec
-> Makefile
- PKG_SOURCE_URL:=git://...
+ PKG_SOURCE_URL:=https://git.xiph.org/tremor.git

Package ldns
> it fails during install due to missing subdir doc/man/man3
> create subdir doc/man/man3 and create some empty file in it (touch file) in build_dir

Package squeezelite
-> Makefile
- PKG_SOURCE_URL:=https://code.google....
+ PKG_SOURCE_URL:=https://anonscm.debian.org/collab-maint/squeezelite.git

Package iptables/extension
> Add libnetfilter_conntrack & libnfnetlink to build cmd for libiptext.so, liblibiptext4.so, libiptext6.so in (build_dir) -> iptables/extension/GNUmakefile

Package iptables
> ipkg build fails because of missing reference to libnetfilter*, libnfnetlink* and libmnl*
cp staging_dir/target.../opt/lib/libnetfilter* build_dir/target.../linux.../iptables.../ipkg-install/opt/lib/
cp staging_dir/target.../opt/lib/libnfnetlink* build_dir/target.../linux.../iptables.../ipkg-install/opt/lib/
cp staging_dir/target.../opt/lib/libmnl* build_dir/target.../linux.../iptables.../ipkg-install/opt/lib/

Best regards
Bernhard

**Comment by zyxmon** [comment]
There are no problems building arm, mips, intel packages with debian jesssie. If you have fixes for some new packages please make PR.
