### ISSUE TITLE
Package request: quota (edquota, quotacheck, repquota, etc.)

### ISSUE THREAD

**Issue by jpap** [Entware-ng/Entware-ng#289]
I've installed afpd (netatalk) for use with OS X Time Machine backups to a large USB 3.0 connected RAID1 HDD enclosure.

Disk quotas would allow me to limit the amount of disk Time Machine soaks up for old backups.

**Comment by ryzhovau** [comment]
There's no quota support on most of embedded devices.
Kernel must be recompiled for quota suport, so it's up to your current firmware.
