### ISSUE TITLE
accel-ppp not working on Tomato

### ISSUE THREAD

**Issue by stavultras** [Entware-ng/Entware-ng#29]
after upgrade accel-ppp from 1.7.3 to 1.9.0 from new repo - accel-pppd process use 33% of memory consumption and VPN clients can't connect to server without any errors in logs.

I tried to change settings in conf file - nothing helped.

Firmware version: 1.28.7507 MIPSR2Toastman-RT K26 USB Lite

**Comment by ryzhovau** [comment]
Can't reproduce it, sorry. 
You may turn on debug log by:
```
log-debug=/opt/var/log/accel-ppp/debug.log
```

**Comment by stavultras** [comment]
**emerg.log:**
iprange: iprange module disabled so improper ip address assigning may cause kernel soft lockup!

**debug.log** (Debug level: **3**)
[2015-11-23 14:15:03.066] ppp: kernel doesn't support ipv6
[2015-11-23 14:15:03.069] accel-ppp version 1.9.0
*# After tried to connect from VPN client*
[2015-11-23 14:18:52.108] : : failed to bind PPTP socket (Operation not supported)
[2015-11-23 14:18:52.110] : : disconnected

**accel-ppp.conf**
[modules]
log_syslog
pptp

auth_mschap_v2
auth_mschap_v1
auth_chap_md5
auth_pap

ippool
sigchld
pppd_compat
chap-secrets

[core]
log-error=/opt/log/accel-ppp/core.log
thread-count=4

[ppp]
verbose=1
min-mtu=1280
mtu=1400
mru=1400
#mppe=require
ipv4=require
ipv6=deny
lcp-echo-interval=20
lcp-echo-timeout=120

[auth]
[pptp]
echo-interval=30
verbose=1
mppe=allow

[dns]
dns1=8.8.8.8
dns2=8.8.4.4

[client-ip-range]
0.0.0.0/0

[ip-pool]
gw-ip-address=192.168.100.1
attr=Framed-Pool
192.168.100.2-192.168.100.254

[log]
log-file=/opt/log/accel-ppp/accel-ppp.log
log-emerg=/opt/log/accel-ppp/emerg.log
log-fail-file=/opt/log/accel-ppp/auth-fail.log
log-debug=/opt/log/accel-ppp/debug.log
syslog=accel-pppd,daemon
copy=1
level=3

[pppd-compat]
ip-up=/opt/etc/ppp/ip-up
ip-down=/opt/etc/ppp/ip-down
verbose=1

[chap-secrets]
gw-ip-address=192.168.200.220
chap-secrets=/opt/etc/ppp/chap-secrets

**top:**
![top - 30%](http://c2n.me/3qJ0Kj6.png)

**Comment by ryzhovau** [comment]
I'll edit Issue caption, that's no a CPU load, that's a memory consumption.

**Comment by stavultras** [comment]
Oh, sorry, my mistake... But anyway - not works :-)

**Comment by stavultras** [comment]
Just notice: i tried to install shibby build of TomatoUSB, notice in debug.log **[2015-11-23 14:15:03.066] ppp: kernel doesn't support ipv6** is gone, but VPN still not working.

**Comment by stavultras** [comment]
After today update of accel-pppd - VPN working, but %VSZ (memory) still 33%.

Thank you.
