### ISSUE TITLE
Package request: Tribler torrent client

### ISSUE THREAD

**Issue by BYTeXperience** [Entware-ng/Entware-ng#290]
It will be a nice touch to have ported Tribler torrret client (tribler.org) from https://github.com/Tribler/tribler.
This will be a big step forward integrating this client with Tor-inspired onion routing.

**Comment by ryzhovau** [comment]
Let's give it a bit more time to see how Tribler will (not) become popular. I see no sense to add package with near to zero number of users. Closing for now, sorry.
