### ISSUE TITLE
Package Request: exif

### ISSUE THREAD

**Issue by jwagner010** [Entware-ng/Entware-ng#291]
Can you add exif to entware for Synology NAS x86-64. It currently exists in Optware/ipkg. 

I find exif to be a great utility that enables me to manage metadata in my multimedia files through various shell scripts I have written that call exif.  

Thank you in advance.

**Comment by ryzhovau** [comment]
Did you tried `perl-image-exiftool` or `jhead` instead of `exif`?

**Comment by jwagner010** [comment]
Have not tried jhead as I understand it is limited to jpeg and I need for a more diverse set of media file types.

**Comment by ryzhovau** [comment]
Well, no means no.
