### ISSUE TITLE
Is there possible to mirror entware packages?

### ISSUE THREAD

**Issue by flzyup** [Entware-ng/Entware-ng#292]
Hi, ryzhovau & zyxmon:
  Is there possible to mirror entware packages? Since we're from China. As the world know, the gfw blocked your site: http://pkg.entware.net/binaries, And we can't directly download the packages from your site. So I made a small client: https://github.com/flzyup/entwaremirror to download ipk/packages from your site with single thread. But... your server firewall blocked my server's ip. I'm not really want to do any harm to the site, just want to mirror your site at China mainland. Wait for your reply, for convenient, we can directly talk about this via mail: yonnie.lu.inc@gmail.com

**Comment by ryzhovau** [comment]
Please, stop mirroring pkg.entware.net, bet you're already banned! Here is details...

We suffered from few DDoS attacks last year and some of Asian subnets was blocked to prevent it. Our traffic limit was almost over then. Now, we managed to block DDoS attempts automatically. As we discovered, it brings no harm to legal users (including embedded devices or browsers) but cut out leaches like... you (sorry). By using mirroring script you increasing you ban time more and more. Not sure this is what you want.

As for us, repo mirroring (with all it's heavy static content) leads to the same sad end as DDoS: we'll be out of our traffic limit.

So, I'm not sure you blocked by GFC, it's up to our protection. Just stop you scripts, wait couple of days and try to get something from repo to check that.

Also, you can always set proxy for opkg, [see how](https://wiki.openwrt.org/doc/techref/opkg#proxy_support).

**Comment by flzyup** [comment]
Ok，we got it. Thanks for you reply. We can access your sites now and I was stop mirror the packages.
