### ISSUE TITLE
Package request : shntool

### ISSUE THREAD

**Issue by itdaboyz** [Entware-ng/Entware-ng#293]
Hi,

Could you add this to the packages list : http://www.etree.org/shnutils/shntool/
It seems it was in IPKG http://ipkg.nslu2-linux.org/feeds/optware/cs08q1armel/cross/stable/Packages

Thanks !

**Comment by ryzhovau** [comment]
I see no sense to add tool, which is abandoned seven years ago, sorry.

**Comment by itdaboyz** [comment]
It's still used by Headphones to cut audio files in multiple tracks. Headphones can also uses "xld" but it seems to be specific to OSX.

I requested it in Entware because it's not really possible on Asustor NAS to install a tar.gz without getting it with Entware.
