### ISSUE TITLE
Package request: chillispot

### ISSUE THREAD

**Issue by MrDini123** [Entware-ng/Entware-ng#295]
Hi!

My Tomato based mips router Can't use radius accounting function and the stock Captive Portal is buggy too. So I looked for an alternative and I found the chillispot, which is a very good CP and radius manager too.

So Can anybody add it to the entware-ng repo?

Or how Can I compile it? Because I think I Can't compile anything on my router directly, 'cause on MIPS gcc isn't available... I have an Ubuntu 14.04 based PC (x64)...

Thanks!

Ps: Sorry for my bad English...

**Comment by ryzhovau** [comment]
No any captive portals will be in repo as long as it's for non-commercial use only.

**Comment by MrDini123** [comment]
Ok. But Can You help me how Can I compile it myself for a mips router? I will only use this at home.

**Comment by ryzhovau** [comment]
Please, [see how](https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources) to deploy our Buildroot.
[See how](https://wiki.openwrt.org/doc/howto/build) to add new package after then.
