### ISSUE TITLE
Amule crash

### ISSUE THREAD

**Issue by thuantran** [Entware-ng/Entware-ng#299]
Hi there,

I'm using the armv7 version on RT-AC56U upgraded with latest version of entware-ng. Running amule returns this error at the moment:
Fatal Error: Mismatch between the program and library build versions detected.
The library used 2.8 (no debug,Unicode,compiler with C++ ABI 1002,wx containers,compatible with 2.6),
and your program used 2.8 (no debug,Unicode,compiler with C++ ABI 1009,wx containers,compatible with 2.6).
Aborted
admin@RT-AC56U-84E0:/tmp/mnt/sda1/entware.arm/var# amuled -f -c /opt/var/amule
Fatal Error: Mismatch between the program and library build versions detected.
The library used 2.8 (no debug,Unicode,compiler with C++ ABI 1002,wx containers,compatible with 2.6),
and your program used 2.8 (no debug,Unicode,compiler with C++ ABI 1009,wx containers,compatible with 2.6).
Aborted

Please help check it.
Best regards,
Thuan

**Comment by zyxmon** [comment]
Please try to reinstall libwxbase `opkg install --force-reinstall libwxbase`

**Comment by thuantran** [comment]
Yup, that fixed it. Thanks.
