### ISSUE TITLE
Please add hadouken

### ISSUE THREAD

**Issue by thuantran** [Entware-ng/Entware-ng#30]
First up thanks for the next gen entware, it has been working beautifully upgraded from original entware on my RT-AC56U.

I have a new package would like to be added. If it's not an appropriate place to add these request please do tell.

The repo: https://github.com/hadouken/hadouken

This is a torrent client that is based on the same libtorrent-rasterbar as deluge and has the same GUI as older desktop utorrent which has the same feature set as deluge-webui. But as it's written in C++, it's lighter than deluge and thus is better than transmission or the complicated setup process for the same feature set on rtorrent with rutorrent gui.

BR,

**Comment by ryzhovau** [comment]
Giving up compiling for MIPS (uClibc). I hope @zyxmon will try to make ARM (Glibc) build. If not, we'll assume cross-compiltaion of Hadouken is broken.

https://github.com/ryzhovau/hadouken-package

**Comment by ryzhovau** [comment]
Hadouken requires C++14 features, which is absent in our gcc 4.8.5.

**Comment by zyxmon** [comment]
I have compiled Hadouken and tried to run it in armv7 NAS. It crushes after entering login/passwd with

```
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted
```

Probably the same bug as in https://github.com/hadouken/hadouken/issues/185

**Comment by thuantran** [comment]
Thanks for all the efforts, let's try to wait for them to fix it.

**Comment by vktr** [comment]
Hi, I don't think the linked issue is related to your (@zyxmon) error. The issue you linked to is about not being able to load the UI at all where here it seems it crashes when you enter the credentials.

I haven't had a lot of time for Hadouken lately, but I'll see if I can reproduce and fix this error.

**Comment by zyxmon** [comment]
Thank you @vktr for the fast answer. I have tried to strace the error - but it did not help.

**Comment by vktr** [comment]
Just a wild guess here - you compiled Hadouken yourself, right? If so, you could try to change this line, https://github.com/hadouken/hadouken/blob/develop/src/http/http_server.cpp#L44

to

```
request_handlers_["^/api[/]?$"] = std::make_shared<api_request_handler>([this](std::string f) {
```

i.e, remove the escaping backwards slashes. This might yield success in your case since that is the only regex error I can think of. It seems some newer versions of GCC and MSVC handle it better even though it's an error I never got around fixing (since they accept it).

Let me know if it works.

**Comment by zyxmon** [comment]
@vktr - yes I do compile Hadouken and rblibtorrent myself. The main differences are
