### ISSUE TITLE
Package request veracrypt

### ISSUE THREAD

**Issue by annode** [Entware-ng/Entware-ng#300]
Hi,
I'm using veracrypt encrypted file containers under windows. Since I use a qnap NAS I put the containers on qnap server. It would be helpful to mount the containers on qnap nativelly. 
Veracrypt offers a version for linux systems. Could you think about taking veracrypt into entware packages?

Best Regards
Andreas

**Comment by RogueScholar** [comment]
Is this possible? I have a feeling if it was it already would've been done.

**Comment by zyxmon** [comment]
I have recently surveyed possible cryptographic  packages for Entware. As a result encfs package was added. Veracrypt looks not so simple to add.
