### ISSUE TITLE
error reported while installing 'lxml' through pip

### ISSUE THREAD

**Issue by COLDMOUNT** [Entware-ng/Entware-ng#303]
I am trying to install python module 'lxml' through pip, and get the following error report:

    In file included from src/lxml/lxml.etree.c:320:0:
    src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
    compilation terminated.
    Compile failed: command 'arm-openwrt-linux-gnueabi-gcc' failed with exit status 1
    creating opt
    creating opt/tmp
    cc -I/usr/include/libxml2 -c /opt/tmp/xmlXPathInitCms7L8.c -o opt/tmp/xmlXPathInitCms7L8.o
    unable to execute 'cc': No such file or directory
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'arm-openwrt-linux-gnueabi-gcc' failed with exit status 1
    

Actually libxml2 has been installed through opkg, but there is really no such a file named 'xmlversion.h', which should be in path "/usr/include/libxml2/libxml/" for a normal linux system.
After searching the details about the problem, I found that it could be solved by installing libxml2-dev package, which unfortunately is not included in the package list of Entware.

Anyone may have some suggestions on this? Does it mean I have to compile a .ipk file myself?
Thanks in advance.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-%28native-compilation%29#headers-installation
