### ISSUE TITLE
Package request: ocserv

### ISSUE THREAD

**Issue by xfgavin** [Entware-ng/Entware-ng#304]
This is the server side of openconnect, you have already put it's client in the repository.

There is one shipped with openwrt.

Here is the official website: http://www.infradead.org/ocserv/

BTW, I'm using asuswrt-merlin on an armv7 router (AC68P).

Thanks.

**Comment by zyxmon** [comment]
@xfgavin here are 2 packages for testing - 
http://pkg.entware.net/binaries/armv7/test/libhttp-parser_2.3.0-1_armv7soft.ipk
http://pkg.entware.net/binaries/armv7/test/ocserv_0.11.2-1_armv7soft.ipk

Please report back. A working startup script is welcomed.

**Comment by xfgavin** [comment]
Thank you.

It works great though I am still having a hard time to have the virtual adapter NATed.

One issue is the isolate-workers option can't be turned on because the binary was not compiled with seccomp.

Also, will need to open ports using iptables accordingly.

Can anyone help with getting the virtual adapter NATed to the internet?

Here are sample configuration files, please remove the .txt extension name:
ocserv.conf is to be put in /opt/etc/ocserv
S79ocserv is to be put in /opt/etc/init.d

[ocserv.conf.txt](https://github.com/Entware-ng/Entware-ng/files/303350/ocserv.conf.txt)

[S79ocserv.txt](https://github.com/Entware-ng/Entware-ng/files/303346/S79ocserv.txt)

**Comment by zyxmon** [comment]
Thanks for testing and attached files. 
ocserv added to the repo

**Comment by xfgavin** [comment]
Here is a useful iptables script to open ports and permit interfaces
[ocserv_iptables.txt](https://github.com/Entware-ng/Entware-ng/files/311306/ocserv_iptables.txt)

**Comment by liuhangcheng** [comment]
@xfgavin  is it working now ?
