### ISSUE TITLE
Package request: php5-apcu

### ISSUE THREAD

**Issue by omega69** [Entware-ng/Entware-ng#305]
Hello

I would like to use php5-apcu to optimize owncloud on my Asus router (AC56U with RMerlin of course). Any chance it can be available?

Thanks in advance

**Comment by RogueScholar** [comment]
I was hoping to do the same thing on my Netgear R7000 running TomatoUSB ShibbyMod. I'm afraid building the package is currently out of my paygrade, but adding my desire to the record might help those with such skills prioritize their efforts better.

**Comment by chris-koester** [comment]
I am trying do do the same with my R7000. Any chance this could be done?

**Comment by zyxmon** [comment]
The last PHP version that had the php_apc extension included in was PHP 5.3. * Newer versions of PHP have replaced APC with php_opcache.
The a package php5-mod-opcache is in the repo.

**Comment by ryzhovau** [comment]
php5 packages becomes obsolete and will not being developed anymore.

**Comment by omega69** [comment]
OK. thx. will check php5-mod-opcache as you have proposed and see the newer php version status
