### ISSUE TITLE
Package request: pixman

### ISSUE THREAD

**Issue by calundi** [Entware-ng/Entware-ng#306]
only pixman is missing within the libgdiplus to run the OpenSimulato

![libgdiplus so-analyse](https://cloud.githubusercontent.com/assets/7644302/15802972/c14edcc6-2ac6-11e6-914a-a0b9259c642e.jpg)

**Comment by zyxmon** [comment]
There is nothing in common with mono and your screenshot with entware.
Entware libraries and binaries are located in /opt folder. There is no mono in Entware.

**Comment by calundi** [comment]
...thanks zyxmon for the fast answer. Sure as a PC/Network assembler (Hardware) I only have very lil bit programmers knowledge. One request in addition (if it's allowed to ask you for)...Mono was and is always a big drama on the QNAP NAS systems. So I was happy to get one mono version running for my clients OPENSIM use.So far that mono version shows the missing libs and I only had to install it via the old (not supported any longer) Optware/IPKG for the Qnap. So with installing the missing pixman via ipkg install pixman, that lib is inserted in the Optware/lib folder and all is running well. My thought was, making a link out of that folder up to your opt ...of course with the ability to find the libpixman there.Or is there any other ability to transfer/convert 'old' ipkgs?

Thanks very much for the reading, maybe you can give me a hint of what to do, as I hate these sentences for my clients beginning with "Sorry from now on you can't work with your system any longer with the new upgrade/update". That always makes me sad

**Comment by zyxmon** [comment]
Entware libraries are incompatible with firmware or optware binaries/libs.
