### ISSUE TITLE
Package Request: Unison and/or Ocaml

### ISSUE THREAD

**Issue by der-martin85** [Entware-ng/Entware-ng#307]
I use Unison for syncrinizing two NAS and several PCs. I compiled it myseld so far but for that I also need Ocaml.

**Comment by ryzhovau** [comment]
Can't say Ocaml is cross-compilation friendly:) Tried several times before. It's better to build Ocaml-based natively.

**Comment by dugwood** [comment]
See https://github.com/Entware-ng/Entware-ng/issues/446#issuecomment-316628232

**Comment by dugwood** [comment]
See: https://github.com/Entware-ng/Entware-ng/issues/477#issuecomment-316628740
