### ISSUE TITLE
Package rsnaphot needs perlbase-ipc

### ISSUE THREAD

**Issue by BertHankes** [Entware-ng/Entware-ng#310]
I just installed rsnaphot and it lacks perlbase-ipc.

So can you fix that? 

TIA

**Comment by zyxmon** [comment]
rsnapshot depends on perlbase-ipc.
perlbase-ipc is installed as a dependancy.

**Comment by BertHankes** [comment]
Sorry,.. but I had to install it myself after installing the rsnapshot package...
