### ISSUE TITLE
Package request: Cyrus IMAP server

### ISSUE THREAD

**Issue by PhillipLauder** [Entware-ng/Entware-ng#311]
Please make a package for the Cyrus IMAP server that runs on the Asus RT-AC68U router (an ARMv7 router).  There's a version of Cyrus IMAP server in Optware-NG, however it doesn't work.  I have done a few tricks to try to make it work.  However, there's an issue with "listusers" failing.  I changed the username from mail:root to admin:root, but the IMAP server won't start up.  The following output is from the Optware-NG version:

$ /opt/bin/ipkg install cyrus-imapd
Installing cyrus-imapd (2.4.17-caldav-beta10-1) on /opt/.
Downloading file:///opt/home/public/optware-ng/cyrus-imapd_2.4.17-caldav-beta10-1_arm.ipk.
package cyrus-imapd suggests installing cyrus-imapd-doc
Installing cyrus-sasl (2.1.25-1) on /opt/.
Downloading file:///opt/home/public/optware-ng/cyrus-sasl_2.1.25-1_arm.ipk.
Configuring cyrus-sasl.

Please read the man page of saslauthd and
check settings in /opt/etc/init.d/S52saslauthd

If you dislike the link /usr/lib/sasl2 -> /opt/lib/sasl2
then you may want to set SASL_PATH instead

(re)starting service saslauthd
Configuring cyrus-imapd.
adding new service(s) ... failed
set arm-linux-saslpasswd2 for user 'admin' ... listusers failed
failed
changing permission ...
chown: /opt/etc/sasl2: No such file or directory
chmod: /opt/etc/sasl2: No such file or directory

You may want to update your Perl modules first:
        $ cpan
        > install Bundle::CPAN
        > install HTTP::Date

Please read the man-pages and docs carefully,
        $ less /opt/share/docs/cyrus-imapd/README
        $ man cyrus_master
        $ lynx /opt/share/docs/cyrus-imapd/html/index.html

then configure cyrus-imapd,
        $ vi /opt/etc/cyrus.conf
        $ vi /opt/etc/imapd.conf

create users with cyradm
        $ cyradm -u admin localhost

and start the server
        $ /opt/etc/init.d/S59cyrus-imapd

**Comment by ryzhovau** [comment]
We've got few POP3/IMAP servers in repo, why we need another one?

**Comment by PhillipLauder** [comment]
Sorry, I did not see the Dovecot package.  Now I'm successfully running Xmail for POP3 and Dovecot for IMAP, on the Asuswrt-Merlin RT-AC68U router.
