### ISSUE TITLE
Package request: ssldump

### ISSUE THREAD

**Issue by dgalimov** [Entware-ng/Entware-ng#314]
Hi,
Is it possible to include ssldump package? Should be handy for dumping https traffic

**Comment by zyxmon** [comment]
@dgalimov 
please check and report (my guess you use mipsel router)
http://pkg.entware.net/binaries/mipsel_test/ssldump_0.9b3_mipselsf.ipk

**Comment by dgalimov** [comment]
It seems to do not work correctly :

````
/opt/home/admin # ssldump -i eth3
ERROR: Couldn't create network handler
/opt/home/admin # ssldump -i br0
ERROR: Couldn't create network handler
/opt/home/admin # ssldump -i ra0
PCAP: ra0: no IPv4 address assigned
/opt/home/admin # ssldump -i rai0
PCAP: rai0: no IPv4 address assigned
/opt/home/admin # ssldump
PCAP: ra0: no IPv4 address assigned
````

**Comment by dgalimov** [comment]
There is also a bug in OpenWRT about this: https://dev.openwrt.org/ticket/13399

**Comment by dgalimov** [comment]
Maybe a different version of openssl (or ssldump) is required? https://trac.macports.org/ticket/8832

**Comment by zyxmon** [comment]
openssl is used by a lot of packages. no chance to change its version.
ssldump latest sources were used to build package.

**Comment by dgalimov** [comment]
could you please rebuild ssldump with these options:

````
rebuild it to give more error information by doing
>         CFLAGS="-DR_TRACE_ERRORS" ./configure <...put your configure options" ?
````

**Comment by dgalimov** [comment]
maybe this patch also should be applied:
https://sourceforge.net/p/ssldump/patches/4/

**Comment by zyxmon** [comment]
This patch was applied in the previous build.
http://pkg.entware.net/binaries/mipsel_test/ssldump_0.9b3-2_mipselsf.ipk

**Comment by dgalimov** [comment]
Now it gives the list of error, but still doesn't work :-(

````
/opt/home/admin # ssldump -i eth3
ABORT: error 1 at ./ssl/ssldecode.c:139 (function ssl_decode_ctx_create)
ABORT: error 1 at ./ssl/ssl_analyze.c:222 (function create_ssl_ctx)
ABORT: error 1 at ./base/network.c:83 (function network_handler_create)
ERROR: Couldn't create network handler
````

**Comment by zyxmon** [comment]
На правах гадалки - ssldump расчитан на старые версии openssl. Или ищите патчи для работы с новыми версиями или аналог современный ssldump. Не зря ыыдвгьз сейчас в owrt не поддерживается!

**Comment by dgalimov** [comment]
Да, я тоже так думаю. А какие аналоги есть?

**Comment by zyxmon** [comment]
A have applied debian patches - https://packages.debian.org/sid/net/ssldump
(debian sid uses openssl 1.0.2)
now ssldump starts ok. 
@dgalimov  please check this version
http://pkg.entware.net/binaries/mipsel_test/ssldump_0.9b3-1_mipselsf.ipk

**Comment by dgalimov** [comment]
Yes, it seems to work! Thank you! :+1:

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/entware-oldpackages-ports/commit/b5eed4fed944a8c94217348e349969b519c92e5e
