### ISSUE TITLE
Package update request: bind-server (Build with  --enable-filter-aaaa)

### ISSUE THREAD

**Issue by jamesmacwhite** [Entware-ng/Entware-ng#315]
Would it be possible for the `bind-server` package to be built with `--enable-filter-aaaa` support?

Currently you cannot use `filter-aaaa-on-v4` because the opkg package wasn't built with it.

According to https://github.com/Entware-ng/entware-packages/blob/0a2ff07815e54bfb791eb49a53d62818cac0d936/net/bind/Makefile it does appear to be setup for it, but on my ASUS RT N66U (DD-WRT):

```
named-checkconf /opt/etc/bind/named.conf
/opt/etc/bind/named.conf:21: option 'filter-aaaa-on-v4' was not enabled at compile time
/opt/etc/bind/named.conf:21: parsing failed
```

**Comment by dfelicia** [comment]
+1 - this would be *very* useful for: https://www.ploek.org/post/netflix_openwrt/

**Comment by jamesmacwhite** [comment]
This is the main reason why I needed the functionality. Once you understand the OpenWRT build system, it fairly easily to compile bind for mipsel or ARM without too much trouble. Would be great if the parameter was enabled by default though.

**Comment by jamesmacwhite** [comment]
@dfelicia Change has been made upstream by the package maintainer.

https://github.com/openwrt/packages/commit/909209e7531de2ea63f1f298adce985406d8ba08

The next sync Entware does with the OpenWRT source should pull this in.

**Comment by dfelicia** [comment]
Awesome!

**Comment by jamesmacwhite** [comment]
https://github.com/Entware-ng/Entware-ng/issues/521
