### ISSUE TITLE
Subsonic

### ISSUE THREAD

**Issue by maria95posteonet** [Entware-ng/Entware-ng#318]
Best music server but there has been no ready-to-install .spk in Synology's DSM Package Center since several versions...

Use this on a daily basis so would be extremely grateful if someone could find a way to provide and keep Subsonic updated on Synology. 

I have no idea how I would prepare this myself, but I imagine it might take 2 seconds for someone who knows what they're doing ? 

If so, I would be SOOOOO eternally daily-basis grateful, I NEED Subsonic!

The website is here

http://subsonic.org

The various "builds" or whatever, versions for different OS's etc. are here: 

http://www.subsonic.org/pages/download.jsp

Thank you again

**Comment by ryzhovau** [comment]
No Java support because it's too heavy for embedded devices.
