### ISSUE TITLE
 * opkg_install_cmd: Cannot install package uclibc-opt.

### ISSUE THREAD

**Issue by bbt88** [Entware-ng/Entware-ng#320]
Got this during install.

Upgrade will be continued in 30 seconds. Press 'Ctrl+c' to abort
...............................starting upgrade!
[1/4] Trying to stop running services...
The following packages will be reinstalled after upgrade:
findutils ldconfig libc libgcc libpthread librt libstdcpp uclibc-opt
[2/4] Uninstalling existing packages...
Removing package findutils from root...
Removing package ldconfig from root...
Removing package libc from root...
Removing package libgcc from root...
Removing package libpthread from root...
Removing package librt from root...
Removing package libstdcpp from root...
Removing package uclibc-opt from root...
[3/4] Deploying Entware-ng opkg package manager...
Downloading /opt/bin/opkg... success!
Downloading /opt/etc/opkg.conf... success!
Downloading /opt/etc/profile... success!
Downloading /opt/etc/init.d/rc.func... success!
Downloading /opt/etc/init.d/rc.unslung... success!
[4/4] Installing new versions of packages...
Downloading http://pkg.entware.net/binaries/mipsel/Packages.gz.
Updated list of available packages in /opt/var/opkg-lists/entware-ng.
No packages removed.
Installing ldconfig (1.0.13-3) to root...
Downloading http://pkg.entware.net/binaries/mipsel/ldconfig_1.0.13-3_mipselsf.ipk.
Installing findutils (4.6.0-1) to root...
Downloading http://pkg.entware.net/binaries/mipsel/findutils_4.6.0-1_mipselsf.ipk.
Installing libc (1.0.13-3) to root...
Downloading http://pkg.entware.net/binaries/mipsel/libc_1.0.13-3_mipselsf.ipk.
Installing libgcc (5.3.0-3) to root...
Downloading http://pkg.entware.net/binaries/mipsel/libgcc_5.3.0-3_mipselsf.ipk.
Installing libssp (5.3.0-3) to root...
Downloading http://pkg.entware.net/binaries/mipsel/libssp_5.3.0-3_mipselsf.ipk.
Package findutils (4.6.0-1) installed in root is up to date.
Package ldconfig (1.0.13-3) installed in root is up to date.
Package libc (1.0.13-3) installed in root is up to date.
Package libgcc (5.3.0-3) installed in root is up to date.
Installing libpthread (1.0.13-3) to root...
Downloading http://pkg.entware.net/binaries/mipsel/libpthread_1.0.13-3_mipselsf.ipk.
Installing librt (1.0.13-3) to root...
Downloading http://pkg.entware.net/binaries/mipsel/librt_1.0.13-3_mipselsf.ipk.
Installing libstdcpp (5.3.0-3) to root...
Downloading http://pkg.entware.net/binaries/mipsel/libstdcpp_5.3.0-3_mipselsf.ipk.
Unknown package 'uclibc-opt'.
Configuring ldconfig.
Configuring libgcc.
Configuring libc.
Configuring libpthread.
Configuring libstdcpp.
Configuring librt.
Configuring libssp.
Configuring findutils.
Collected errors:
 ***** opkg_install_cmd: Cannot install package uclibc-opt.**
Done. Found a bug? Please report us at
https://github.com/Entware-ng/Entware-ng/issues**
root@TomatoUSB:/usr/sbin#

**Comment by ryzhovau** [comment]
Can't reproduce that. Please, check filesystem first.

**Comment by zyxmon** [comment]
This is normal when running http://pkg.entware.net/binaries/mipsel/installer/upgrade.sh
to upgrade Entware -> Entware-ng
Not all Entware packages are in Entware-ng.

**Comment by zyxmon** [comment]
dublicate of https://github.com/Entware-ng/Entware-ng/issues/78
