### ISSUE TITLE
Package Request: forked-daapd

### ISSUE THREAD

**Issue by jsetton** [Entware-ng/Entware-ng#322]
It seems that the package exists in the [OpenWrt packages feed](https://github.com/Entware-ng/entware-packages/tree/master/sound/forked-daapd) but is not available in the Entware-ng package repo. Is it possible to make this package available?

**Comment by ryzhovau** [comment]
We've tried `mtdaapd`, `forked-daapd` and `firefly` before. The last one is taken as compromise between number of features and number of dependencies. I see no reason to add another fork to repo, sorry.
