### ISSUE TITLE
Is mipsel compatible with MIPS?

### ISSUE THREAD

**Issue by gator1** [Entware-ng/Entware-ng#324]
I wonder if the mipsel build run on Netgear WNR3500v2 which has a broadcom BCM47186	which is MIPS 74K. 

My guess is that MIPSEL and MIPS aren't compatible. 

I am looking for a newer build of Asterisk on BCM47186.

**Comment by lancethepants** [comment]
Do you mean WNR3500Lv2. No way you could get asterisk running on a WNR3500v2 unless it's possible to mod it with a USB port.  In either case both routers are mipsel.

**Comment by gator1** [comment]
Yes, it's WNR3500Lv2. yes I have a usb stick on it and have run asterisk on it for the last five years. 
I need to upgrade and ipkg doesn't have the new version that I need.

**Comment by zyxmon** [comment]
Please note - issues are for bug reports and feature requests
