### ISSUE TITLE
Package request: liblzm4

### ISSUE THREAD

**Issue by relictMarauder** [Entware-ng/Entware-ng#327]
Please enable build of liblzm4 in feeds/packages/lib

**Comment by ryzhovau** [comment]
Please, tell us how you going to use it?

**Comment by relictMarauder** [comment]
I will build "borg backup" (https://borgbackup.readthedocs.io)
for building liblzm4 i have created pullRequest (https://github.com/Entware-ng/entware-packages/pull/2)

**Comment by ryzhovau** [comment]
I see no sense to add any orphaned library to repo, which is not used by any other existing package, sorry.

**Comment by zyxmon** [comment]
liblzm4 can be accepted with "borg backup" PR

**Comment by relictMarauder** [comment]
borg backup PR is already requested(https://github.com/Entware-ng/Entware-ng/issues/142) and rejected :(

**Comment by zyxmon** [comment]
@relictMarauder #142 is not a PR. It is a simple request.

**Comment by relictMarauder** [comment]
is PR a Pull Request or Package Request? :)

**Comment by zyxmon** [comment]
PR = Pull Request
