### ISSUE TITLE
Package request: seafile

### ISSUE THREAD

**Issue by chris-koester** [Entware-ng/Entware-ng#33]
Seafile can act as a self hosted Dropbox alternative. 

They also have an arm build for the raspberry pi (if this is of any help):
https://github.com/haiwen/seafile-rpi/releases

Homepage: https://www.seafile.com/en/home/

**Comment by chris-koester** [comment]
Some requirements would need to be added as well (python-imaging, python-ldap, sqlite3 or python-mysqldb and python-memcache).

**Comment by Loader23** [comment]
+1

**Comment by jult** [comment]
+1, only thing missing for seafile to work on my ASUSTOR nas is pyhton-imaging

**Comment by zyxmon** [comment]
python-imglib package in repo is the name of python-imagine

**Comment by jult** [comment]
Next one missing: python-mysqldb
How is that named in entware-ng ?

**Comment by zyxmon** [comment]
you can build it yourself - https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-python-modules

**Comment by jult** [comment]
Already tried that:
```
# pip install python-mysqldb
Collecting python-mysqldb
  Could not find a version that satisfies the requirement python-mysqldb (from versions: )
No matching distribution found for python-mysqldb

**Comment by zyxmon** [comment]
Finding what pip package you need may be the simplest step in building python module. You may need to modify sources. There is a topic "Help needed to install pycrypto" on Entware subforum on official QNAP forum that describes some difficulties that can be on your way.
Issues section here is not a place for such QA.

**Comment by jult** [comment]
Here's the nitty gritty, zyxmon:

- installing syncthing in entware-ng on NAS: 10 minutes work, runs fine.
- installing seafile-server in entware-ng on NAS: days of problem-solving, still doesn't run.

You do the math ;-)
Thanks for the help, but I'm not opening that sick python can of worms.

**Comment by zyxmon** [comment]
seafile 5.0.6 is in the repo. Binaries will arrive soon!
seafile is VERY memory hungry. Do not even try to run it on devices with less then 512MB of RAM. 1GB or more is recommended. Swap is required.
Binaries will be built for x86_64 and armv7 only.

**Comment by jult** [comment]
Just an FYI;
On my asustor AS-604T NAS, with an Intel Atom 2.13 GHz Dual-Core and 1GB RAM the seafile (server and hub) total memory usage is almost *half* that of syncthing! Very promising.

Thanks a lot for adding it!

**Comment by jult** [comment]
It's now at 5.1.1, could you upgrade them for entware-ng ? Also, recently tried --force-reinstall and got:

```
/opt/share/seafile/seafile-server/seafile/bin/seaf-server-init: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
Failed to generate seafile configuration

```

**Comment by jult** [comment]
Server says it's 5.0.4, not 5.0.6. By the way, 5.1.1 is out. Could you update it someday?
