### ISSUE TITLE
Request sigmavpn

### ISSUE THREAD

**Issue by paway** [Entware-ng/Entware-ng#331]
can you do Sigmavpn? Thanks any way

**Comment by ryzhovau** [comment]
We've got bunch of VPN solutions in repo so I see no reason to add another one.
 What's the killer feature of `sigmavpn`? Looks like development of `sigmavpn` is [stopped about year ago](https://github.com/neilalexander/sigmavpn).

**Comment by paway** [comment]
well, I can not get quicktun work. but Sigmavpn works smoothly. and Sigmavpn has a android app.

**Comment by paway** [comment]
I am trying to build a package.  "https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources". but make toolchain/install ..
"""
Location: http://open-source-box.org/gcc/gcc-/gcc-.tar.bz2 [following]
converted 'http://open-source-box.org/gcc/gcc-/gcc-.tar.bz2' (ANSI_X3.4
"""
I think the right url should be http://www.localmsp.org/gnu/gcc/gcc-4.8.5/gcc-4.8.5.tar.bz2. right? any idea? tks anyway.

**Comment by zyxmon** [comment]
@paway Have you selected the right config file for your architecture? Current configs use gcc5.3. gcc 4.8.5 can be selected for historical reasons and was not checked and used for monthes.

**Comment by paway** [comment]
@ryzhovau The problem in---the shell does not pass the gcc version variable. It's a bug,right?
