### ISSUE TITLE
Package request: Domoticz

### ISSUE THREAD

**Issue by Obruut** [Entware-ng/Entware-ng#333]
Is it possible to include Domoticz? http://www.domoticz.com

Would love to have it running on my R7000 router (armv7) with TomatoUSB

**Comment by zyxmon** [comment]
Here is a package for testing - http://pkg.entware.net/binaries/armv7/test/domoticz_3.4834-1_armv7soft.ipk

**Comment by Obruut** [comment]
For starters; Thank you for the quick reply and the test package! Awesome to see that Domoticz run smoothly on my router :-)

After a day of intensive testing, I've encountered some problems and so far one showstopper.

**1. No detection of USB device(s) -> showstopper**
The connected USB receiver doesn't come available on Setup -> Devices.

When I start Domoticz on my Debian VM, every 30 seconds this line pop's up;
```
Fri Jul  8 00:00:30 2016 Hardware Monitor: Fetching data (System sensors)
```
Is this a limitation in the code of Domoticz (https://github.com/domoticz/domoticz/search?utf8=✓&q=Hardware+Monitor%3A+Fetching+data+%28System+sensors%29) or is there something missing?

Seeing that Domoticz runs a root, this isn't a issue? ->
https://www.domoticz.com/wiki/Linux#Allow_non-root_user_to_access_ttyUSB.2A_ports

<del>The only wild guess I could make is that it needs libusb-compat? Found something similar about Domoticz and OpenWRT over here: https://github.com/openwrt/packages/pull/2883.</del>
Never mind: That package is installed.

**2. No HTTPS**
```
Error: WebServer(SSL) startup failed on address 0.0.0.0 with port: 443: use_certificate_chain_file: asio.ssl error
```
I'm note sure if this is an easy fix? I can live without this, but maybe for other users who wants to make Domoticz remotely accessible this can come in handy. 

**3. SUDO**
Rebooting of Shut down system from GUI isn't working
```
sh: sudo: not found
2016-07-07 22:14:23.963  Error: Error executing shutdown command. returned: 32512
```
I minor issu and again I could easily live with this, but maybe it's a simple patch? Both (#2 and #3) aren't worth researching of #1 isn't fixable.

**Comment by zyxmon** [comment]
1. It does use both libusb:
     ldd /opt/share/domoticz/domoticz
        libusb-0.1.so.4 => /opt/lib/libusb-0.1.so.4 (0xb6ec8000)
        libusb-1.0.so.0 => /opt/lib/libusb-1.0.so.0 (0xb6eab000)
        libssl.so.1.0.0 => /opt/lib/libssl.so.1.0.0 (0xb6e55000)
        libcrypto.so.1.0.0 => /opt/lib/libcrypto.so.1.0.0 (0xb6d1f000)
        ........
Makefile used to compile domoticz is here - https://github.com/Entware-ng/graveyard/tree/master/domoticz
May be someone can fix the issues. I have no appropriate equipment ant time for it.

**Comment by kofec** [comment]
Hi,
I was able to compile fo mipsel architecture. Below you can find logs:
git clone https://github.com/Entware-ng/graveyard
make package/symlinks
/Entware-ng-3x $  make package/domoticz/compile -j4

ERROR: please fix package/graveyard/perl-list-moreutils/Makefile - see logs/pack                                                                                                                               age/graveyard/perl-list-moreutils/dump.txt for details
Collecting package info: done
WARNING: your configuration is out of sync. Please run make menuconfig, oldconfig or defconfig!
 make[1] package/domoticz/compile
 make[2] -C package/libs/toolchain compile
 make[2] -C feeds/packages/libs/boost host-compile
 make[2] -C package/libs/gettext-full host-compile
 make[2] -C feeds/packages/libs/expat host-compile
 make[2] -C feeds/packages/libs/libffi host-compile
 make[2] -C package/utils/bzip2 host-compile
 make[2] -C package/libs/ncurses host-compile
 make[2] -C package/libs/ocf-crypto-headers compile
 make[2] -C package/utils/bzip2 compile
 make[2] -C package/libs/libusb compile
 make[2] -C package/libs/libiconv-full compile
 make[2] -C package/libs/zlib compile
 make[2] -C feeds/packages/libs/expat compile
 make[2] -C feeds/packages/libs/gdbm compile
 make[2] -C feeds/packages/libs/libffi compile
 make[2] -C feeds/packages/lang/python host-compile
 make[2] -C package/libs/libreadline compile
 make[2] -C package/libs/ncurses compile
 make[2] -C package/libs/openssl compile
 make[2] -C package/libs/libusb-compat compile
 make[2] -C package/network/utils/curl compile
 make[2] -C feeds/packages/libs/libxml2 compile
 make[2] -C feeds/packages/libs/db47 compile
 make[2] -C feeds/packages/libs/sqlite3 compile
 make[2] -C feeds/packages/lang/python compile
 make[2] -C feeds/packages/libs/boost compile
 make[2] -C package/graveyard/domoticz compile

**Comment by kofec** [comment]
I found small issue. package domoticz.ipk is not created :-) but there is no error during compilation. I noticed that CONTROL folder is not created and control file is not created. Only this error occured:
Scanning dependencies of target revisiontag
make[5]: Leaving directory `/media/kofec/Berryboot/Entware-ng-3x/build_dir/target-mipsel_mips32r2_glibc-2.23/domoticz'
make[5]: Entering directory `/media/kofec/Berryboot/Entware-ng-3x/build_dir/target-mipsel_mips32r2_glibc-2.23/domoticz'
-- Found Git: /media/kofec/Berryboot/Entware-ng-3x/staging_dir/host/bin/git (found version "1.9.1")
fatal: Not a git repository: './.git'
-- Failed to get ProjectRevision from git, set it to 0
fatal: Not a git repository: './.git'
-- Failed to get ProjectHash from git, set it to 0
fatal: Not a git repository: './.git'
-- Failed to get ProjectDate from git, set it to 0
fatal: Not a git repository: './.git'
-- ProjectDate is 0 and appversion.default exists, copy it
make[5]: Leaving directory `/media/kofec/Berryboot/Entware-ng-3x/build_dir/target-mipsel_mips32r2_glibc-2.23/domoticz'
[  0%] Built target revisiontag
make[5]: Entering directory `/media/kofec/Berryboot/Entware-ng-3x/build_dir/target-mipsel_mips32r2_glibc-2.23/domoticz'
Scanning dependencies of target lua
make[5]: Leaving directory `/media/kofec/Berryboot/Entware-ng-3x/build_dir/target-mipsel_mips32r2_glibc-2.23/domoticz'
make[5]: Entering directory `/media/kofec/Berryboot/Entware-ng-3x/build_dir/target-mipsel_mips32r2_glibc-2.23/domoticz'
[  1%] Building C object lua/src/CMakeFiles/lua.dir/lauxlib.c.o

**Comment by kofec** [comment]
It is working fine on Xiaomi Mini with padavan:
2016-09-15 20:25:28.126 Domoticz V3.4834 (c)2012-2016 GizMoCuz
2016-09-15 20:25:28.127 Build Hash: 2bd98a1, Date: 2016-03-02 07:36:12
2016-09-15 20:25:28.129 Startup Path: /opt/share/domoticz/
2016-09-15 20:25:29.324 Active notification subsystems: http (1/11)
2016-09-15 20:25:29.342 WebServer(HTTP) started on address: 0.0.0.0 with port 8080
2016-09-15 20:25:29.371 Error: WebServer(SSL) startup failed on address 0.0.0.0 with port: 443: use_certificate_chain_file: asio.ssl error
2016-09-15 20:25:29.371 Error: WebServer(SSL) check privileges for opening ports below 1024
2016-09-15 20:25:29.373 Proxymanager started.
2016-09-15 20:25:29.387 Starting shared server on: 0.0.0.0:6144
2016-09-15 20:25:29.388 TCPServer: shared server started...
2016-09-15 20:25:29.389 RxQueue: queue worker started...
2016-09-15 20:25:31.392 EventSystem: reset all events...
2016-09-15 20:25:31.396 EventSystem: reset all device statuses...
2016-09-15 20:25:31.398 EventSystem: Started
2016-09-15 20:26:01.836 Incoming connection from: 192.168.1.244
2016-09-15 20:29:21.092 Hardware Monitor: Started
2016-09-15 20:29:24.093 Hardware Monitor: Fetching data (System sensors)
2016-09-15 20:29:54.138 Hardware Monitor: Fetching data (System sensors)
2016-09-15 20:30:24.174 Hardware Monitor: Fetching data (System sensors)
2016-09-15 20:30:54.386 Hardware Monitor: Fetching data (System sensors)
2016-09-15 20:31:24.626 Hardware Monitor: Fetching data (System sensors)

**Comment by zyxmon** [comment]
@kofec - have you made any changes to the Makefile from previous comment - https://github.com/Entware-ng/Entware-ng/issues/333#issuecomment-231274663

**Comment by kofec** [comment]
Hi,
I didn't modify Makefile. I didn't test any USB device. I compiled on Entware-3x fork.
Below you can see the additional steps I did.

git clone https://github.com/Entware-ng/graveyard
make package/symlinks
/Entware-ng-3x $ make package/domoticz/compile -j4

There were no error but as I mention ipk package  was not created. But all files exist so just copied to my router and run. More info you can find in my above 3 comments.
Thanks

**Comment by zyxmon** [comment]
>>  I didn't test any USB device.

Domoticz is not usable without USB devices.

**Comment by kofec** [comment]
Hi, Let me don't agree. I use it also on raspberry where I use GPIO but also lot of equipment on ethernet like:
ESP8266 WiFi module, Satel, many TVs, KODI, enigma, Logitech Media Server and many many other which you can find:
https://www.domoticz.com/wiki/Domoticz_Wiki_Manual

**Comment by uysy** [comment]
Obruut, do you have any manual how to run Domoticz on Tomato Shibby ? :/

**Comment by zyxmon** [comment]
Domoticz package was not added to Entware.

**Comment by uysy** [comment]
Hi zyxmon,
do you have any plans to implement this package to Entware ? (ARMv7).

**Comment by zyxmon** [comment]
Domoticz test builds were only partially functional. Probably we will try build new Domoticz later.
