### ISSUE TITLE
Request netperf

### ISSUE THREAD

**Issue by maurerr** [Entware-ng/Entware-ng#334]
Hi,

Can you please add netperf ?
it's a nice tool to be able to run speedtest:
https://github.com/richb-hanover/OpenWrtScripts/blob/master/betterspeedtest.sh

thanks

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/entware-packages/commit/47ea99285eade2a6601acb885aaa8612639f1ac3
Binaries will arrive soon.
