### ISSUE TITLE
Request fastd

### ISSUE THREAD

**Issue by paway** [Entware-ng/Entware-ng#336]
it's included in openwrt's official already . Please !

**Comment by ryzhovau** [comment]
Why should we add another VPN solution? What's the killer feature of `fastd`?

**Comment by paway** [comment]
small   fast  secure.  more info https://projects.universe-factory.net/projects/fastd/wiki

**Comment by ryzhovau** [comment]
We've got number of other fast, small and secure VPN clients.

I'll keep this issue open for a month to see if there other users who wants `fastd` too.

**Comment by idcrisis** [comment]
request!

hi, this is not a vpn solution. it's a mesh solution. 

vpns are so 5 mins ago. connecting to a vpn is no better except for the secured first hop.

**Comment by ryzhovau** [comment]
Done for MIPSEL. Arm/x86 binaries will arrive late.

**Comment by paway** [comment]
arm version works ok.
but MIPSEL  " socketpair: Invalid argument ". need help. 
really tks.

**Comment by ryzhovau** [comment]
Too old kernel and/or some syscalls are absent on target system.
