### ISSUE TITLE
can't install entware-ng

### ISSUE THREAD

**Issue by myxa781** [Entware-ng/Entware-ng#337]
android 4.4.2 (root)
Qualcomm Snapdragon 400 
i try different scripts for install entware-ng (also tried it by hand in terminal)
all is good but when script (or by hand) try /opt/bin/opkg update (or other opkg commands) i got Segmentation fault
so, how i can install it properly ?
thx 4 help! ;)

**Comment by zyxmon** [comment]
http://www.zyxmon.org/2016/04/17/entware-ng-na-android/
Russian

**Comment by myxa781** [comment]
yeah! tried this script also ;) result r same - /bin/opt/opkg update - Segmentation fault

**Comment by zyxmon** [comment]
I am afrad your system is incompatable with entware.

**Comment by myxa781** [comment]
it's a pity ;(
thx 4 answers!!!

**Comment by zyxmon** [comment]
I am away from my home computer for a week. I can suggest some tests for you after 19.07 to find what is wrong with your system.

**Comment by myxa781** [comment]
ok!!! thank you so much and my best wishes ;)

**Comment by myxa781** [comment]
p.s. i found two guys with same problem on 4pda ( http://4pda.ru/forum/index.php?s=&showtopic=745536&view=findpost&p=51147844 )
android 4.4.2

**Comment by zyxmon** [comment]
Let's try a voodoo dance. 
Change opkg URL in the script to this one - http://pkg.entware.net/binaries/armv7/experimental/opkg

Please report.

**Comment by myxa781** [comment]
yeah! opkg now is working... but ;) i'm install busybox... and it's segmentation fault ;(

**Comment by zyxmon** [comment]
So, let's have more dancing in the dark. Please post the output of (I hope it will not segfault)
`/opt/lib/ld-linux.so.3 --list /opt/bin/busybox`
Please also post all environment variables. If you have a working copy of busybox - use `env` command from that version. If not - just use `set` command.

**Comment by myxa781** [comment]
ok, boogie-woogie:
	/vendor/lib/libNimsWrap.so (0xb6f75000)
	libm.so.6 => /opt/lib/libm.so.6 (0xb6ec0000)
	libc.so.6 => /opt/lib/libc.so.6 (0xb6d83000)
	libdl.so => /system/lib/libdl.so (0xb6d7f000)
	libc.so => /system/lib/libc.so (0xb6d24000)
	libcutils.so => /system/lib/libcutils.so (0xb6d18000)
	/opt/lib/ld-linux.so.3 (0xb6fde000)
	liblog.so => /system/lib/liblog.so (0xb6d13000)
	libstdc++.so => /system/lib/libstdc++.so (0xb6d10000)
	libm.so => /system/lib/libm.so (0xb6cf5000)

-----------------------------------------------------------------------



_=/system/xbin/env
PATH=/vendor/bin:/system/bin:/system/xbin
LOOP_MOUNTPOINT=/mnt/obb
ANDROID_ROOT=/system
VIBE_PIPE_PATH=/dev/pipes
SHELL=/tmp-mksh/tmp-mksh
LD_LIBRARY_PATH=/vendor/lib:/system/lib
ANDROID_SOCKET_zygote=11
LOGNAME=root
CLASSPATH=/data/data/de.robv.android.xposed.installer/bin/XposedBridge.jar
ANDROID_ASSETS=/system/app
TERM=screen
ANDROID_PROPERTY_WORKSPACE=9,0
ANDROID_BOOTLOGO=1
HOSTNAME=w7
ANDROID_DATA=/data
BOOTCLASSPATH=/system/framework/core.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/framework2.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/services.jar:/system/framework/apache-xml.jar:/system/framework/webviewchromium.jar:/system/framework/telephony-msim.jar:/system/framework/com.lge.frameworks.jar:/system/framework/qcom.fmradio.jar:/system/framework/org.codeaurora.Performance.jar
EMULATED_STORAGE_SOURCE=/mnt/shell/emulated
EXTERNAL_ADD_STORAGE=/storage/external_SD
EMULATED_STORAGE_TARGET=/storage/emulated
ANDROID_STORAGE=/storage
MKSH=/system/bin/sh
EXTERNAL_STORAGE=/storage/emulated/legacy
LD_PRELOAD=/vendor/lib/libNimsWrap.so
RANDOM=11392
ASEC_MOUNTPOINT=/mnt/asec
SECONDARY_STORAGE=/storage/external_SD
USER=root
HOME=/

**Comment by zyxmon** [comment]
Try to `unset LD_LIBRARY_PATH`. Does busybox starts to work?
Add this command to the start of `/opt/etc/init.d/rc.unslung` and to `/opt/etc/profile`

If this helps - I'll update the installer. New `opkg` binary is not needed!

**Comment by zyxmon** [comment]
After unsetting two environment variables check the output of `/opt/lib/ld-linux.so.3 --list /opt/bin/busybox`

**Comment by myxa781** [comment]
yeah, man! u r awesome dancer! ;) after two unset, busybox is works!
tomorrow i'll try install via opkg some pakages, and write comment :-)
p.s thx so much....cheers ;)

**Comment by myxa781** [comment]
yeah, man! u r awesome dancer! ;) after two unset, busybox is works!
tomorrow i'll try install via opkg some pakages, and write comment :-)
p.s thx so much....cheers ;)

**Comment by zyxmon** [comment]
I have fixed the installation script (added `unset LD_LIBRARY_PATH` and `unset LD_PRELOAD` to it at the very beginning) and added unset `LD_LIBRARY_PATH` and `unset LD_PRELOAD` to `rc.unslung` and `profile` scripts through android-opt package.
Everything should work now. Your comments are welcome. )))
