### ISSUE TITLE
Package request: fossil-scm

### ISSUE THREAD

**Issue by rodoviario** [Entware-ng/Entware-ng#338]
I am starting to use it, is open source, cross-platform software version control system, with command-line and web interface alike, all in a single and small excecutable binary. Is portable as well. Every repo is a single file too. It has a generic linux binary, an exe for windows and a mac version too. It can import from git repos too.

Info: [https://www.fossil-scm.org/fossil/doc/trunk/www/index.wiki]

**Comment by ryzhovau** [comment]
Binaries will arrive (approx.) on the weekend. We are in the middle of month sync with upstream.
