### ISSUE TITLE
Package request: syncthing 

### ISSUE THREAD

**Issue by chris-koester** [Entware-ng/Entware-ng#34]
Syncthing can act as a btsync alternative. 

They also have an arm build ready.

https://syncthing.net

**Comment by ryzhovau** [comment]
Short answer: no.

* Syncthing is written in GO, which is not ready for cross-complation.
* It's painfully slow on embedded devices.

I've [tried](http://blog.robertnash.org/2015/08/09/building-syncthing-for-my-book-live-duo/) it on my WD MBL (PowerPC @800MHz) and was very disappointed:

* It starts ~60 seconds, keeping 100% CPU load all this time,
* It consumes too much resources while running,
* It can't sync files on changes, no any inotify-like features are used. Just stupid timer to sync files once per minute (configurable). Imagine you have to have wait a minute before closing laptop to make sure files are being synced.

**Comment by zebralight** [comment]
is there a recommended alternative for syncing files between WAN and LAN?

**Comment by zyxmon** [comment]
BTW Syncthing is in the repo now. But it IS heavy!
Alternatives - seafile, rsync, and other ....

**Comment by zebralight** [comment]
thank you.  I wasn't able to run syncthing at all and got memory allocation errors, but I created a swap file on my usb 3.0 flash drive and it runs.  As others have said, syncthing is heavy but suits my needs.
