### ISSUE TITLE
Package request: Offline Imap

### ISSUE THREAD

**Issue by TheMuso** [Entware-ng/Entware-ng#341]
Hi.

Is it possible to add offlineimap, https://github.com/OfflineImap/offlineimap? I did try to set it up by hand with entware-ng x86-64 as a base, but there was a missing symbol in one of the python modules relating to unicode...

Thanks.

**Comment by ryzhovau** [comment]
Please, follow [this manual](https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-python-modules) to add new python modules. You've got all necessary tools for native compilation.
