### ISSUE TITLE
Package request : ddclient

### ISSUE THREAD

**Issue by lLysl** [Entware-ng/Entware-ng#342]
Hello,

Would it be possible to include [ddclient](https://sourceforge.net/projects/ddclient/)?

Thanks!

**Comment by ryzhovau** [comment]
It's just a perl script. I see no reason to pack it into repo.

**Comment by PiotrC1** [comment]
Well, I have installed it and it definitelly needs some more effort to install:
1) Install Perl,
2) Install Perl modules (as pure Perl is not enough)
3) Create  /opt/etc/ddclient and /opt/var/cache/ddclient,
4) Copy ddclient to /opt/sbin/
5) Edit ddclient - change /etc/ddclient/ to /opt/etc/ddclient/ and /var/cache/ddclient/ to /opt/var/cache/ddclient/
6) Make starting script in /opt/etc/init.d/

In Debian it is a separate package.
