### ISSUE TITLE
tvheadend with transcoding for the armv7

### ISSUE THREAD

**Issue by pewolfe** [Entware-ng/Entware-ng#343]
Is it possible to get the tvheadend package with transcoding as an option. the version now does not have transcoding profiles.

**Comment by pewolfe** [comment]
I also wanted to add that I am using an qnap ts-431. It is using a freescale arm cortex 9 processor. 

https://www.qnap.com/i/useng/product/model.php?II=156&event=2

According to this article it has a 1080p hardware encoder/decoder.

https://www.element14.com/community/docs/DOC-51240/l/freescale-imx-6-series-with-arm-cortex-a9-for-consumer-and-general-embedded

**Comment by ryzhovau** [comment]
There must be kernel space driver and user space software recompiled to use hardware en-/decoder. Entware is hardware independent repo so we can't put here some QNAP-specific stuff. So, you can rely on software en-/decoding only.

Also, tvheadend was added only as [DVR](https://en.wikipedia.org/wiki/Digital_video_recorder) for IPTV with [EPG](https://en.wikipedia.org/wiki/Electronic_program_guide) support only. There's no DVB or other hardware support. I think it's better to use some external transcoding tool _after_ some program has been recorded by tvheadend.

**Comment by pewolfe** [comment]
I noticed that the Raspberry Pi has transcoding available with tvheadend.

https://tvheadend.org/boards/5/topics/13892

I was just asking if the tvheadend could have transcoding compiled into the binary so transcode profiles are available.

https://tvheadend.readthedocs.io/en/stable/webui/config_streamprofile/

Thanks

**Comment by ryzhovau** [comment]
No plans to add it, sorry.

**Comment by domhardt** [comment]
These are sad news. :( Are there any technical restrictions or problems?
