### ISSUE TITLE
Package request: duplicity

### ISSUE THREAD

**Issue by mbeiter** [Entware-ng/Entware-ng#344]
Can you please add duplicity: http://duplicity.nongnu.org/ 

Thanks!

Mike

**Comment by Gedankenleser** [comment]
+1

**Comment by zyxmon** [comment]
This is a python program that requires packages from repo -
librsync v0.9.6 or later
GnuPG v1.x for encryption 
and some other python stuf. Try to build it yourself using instructions from wiki - https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-python-modules

**Comment by ryzhovau** [comment]
No response too.
