### ISSUE TITLE
Entware package list doesn't get updated

### ISSUE THREAD

**Issue by diman82** [Entware-ng/Entware-ng#346]
I run:
opkg update
opkg upgrade

And nothing happens, I know that, cause all of the following example packages below are either of a lower version or completely not in the list.

Packages for example:
boost-chrono_1_61_0-1_armv7soft.ipk                       9,650   
boost-filesystem_1_61_0-1_armv7soft.ipk                  35,283   
boost-program_options_1_61_0-1_armv7soft.ipk            145,529   
boost-regex_1_61_0-1_armv7soft.ipk                      292,654   
boost-system_1_61_0-1_armv7soft.ipk                       4,549   
boost-test_1_61_0-1_armv7soft.ipk                       238,638   
boost-timer_1_61_0-1_armv7soft.ipk                        8,633   
grive2_0.5-20160114-2_armv7soft.ipk                     222,027   
libbfd_2.25-1_armv7soft.ipk                             314,978   
libstdcpp_5.3.0-4_armv7soft.ipk                         393,379   
yajl_2.1.0-1_armv7soft.ipk                               14,068   

opkg list-upgradable yields nothing as well.
Am I missing something, is a different command I should use?

**Comment by zyxmon** [comment]
opkg update should show that it downloads packages list. Do you have a working copy of wget on your device?

**Comment by diman82** [comment]
It downloads an updated list, that is not a problem, but what I do next?
What command should I run to import this newly downloaded list?

**Comment by zyxmon** [comment]
This is not a place for such questions. 
Issues is used for bug reports and feature requests.
Please ask your questions on the forum (for your device) if you cannot find how to use opkg somewhere else.
