### ISSUE TITLE
Package request: onedrive-sdk-python

### ISSUE THREAD

**Issue by diman82** [Entware-ng/Entware-ng#347]
Can you please add onedrive-sdk-python: [](https://github.com/OneDrive/onedrive-sdk-python)

Thanks,
diman82

**Comment by zyxmon** [comment]
Have you tried to build it yourself - https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-python-modules

**Comment by diman82** [comment]
Successfully installed on Python3.5 (after installing tons of dependencies, almost all Python3 packages that exist):
python3.5 /opt/bin/pip3.5 install onedrivesdk

p.s Had error on Python2.7:
_Python pip install gives “Command ”python setup.py egg_info“ failed with error code 1”_

**Comment by zyxmon** [comment]
Closing (Success on Python3.5).
