### ISSUE TITLE
Package request: nagios nrpe

### ISSUE THREAD

**Issue by backbohne** [Entware-ng/Entware-ng#349]
Hi Alexander,

would it be possible to add the Nagois NRPE package to be able to support a simple kind of opsview-agent.

https://sourceforge.net/projects/nagios/files/nrpe-3.x/

Regards
Frank

**Comment by ryzhovau** [comment]
We are using the last release from 3.x fork and not going to update/develop it in future, sorry. 

Take a look at wiki pages too find out how to build new package.
