### ISSUE TITLE
Package request: exif utility

### ISSUE THREAD

**Issue by d4nirod** [Entware-ng/Entware-ng#35]
I'm trying to write a script to automatically sort photos stored on my Qnap NAS based on the exif data. The script would be run by cron and rename image files with the exif dates, create a folder for each month and move files to the appropriate folder.
Most examples I found around the net rely on the exif tool http://sourceforge.net/projects/libexif/files/exif/ which depends on libexif and popt, both already present on openwrt upstream.

Any chance to get this package available on Entware-ng?

PD. Another option would be jhead http://www.sentex.net/~mwandel/jhead/ but I'm not sure if it would be more difficult to compile.

**Comment by zyxmon** [comment]
http://exiftool.sourceforge.net/
perl library and binary are in repo.
package name is perl-image-exiftool

**Comment by zyxmon** [comment]
jhead is also in repo.

**Comment by d4nirod** [comment]
Excellent. Exiftool seems a better option indeed. Already installing...

Thanks a lot.
