### ISSUE TITLE
dd-wrt - Atheros mips "sh: opkg: Permission denied"

### ISSUE THREAD

**Issue by vasek00** [Entware-ng/Entware-ng#350]
root@Buf:/opt/tmp# wget -O - http://pkg.entware.net/binaries/mipsel/installer/installer.sh | sh
 Connecting to pkg.entware.net (81.4.123.217:80)
                    100% |************************************************************************************************************|  1359   0:00:00 ETA
 Info: Creating folders...
 Warning: Folder /opt/tmp exists! If something goes wrong please clean /opt folder and try again.
 Info: Deploying opkg package manager...
 Downloading /opt/bin/opkg... success!
 Downloading /opt/etc/opkg.conf... success!
 Downloading /opt/etc/profile... success!
 Downloading /opt/etc/init.d/rc.func... success!
 Downloading /opt/etc/init.d/rc.unslung... success!
 Info: Basic packages installation...
 sh: opkg: Permission denied
 sh: opkg: Permission denied
 
Congratulations!
 If there are no errors above then Entware-ng is successfully initialized.
Found a Bug? Please report at https://github.com/Entware-ng/Entware-ng/issues
Type 'opkg install <pkg_name>' to install necessary package.
root@Buf:/opt/tmp# cd /opt/bin
root@Buf:/opt/bin# ls -l
-rwxr-xr-x    1 root     root        473024 Jul 28 15:35 opkg
root@Buf:/opt/bin# ./opkg
-sh: ./opkg: Permission denied
root@Buf:/opt/tmp# uname -a
Linux Buf 3.10.102 #25589 Fri Jul 1 02:06:23 CEST 2016 mips DD-WRT
root@Buf:/opt/tmp# `

**Comment by zyxmon** [comment]
AFAIK Atheros is mips, not mipsel. The only mips entware repo is for a couple of zyxel keenetic router models.

**Comment by zyxmon** [comment]
BTW. I am participating in the new Entware fork project - https://github.com/Entware-for-kernel-3x
I hope you can guess what is it about from the title.
We have not seen users in mips feeds. Can you tell what firmwares/routers have 3.x kernels and mips (be) chipset?
