### ISSUE TITLE
hplip missing phyton-gobject

### ISSUE THREAD

**Issue by daskorn** [Entware-ng/Entware-ng#351]
I tried to install hplip on my qnap Intel NAS 453. All python scripts stuck on the following error:
ImportError: No module named gobject

Sadly the opkg repository is missing the phyton-gobject package.

**Comment by zyxmon** [comment]
We are aware of problems in hplip and hope it can be configured manually.
If you need python-gobject (PyGObject), you can try to add it yourself as described here - 
https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-python-modules

**Comment by ryzhovau** [comment]
No response.
