### ISSUE TITLE
Package update request: Libsodium 1.0.11

### ISSUE THREAD

**Issue by AtAM1** [Entware-ng/Entware-ng#354]
Hi @ryzhovau 

Libsodium 1.0.11 has been released.

Appreciate if you could update it - changelog: https://github.com/jedisct1/libsodium/blob/master/ChangeLog

Cheers

**Comment by ryzhovau** [comment]
I see no sense to catch up every minor release. `libsudium` will be updated with next [upstream](https://github.com/openwrt/packages/tree/master/libs/libsodium) sync.
