### ISSUE TITLE
Segmentation Fault Dune HD 301

### ISSUE THREAD

**Issue by dunehd-301w** [Entware-ng/Entware-ng#356]
Hi All,

I have installed to my Dune HD 301 this version of Entware:
http://pkg.entware.net/binaries/mipsel/installer/installer.sh

Here is the info of 301:
Sigma Designs 8670 platform:
   CPU:           MIPS 24Kf 700 MHz (little endian)
   Linux kernel:  2.6.29

Installation was without problem but some of installed packages failed with a segmentation fault.
These packages work : htop, vitetris, lighttpd.
These packages failed : rtorrent, transmission, mc, 

PS. The old above packages of Optware worked without problems.

Do you have any idea how to resolve this kind of fault ?

Thanks

**Comment by dunehd-301w** [comment]
here is it, what  i get when i tried to run transmission-daemon :
http://i.imgur.com/Tblf7nb.png

tangox[root]# /opt/etc/init.d/S88transmission start
 Starting transmission-daemon... sleep: invalid number '1s'
sleep: invalid number '1s'
sleep: invalid number '1s'
sleep: invalid number '1s'
sleep: invalid number '1s'
sleep: invalid number '1s'
sleep: invalid number '1s'
sleep: invalid number '1s'
sleep: invalid number '1s'
sleep: invalid number '1s'
sleep: invalid number '1s'
             failed.
tangox[root]#

Do you have any ideas how to resole it ?
thx

**Comment by ryzhovau** [comment]
Looks like a buggy busybox on Dune. You may replace `sleep 1s;` to `sleep 1;` in `/opt/etc/init.d.rc.unslung`, but it won't help, the problem is somewhere else. Try to run transmission from console to see whats wrong:
```
transmission-daemon -g /opt/etc/transmission
```

**Comment by dunehd-301w** [comment]
thanks to getting back to me. 
i have replaced sleep 1s to sleep 1 in /opt/etc/init.d/rc.func ( i could not find sleep in file rc.unslug )
here is the error 

> tangox[init.d]# ./S88transmission  start
> Starting transmission-daemon...              failed.

and here is the log of 

> transmission-daemon -g /opt/etc/transmission

> tangox[init.d]# transmission-daemon -g /opt/etc/transmission
> Segmentation fault

i don't know, whats wrong, these packages works without fault of Segmentation. But unfortunately these oleg's packages are outdated.

**Comment by zyxmon** [comment]
@dunehd-301w - my guess is: dune  kernel 2.6.29 is very old and does not have syscalls (backports) that the kernel used to build entware binaries has. So entware binaries are partially incompatiible with dune.

**Comment by dunehd-301w** [comment]
thank you for your answer.

its strange, that Dune doesn't support Entware-ng. The reason of strange is, that Dune 101 can run the package transmission without faults. Dune 101 has the same specification as Dune 301.

Here is the info from official site :
Sigma Designs 8670 platform:
   STB models:    TV-101, TV-102p, TV-201*, TV-301.
   CPU:           MIPS 24Kf 700 MHz (little endian)
   Linux kernel:  2.6.29

Here you can see more about Dune :
http://files.dune-hd.com/sdk/doc/txt/dune_devel_info.txt

Why some packages works, as htop, lighttpd, aria2, some games but rtorrent, transmission, ctorrent, amule show segmentation fault.

thanks in advance.

**Comment by zyxmon** [comment]
You are to investigate the segfault yourself.

I can suggest you to disable watch dir in settings.json. If enabled it causes segfault on kernels/filesystems that do not have inotify enabled.

**Comment by dunehd-301w** [comment]
Thank you for your effort !
I have tried to disable watch dit but it did not help, i got again that segfault.

I think as you said, due to very old version of kernel Entware is incompatabilty with Dune :( sad.
