### ISSUE TITLE
automatic errors

### ISSUE THREAD

**Issue by shunjou** [Entware-ng/Entware-ng#357]
I am trying to use the package automatic 0.8.3-20160310-1 on my armv5 device and running into a few issues. I am only using it to download torrent files to a local directory, not with transmission. When trying to start the daemon from init.d I receive the error "automatic.c, 796: Error: Daemonize failed. Aborting...". I tried with different arguments including forgoing the log file but am always met with the same result. However, the daemon starts fine if I run it manually with something like "automatic -l /opt/var/log/log.auto".

Even after the daemon is running and has no errors in the log, when it encounters a filter match, it fails to write to the state file resulting in the same torrent being downloaded repeatedly on the refresh interval. The state file exists and is writable but automatic never stores downloaded torrents information.

**Comment by zyxmon** [comment]
Please. check the previous automatic version (all previus package version are in archive subfolder).
http://pkg.entware.net/binaries/armv5/archive/automatic_0.8.3-20150317-1_armv5soft.ipk

May be the latest uodate has errors.

PS I have now only Entware-3x - https://github.com/Entware-for-kernel-3x/Entware-ng-3x installed on the singe armv5 device. I have never used automatic. After several tries I have got

```
[~] # automatic -l /opt/var/log/automatic.log -a
fopen: No such file or directory
Error parsing config file: Cannot find file '/opt/etc/automatic.conf'

[~] # automatic -l /opt/var/log/automatic.log -a
Error parsing config file: Unknown error

[~] # automatic --help
usage: automatic [-fh] [-v level] [-l logfile] [-c file] [-p pidfile]

Automatic 0.8x (0b8355fe33d37c883f547fa821bfa11c9e334a95)

  -f --nodeamon             Run in the foreground and log to stderr
  -h --help                 Display this message
  -v --verbose <level>      Set output level to <level> (default=1)
  -c --configfile <path>    Path to configuration file
  -o --once                 Quit Automatic after first check of RSS feeds
  -l --logfile <file>       Log messages to <file>
  -a --append-log           Don't overwrite logfile from a previous session
  -p --pidfile              create pidfile
```

May be there is an error in your config file? I can also suggest you to increase verbose <level>.

**Comment by shunjou** [comment]
The archived automatic 0.8.3-20150317-1 functions the same as the latest package. The init script's failure point seems to occur on a slightly earlier line with "automatic.c, 780: Error: Daemonize failed. Aborting...".

This is what occurs:
```
[~]# /opt/etc/init.d/S91automatic check
 Checking automatic...              dead. 
[~]# /opt/etc/init.d/S91automatic start
 Starting automatic...              done. 
[~]# /opt/etc/init.d/S91automatic check
 Checking automatic...              dead. 
[~]# automatic -v 2 -l /opt/var/log/automatic.log
[~]# /opt/etc/init.d/S91automatic check
 Checking automatic...              alive. 
```

Running the daemon manually with verbose level set to 2 helped me realize why the state file wasn't being written to. It seems that having the option "use-transmission" set to no does not trigger the state file to be written to after downloading a torrent file. Setting that option to yes adds the torrent to transmission and deletes it from the torrent download folder (I have transmission installed but do not want it used by automatic). Setting the transmission version to 1.2 or external (1.1) has no effect and behaves as if "use-transmission" is set to no as well. Trying to workaround by breaking its support with 1.3, by changing the port to something invalid for example, causes a failure error and the torrent is never downloaded at all. I assume this oversight is caused by the author never having used automatic as a torrent downloader without transmission integration.

With "use-transmission" set to yes:
```
automatic.c, 765: Automatic version: 0.8x (0b8355fe33d37c883f547fa821bfa11c9e334a95)
state.c, 120: Restored 0 old entries
automatic.c, 283: Transmission version: 1.3
automatic.c, 284: RPC host: localhost
automatic.c, 285: RPC port: 9091
automatic.c, 286: RPC auth: none
automatic.c, 287: config file: /opt/etc/automatic.conf
automatic.c, 288: Transmission home: /root/.config/transmission
automatic.c, 289: check interval: 30 min
automatic.c, 290: Upload limit: -1 KB/s
automatic.c, 291: torrent folder: /mnt/usb0/.bt
automatic.c, 292: start torrents: no
automatic.c, 293: state file: /opt/var/auto.state
automatic.c, 300: Transmission RPC Version: 15
automatic.c, 320: 1 feed URLs
automatic.c, 321: Read 10 filters from config file
[16/08/05 06:29:35] automatic.c, 799: Daemon started
automatic.c, 802: verbose level: 2
automatic.c, 803: foreground mode: no
[16/08/05 06:29:35] automatic.c, 807: ------ Checking for new episodes ------
automatic.c, 691: Checking feed 'https://rss.feed/rssdd.php?category=41' (25 items)
regex.c, 70: [isRegExMatch] '(?!.+proper)(some\.show)\.S[0-9][0-9]E[0-9][0-9].+(1080p\.web-dl)' matches 'Some.Show.S01E11.Title.Name.1080p.WEB-DL.DD5.1.H.264'
[16/08/05 06:29:35] automatic.c, 589: [1] Found new download: Some.Show.S01E11.Title.Name.1080p.WEB-DL.DD5.1.H.264 (https://rss.feed/download.php?id=#)
torrent.c, 55: Content-Filename: Some.Show.S01E11.Title.Name.1080p.WEB-DL.DD5.1.H.264.torrent
json.c, 135: folder_str: "download-dir": "/mnt/usb1/0",
torrent.c, 149: Torrent upload successful!
state.c, 66: Saving state (1 downloaded torrents) to disk
state.c, 89: Done saving state
```

With "use-transmission" set to no:
```
automatic.c, 765: Automatic version: 0.8x (0b8355fe33d37c883f547fa821bfa11c9e334a95)
state.c, 120: Restored 0 old entries
automatic.c, 283: Transmission version: 1.3
automatic.c, 284: RPC host: localhost
automatic.c, 285: RPC port: 9091
automatic.c, 286: RPC auth: none
automatic.c, 287: config file: /opt/etc/automatic.conf
automatic.c, 288: Transmission home: /root/.config/transmission
automatic.c, 289: check interval: 30 min
automatic.c, 290: Upload limit: -1 KB/s
automatic.c, 291: torrent folder: /mnt/usb0/.bt
automatic.c, 292: start torrents: no
automatic.c, 293: state file: /opt/var/auto.state
automatic.c, 320: 1 feed URLs
automatic.c, 321: Read 10 filters from config file
[16/08/05 06:24:25] automatic.c, 799: Daemon started
automatic.c, 802: verbose level: 2
automatic.c, 803: foreground mode: no
[16/08/05 06:24:25] automatic.c, 807: ------ Checking for new episodes ------
automatic.c, 691: Checking feed 'https://rss.feed/rssdd.php?category=41' (25 items)
regex.c, 70: [isRegExMatch] '(?!.+proper)(some\.show)\.S[0-9][0-9]E[0-9][0-9].+(1080p\.web-dl)' matches 'Some.Show.S01E11.Title.Name.1080p.WEB-DL.DD5.1.H.264'
[16/08/05 06:24:26] automatic.c, 589: [1] Found new download: Some.Show.S01E11.Title.Name.1080p.WEB-DL.DD5.1.H.264 (https://rss.feed/download.php?id=#)
torrent.c, 55: Content-Filename: Some.Show.S01E11.Title.Name.1080p.WEB-DL.DD5.1.H.264.torrent
file.c, 94: Saved torrent file '/mnt/usb0/.bt/Some.Show.S01E11.Title.Name.1080p.WEB-DL.DD5.1.H.264.torrent'
```

**Comment by zyxmon** [comment]
Since it works with "use-transmission" set to yes, I am closing the issue.
