### ISSUE TITLE
FreeRadius OpenSSL Error

### ISSUE THREAD

**Issue by dumdedumda** [Entware-ng/Entware-ng#358]
Tried searching for a solution before opening a new issue request. I'm following the Wiki on "[Setting up FreeRadius2 through Entware](https://github.com/RMerl/asuswrt-merlin/wiki/Setting-up-FreeRadius2-through-Entware)," and receive the error below when attempting to generate a private key using the following command:

root@XXXXXX:/opt/etc/freeradius2/certs# openssl ecparam -name secp521r1 -genke
y -noout | openssl ec -aes256 -out CA/private/ec-cakey.pem
openssl:Error: 'ecparam' is an invalid command.

Standard commands
enc            req            rsa            x509

Cipher commands (see the `enc' command for more details)
aes-128-cbc    aes-128-ecb    aes-192-cbc    aes-192-ecb    aes-256-cbc
aes-256-ecb    bf-cbc         bf-ecb

openssl:Error: 'ec' is an invalid command.

Standard commands
enc            req            rsa            x509

Cipher commands (see the `enc' command for more details)
aes-128-cbc    aes-128-ecb    aes-192-cbc    aes-192-ecb    aes-256-cbc
aes-256-ecb    bf-cbc         bf-ecb

**Comment by zyxmon** [comment]
Just checked this command. No problems with it

```
[~] # openssl ecparam -name secp521r1 -genkey -noout | openssl ec -aes256 -out CA/private /ec-cakey.pem
read EC key
writing EC key
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
```

**Comment by ryzhovau** [comment]
No response.
