### ISSUE TITLE
updatedb can't load library 'libc.so.0'

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-ng/Entware-ng#359]
Running updatedb from entware-ng on N56U firmware 3.4.3.9-099 results in an error.

/opt/home/admin # opkg install findutils-locate
Installing findutils-locate (4.6.0-1) to root...
Downloading http://pkg.entware.net/binaries/mipsel/findutils-locate_4.6.0-1_mipselsf.ipk.
Configuring findutils-locate.
/opt/home/admin # updatedb
/opt/lib/frcode: can't load library 'libc.so.0'
Failed to generate /opt/var/locatedb.n

How to fix this?

**Comment by zyxmon** [comment]
Have you updated packages before installing?

```
opkg update
opkg upgrade
```

What command do use use to install updatedb (and other packages)?

**Comment by ProBackup-nl** [comment]
Thank you @zyxmon, after running `opkg update && opkg upgrade` the command `updatedb` no longer returns an error.
