### ISSUE TITLE
Package request: php5-mod-ssh2

### ISSUE THREAD

**Issue by stavultras** [Entware-ng/Entware-ng#36]
Please, build [php5-mod-ssh2](http://pecl.php.net/package/ssh2) PHP module for working with SFTP/SSH protocol, if it's possible.

Thank you.

**Comment by stavultras** [comment]
If someone need this is package, i build for MipsR2 (Asus RT-N16):
Just install via opkg: opkg install http://178.217.4.44/MipsR2/php5-pecl-ssh2_0.12-1_mipselsf.ipk 

**And package with config for entware repo:** http://178.217.4.44/MipsR2/php5-pecl-ssh2.zip

**Comment by ryzhovau** [comment]
Sorry for the long response, glad you figured out how to compile it.
Closing this.
