### ISSUE TITLE
mlocate: updatedb: can not find group 'mlocate'

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-ng/Entware-ng#360]
After running:
```
# opkg update && opkg upgrade
# opkg remove findutils-locate
# opkg install mlocate
```
The resulting (error) output of the `updatedb` command is:
`updatedb: can not find group `mlocate'`

`# grep -s mlocate /etc/group`
no resulting output

Shouldn't this mlocate package be extended with commands that automagically create the group and correct the file access rights on its installation? 

Like:
```
# grep -s mlocate /etc/group || addgroup mlocate
# chgrp mlocate /opt/var/mlocate
# chmod g=rx,o= /opt/var/mlocate
# chgrp mlocate /opt/bin/locate
# chmod g+s,go-w /opt/bin/locate
# touch /opt/var/mlocate/mlocate.db
# chgrp mlocate /opt/var/mlocate/mlocate.db
```

**Comment by zyxmon** [comment]
Adding group to /etc/group is firware specific and is not allways preserved after reboot.
This is solved in (experimental) Entware-3g fork - https://github.com/Entware-for-kernel-3x/Entware-ng-3x for the "alternative install" type.
The instruction to install Entware-3x (Russian) for your firmware is here - http://forums.zyxmon.org/viewtopic.php?f=5&t=5399

**Comment by blackwind** [comment]
Still an issue with 3x-alt, but `addgroup mlocate` is enough to solve it now. Package should be updated to add the group automatically.

**Comment by meffect** [comment]
i cant run addgroup on my synology , dont know how to fix this one

**Comment by hamityanik** [comment]
Create a "mlocate" group from DSM Control Panel.
Control Panel > Gruop > Create > Group name: mlocate

After that, run **updatedb** command from terminal. 

`updatedb: can not find group mlocate` error will be gone.
