### ISSUE TITLE
 smartmontools (6.5-1) mips Segmentation fault

### ISSUE THREAD

**Issue by listenfree** [Entware-ng/Entware-ng#361]
when run smartctl in  mips router,
[RT-AC1200HP /opt/etc]# smartctl
Segmentation fault

maybe need to recompile with  "Disable optimization" option.
https://www.smartmontools.org/ticket/219

**Comment by zyxmon** [comment]
I have checked smartctl on three different mipsel routers (RT6856, MT7620, MT7620) running different firmwares. This is your device problem. 
Try to install Padavan's firmware or upgrade it, if you use it.
You can even use Entware-3x fork with it (English installation instruction is not ready, sorry).
