### ISSUE TITLE
Package Request - Man Pages

### ISSUE THREAD

**Issue by jump** [Entware-ng/Entware-ng#363]
although i have used *nix systems for a bit over 10 years, I still find myself often reading man pages, and for me I'm certain it will always be this way. 

anyone like to see manpages rolled into entware, at least making the package available for download? 

if there is no interest perhaps eventually i'll just write a python utility that will query for any man page esque commands, and will symlink it into /opt/bin/man

**Comment by ryzhovau** [comment]
This is repo for embedded systems. No man pages by design.

**Comment by wildermj** [comment]
There are packages for building from source and all sorts of other non-embedded things, why not the ability to read simple documentation?

Or are there simply no manpages installed on the machine making the utility useless?

**Comment by ryzhovau** [comment]
This is minimalist approach, taken from OpenWrt, which allow you (as example) to deploy Entware-ng to tmpfs even on 32MB RAM devices. I see no sense to change this approach in future. 

Also, you can always read any man pages online.
