### ISSUE TITLE
Support for older kernels

### ISSUE THREAD

**Issue by Mijzelf** [Entware-ng/Entware-ng#367]
Some time ago I wrote a package to install Entware-ng on a ZyXEL nas. (More [here](http://zyxel.nas-central.org/wiki/Entware-ng)). As the armv5 variants all have a kernel older than 2.6.32, I had to provide an alternative libc. I did so by building the Entware libc from source, edit the build_dir/toolchain_NNN/glibc-2.XX-final/config.h to support older kernels, and build it again.

As far as I know this causes libc to include some stubs to emulate functionality not available in older kernels. This stubs are not used on a newer kernel.  But actually I couldn't find any stub activated in the sourcecode, and my generated libc was a bit _smaller_ than the official one. (1252720 bytes for libc_2.23-4, vs 1256816 for the official one). So it seems the supported kernel version is just an artificial limitation.

AFAIK the patched libc works fine. I have no feedback that it causes any problems.

Now the issue: since I created the package, the installation has been broken twice by an upgrade of libc (2.23 and 2.24). For 2.23 I created a new patched ipk file, and I'll also build one for 2.24, but I wonder if it would be possible to set the target kernel version to 2.6.24 in the stock package.

**Comment by zyxmon** [comment]
I suggest you to try and build the whole repo with 2.6.24.
Another option is to add hold flag to the libc package so it will not be upgraded.

**Comment by Mijzelf** [comment]
> I suggest you to try and build the whole repo with 2.6.24.
How does that help?

**Comment by zyxmon** [comment]
Iа you build entware with your device kernel sources and supported libc - binaries will be compatible with your device. You can select uclibc-ng as a system library to make building easier.

**Comment by Mijzelf** [comment]
In that case there is a misunderstanding. All stock armv5 packages are running fine on the 'patched' libc package. (Well, to be fair, I didn't test all of them. But I haven't found any problems, and haven't had any reports either. The patched libc package is downloaded about 2500 times (by an installer script), so I think I can say it's running on at least 1000 boxes).
