### ISSUE TITLE
always "Segmentation fault" for all applications install via opkg

### ISSUE THREAD

**Issue by kofec** [Entware-ng/Entware-ng#368]
Hi,
For all installed application I have "Segmentation fault". What I can check ? Any suggestions ?

```
/opt/home/admin # opkg install n2n
Installing n2n (2.1.0-20130823-1) to root...
Downloading http://pkg.entware.net/binaries/mipsel/n2n_2.1.0-20130823-1_mipselsf.ipk.
Configuring n2n.
/opt/home/admin # edge --help
Segmentation fault
/opt/home/admin # uname -an
Linux MI-MINI 3.4.112 #1 Sun Jun 26 01:07:16 UTC 2016 mips GNU/Linux
/opt/home/admin # mc
Segmentation fault
```

**Comment by zyxmon** [comment]
post the output of env command

**Comment by kofec** [comment]
Sorry my fault. I just read about: https://github.com/Entware-ng/Entware-ng/wiki/Install-on-Padavan-firmware
and find this:
https://github.com/Entware-for-kernel-3x/Entware-ng-3x/
Issue is closed

**Comment by zyxmon** [comment]
Try to

```
unset LD_LIBRARY_PATH
unset LD_PRELOAD
```

before running any entware binary.
