### ISSUE TITLE
Update to latest versions: TOR, Dnscrypt, Libsodium

### ISSUE THREAD

**Issue by blackfuel** [Entware-ng/Entware-ng#369]
TOR 0.2.8.9
Dnscrypt 1.7.0
Libsodium 1.0.11

Thank you.

**Comment by vbauerster** [comment]
+1

**Comment by ryzhovau** [comment]
`dnscrypt` and `libsodium` are updated, binaries will arrive soon.

There's another issue about TOR, which I'll keep open https://github.com/Entware-ng/Entware-ng/issues/427
