### ISSUE TITLE
Patch to update libgpg-error to 1.21 (or better?)

### ISSUE THREAD

**Issue by blackfuel** [Entware-ng/Entware-ng#370]
See the patch file.
[100-mkheader-triplet-openwrt.patch.txt](https://github.com/Entware-ng/Entware-ng/files/432804/100-mkheader-triplet-openwrt.patch.txt)

**Comment by zyxmon** [comment]
Is there a simple test to verify your patch?

**Comment by blackfuel** [comment]
This patch allows the latest libgpg-error to compile without error.  If it already compiles for you, then please disregard this issue.

**Comment by ryzhovau** [comment]
Done. Package updated.
