### ISSUE TITLE
nvram setfile2nvram not working as expected, users cannot persist across reboots

### ISSUE THREAD

**Issue by amurabito** [Entware-ng/Entware-ng#371]
per the instructions @ http://tomatousb.org/tut:adding-your-own-users

it seems to be possible to preserve across reboots new users. however, this doesn't appear to work. 

nvram setfile2nvram /etc/passwd.custom
nvram setfile2nvram /etc/group.custom
nvram setfile2nvram /etc/shadow.custom

Is there any official way within entware-ng to add user accounts, and have them preserved across reboots?

**Comment by zyxmon** [comment]
You can install Entware-3x (alternative install) -https://github.com/Entware-for-kernel-3x/Entware-ng-3x/wiki if your hardware fits the requrements.
