### ISSUE TITLE
CUPS 2.1.4-1 incomplete.

### ISSUE THREAD

**Issue by PiotrC1** [Entware-ng/Entware-ng#372]
Trying to install CUPS 2.1.4-1 for ARMv7 I have seen that directory /opt/share/doc/cups (or rather /opt/share/cups/doc) is missing, making impossible to open webpage for administration (http://myhost:631). After copying missing files from another computer it starts to work.

**Comment by ryzhovau** [comment]
This package not contains web interface by (OpenWrt) design.

**Comment by PiotrC1** [comment]
OK, so how to control printers?

**Comment by ryzhovau** [comment]
[From console only](https://wiki.openwrt.org/doc/howto/cups.server).

**Comment by PiotrC1** [comment]
Thank you very much.  But even in a link you sent me there is a remark of adding drivers via web interface.

 

BTW. There are missing urf types which are necessary for AirPrint printing.

 

Best regards,

Piotr Cieslinski

**Comment by davygravy** [comment]
@ryzhovau , the documents at OpenWRT << https://wiki.openwrt.org/doc/howto/cups.server >> say that access via the web interface (:631) is -indeed- expected.

AirPrint is not possible without this interface.
