### ISSUE TITLE
Package Request: Asterisk Gui

### ISSUE THREAD

**Issue by H3xx1st** [Entware-ng/Entware-ng#373]
Asterisk Gui can be installed using this guide, 
http://www.telecom-cafe.com/forum/viewthread.php?tid=4817&extra=&page=1
but its a massive pain.
What are the chances of getting an opkg installable gui for asterisk11, or is there one already available that I missed?

**Comment by ryzhovau** [comment]
It was excluded from OpenWrt feeds as broken. 
Also, it was abandoned 5 years ago.

**Comment by evs38** [comment]
It was broken in OpenWrt, but not broken itself. Revision 5220 from http://svn.digium.com/svn/asterisk-gui/branches/2.0/ is working very well with Asterisk 11 on MIPS and ARM platforms (despite of stopped development). Please include it into entware-ng. Aslo, it is still included in Optware-ng :)
