### ISSUE TITLE
Outdated apcupsd.conf in apcupsd packages

### ISSUE THREAD

**Issue by atx32** [Entware-ng/Entware-ng#374]
The apcupsd packages for every platform do not include a current apcupsd.conf file (which is built from platforms/etc/apcupsd.conf.in). They all show a file built for version 3.14.1. Some parameter names have changed since then so perhaps the packages need to be rebuilt using all the current source files. Thanks.

**Comment by zyxmon** [comment]
fixed - https://github.com/Entware-ng/entware-packages/commit/02cc91595257c635e4483d86975630351b6211a3
Binaries will arrive soon.

**Comment by atx32** [comment]
I see the apcupsd.conf file is updated, but the package filename is still using a -1 number. Shouldn't it be -2 so installations will update properly?

**Comment by zyxmon** [comment]
Have you reinstalled the package?

**Comment by atx32** [comment]
Yes I can force a reinstall, but I thought the updated package would get a new revision number so that opkg would automatically show it as an available upgrade. Sorry if I am missing something here.

**Comment by zyxmon** [comment]
I have considered apcupsd.conf change to be a minor change to increase PKG_RELEASE.
