### ISSUE TITLE
Avahi daemon startup error - 'nogroup' missing

### ISSUE THREAD

**Issue by PiotrC1** [Entware-ng/Entware-ng#376]
Starting avahi-daemon via /opt/etc/init.d/S42avahi-daemon start causes error "Failed to find group 'nogroup'"

**Comment by ryzhovau** [comment]
Duplicate of https://github.com/Entware-ng/Entware-ng/issues/377

**Comment by TCB13** [comment]
Seems like this was never fixed and I can't start avahi... any tips? Is there another way to make it start?

**Comment by PiotrC1** [comment]
Honestly? I'm not using entware-ng any more. Instead I reverted to optware-ng with perfect support.

**Comment by TCB13** [comment]
Yeah still here. 😞

**Comment by zyxmon** [comment]
Running avahi may depend on your device and firmware. For Asuswrt here is the solution
https://www.snbforums.com/threads/avahi-install.10218/

**Comment by TCB13** [comment]
Running on R7000 but I'll give it a try later. Thanks!
