### ISSUE TITLE
CUPS 2.1.4-1 issues

### ISSUE THREAD

**Issue by PiotrC1** [Entware-ng/Entware-ng#377]
There are few CUPS issues:
1) Groups sys and lpadmin missing - daemon cannot start.
2) CUPS doesn't advertise shared printers via D-Bus so Avahi-daemon cannot advertise them further.

**Comment by ryzhovau** [comment]
* Groups is system-specific configuration while Entware stays firmware-independent.
* CUPS doesn't advertise printers via D-Bus to reduce package dependencies. Not all installation requires it.
