### ISSUE TITLE
Package request: XMLStarlet

### ISSUE THREAD

**Issue by linuxnutzer** [Entware-ng/Entware-ng#379]
https://sourceforge.net/projects/xmlstar/

XMLStarlet is a set of command line utilities (tools) to transform, query, validate, and edit XML documents and files using simple set of shell commands in similar way it is done for text files with UNIX grep, sed, awk, diff, patch, join, etc utilities.

Thank you,

Linuxnutzer

**Comment by ryzhovau** [comment]
Now we've got command line tools both for XML and JSON parsing. 

MIPSEL binaries are here, the others will arrive in few days.

**Comment by linuxnutzer** [comment]
Thank you! That was fast. I am impressed.

Linuxnutzer
