### ISSUE TITLE
uClibc-ng-1.0.7.tar.bz2 MD5 sum of the downloaded file does not match (file: 6a3f9de8d11b449471467f5ed3b68d65, requested: d7dbc8ddb0274beacbb48e6928d7b097)

### ISSUE THREAD

**Issue by hiboyhiboy** [Entware-ng/Entware-ng#38]
uClibc-ng-1.0.7.tar.bz2

http://downloads.uclibc-ng.org/releases/1.0.7/uClibc-ng-1.0.7.tar.bz2

MD5 sum of the downloaded file does not match (file: 6a3f9de8d11b449471467f5ed3b68d65, requested: d7dbc8ddb0274beacbb48e6928d7b097) - deleting download.

del 100-no_fanotify_2.6.22.patch
del 200-unistd.patch

**Comment by zyxmon** [comment]
Entware-ng uses 1.0.8 version of uClibc-ng
