### ISSUE TITLE
Package update request: nginx (Build with stream support)

### ISSUE THREAD

**Issue by cmanis** [Entware-ng/Entware-ng#382]
It would be nice to have tcp stream proxy support for proxying ssh/openvpn/etc introduced in 1.9.  It looks like nginx needs to be built with:

--with-stream
--with-stream_ssl_module

Thanks

**Comment by ryzhovau** [comment]
Just added `nginx-extras` package where both options are active. This package is very close to `nginx-extras` Debian package. Binaries will arrive soon.

**Comment by michgeek** [comment]
To people who are interested in that module,  `nginx-extras` is built with `--with-stream=dynamic`.
This mean you have to load the module explicitly in your `nginx.conf` 

```
load_module "lib/nginx/ngx_stream_module.so";
```
