### ISSUE TITLE
Nut Missing Driver Control

### ISSUE THREAD

**Issue by arrmo** [Entware-ng/Entware-ng#384]
Hi,

Having issues very much like in PR #119 - and inside /opt/etc/init.d, this file does not exist.

Also, I see what appears to be needed in the code (repository) - but it's also not installing / showing up. Thoughts?

Thanks!

**Comment by zyxmon** [comment]
Please give more details for you problem.

**Comment by arrmo** [comment]
Sorry - I messed up ... it's inside entware-packages ... do I need to move this issue?

In any case though, if you look at https://github.com/Entware-ng/entware-packages/tree/master/net/nut/files - you can see that nut-server.init includes a line to start the driver ("upsdrvctl start") ... but this is not on the target, when entware-ng is installed.

Thanks!

**Comment by zyxmon** [comment]
Can you provide the correct Entware startup file or make a PR?

**Comment by arrmo** [comment]
I'd like to! But I admit, not sure why the files that are there are not getting installed as part of the overall install - they would fix the issue.

Sorry!

**Comment by zyxmon** [comment]
`upsdrvctl` is installed in `/opt/sbin` folder. Please provide an Entware style startup script that uses it. Entware developers do not use nut. Only users that use nut can fix and check the script.

**Comment by arrmo** [comment]
Sure! As this is a router, here is what I have added to my init script (and confirmed, this works),

upsdrvctl start
ln -s /opt/share/www/cgi-bin/nut /tmp/var/wwwext/cgi-bin/nut

echo '#!/bin/sh' > /etc/nut-notifycmd
echo '(echo "Subject: $*"; echo; echo "UPS Status (`uname -n`)..."; upsc Belkin@localhost) | msmtp xxxx@xxxx.xxx' >> /etc/nut-notifycmd
chmod +x /etc/nut-notifycmd

Does this help?

**Comment by zyxmon** [comment]
>> Does this help?

There is no stop command for `upsdrvctl`. This may helpful for other users. But it is not the full script to be included in Entware. I am closing the issue. If somebody publishes a full solution or a PR it will be added to Entware.
