### ISSUE TITLE
Package Update Request - Snort 2.9.7.2-4 to 2.9.8.3 for ruleset support

### ISSUE THREAD

**Issue by m0rd3cai** [Entware-ng/Entware-ng#386]
I cannot located default rules package for 2.9.7.2-4 anywhere and i'm not able to find ruleset for this version. I am also not knowlegable enough to compile a newer version for Arm. Can someone please compile 2.9.8.3 which is the newest supported version of snort for Arm? Unless you can manually build your own ruleset, this package is basically useless.

**Comment by ryzhovau** [comment]
Please, ask [upstream](https://github.com/openwrt/packages/tree/master/net/snort) for that and update will arrive here in next month.
