### ISSUE TITLE
minidlna armv5 - broken dependencies - libx264

### ISSUE THREAD

**Issue by tytusmastah** [Entware-ng/Entware-ng#387]
Hi, 
Cannot install minidlna on armv5 because the lack of libx264.

`[~] # opkg update; opkg install minidlna`
`Downloading http://pkg.entware.net/binaries/armv5/Packages.gz.`
`Updated list of available packages in /opt/var/opkg-lists/packages.`
`Installing minidlna (1.1.5-1a) to root...`
`Downloading http://pkg.entware.net/binaries/armv5/minidlna_1.1.5-1a_armv5soft.ipk.`
`Collected errors:`
` * satisfy_dependencies_for: Cannot satisfy the following dependencies for minidlna:`
` * 	libx264 * `
` * opkg_install_cmd: Cannot install package minidlna.`
`[~] # date`
`Fri Sep  9 21:20:59 CEST 2016`
`[~] # uname -a`
`Linux 3.4.6 #1 Thu Sep 1 09:48:22 CST 2016 armv5tel GNU/Linux`

**Comment by zyxmon** [comment]
Try to install with force-depends flag. The issue will be fixed later. There is no libx264 for armv5.

**Comment by zyxmon** [comment]
fixed - https://github.com/Entware-ng/entware-packages/commit/2df2eed9f9225d3118445a1f0b5fdc7ee88b2255
