### ISSUE TITLE
asterisk11-chan-sccp-b not working

### ISSUE THREAD

**Issue by evs38** [Entware-ng/Entware-ng#389]
mipself version of asterisk. When loading this module into Asterisk, it stops with following error message:
`ERROR[2771]: sccp_utils.c:2186 __start_iconv: SCCP:conversion from 'UTF-8' to 'ISO8859-1' not available.`
iconv, libcharset and libiconv-full packages are installed.

**Comment by ryzhovau** [comment]
PR's are welcome as long as we don't use asterisk.
This package came from OpenWrt upstream without any changes.

**Comment by ryzhovau** [comment]
We going to sit on this and wait for fix from upstream.
