### ISSUE TITLE
reconfigure package "shadowsocks-libev" and "shadowsocks-libev-polarssl"

### ISSUE THREAD

**Issue by mzhboy** [Entware-ng/Entware-ng#39]
we need executable file `ss-local` and `ss-server` , but the package `shadowsocks-libev` and `shadowsocks-libev-polarssl` do not have them.

**Comment by zyxmon** [comment]
This comes from openwrt Makefile - https://github.com/openwrt/packages/blob/master/net/shadowsocks-libev/Makefile

Line 78.
`ss-local` and `ss-server` are built for some reason not included in ipk.

**Comment by zyxmon** [comment]
fixed in https://github.com/Entware-ng/entware-packages/commit/da77e29bb66b43a590da9ce9de346df2877788d5
also upgraded to 2.4.2
