### ISSUE TITLE
Package request - wireless-tools

### ISSUE THREAD

**Issue by StephenSuley** [Entware-ng/Entware-ng#394]
Hello, 

I was wondering if you could add the package **wireless-tools** package to the armv7 trunk?  

https://packages.debian.org/wheezy/wireless-tools

Its used to manipulate the Linux Wireless Extensions. The Wireless Extension is an interface allowing you to set Wireless LAN specific parameters and get the specific stats.

airmon-ng  requires it as well.

**Comment by ryzhovau** [comment]
There's no sense in `wireless-tools

**Comment by StephenSuley** [comment]
I understand. Would adding only the wireless-tools for bcrm47xx and bcrm57xx based SoC device be an option?

**Comment by ryzhovau** [comment]
No, it won't work with Broadcom SoCs. Tried before.

**Comment by StephenSuley** [comment]
oh, okay then , that settles it. Thanks for responding and all your work on entware.
