### ISSUE TITLE
Entware-ng on ZyXel VMG8324-B10A

### ISSUE THREAD

**Issue by DOFfactory** [Entware-ng/Entware-ng#396]
Sorry for bothering you with this issue but I am struggling with installing entware-ng on my type of router (ZyXel VMG8324-B10A). As far as I know it is a MIPSEL-based, so theoretically it should be possible to install entware on it.

However, I am unable to locate the pre-mount and pre-unmount script possibilities, required by the entware-ng installation: [https://github.com/Entware-ng/Entware-ng/wiki/Install-on-Asus-stock-firmware](url)

Can any of you help me with the beginning of the installation steps? I would be extremely grateful for any help or showing me the right direction.

**Comment by zyxmon** [comment]
It should be also linux based (not ZyNOS based) and have some hooks to start external scripts.
Ask your question on some zyxel forums. Entware is a univrsal repo. We have published all installation methods we know.
