### ISSUE TITLE
Package Update: pixelserv-tls (v35.HZ12.Ki)

### ISSUE THREAD

**Issue by Veldkornet** [Entware-ng/Entware-ng#398]
Update pixelserv-tls from (v35.HZ12.Kh) to (v35.HZ12.Ki)

https://github.com/kvic-z/pixelserv-tls/wiki/Release-notes-for-version-Ki-(v35.HZ12.Ki)

**Comment by ryzhovau** [comment]
Done, binaries will arrive soon.
