### ISSUE TITLE
A toolchain cross compiler for the entware-ng

### ISSUE THREAD

**Issue by houzi-** [Entware-ng/Entware-ng#40]
erro:
```shellscript
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... no
checking whether pthreads work with -pthreads... no
checking whether pthreads work with -mthreads... no
checking for the pthreads library -lpthread... no
checking whether pthreads work with --thread-safe... no
checking whether pthreads work with -mt... no
checking for pthread-config... no
configure: error: Missing Pthread Library
```
My compiler parameter is：
```shellscript
LIBS="-ldl" LDFLAGS="-Wl,-static -static -static-libgcc" ./configure --host=mipsel-openwrt-linux-uclibc CC=mipsel-openwrt-linux-gcc --with-openssl=/home/mipsel/openssl --with-zlib=/home/mipsel/zlib
```

**Comment by zyxmon** [comment]
It is configure script that cannot find threads support.
Please use openwrt style Makefiles to build packages. Try to set `PKG_FIXUP:=autoreconf` in case of similar errors.

**Comment by houzi-** [comment]
@zyxmon Because shadowsocks-libev update to the latest version, and entware or old version , want to build a new one, I do not know whether you will update shadowsocks-libev
https://github.com/shadowsocks/shadowsocks-libev

**Comment by zyxmon** [comment]
All you need to change - is to update Makefile (and patches) here - https://github.com/Entware-ng/entware-packages/tree/master/net/shadowsocks-libev

**Comment by zyxmon** [comment]
the package is upgraded in - https://github.com/Entware-ng/entware-packages/commit/da77e29bb66b43a590da9ce9de346df2877788d5
