### ISSUE TITLE
Package request: ttyd - Share your terminal over the web

### ISSUE THREAD

**Issue by hiboyhiboy** [Entware-ng/Entware-ng#400]
https://github.com/tsl0922/ttyd

ttyd is a simple command-line tool for sharing terminal over the web, inspired by GoTTY.

![image](https://cloud.githubusercontent.com/assets/10822946/18977351/2a161f18-86ec-11e6-8d0a-9e712a140dec.png)

**Comment by zyxmon** [comment]
It it better then shellinabox, that is already in repo?
https://github.com/shellinabox/shellinabox

**Comment by hiboyhiboy** [comment]
shellinabox better

**Comment by zyxmon** [comment]
I am leaving the issue open - ttyd was added to owrt packages list 3 days ago - https://github.com/openwrt/packages/tree/master/utils/ttyd
May be we will add this package when we will sync with owrt....

**Comment by ryzhovau** [comment]
Done.
