### ISSUE TITLE
Package request: trickle

### ISSUE THREAD

**Issue by kustra** [Entware-ng/Entware-ng#401]
Trickle (https://github.com/mariusae/trickle) is a voluntary, cooperative bandwidth shaper. trickle works entirely in userland and is cross platform compatible.

Usage:
`trickle -d Download_Bandwidth -u Upload_Bandwidth command`

A guide for using it: https://linuxaria.com/article/manage-your-bandwidth-with-trickle

**Comment by ryzhovau** [comment]
Looks like old object overload hack for libc, which is incompatible for some libc implementations.
