### ISSUE TITLE
very old mkvtoolnix

### ISSUE THREAD

**Issue by 1soproni** [Entware-ng/Entware-ng#405]
Hi,

I just installed entware-ng to my Synology DS416play.
I wanted to use mkvtoolnix so I installed it and it is very old (2010-07-28).
9.4.2 was published already.

Package: mkvtoolnix
Version: 4.2.0-4
Depends: libc, libssp, librt, libpthread, boost-filesystem, boost-regex, libbz2, libexpat, libflac, liblzo, libmagic, libmatroska, libvorbis, libiconv-full, libintl-full
Status: install user installed
Section: multimedia
Architecture: x86-64
Maintainer: Entware team, http://entware.net
MD5Sum: 915248b9fcb2e43230f07f24cd4e6497
Size: 1835257
Filename: mkvtoolnix_4.2.0-4_x86-64.ipk
Source: feeds/rtndev/mkvtoolnix
Description: A set of tools to create, alter and inspect Matroska files.
Installed-Time: 1475583223

**Comment by zyxmon** [comment]
This is the last mkvtoolnix version that uses gnu make.
All new mkvtoolnix versions use drake (ruby based) that is not supported by openwrt buildroot. Probably we will try to build a newer version later. But it requires a lot of efforts.

**Comment by zyxmon** [comment]
The latest version 9.6.0 will be in binary repos in few days
https://github.com/Entware-ng/rtndev/commit/63fb8ee2617f348ee0062882be7deb6196c3f934
