### ISSUE TITLE
at - 3.1.16-2 has issues

### ISSUE THREAD

**Issue by hchr** [Entware-ng/Entware-ng#407]
If I try to run at with
at now +1 minutes -f /mnt/logs/delete-this-is-a-test.sh
at says
Cannot get gid for nogroup: Success

If I do
echo nogroup:x:0: >>/etc/group

and then
at now +1 minutes -f /mnt/logs/delete-this-is-a-test.sh 
warning: commands will be executed using /bin/sh
job 32 at Wed Oct  5 14:39:00 2016
Can't open /var/run/atd.pid to signal atd. No atd running?

atq now has a job
atq
32      Wed Oct  5 14:39:00 2016 a root

If I do 
service atd start
.
Done.

and run
at now +1 minutes -f /mnt/logs/delete-this-is-a-test.sh 
warning: commands will be executed using /bin/sh
job 33 at Wed Oct  5 14:42:00 2016
Can't open /var/run/atd.pid to signal atd. No atd running?

If do
ls -al /var/run/
drwxr-xr-x    2 root     root           180 Oct  5 16:30 .
drwxr-xr-x   11 root     root           220 Jan  1  1970 ..
-rw-r--r--    1 root     root             5 Jan  1  1970 crond.pid
-rw-r--r--    1 root     root             5 Oct  5 16:30 dnsmasq.pid
-rw-r--r--    1 root     root             5 Jan  1  1970 dropbear.pid
-rw-r--r--    1 root     root             4 Oct  5 16:25 httpd.pid
-rw-r--r--    1 root     root             4 Jan  1  1970 klogd.pid
-rw-r--r--    1 root     root             4 Jan  1  1970 syslogd.pid
-rw-r--r--    1 root     root             5 Oct  5 16:25 udhcpc-wan.pid

there is no atd.pid

If I do
touch /var/run/atd.pid

and then run
at now +1 minutes -f /mnt/logs/delete-this-is-a-test.sh 
warning: commands will be executed using /bin/sh
job 34 at Wed Oct  5 14:45:00 2016

Then no more complaining about ATD, but the script isn't started at the specified time.

**Comment by zyxmon** [comment]
Thanks for reporting and a small investigation. Bug is fixed - https://github.com/Entware-ng/entware-packages/commit/1ccafdd8703c81998cbc15665eaf3c20cc2b27e5
nogroup is replaced by nobody group - it looks it is used in different firmwares.
pid folder is fixed. Binaries will be available with next sync with owrt.
