### ISSUE TITLE
Package request: pdnsd

### ISSUE THREAD

**Issue by 275761919** [Entware-ng/Entware-ng#408]
pdnsd can transform from udp domain name requests to tcp  domain name requests.

pdnsd - offical site:
http://members.home.nl/p.a.rombouts/pdnsd/

OpenWrt remove the pdnsd in Chaos Calmer 15.05, I don't know the reason that they do so.

Hope you can include the package pdnsd!

**Comment by ryzhovau** [comment]
I see no sense to add another DNS server to repo, sorry. 
You can use `unbound` for TCP-only querries.
