### ISSUE TITLE
Package update request: tmux 2.3

### ISSUE THREAD

**Issue by moontear** [Entware-ng/Entware-ng#409]
We're currently on tmux 2.2-1 which is great, but tmux 2.3 would be so much better: https://github.com/tmux/tmux/blob/master/CHANGES

> - New option 'pane-border-status' to add text in the pane borders.

The best option since sliced bread, be able to name your panes without ugly hacks and workarounds. Please update the package to the newest version.

**Comment by zyxmon** [comment]
Repository is updated. Binaries will arrive soon.
