### ISSUE TITLE
package request/update psutil to 3.3.0

### ISSUE THREAD

**Issue by jump1e** [Entware-ng/Entware-ng#41]
hello, first time using this so I hope I do it right! Could psutil be updated to 3.3.0 by any chance? Thank you! :)

**Comment by zyxmon** [comment]
AFAIU @jump1e wants this package - https://github.com/Entware-ng/rtndev/tree/master/python-psutil
to be upgraded. But he did not give us the feed he uses. I cannot build package for testing without knowing the feed/architecture!

**Comment by zyxmon** [comment]
@jump1e - please test the package and report here
http://entware.zyxmon.org/binaries/x86-64/test/python-psutil_3.3.0-1_x86-64.ipk

run to install
```
opkg install http://entware.zyxmon.org/binaries/x86-64/test/python-psutil_3.3.0-1_x86-64.ipk
```

**Comment by jump1e** [comment]
It seems to be working! I'm using it with HTPC Manager (https://github.com/Hellowlol/HTPC-Manager) and now I'm getting all my system stats, thank you so much! :)

**Comment by ryzhovau** [comment]
Done https://github.com/Entware-ng/rtndev/commit/5028c75be5ede34eb792c751701b9a547d5cc2df.

Binaries will be arrive on this week.
