### ISSUE TITLE
Package update request: iptables 1.6.0

### ISSUE THREAD

**Issue by OkashiOdayakana** [Entware-ng/Entware-ng#410]
Update iptables from v1.4.21 to v1.6.0

https://www.netfilter.org/projects/iptables/files/changes-iptables-1.6.0.txt

**Comment by zyxmon** [comment]
compiling iptables requires raw kernel headers, that are rather old for entware-ng.
If you have a new kernel and need new iptables - upgrade to Entware-3x - https://github.com/Entware-for-kernel-3x
