### ISSUE TITLE
make all fails due to feeds/oldports/unfs3 refrering to non-existant git-hub repo

### ISSUE THREAD

**Issue by droberg** [Entware-ng/Entware-ng#411]
From feeds/oldports/unfs3/Makefile :
...
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.bz2
PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
PKG_SOURCE_URL:=https://github.com/markusn/unfs3.git
PKG_SOURCE_PROTO:=git
PKG_SOURCE_VERSION:=$(PKG_REV)
...

https://github.com/markusn/unfs3.git seems to have disappeared from github.

**Comment by zyxmon** [comment]
I have added `unfs3-0.9.23.tar.bz2` to Entware sources mirror as a temporary solution
