### ISSUE TITLE
make all fails because librsync secretly depends on popt

### ISSUE THREAD

**Issue by droberg** [Entware-ng/Entware-ng#412]
In feeds/oldports/librsync/Makefile dependencies on libbz2 and zlib are listed. However, librsync also depends on package/libs/popt.

```
feeds/oldports/librsync/Makefile:
----------------------------------------------
define Package/librsync
  SECTION:=libs
  CATEGORY:=Libraries
  TITLE:=implementation of the rolling-checksum algorithm
  DEPENDS:=+libbz2 +zlib
  URL:=http://librsync.sourceforge.net/
endef
-----------------------------------------------
```
I don't know whether these things should be reported upstreams or if report should go somewhere completely different. Please point me in any direction you'd like.

**Comment by zyxmon** [comment]
Cannot confirm it

```
 # opkg install librsync
Installing librsync (2.0.0-1) to root...
Downloading http://entware-3x.zyxmon.org/binaries/mipsel/librsync_2.0.0-1_mipsel-3x.ipk.
Configuring librsync.
# opkg files librsync
Package librsync (2.0.0-1) is installed on root and has the following files:
/opt/lib/librsync.so.2
/opt/lib/librsync.so.2.0.0
/opt/lib/librsync.so
# ldd /opt/lib/librsync.so
ldd: $warning: you do not have execution permission for `/opt/lib/librsync.so'
        libbz2.so.1.0 => /opt/lib/libbz2.so.1.0 (0x77ca0000)
        libz.so.1 => /opt/lib/libz.so.1 (0x77c7c000)
        libc.so.6 => /opt/lib/libc.so.6 (0x77af9000)
        /lib/ld.so.1 (0x77d0e000)
```

**Comment by droberg** [comment]
Weird, I had to manually install it to move on. Unfortunately I don't recall the exact error message. I'll get back with some more info.

**Comment by droberg** [comment]
Ok, so I did some digging:

`../build_dir/target-arm_cortex-a9_glibc-2.23_eabi/librsync-2.0.0$ cat CMakeLists.txt  | grep -i popt`
`# Find POPT`
`find_package(POPT REQUIRED)`
`if ( POPT_FOUND )`
`  include_directories(${POPT_INCLUDE_DIRS})`
`endif ( POPT_FOUND )`
`target_link_libraries(rdiff rsync ${POPT_LIBRARIES})`

To retrigger the error i did
`../build_dir/target-arm_cortex-a9_glibc-2.23_eabi/librsync-2.0.0$ rm -rf librsync-2.0.0`
'..$ find staging_dir/target-arm_cortex-a9_glibc-2.23_eabi/opt/lib -name "libpopt.*" | xargs rm' 
'..$ make V=s package/feeds/oldports/librsync/compile'
This gives:

> CMake Error at /mnt/Agent007-homes/oberg/Projects/AsusWRT/Entware- ng/staging_dir/host/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
>  Could NOT find POPT (missing: POPT_LIBRARIES POPT_INCLUDE_DIRS)

**Comment by droberg** [comment]
An to solve the error i added "+popt" in Makefile ending up with:

```
feeds/oldports/librsync/Makefile:
----------------------------------------------
define Package/librsync
  SECTION:=libs
  CATEGORY:=Libraries
  TITLE:=implementation of the rolling-checksum algorithm
  DEPENDS:=+libbz2 +zlib +popt
  URL:=http://librsync.sourceforge.net/
endef
----------------------------------------------

```

**Comment by zyxmon** [comment]
Thanks for reporting. Bug is confirmed and fixed differently - https://github.com/Entware-ng/entware-oldpackages-ports/commit/2258d52f119663ed05c6da3d1229ad67b33f3fe6
