### ISSUE TITLE
Syncthing 0.14

### ISSUE THREAD

**Issue by onichan88** [Entware-ng/Entware-ng#414]
Hello,

Ok, now I know that is not possible to compile syncthing 0.14, because it needs at least go 1.5

But can be possible to install the binary arm of syncthing? And if is possible, how can be configured?

There are plans to updste gccgo?

**Comment by zyxmon** [comment]
gccgo is a part of gcc project. I hму no idea when gccgo will be updated.
You can try to build Syncthing for arm (v7) using Google go compiler yourself.
