### ISSUE TITLE
[Subversion Server] mod_dav_svn and mod_authz_svn apache modules missing

### ISSUE THREAD

**Issue by JANogueira** [Entware-ng/Entware-ng#415]
Hi All,

I am using Entware-NG for ARMv7 (I own a QNAP TS-131) and I found that these two Apache modules are missing from subversion server installation.
mod_dav_svn
mod_authz_svn

These modules are generally part of the subversion-server package, but are missing on the current Entware-ng available package.
Can you please add them? This is important to enable SVN over HTTP(S) and also to enable Web managers for SVN Server (like uSVN).

Thank you in advance.
Cheers
J.A.Nogueira

**Comment by zyxmon** [comment]
Entware follows Openwrt packages configuration. We cannot change individual packages configuration because it will make sync with owrt difficult.
Please ask owrt developers to add these modules. We will do the same.
