### ISSUE TITLE
Package Request: collectd

### ISSUE THREAD

**Issue by nixikanius** [Entware-ng/Entware-ng#417]
https://wiki.openwrt.org/doc/howto/statistic.collectd

collectd is a small daemon which collects system information periodically and provides mechanisms to store the values in a variety of ways.

**Comment by kofec** [comment]
I am also interested in. Please add this package

**Comment by kofec** [comment]
Hi,
Can you help me - the package seems to compile fine but package was not create:

...../Entware-ng-3x $ make package/collectd/compile
WARNING: your configuration is out of sync. Please run make menuconfig, oldconfig or defconfig!
 make[1] package/collectd/compile
 make[2] -C package/libs/toolchain compile
 make[2] -C package/libs/libtool compile
 make[2] -C package/libs/zlib compile
 make[2] -C feeds/packages/utils/collectd compile
....../Entware-ng-3x $ ls -al bin/mipsel-3x-glibc/packages/
and no package "collectd" here

**Comment by zyxmon** [comment]
@kofec - have you selected `collectd` in `make menuconfig`?

**Comment by kofec** [comment]
no. but I tried and modified .config and  change line:
CONFIG_PACKAGE_collectd=m

Now I have diffrent issue:
mkdir -p /home/kofec/openwrt/Entware-ng-3x/bin/mipsel-3x-glibc/packages /home/kofec/openwrt/Entware-ng-3x/build_dir/target-mipsel_mips32r2_glibc-2.23/collectd-5.5.2/ipkg-mipsel-3x/collectd/CONTROL /home/kofec/openwrt/Entware-ng-3x/staging_dir/target-mipsel_mips32r2_glibc-2.23/pkginfo
install -d -m0755 /home/kofec/openwrt/Entware-ng-3x/build_dir/target-mipsel_mips32r2_glibc-2.23/collectd-5.5.2/ipkg-mipsel-3x/collectd/usr/sbin
install -m0755 /home/kofec/openwrt/Entware-ng-3x/build_dir/target-mipsel_mips32r2_glibc-2.23/collectd-5.5.2/ipkg-install/usr/sbin/collectd /home/kofec/openwrt/Entware-ng-3x/build_dir/target-mipsel_mips32r2_glibc-2.23/collectd-5.5.2/ipkg-mipsel-3x/collectd/usr/sbin/
install: cannot stat '/home/kofec/openwrt/Entware-ng-3x/build_dir/target-mipsel_mips32r2_glibc-2.23/collectd-5.5.2/ipkg-install/usr/sbin/collectd': No such file or directory
make[2]: *** [/home/kofec/openwrt/Entware-ng-3x/bin/mipsel-3x-glibc/packages/collectd_5.5.2-2_mipsel-3x.ipk] Error 1
make[2]: Leaving directory `/home/kofec/openwrt/Entware-ng-3x/feeds/packages/utils/collectd'
make[1]: *** [package/feeds/packages/collectd/compile] Error 2
make[1]: Leaving directory `/home/kofec/openwrt/Entware-ng-3x'
make: *** [package/collectd/compile] Error 2

**Comment by zyxmon** [comment]
Entware uses `/opt` folder, your Makefile has bugs.

**Comment by kofec** [comment]
It looks like that the path is wrong I will try symlink:
all files are: 
/home/kofec/openwrt/Entware-ng-3x/build_dir/target-mipsel_mips32r2_glibc-2.23/collectd-5.5.2/ipkg-install/opt/bin/
but not in:
/home/kofec/openwrt/Entware-ng-3x/build_dir/target-mipsel_mips32r2_glibc-2.23/collectd-5.5.2/ipkg-mipsel-3x/collectd/usr/sbin

**Comment by kofec** [comment]
aaa OK. But it is your makefile - collectd is in your repository but not mark to compile

**Comment by zyxmon** [comment]
It is a Makefile for openwrt. You need to modify it to make an entware package. I do not think issues is a proper place for your questions. Use forums to discuss package creation.

**Comment by kofec** [comment]
OK I will do that. Please point me to forum which I can use.

**Comment by zyxmon** [comment]
Closing.

**Comment by nixikanius** [comment]
Am I right understand that you added collectd package to repo?

**Comment by zyxmon** [comment]
>> Am I right understand that you added collectd package to repo?
This means I have not found the forum with package creation discussion and a topic by @kofec

**Comment by zyxmon** [comment]
Probably collectd is to heavy for mipsel. Vnstat(d) is tested and working in Entware.

**Comment by nixikanius** [comment]
vnstat is a tool only for network monitoring. collectd is universal monitoring tool that could monitor CPU, memory, swap, disk, network, etc. collectd is main collector tool for time series databases like graphite, influxdb, opentsdb, prometheus, etc.

If in help with Entware we could install nginx, openvpn and other heavy for mipsel tools I think collectd is needed for modern monitoring of them.

**Comment by zyxmon** [comment]
As I can see @kofec managed to build collectd. The only thing he did not do - he di not modified Makefile: /usr -> /opt ....
I hope he will build collectd correctly and test it. We will add package after such tests.
PS If the package is created does not mean it is working!

**Comment by nixikanius** [comment]
OK, thank you!

**Comment by ProBackup-nl** [comment]
@zyxmon I am stuck with "my first Entware-ng package creation". I have read OpenWrt documentation, have adapted the Makefile for "/opt" and changed "SECTION:=net" to "SECTION:=network". The /prepare phase does stuff, however /compile phase seems to do very little. Which forum do you recommend for discussing "package creation"?
