### ISSUE TITLE
Package Request: Comskip

### ISSUE THREAD

**Issue by mikeburgh** [Entware-ng/Entware-ng#418]
Looking for a package for Comskip: https://github.com/erikkaashoek/Comskip

**Comment by zyxmon** [comment]
I am afraid it it too heavy for most embedded devices that are using entware.
Let us wait for more requests for comskip.

**Comment by mikeburgh** [comment]
Thanks, appreciate the response, and agree far to heavy for most. I will keep trying to get it to compile on QNAP.
