### ISSUE TITLE
Package request: fdupes (duplicate files - was on Optware ipkg)

### ISSUE THREAD

**Issue by max-devel** [Entware-ng/Entware-ng#419]
Hi. fdupes is a program for identifying or deleting duplicate files. It was part of Optware and I had it working with ipkg on my QNAP NAS so hopefully it is not too hard to bring back. The source is here https://github.com/adrianlopezroche/fdupes and wikipedia has an article here https://en.wikipedia.org/wiki/Fdupes
Many thanks.

Best,
Max

**Comment by libertyx82** [comment]
I hope also that it can be taken from ipkg

**Comment by zyxmon** [comment]
fdupes was added to Entware-3x fork and will be available in binary repos in few days
https://github.com/Entware-for-kernel-3x/rtndev-3x/tree/master/fdupes

**Comment by libertyx82** [comment]
is it already in the binary repos?
On the reason that i can´t find it :(

**Comment by ryzhovau** [comment]
Done.
