### ISSUE TITLE
strongswan ipsec start issues

### ISSUE THREAD

**Issue by Karnith** [Entware-ng/Entware-ng#420]
Tomato v1.28.0000 -138 K26ARM USB AIO-64K

root@unknown:/tmp/home/root# ipsec start
no files found matching '/opt/etc/strongswan.d/*.conf'
Starting strongSwan 5.5.0 IPsec [starter]...
modprobe: module af_key not found in modules.dep
no netkey IPsec stack detected
modprobe: module ipsec not found in modules.dep
no KLIPS IPsec stack detected
no known IPsec stack detected, ignoring!
root@unknown:/tmp/home/root#

This is an arm tomato Asus router Asus RT-AC68U

Some more context:

root@unknown:/tmp/home/root# /opt/lib/ipsec/starter --nofork; echo $?
no files found matching '/opt/etc/strongswan.d/.conf'
Starting strongSwan 5.5.0 IPsec [starter]...
modprobe: module af_key not found in modules.dep
no netkey IPsec stack detected
modprobe: module ipsec not found in modules.dep
no KLIPS IPsec stack detected
no known IPsec stack detected, ignoring!
00[LIB] no files found matching '/opt/etc/strongswan.d/.conf'
00[DMN] Starting IKE charon daemon (strongSwan 5.5.0, Linux 2.6.36.4brcmarm, armv7l)
00[CFG] disabling load-tester plugin, not configured
00[LIB] plugin 'load-tester': failed to load - load_tester_plugin_create returned NULL
00[LIB] failed to open /dev/net/tun: No such file or directory
00[LIB] plugin 'kernel-libipsec': failed to load - kernel_libipsec_plugin_create returned NULL
00[NET] installing IKE bypass policy failed
00[NET] installing IKE bypass policy failed
00[NET] enabling UDP decapsulation for IPv6 on port 4500 failed
00[NET] installing IKE bypass policy failed
00[NET] installing IKE bypass policy failed
00[NET] enabling UDP decapsulation for IPv4 on port 4500 failed
00[LIB] feature CUSTOM:libcharon in critical plugin 'charon' has unmet dependency: CUSTOM:kernel-ipsec
00[CFG] attr-sql plugin: database URI not set
00[CFG] loading ca certificates from '/opt/etc/ipsec.d/cacerts'
00[CFG] loading aa certificates from '/opt/etc/ipsec.d/aacerts'
00[CFG] loading ocsp signer certificates from '/opt/etc/ipsec.d/ocspcerts'
00[CFG] loading attribute certificates from '/opt/etc/ipsec.d/acerts'
00[CFG] loading crls from '/opt/etc/ipsec.d/crls'
00[CFG] loading secrets from '/opt/etc/ipsec.secrets'
00[CFG] loaded IKE secret for 50.245.158.5 104.40.54.31
00[CFG] sql plugin: database URI not set
00[CFG] loaded 0 RADIUS server configurations
00[CFG] HA config misses local/remote address
00[CFG] coupling file path unspecified
00[LIB] failed to load 1 critical plugin feature
00[DMN] initialization failed - aborting charon
charon has quit: initialization failed
charon refused to be started
ipsec starter stopped
0

thx

**Comment by zyxmon** [comment]
Entware is a universal repo for different devices. If you need some kernel modules for ipsec - ask for them from firmware manufacturer.
