### ISSUE TITLE
syncthing package needs update

### ISSUE THREAD

**Issue by meoso** [Entware-ng/Entware-ng#421]
Syncthing package for [ARMv5](http://pkg.entware.net/binaries/armv5/Packages.html) is at version `0.13.4-1` but version `0.14.7` is available and required for compatibility with other updated clients.

edit: https://github.com/syncthing/syncthing/releases shows `0.14.8`

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/Entware-ng/issues/413

You can try to compile it yourself using glang. It is impossible now in Entware!

**Comment by meoso** [comment]
Without extended review (just some quick and dirty config), it seems the official released binary works out of the box.

**Comment by zyxmon** [comment]
https://github.com/golang/go/wiki/GoArm
It looks like syncthing arm binary was compiled with GOARM=5 value - so it will work!
