### ISSUE TITLE
hplip not complied with scanning support?

### ISSUE THREAD

**Issue by ggppjj** [Entware-ng/Entware-ng#422]
Hello!

I am attempting to follow the instructions in the Wiki to enable network scanning using SANE and my HP CM1015 MFP scanner. The scanner is detected, all services are running, but attmepting to scan gives me:

> scanimage: open of device hpaio:/usb/HP_Color_LaserJet_CM1015?serial=00CNCY72S0YH failed: Error during device I/O

Attempting to run hp-scan says:

> error: Scanning disabled in build. Exiting

Not sure what's going on, but seems like there's a bug in hplip's mipselsf package not being built with scanning support, or something else odd going on.

**Comment by ggppjj** [comment]
DD-WRT build 30771, newest available mipselsf packages following the wiki exactly, all services started and running successfully, WNDR4500v1,

**Comment by zyxmon** [comment]
From the hplip site - http://hplipopensource.com/hplip-web/models/color_laserjet/hp_color_laserjet_cm1015.html

>> This printer REQUIRES a downloadable driver plug-in, which is required to enable print, fax or scan support. Use hp-setup to install the printer, and to download and install the plug-in. Driver plug-ins are released under a proprietary (non-open) license and are not part of the HPLIP tarball release.

I am not sure propriety plug-in will work with mipsel.

**Comment by ggppjj** [comment]
Huh. Well that's annoying, but not really Entware-ng's packaging fault. Thanks!
