### ISSUE TITLE
New feed for homeautomation (Was Package request: telldus-core et al)

### ISSUE THREAD

**Issue by droberg** [Entware-ng/Entware-ng#425]
I hav prepared a feed for telldus-core:
https://github.com/droberg/entware-tellstick

This will also include a package for a python server .

The code currently compiles for armv7, but I believe I need to apply a pair of patches to make it compile for mips.

Please advice regarding steps to eventually add this somewhere appropriate .

**Comment by droberg** [comment]
I have now renamed my repository to entware-homeautomation (https://github.com/droberg/entware-homeautomation). I plan to add openHAB, Home Assistant and TellLive python wrapper + possibly other home automation software. 

Currently I have added packages and dependencies for
* telldus-core
* tellcore-py
and tellprox is coming up. After that I will start with the others.

**Comment by ryzhovau** [comment]
Thanks for info! 

Is there something wrong with [`python-werkzeug`](https://github.com/Entware-ng/rtndev/tree/master/python-werkzeug) package from rtndev feed? It's tested with `weave-minimal` with no issues.

**Comment by droberg** [comment]
Most likely not, I played it safe and used the same versions of all packages that I had working trough setuptool to simplify the debugging. (I wasn't 100% sure of what I was doing at the time and had some strange issues with missing stuff.)

I will soon upgrade all packages to later versions and then I will switch to the already available werkzeug package. 

Thanks for pointing it out so I don't forget.

**Comment by ryzhovau** [comment]
I don't how to deal with this issue. Most likely I have to close it because there's no any task for us to do.

**Comment by droberg** [comment]
Now that it isn't a package-request anymore I guess  you are right. A long time goal is that the packages are either accepted in some of the other feeds or that the feed could be added to the "official" feeds list, but It's not mature enough yet. 

I haven't seen any experimental feeds list but that would be another option.

**Comment by droberg** [comment]
B.t.w., if you need help with some of the other issues I might be able to give it a shot. I figure I might learn something in the process while not taking up to much of your time.

**Comment by ryzhovau** [comment]
Thanks. I'll keep in mind that.
