### ISSUE TITLE
Package update request : Nginx with http_sub_module

### ISSUE THREAD

**Issue by altaroinj** [Entware-ng/Entware-ng#428]
Could you please compile Nginx with the following parameter : 
[--with-http_sub_module](http://nginx.org/en/docs/configure.html)
It would enable string substitutions in nginx response.
[Example](http://marsbard.github.io/2016-07-30-replace-urls-behind-nginx-reverse-proxy/)

**Comment by ryzhovau** [comment]
Check out `nginx-extras` package which is very close to similar Debian package. `http_sub_module` is active here. Binaries will arrive soon.
