### ISSUE TITLE
Package request: nghttp2

### ISSUE THREAD

**Issue by DJCMBear** [Entware-ng/Entware-ng#429]
Can we get version 1.16.0 or higher (highest currently is 1.16.0) of nghttp2 in the repos https://nghttp2.org ideally so I can install it on my QNAP TVS-871?

**Comment by ryzhovau** [comment]
Every library from repo is used by other packages. I see no sense to add libraries without some soft where it will be used. 

Also, you may compile this library on QNAP natively for you own needs.
