### ISSUE TITLE
Package Request: Perl Net::SSLeay & IO::Socket::SSL Modules

### ISSUE THREAD

**Issue by jsetton** [Entware-ng/Entware-ng#430]
Related to the package request for ddclient #342, there is one major issue, while trying to install this tool manually, which requires two Perl SSL modules [Net::SSLeay](http://search.cpan.org/~mikem/Net-SSLeay-1.78/lib/Net/SSLeay.pod) & [IO::Socket::SSL](http://search.cpan.org/~sullr/IO-Socket-SSL-2.038/lib/IO/Socket/SSL.pod) to support SSL connexions.

While IO::Socket::SSL can easily be installed manually, the other module Net::SSLeay requires compilation which is hard to accomplish on mips devices such as older Asus routers. Some DNS providers such as [CloudFlare](https://support.cloudflare.com/hc/en-us/articles/200168816-Does-CloudFlare-work-with-Dynamic-DNS-Can-I-update-my-DNS-records-remotely-) only allows Dynamic IP updates via SSL connexions rendering ddclient hard to use on these devices.

Would it be possible to have these modules added to the package repository?

**Comment by ryzhovau** [comment]
Not sure it will be added quickly. PERL is abandoned in upstream, my [perl-related PR](https://github.com/openwrt/packages/pull/2383) is hanging more then half of year.

**Comment by moontear** [comment]
Still I second this. Net::SSLeay and IO::Socket::SSL are badly needed.

**Comment by immiimmi** [comment]
I would also appreciate Net::SSLeay for armv5
many thanks

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-perl-modules

**Comment by jsetton** [comment]
This issue was specifically opened for devices on which you cannot compile, since there is no gcc package available in the Entware-ng repository for mips devices such an older Asus router in my case.

**Comment by zyxmon** [comment]
@jsetton - I can upload missing packages for mips - how much ram your Asus router has?

**Comment by jsetton** [comment]
@zyxmon Thanks! I have the RT-AC66U with 256MB of RAM.

**Comment by zyxmon** [comment]
http://pkg.entware.net/binaries/other/mipsel.add/
Here are some packages you may need and packed headers (not the latest ones, but they must be OK)

**Comment by jsetton** [comment]
Thanks. I installed all these packages successfully. I can now compile but it looks like I can't get the binaries compiled dynamically. I have set the gcc environment according to the documentation with the relevant dynamic linker library. Any idea what could be the issue here?

```
# env | grep -E 'CFLAGS|LDFLAGS'
LDFLAGS=-Wl,-rpath,/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-uClibc.so.1 -L/opt/lib
CFLAGS=-O2 -pipe -fomit-frame-pointer -fno-caller-saves -I/opt/include

# ls -l /opt/lib/ld-uClibc.so.1
lrwxrwxrwx    1 admin    root            19 Dec 26 14:46 /opt/lib/ld-uClibc.so.1 -> ld-uClibc-1.0.17.so*

# make
cp lib/Net/SSLeay/Handle.pm blib/lib/Net/SSLeay/Handle.pm
cp lib/Net/SSLeay.pod blib/lib/Net/SSLeay.pod
cp lib/Net/SSLeay.pm blib/lib/Net/SSLeay.pm
AutoSplitting blib/lib/Net/SSLeay.pm (blib/lib/auto/Net/SSLeay)
blib/lib/Net/SSLeay.pm: some names are not unique when truncated to 8 characters:
 directory blib/lib/auto/Net/SSLeay:
  do_https3.al, do_https2.al, do_https4.al, do_https.al truncate to do_https
  do_httpx3.al, do_httpx2.al, do_httpx4.al truncate to do_httpx
  get_https.al, get_https3.al, get_https4.al, get_http.al, get_http3.al, get_http4.al, get_httpx.al, get_httpx3.al, get_httpx4.al truncate to get_http
  head_https.al, head_https3.al, head_https4.al, head_http.al, head_http3.al, head_http4.al, head_httpx.al, head_httpx3.al, head_httpx4.al truncate to head_htt
  post_https.al, post_https3.al, post_https4.al, post_http.al, post_http3.al, post_http4.al, post_httpx.al, post_httpx3.al, post_httpx4.al truncate to post_htt
  put_https.al, put_https3.al, put_https4.al, put_http.al, put_http3.al, put_http4.al, put_httpx.al, put_httpx3.al, put_httpx4.al truncate to put_http
  ssl_read_all.al, ssl_read_until.al, ssl_read_CRLF.al truncate to ssl_read
  ssl_write_all.al, ssl_write_CRLF.al truncate to ssl_writ
  tcp_read_all.al, tcp_read_until.al, tcp_read_CRLF.al truncate to tcp_read
  tcp_write_all.al, tcp_write_CRLF.al truncate to tcp_writ
Running Mkbootstrap for Net::SSLeay ()
chmod 644 "SSLeay.bs"
"/tmp/mnt/usb/entware-ng/bin/perl5.22.1" "-Iinc" "/opt/lib/perl5/5.22/ExtUtils/xsubpp"  -typemap "/opt/lib/perl5/5.22/ExtUtils/typemap" -typemap "typemap"  SSLeay.xs > SSLeay.xsc && mv SSLeay.xsc SSLeay.c
mipsel-openwrt-linux-uclibc-gcc -c   -D_REENTRANT -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -I/home/ryzhovau/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/opt/include -I/home/ryzhovau/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/include -I/home/ryzhovau/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/usr/include -I/home/ryzhovau/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/include -O2   -DVERSION=\"1.78\" -DXS_VERSION=\"1.78\" -fPIC "-I/opt/lib/perl5/5.22/CORE"   SSLeay.c
rm -f blib/arch/auto/Net/SSLeay/SSLeay.so
LD_RUN_PATH="/usr/lib" mipsel-openwrt-linux-uclibc-gcc  -shared -rdynamic -L/usr -L/usr/lib -L/home/ryzhovau/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/opt/lib -L/home/ryzhovau/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link=/home/ryzhovau/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-uClibc.so.0 -L/home/ryzhovau/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/usr/lib -L/home/ryzhovau/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/lib SSLeay.o  -o blib/arch/auto/Net/SSLeay/SSLeay.so         \
   -L/usr -L/usr/lib -lssl -lcrypto -lz         \

chmod 755 blib/arch/auto/Net/SSLeay/SSLeay.so
"/tmp/mnt/usb/entware-ng/bin/perl5.22.1" "-Iinc" -MExtUtils::Command::MM -e 'cp_nonempty' -- SSLeay.bs blib/arch/auto/Net/SSLeay/SSLeay.bs 644

# ldd blib/arch/auto/Net/SSLeay/SSLeay.so
checking sub-depends for '/opt/lib/libssl.so.1.0.0'
checking sub-depends for '/opt/lib/libcrypto.so.1.0.0'
checking sub-depends for '/opt/lib/libz.so.1'
checking sub-depends for '/opt/lib/libc.so.0'
checking sub-depends for '/opt/lib/libdl.so.0'
checking sub-depends for '/opt/lib/libc.so.1'
checking sub-depends for '/opt/lib/libgcc_s.so.1'
        libssl.so.1.0.0 => /opt/lib/libssl.so.1.0.0 (0x00000000)
        libcrypto.so.1.0.0 => /opt/lib/libcrypto.so.1.0.0 (0x00000000)
        libz.so.1 => /opt/lib/libz.so.1 (0x00000000)
        libc.so.0 => /opt/lib/libc.so.0 (0x00000000)
        libdl.so.0 => /opt/lib/libdl.so.0 (0x00000000)
        libc.so.1 => /opt/lib/libc.so.1 (0x00000000)
        libgcc_s.so.1 => /opt/lib/libgcc_s.so.1 (0x00000000)
        not a dynamic executable
```

**Comment by zyxmon** [comment]
>>  it looks like I can't get the binaries compiled dynamically. I have set the gcc environment according to the documentation with the relevant dynamic linker library. Any idea what could be the issue here?

No idea. You cannot link statically because many libs are missing.

**Comment by jsetton** [comment]
So it is working properly. I installed the Perl modules using CPAN. I can now use SSL with ddclient. What I saw earlier is probably an issue with the ldd tool. When I run file on the compiled library, it indicates it is dynamically linked. Thanks for your help!

```
# file /opt/lib/perl5/5.22/auto/Net/SSLeay/SSLeay.so
/opt/lib/perl5/5.22/auto/Net/SSLeay/SSLeay.so: ELF 32-bit LSB shared object, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, not stripped
```

**Comment by immiimmi** [comment]
hi zyxmon 
excellent explanation in https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-perl-modules 
i installed SSLeay with cpanm on armv5 (qnap)

i hope tomorrow I will be also successful with  Device::USB

**Comment by moontear** [comment]
I'm not able to install Net:SSLeay due to `SSLeay.xs:163:25: fatal error: openssl/err.h: No such file or directory`. According to [this](https://rt.cpan.org/Public/Bug/Display.html?id=105189) and [this](https://www.experts-exchange.com/questions/28148645/problem-installing-NET-SSLeay-from-CPAN.html) it seems to be solveable by installing openssl-dev / openssl-devel. Unfortunately this package is not available via opkg either. I do have OpenSSL installed (OpenSSL 1.0.2j-fips  26 Sep 2016).

**Comment by jsetton** [comment]
@moontear not sure on which device you are trying to compile but you could use the include.tar.gz that zyxmon provided me in the link above. This tarball includes the OpenSSL header files you are looking for. You just need to put them in /opt/include.

**Comment by moontear** [comment]
Sounds good! Unfortunately not ARM, but Intel Atom processor.

**Comment by jsetton** [comment]
For your processor, you can download it from one of the below links:
32bit => http://pkg.entware.net/binaries/x86-32/include/include.tar.gz
64bit => http://pkg.entware.net/binaries/x86-64/include/include.tar.gz

**Comment by qbox4u** [comment]
You tried the following?

add CPAN modules

[~] # perl -MCPAN -e '$ENV{FTP_PASSIVE} = 1; install GD::Text'

On 31 Dec 2016 04:07, "Dennis Gaida" <notifications@github.com> wrote:

I'm not able to install Net:SSLeay due to SSLeay.xs:163:25: fatal error:
openssl/err.h: No such file or directory. According to this
<https://rt.cpan.org/Public/Bug/Display.html?id=105189> and this
<https://www.experts-exchange.com/questions/28148645/problem-installing-NET-SSLeay-from-CPAN.html>
it seems to be solveable by installing openssl-dev / openssl-devel.
Unfortunately this package is not available via opkg either. I do have
OpenSSL installed (OpenSSL 1.0.2j-fips 26 Sep 2016).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Entware-ng/Entware-ng/issues/430#issuecomment-269816123>,
or mute the thread

**Comment by moontear** [comment]
Nice! I just used the ARM header files (and copied them to /opt/include/openssl/* and SSLeay installed - at least no errors. Later I made a diff to the x86 files and luckily they're the same anyways. So far so good, thanks!
@qbox4u I wouldn't know where to execute `add CPAN modules` as I can't do that from the interactive CPAN shell >> `Unknown shell command 'add'.`. But it works anyways with the manually copied header files. Great!

**Comment by zyxmon** [comment]
@jsetton Please - read the wiki and use apropriate headers for your feed

https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-python-modules

https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-(native-compilation)

**Comment by jsetton** [comment]
@zyxmon I am all set. I was just trying to help @moontear with his issue.

**Comment by jsetton** [comment]
@zyxmon The Perl packages have been updated to 5.24. Would you be able to update the packages you create above or maybe make them permanently available in the mipsel repository?

Unfortunately, I am no longer able to compile the Net::SSLeay package for the new version.

**Comment by zyxmon** [comment]
@jsetton - all packages and headers are synced with openwrt and are updated regularly. The last update was about a week ago.

**Comment by jsetton** [comment]
@zyxmon Unfortunately, not the packages you included in http://pkg.entware.net/binaries/other/mipsel.add/

**Comment by ryzhovau** [comment]
MIPSEL native compilation tools not supported, sorry.

**Comment by jsetton** [comment]
Understood, so what can I do to get the Net::SSLeay and IO::Socket::SSL packages installed on my Asus router? Is there is a way to rollback the Perl packages to a previous version and prevent them from being updated in the future?

**Comment by ryzhovau** [comment]
> Understood, so what can I do to get the Net::SSLeay and IO::Socket::SSL packages installed on my Asus router?

You can try to [make it](https://github.com/Entware-ng/Entware-ng/wiki/How-to-add-a-new-package) for you own needs.

> Is there is a way to rollback the Perl packages to a previous version and prevent them from being updated in the future?

```
$ opkg hold <package name>
```

**Comment by jsetton** [comment]
> You can try to [make it](https://github.com/Entware-ng/Entware-ng/wiki/How-to-add-a-new-package) for you own needs.

It seems to me a lot of work to just get two essentials Perl packages available in the repository.

> `$ opkg flag hold <package name>`

So this will prevent the package from being updated but how can I rollback the Perl packages? It seems that if I try to install the archived version directly it still installs the latest version.

```
$ opkg install http://pkg.entware.net/binaries/mipsel/archive/perl_5.22.1-4_mipselsf.ipk
Downloading http://pkg.entware.net/binaries/mipsel/archive/perl_5.22.1-4_mipselsf.ipk.
Installing perl (5.24.1-1) to root...
Downloading http://pkg.entware.net/binaries/mipsel/perl_5.24.1-1_mipselsf.ipk.
Configuring perl.
```

**Comment by ryzhovau** [comment]
> So this will prevent the package from being updated but how can I rollback the Perl packages? It seems that if I try to install the archived version directly it still installs the latest version.

You have to download it first:
```
$ wget http://pkg.entware.net/binaries/mipsel/archive/perl_5.22.1-4_mipselsf.ipk
opkg install ./perl_5.22.1-4_mipselsf.ipk
```
