### ISSUE TITLE
Package request: GNU Zile

### ISSUE THREAD

**Issue by gavinhungry** [Entware-ng/Entware-ng#431]
https://www.gnu.org/software/zile/

> GNU Zile is a text editor development kit, so that you can (relatively) quickly develop your own ideal text editor without reinventing the wheel for many of the common algorithms and data-structures needed to do so.

I don't know if `zile` faces the same cross-compilation challenges as `emacs`, see #229.

**Comment by gavinhungry** [comment]
I see zile here:
https://github.com/Entware-ng/entware-packages/tree/master/utils/zile

But not here:
http://pkg.entware.net/binaries/x86-64/

**Comment by ryzhovau** [comment]
Why we should add another text editor? What's the killer feature of that one?

**Comment by gavinhungry** [comment]
@ryzhovau,

Without rehashing the Editor Wars, Zile provides (among other things) a lightweight Emacs clone that is better suited to an embedded environment, and as such may well satiate the needs of Emacs users using entware (as it does for me).

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/entware-packages/commit/bba801ddefd178ccba137819fe694dbdb28c4672

zile is now in the intel&arm binary repos
