### ISSUE TITLE
Package request: libavahi-compat-libdnssd-dev

### ISSUE THREAD

**Issue by BerlinSnoop** [Entware-ng/Entware-ng#432]
Hi,
this package is needed to install homebridge with node. Other people are using a Debian chroot but I don't like to install another distro/package manager. (Manual tries with the Debian source itself brings me linking errors).
By the way: Many compiling stuff is now working with your actual gcc package on my DS215j. 
Many thanks for that!

**Comment by ryzhovau** [comment]
*-dev packages are not provided here, sorry. This is by design.
