### ISSUE TITLE
python-pip3 - Bad Interpreter on fresh install

### ISSUE THREAD

**Issue by jheyneman** [Entware-ng/Entware-ng#433]
On my QNAP TS-563, I am trying to install acd_cli. 

Fresh installation of Entware-ng, installed python3-pip using opkg.  When attempting to use pip3, I get a bad interpreter error. This worked when I first set it up last week, but after a botched firmware update, I had to set up my QNAP again. My only guess is that I was running an older version of pip3 before, unless I did something differently this time. Running 'which python3' returns '/opt/bin/python3'. Changing the header in /opt/bin/pip3 to point to the correct path, seems to fix pip3. 

```
 HOME=/share/Apps/python3 pip3 install acdcli
-sh: /opt/bin/pip3: /media/ware3/Entware-ng.2016.10/staging_dir/target-x86_64_glibc-2.23/host/bin/: bad interpreter: No such file or directory
```

**Comment by zyxmon** [comment]
Thanks for reporting - this bug was in the previous version. Will be fixed soon.

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/entware-packages/commit/e39cbfe955c2702f3c7814337f491550f0b00e90
