### ISSUE TITLE
Package has no valid architecture, ignoring.

### ISSUE THREAD

**Issue by fanthos** [Entware-ng/Entware-ng#434]
I am using OpenWrt on x64 KVM machine. After I added Entware to my OpenWrt opkg, I got "Package has no valid architecture, ignoring." after time when I trying to install new package. After a dig, I found that Openwrt has "x86_64" in "Architecture" line, but Entware has "x86-64".

**Comment by zyxmon** [comment]
This is not a good idea to use both openwrt & entware packages.
I suggest you to use different opkg binaries with different opkg.conf files.
run `/opt/bin/opkg ...` for entware packages and `???/bin/opkg` for openwrt packages. This will work if packages are installed to different folders.
