### ISSUE TITLE
Wrong path to perl interpreter in autoconf/automake

### ISSUE THREAD

**Issue by buergi** [Entware-ng/Entware-ng#435]
The autoconf/automake packages still refers to /usr/bin/perl as perl interpreter:
```
> grep -l /usr/bin/perl /opt/bin/auto*
/opt/bin/autoheader
/opt/bin/autom4te
/opt/bin/autoreconf
/opt/bin/autoscan
/opt/bin/autoupdate
```

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/entware-packages/commit/fb33a53de4f30d4847ac6be3cc381c6db7a2729b
