### ISSUE TITLE
vim lacks vimdiff

### ISSUE THREAD

**Issue by buergi** [Entware-ng/Entware-ng#437]
Vim package lacks usefull vimdiff softlink for comparing multiple files:
`ln -s vim /opt/bin/vimdiff`

**Comment by graysky2** [comment]
Simply creating the symlink isn't sufficient.  I believe some diff utils are needed?

```
# vimdiff foo bar
E97: Cannot create diffs
```

**Comment by ryzhovau** [comment]
This package was taken from [upstream](https://github.com/openwrt/packages) without changes. Please, ask OpenWrt guys to improve it.
