### ISSUE TITLE
[Feature Request] Support for MIPS - Atheros based Routers

### ISSUE THREAD

**Issue by ian5142** [Entware-ng/Entware-ng#439]
Hello,
I was wondering if support for Atheros based routers would be possible. MIPS
Routers such as the TP-Link Archer C7 v2 or the DIR-862L.

**Comment by zyxmon** [comment]
If your kernel is 3.2 or higher - you can use Entware-3x repo:
http://entware-3x.zyxmon.org/binaries/mips/
It is compiled for mips big endian. No installers for common firwares are there. You are welcome to make one yourself and share with others.
Entware-3x fork is here - https://github.com/Entware-for-kernel-3x/Entware-ng-3x
