### ISSUE TITLE
Request for optware packages

### ISSUE THREAD

**Issue by nelek** [Entware-ng/Entware-ng#44]
I'm trying to set up a sixxs tunnel with entware-ng on Synology armv7.

Sixxs has a tutorial online to do so : https://www.sixxs.net/wiki/IPv6_on_Synology

However, the following packages are missing from entware to complete the tutorial : 

* bison
* flex
* pkgconfig

Since they were in optware, can they be added to entware-ng?

**Comment by zyxmon** [comment]
we are not going do make more developers tools for Entware-ng. It is much more easier to build package using these instructions - https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources
