### ISSUE TITLE
Kernel support

### ISSUE THREAD

**Issue by ian5142** [Entware-ng/Entware-ng#440]
Is support for K3X on dd-wrt possible? I am running a Broadcom (MIPS) router but it is running Linux 3.10.104 #14777 Tue Nov 1 16:23:58 CET 2016 mips

**Comment by zyxmon** [comment]
It is here - https://github.com/Entware-for-kernel-3x/Entware-ng-3x
Binary repositories are here - http://entware-3x.zyxmon.org/binaries/
(armv5, armv7, mips le, mips be, x64).
