### ISSUE TITLE
Update snmpd to 5.7.3 (LTS)

### ISSUE THREAD

**Issue by nixikanius** [Entware-ng/Entware-ng#442]
Now in Entware repo there is snmpd version 4.4.4. This is previous LTS version which have one unpleasant bug (https://dev.openwrt.org/ticket/14052) under which snmpd floods log with errors about missing lines in /proc/vmstat output. It is essential when log dir placed on flash drives - the only one (very dirty) way to supress it is to turn off all logging.

In 5.7.3 (current LTS version) this bug fixed so it would be good to update version in repo.

**Comment by zyxmon** [comment]
This bug was reported 3 years ago. The snmpd version is different now. We sync versions with openwrt - the current one is 5.4.4. We will update this version after openwrt updates it.

**Comment by nixikanius** [comment]
Sorry my mistake - Entware snmpd version now is 5.4.4, you are right. It's a pity that openwrt in no hurry to update version.

**Comment by ryzhovau** [comment]
Please, send this issue to [upstream](https://github.com/openwrt/packages/issues) and update will arrive here in next month.
