### ISSUE TITLE
https Support Documentation and/or Default Use

### ISSUE THREAD

**Issue by mentalisttraceur** [Entware-ng/Entware-ng#444]
It seems that the entirety of Entware defaults to the unsecured "http" for everything. Consequently, our routers and other devices which use Entware, which are often in sensitive/privileged positions in our networks (firewall against the outside, in position to perform MitM attacks on all traffic going through them, etc), are basically one compromised download away from being pwned by an external, malicious party.

This means that if an attacker merely manages to compromise _one_ download from Entware, ever, it's game over for the effected device(s). I realize a lot of our devices do not support https out of the box. I think that https support should definitely be documented (it does seem the install script can be copied over https, at least), that a secure download->setup->use path using the https support should preferably be documented, and that a default install which sets up for using https would be ideal (check if `wget` that is installed can do https, if not, pull down one that can. Maybe try other common programs like `curl` as well, in case that's already installed).

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/Entware-ng/issues/18
