### ISSUE TITLE
netdata for armv7

### ISSUE THREAD

**Issue by Veldkornet** [Entware-ng/Entware-ng#445]
I noticed that you already have [netdata ](https://github.com/firehol/netdata/wiki) is already available [here](https://github.com/Entware-ng/entware-packages/tree/master/admin)

Which is a clone of the OpenWRT version [here](https://github.com/openwrt/packages/tree/master/admin/netdata)

But I don't see the package listed for [armv7](http://pkg.entware.net/binaries/armv7/Packages.html)

Would it be possible to add netdata for armv7 as well? I want to install it on Asuswrt-merlin on the RT-AC87U.

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/entware-packages/commit/673d5dce4687b52a40d249f6541e2580713a33fb

netdata is tested and added (arm & intel feeds) - works fine on embedded devices with special settings:
https://github.com/firehol/netdata/wiki/Memory-Requirements#running-netdata-in-embedded-devices
