### ISSUE TITLE
Package request: ocaml

### ISSUE THREAD

**Issue by gitze** [Entware-ng/Entware-ng#446]
I'm using Unison (File Synchronizer) on a Synology system. To compile it "ocaml"  is needed 
ocaml: https://ocaml.org/docs/install.html
unison: http://www.cis.upenn.edu/~bcpierce/unison/

Thank you

**Comment by zyxmon** [comment]
I have succefully built ocaml (4.03.00) natively using gcc some time ago, The only tricky is a configure params. I have used

```
./configure -prefix /opt \
-cc "gcc -O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -msoft-float \
-Wl,-rpath=/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-uClibc.so.0 -L/opt/lib" \
-no-pthread -no-shared-libs -no-debugger -no-ocamldoc -no-graph -no-cfi
```

These are params for mipsel. Take your params from /opt/bin/gcc_env.sh script. Please read https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-(native-compilation)

**Comment by ryzhovau** [comment]
No response.

**Comment by dugwood** [comment]
For those who need the full install (tested on Synology):
First install:
```
opkg install gcc make
```

Then download from https://ocaml.org/releases/
For example:
```
cd /tmp/
wget http://caml.inria.fr/pub/distrib/ocaml-4.05/ocaml-4.05.0.tar.gz
```

Then:
```
tar -xvzf ocaml-4.05.0.tar.gz
cd ocaml-4.05.0
./configure -prefix /opt
make world.opt
make install
```
