### ISSUE TITLE
Request w3m browser 

### ISSUE THREAD

**Issue by ilje** [Entware-ng/Entware-ng#447]
hi please add w3m for armv7
```
http://w3m.sourceforge.net/
https://sourceforge.net/projects/w3m/files/
```

**Comment by zyxmon** [comment]
Repositiry has elinks and lynx text browsers. Is w3m somehow better or has some features missing in elinks/lynx?

**Comment by ilje** [comment]
hi i know for lynx and elinks but i need w3m if you can

**Comment by ryzhovau** [comment]
We still see no reason to add 3rd browser here, if `w3m` has no any killer feature(s).
