### ISSUE TITLE
make tools/go-bin/install issue

### ISSUE THREAD

**Issue by giveup** [Entware-ng/Entware-ng#449]
Here has some log.
`make[2]: Leaving directory `/Volumes/Entware-dev/Entware-ng/tools/tar'
make[2]: Entering directory `/Volumes/Entware-dev/Entware-ng/tools/go-bin'
. /Volumes/Entware-dev/Entware-ng/include/shell.sh; gzip -dc /Volumes/Entware-dev/Entware-ng/dl/go1.4.2.linux-amd64.tar.gz | trapret 2 tar -C /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/.. -xf - 
touch /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/.prepareddb6e3a01347d79bcf051a753855a4445
(cd /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/; if [ -x configure ]; then cp -fpR /Volumes/Entware-dev/Entware-ng/scripts/config.{guess,sub} /Volumes/Entware-dev/Entware-ng/staging_dir/host/go// &&  bash ./configure CC="gcc" CFLAGS="-O2 -I/Volumes/Entware-dev/Entware-ng/staging_dir/host/include -I/Volumes/Entware-dev/Entware-ng/staging_dir/host/usr/include  -I/usr/local/opt/openssl/include" CPPFLAGS="-I/Volumes/Entware-dev/Entware-ng/staging_dir/host/include -I/Volumes/Entware-dev/Entware-ng/staging_dir/host/usr/include " LDFLAGS="-L/Volumes/Entware-dev/Entware-ng/staging_dir/host/lib -L/Volumes/Entware-dev/Entware-ng/staging_dir/host/usr/lib  -L/usr/local/opt/openssl/lib" SHELL="/usr/bin/env bash" --target=x86_64-apple-darwin16.1.0 --host=x86_64-apple-darwin16.1.0 --build=x86_64-apple-darwin16.1.0 --program-prefix="" --program-suffix="" --prefix=/Volumes/Entware-dev/Entware-ng/staging_dir/host --exec-prefix=/Volumes/Entware-dev/Entware-ng/staging_dir/host --sysconfdir=/Volumes/Entware-dev/Entware-ng/staging_dir/host/etc --localstatedir=/Volumes/Entware-dev/Entware-ng/staging_dir/host/var --sbindir=/Volumes/Entware-dev/Entware-ng/staging_dir/host/bin ; fi )
touch /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/.configured`

`cmd/6c
/Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/6c/txt.c:995:28: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
/Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/6c/txt.c:1045:28: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
go tool dist: FAILED: clang -Wall -Wstrict-prototypes -Wextra -Wunused -Wno-sign-compare -Wno-missing-braces -Wno-parentheses -Wno-unknown-pragmas -Wno-switch -Wno-comment -Wno-missing-field-initializers -Werror -fno-common -ggdb -pipe -Wuninitialized -O2 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -mmacosx-version-min=10.6 -c -m64 -I /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/include -I /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/6c -o /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/pkg/obj/cmd/6c/txt.o /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/6c/txt.c
make[2]: *** [/Volumes/Entware-dev/Entware-ng/staging_dir/host/go/.built] Error 1
make[2]: Leaving directory `/Volumes/Entware-dev/Entware-ng/tools/go-bin'
make[1]: *** [tools/go-bin/compile] Error 2
make[1]: Leaving directory `/Volumes/Entware-dev/Entware-ng'
make: *** [tools/go-bin/install] Error 2`

**Comment by zyxmon** [comment]
There in no issue on debian jessie. Recent *buntu releases do have it. Just disable go in tools (manually )and in toolchain if you have an issue with go.

**Comment by giveup** [comment]
Just edit go-bin makefile 1.4.2 to 1.4.3
and set
` GOOS=arwin  GOARCH=amd64 GOROOT=$(STAGING_DIR_HOST)/go CGO_ENABLED=0 ./make.bash --no-clean ; \ `

` GOOS=linux GOARCH=arm GOARM=7 GOROOT=$(STAGING_DIR_HOST)/go CGO_ENABLED=0 ./make.bash --no-clean ; \ `
