### ISSUE TITLE
radvd

### ISSUE THREAD

**Issue by nelek** [Entware-ng/Entware-ng#45]
aiccu, wich is included in the entware repository, is useless without radvd. 

Would it be possible to make a package for radvd for armv7 so we can use aiccu?

**Comment by zyxmon** [comment]
@nelek please test - http://pkg.entware.net/binaries/armv7/test/radvd_2.11-1_armv7soft.ipk
and provide feedback

**Comment by nelek** [comment]
@zyxmon the package installs and the binary runs, so it seems to work. I will test it in a live setup shortly to see if the radvd itself is also functional.

**Comment by ryzhovau** [comment]
No response.

**Comment by nelek** [comment]
I couldn't do a functionality test as the aiccu package in entware doesn't seem to work.
