### ISSUE TITLE
Using Let's Encrypt !! letsencrypt.sh has been renamed to dehydrated !!

### ISSUE THREAD

**Issue by Jamyz** [Entware-ng/Entware-ng#450]
Hi !! When i try 
`bash ./letsencrypt.sh --domain my.domain.ru --cron`

I Have,

`
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! letsencrypt.sh has been renamed to dehydrated !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Due to trademark violation letsencrypt.sh had to be renamed and is know called dehydrated.

To make a clean cut dehydrated doesn't use the old config locations /etc/letsencrypt.sh and
/usr/local/etc/letsencrypt.sh anymore, also the script file has been renamed.

If you were using the default WELLKNOWN location please also update your webserver to use /var/www/dehydrated.

You are currently running (or reading) a temporary wrapper which handles the old config locations,
you should update your setup to use /etc/dehydrated and the 'dehydrated' script file as soon as possible.

Script execution will continue in 10 seconds.
`

How i can solve this ?????

**Comment by ryzhovau** [comment]
> How i can solve this ?????

You've got write access to wiki pages, so you can fix that without our help.
