### ISSUE TITLE
lrzsz package needed: x/y/zmodem protocols doesn't work in minicom

### ISSUE THREAD

**Issue by starter48** [Entware-ng/Entware-ng#451]
I've tried to use **minicom** terminal to transfer a file via xmodem, but failed since minicom utilizes external file transfer protocol, that doesn't exists in minicom.ipk
So I ask to add a package with these protocols:
I've checked **Ubuntu** repo and found these protocols stored in **lrzsz** package.

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/entware-packages/commit/7ab62532cc50c5afc30bd37d3125518659499767
Binaries will arrive soon
