### ISSUE TITLE
Request for more documentation on how to add a new package, is OpenWrt required to be installed?

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-ng/Entware-ng#452]
When I read https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources I miss some hints that give me the big picture.

To create a new entware-ng package it is clear that the OpenWrt buildroot environment is needed.

Will that be OpenWrt buildroot stuff be installed automatically when running 'make package/symlinks' command in the /Entware-ng/ folder ?

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources#you-can-run-make-in-several-steps

You need to run 3 steps before you can build any package.

**Comment by ProBackup-nl** [comment]
Instead of giving examples with "squid" and "tmux", is there a small "hello world" type of package (without dependencies) to quickly test the entware-ng buildroot setup?

**Comment by ProBackup-nl** [comment]
I ended up using the build-in (not Entware-ng-packages) "`usbreset`" package to test:
```
$ make package/usbreset/install
$ ls -la bin/mipselsf-uClibc/packages | grep usbreset
```

**Comment by zyxmon** [comment]
We use only `make package/xxxxx/compile` (or clean, prepare, configure) in Entware.
