### ISSUE TITLE
Compile from source: "make -r world" fails at uClibc extra/locale locale_headers, how to fix or disable its locale support?

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-ng/Entware-ng#453]
My first trying to build an Entware-ng package from source stops with an error at "make -r world", see below for the verbose output.

My guess is that the issue has got to do with locale support in uClibc.

Strange is that OpenWrt "chaos-calmer" builds compiles without errors:
...
 make[3] -C toolchain/kernel-headers install
 make[3] -C toolchain/uClibc/headers compile
 make[3] -C toolchain/uClibc/headers install
 make[3] -C toolchain/gcc/initial compile
...

How to fix this issue or disable uClibc locale support?

Note: I don't need locale support on an embedded device

---
$ make -r world -j1 V=s
make[1]: Entering directory `/Volumes/Entware-ng/Entware-ng'
make[2]: Entering directory `/Volumes/Entware-ng/Entware-ng'
+ mkdir -p /Volumes/Entware-ng/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16
+ cd /Volumes/Entware-ng/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16
+ mkdir -p bin lib include stamp
mkdir -p /Volumes/Entware-ng/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/stamp
touch /Volumes/Entware-ng/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/.prepared
make[3]: Entering directory `/Volumes/Entware-ng/Entware-ng/toolchain/binutils'
make[3]: Nothing to be done for `prepare'.
make[3]: Leaving directory `/Volumes/Entware-ng/Entware-ng/toolchain/binutils'
make[3]: Entering directory `/Volumes/Entware-ng/Entware-ng/toolchain/binutils'
make[3]: Nothing to be done for `compile'.
make[3]: Leaving directory `/Volumes/Entware-ng/Entware-ng/toolchain/binutils'
make[3]: Entering directory `/Volumes/Entware-ng/Entware-ng/toolchain/binutils'
make[3]: Nothing to be done for `install'.
make[3]: Leaving directory `/Volumes/Entware-ng/Entware-ng/toolchain/binutils'
make[3]: Entering directory `/Volumes/Entware-ng/Entware-ng/toolchain/gcc/minimal'
make[3]: Nothing to be done for `prepare'.
make[3]: Leaving directory `/Volumes/Entware-ng/Entware-ng/toolchain/gcc/minimal'
make[3]: Entering directory `/Volumes/Entware-ng/Entware-ng/toolchain/gcc/minimal'
make[3]: Nothing to be done for `compile'.
make[3]: Leaving directory `/Volumes/Entware-ng/Entware-ng/toolchain/gcc/minimal'
make[3]: Entering directory `/Volumes/Entware-ng/Entware-ng/toolchain/gcc/minimal'
make[3]: Nothing to be done for `install'.
make[3]: Leaving directory `/Volumes/Entware-ng/Entware-ng/toolchain/gcc/minimal'
make[3]: Entering directory `/Volumes/Entware-ng/Entware-ng/toolchain/kernel-headers'
make[3]: Nothing to be done for `prepare'.
make[3]: Leaving directory `/Volumes/Entware-ng/Entware-ng/toolchain/kernel-headers'
make[3]: Entering directory `/Volumes/Entware-ng/Entware-ng/toolchain/kernel-headers'
make[3]: Nothing to be done for `compile'.
make[3]: Leaving directory `/Volumes/Entware-ng/Entware-ng/toolchain/kernel-headers'
make[3]: Entering directory `/Volumes/Entware-ng/Entware-ng/toolchain/kernel-headers'
make[3]: Nothing to be done for `install'.
make[3]: Leaving directory `/Volumes/Entware-ng/Entware-ng/toolchain/kernel-headers'
make[3]: Entering directory `/Volumes/Entware-ng/Entware-ng/toolchain/uClibc/headers'
make[3]: Nothing to be done for `prepare'.
make[3]: Leaving directory `/Volumes/Entware-ng/Entware-ng/toolchain/uClibc/headers'
make[3]: Entering directory `/Volumes/Entware-ng/Entware-ng/toolchain/uClibc/headers'
make[3]: Nothing to be done for `compile'.
make[3]: Leaving directory `/Volumes/Entware-ng/Entware-ng/toolchain/uClibc/headers'
make[3]: Entering directory `/Volumes/Entware-ng/Entware-ng/toolchain/uClibc/headers'
PATH='/Volumes/Entware-ng/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/bin:/Volumes/Entware-ng/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/bin:/Volumes/Entware-ng/Entware-ng/staging_dir/host/bin:/Volumes/Entware-ng/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/bin:/Volumes/Entware-ng/Entware-ng/staging_dir/host/bin:/Volumes/Entware-ng/Entware-ng/staging_dir/host/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin' /Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Volumes/Entware-ng/Entware-ng/build_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/uClibc-ng-1.0.16 PREFIX="/Volumes/Entware-ng/Entware-ng/build_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/uClibc-dev/" DEVEL_PREFIX=/ RUNTIME_PREFIX="/Volumes/Entware-ng/Entware-ng/build_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/uClibc-dev/" HOSTCC="gcc" CC="mipsel-openwrt-linux-uclibc-gcc" CPU_CFLAGS="-O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float" ARCH=""mipsel"" pregen install_headers
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C extra/locale locale_headers
gcc ../../extra/locale/gen_locale.c  -o ../..//extra/locale/gen_locale    -Os  -D_GNU_SOURCE -I../..//extra/locale
../../extra/locale/gen_locale.c:204:6: warning: format
      specifies type 'int' but the argument has type
      'long' [-Wformat]
  ...i + (at_strings_end - at_strings));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../extra/locale/gen_locale.c:206:6: warning: format
      specifies type 'int' but the argument has type
      'long' [-Wformat]
  ...i + (at_strings_end - at_strings));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../extra/locale/gen_locale.c:238:6: warning: format
      specifies type 'int' but the argument has type
      'unsigned long' [-Wformat]
  ...pos[__LOCALE_DATA_CATEGORIES-1] + strlen(lc_names[__LOCALE_DATA_CATEGORIES-1]) + 1);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../extra/locale/gen_locale.c:242:6: warning: format
      specifies type 'int' but the argument has type
      'unsigned long' [-Wformat]
  ...pos[__LOCALE_DATA_CATEGORIES-1] + strlen(lc_names[__LOCALE_DATA_CATEGORIES-1]) + 1);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../extra/locale/gen_locale.c:350:62: warning: adding
      'int' to a string does not append to the string
      [-Wstring-plus-int]
  ...are %sabled\n", "dis\0en"+ (default_utf8 << 2));
                     ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
../../extra/locale/gen_locale.c:350:62: note: use array
      indexing to silence this warning
  ...are %sabled\n", "dis\0en"+ (default_utf8 << 2));
                              ^
                     &        [                    ]
../../extra/locale/gen_locale.c:357:63: warning: adding
      'int' to a string does not append to the string
      [-Wstring-plus-int]
  ...are %sabled\n", "dis\0en" + (default_8bit << 2));
                     ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
../../extra/locale/gen_locale.c:357:63: note: use array
      indexing to silence this warning
  ...are %sabled\n", "dis\0en" + (default_8bit << 2));
                               ^
                     &         [                    ]
../../extra/locale/gen_locale.c:382:49: warning: adding
      'unsigned char' to a string does not append to the
      string [-Wstring-plus-int]
  ...__LOCALE_DATA_CODESET_LIST+ ((unsigned char) *s)...
     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
../../extra/locale/gen_locale.c:382:49: note: use array
      indexing to silence this warning
  ...__LOCALE_DATA_CODESET_LIST+ ((unsigned char) *s),...
                               ^
     &                         [                     ]
../../extra/locale/gen_locale.c:954:11: error: use of
      undeclared identifier 'ERA_YEAR'
                DO_NL_S(ERA_YEAR);              /...
                        ^
../../extra/locale/gen_locale.c:827:30: note: expanded
      from macro 'DO_NL_S'
#define DO_NL_S(X)      lc_time_S(X, k++)
                                  ^
../../extra/locale/gen_locale.c:986:11: error: use of
      undeclared identifier 'GROUPING'
        if (X == GROUPING) {
                 ^
../../extra/locale/gen_locale.c:1056:11: error: use of
      undeclared identifier 'GROUPING'
                DO_NL_S(GROUPING);
                        ^
../../extra/locale/gen_locale.c:975:33: note: expanded
      from macro 'DO_NL_S'
#define DO_NL_S(X)      lc_numeric_S(X, k++)
                                     ^
../../extra/locale/gen_locale.c:1083:2: warning: fix the
      char entries for monetary... target signedness of
      char may be different! [-W#warnings]
#warning fix the char entries for monetary... tar...
 ^
../../extra/locale/gen_locale.c:1114:11: error: use of
      undeclared identifier 'MON_GROUPING'
        if (X == MON_GROUPING) {
                 ^
../../extra/locale/gen_locale.c:1184:11: error: use of
      undeclared identifier 'INT_CURR_SYMBOL'
                DO_NL_S(INT_CURR_SYMBOL);
                        ^
../../extra/locale/gen_locale.c:1073:34: note: expanded
      from macro 'DO_NL_S'
#define DO_NL_S(X)      lc_monetary_S(X, k++)
                                      ^
../../extra/locale/gen_locale.c:1185:11: error: use of
      undeclared identifier 'CURRENCY_SYMBOL'
                DO_NL_S(CURRENCY_SYMBOL);
                        ^
../../extra/locale/gen_locale.c:1073:34: note: expanded
      from macro 'DO_NL_S'
#define DO_NL_S(X)      lc_monetary_S(X, k++)
                                      ^
../../extra/locale/gen_locale.c:1186:11: error: use of
      undeclared identifier 'MON_DECIMAL_POINT'
                DO_NL_S(MON_DECIMAL_POINT);
                        ^
../../extra/locale/gen_locale.c:1073:34: note: expanded
      from macro 'DO_NL_S'
#define DO_NL_S(X)      lc_monetary_S(X, k++)
                                      ^
../../extra/locale/gen_locale.c:1187:11: error: use of
      undeclared identifier 'MON_THOUSANDS_SEP'
                DO_NL_S(MON_THOUSANDS_SEP);
                        ^
../../extra/locale/gen_locale.c:1073:34: note: expanded
      from macro 'DO_NL_S'
#define DO_NL_S(X)      lc_monetary_S(X, k++)
                                      ^
../../extra/locale/gen_locale.c:1188:11: error: use of
      undeclared identifier 'MON_GROUPING'
                DO_NL_S(MON_GROUPING);
                        ^
../../extra/locale/gen_locale.c:1073:34: note: expanded
      from macro 'DO_NL_S'
#define DO_NL_S(X)      lc_monetary_S(X, k++)
                                      ^
../../extra/locale/gen_locale.c:1189:11: error: use of
      undeclared identifier 'POSITIVE_SIGN'
                DO_NL_S(POSITIVE_SIGN);
                        ^
../../extra/locale/gen_locale.c:1073:34: note: expanded
      from macro 'DO_NL_S'
#define DO_NL_S(X)      lc_monetary_S(X, k++)
                                      ^
../../extra/locale/gen_locale.c:1190:11: error: use of
      undeclared identifier 'NEGATIVE_SIGN'
                DO_NL_S(NEGATIVE_SIGN);
                        ^
../../extra/locale/gen_locale.c:1073:34: note: expanded
      from macro 'DO_NL_S'
#define DO_NL_S(X)      lc_monetary_S(X, k++)
                                      ^
../../extra/locale/gen_locale.c:1191:11: error: use of
      undeclared identifier 'INT_FRAC_DIGITS'
                DO_NL_C(INT_FRAC_DIGITS);
                        ^
../../extra/locale/gen_locale.c:1076:34: note: expanded
      from macro 'DO_NL_C'
#define DO_NL_C(X) lc_monetary_C(X, k++)
                                 ^
../../extra/locale/gen_locale.c:1192:11: error: use of
      undeclared identifier 'FRAC_DIGITS'
                DO_NL_C(FRAC_DIGITS);
                        ^
../../extra/locale/gen_locale.c:1076:34: note: expanded
      from macro 'DO_NL_C'
#define DO_NL_C(X) lc_monetary_C(X, k++)
                                 ^
../../extra/locale/gen_locale.c:1193:11: error: use of
      undeclared identifier 'P_CS_PRECEDES'
                DO_NL_C(P_CS_PRECEDES);
                        ^
../../extra/locale/gen_locale.c:1076:34: note: expanded
      from macro 'DO_NL_C'
#define DO_NL_C(X) lc_monetary_C(X, k++)
                                 ^
../../extra/locale/gen_locale.c:1194:11: error: use of
      undeclared identifier 'P_SEP_BY_SPACE'
                DO_NL_C(P_SEP_BY_SPACE);
                        ^
../../extra/locale/gen_locale.c:1076:34: note: expanded
      from macro 'DO_NL_C'
#define DO_NL_C(X) lc_monetary_C(X, k++)
                                 ^
../../extra/locale/gen_locale.c:1195:11: error: use of
      undeclared identifier 'N_CS_PRECEDES'
                DO_NL_C(N_CS_PRECEDES);
                        ^
../../extra/locale/gen_locale.c:1076:34: note: expanded
      from macro 'DO_NL_C'
#define DO_NL_C(X) lc_monetary_C(X, k++)
                                 ^
../../extra/locale/gen_locale.c:1196:11: error: use of
      undeclared identifier 'N_SEP_BY_SPACE'
                DO_NL_C(N_SEP_BY_SPACE);
                        ^
../../extra/locale/gen_locale.c:1076:34: note: expanded
      from macro 'DO_NL_C'
#define DO_NL_C(X) lc_monetary_C(X, k++)
                                 ^
../../extra/locale/gen_locale.c:1197:11: error: use of
      undeclared identifier 'P_SIGN_POSN'
                DO_NL_C(P_SIGN_POSN);
                        ^
../../extra/locale/gen_locale.c:1076:34: note: expanded
      from macro 'DO_NL_C'
#define DO_NL_C(X) lc_monetary_C(X, k++)
                                 ^
../../extra/locale/gen_locale.c:1198:11: error: use of
      undeclared identifier 'N_SIGN_POSN'
                DO_NL_C(N_SIGN_POSN);
                        ^
../../extra/locale/gen_locale.c:1076:34: note: expanded
      from macro 'DO_NL_C'
#define DO_NL_C(X) lc_monetary_C(X, k++)
                                 ^
fatal error: too many errors emitted, stopping now
      [-ferror-limit=]
8 warnings and 20 errors generated.
make[5]: *** [../..//extra/locale/gen_locale] Error 1
make[4]: *** [headers] Error 2
make[3]: *** [/Volumes/Entware-ng/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/stamp/.uclibc_headers_installed] Error 2
make[3]: Leaving directory `/Volumes/Entware-ng/Entware-ng/toolchain/uClibc/headers'
make[2]: *** [toolchain/uClibc/headers/install] Error 2

**Comment by zyxmon** [comment]
There is no `make -r world` command in the wiki.
If you strictly follow the wiki and have errors - switch to debian jessie x64.

**Comment by ProBackup-nl** [comment]
When I run plain `make`, it also stops with an identical error message.

The issue is in the toolchain part that builds the uclibc headers. There it looks at the system paths for langinfo.h, resulting in inclusion the OS X included FreeBSD version at `/usr/include/langinfo.h` instead of `./build_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/uClibc-ng-1.0.16/include/langinfo.h`.

I do wish to make an override and add an additional include location to the `Make` section of Entware-ng/toolchain/uClibc/headers near `-I../..//extra/locale`, like `-I../../include`.

Can you give me another welcome hint where to make the edit(s) to add an additional include location for toolchain uClibc headers?

**Comment by zyxmon** [comment]
>> Can you give me another welcome hint where to make the edit(s) to add an additional include location for toolchain uClibc headers?

You can try to contact Uclibc-ng maintainer on this question.

**Comment by ProBackup-nl** [comment]
Ok, disabling NLS in .config will do for now.

Next error, again an include that cannot be found, is at "make[3] -C package/devel/strace compile":

```
In file included from ./ioctlsort.c:36:
/Volumes/Case-sensitive/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/linux-mipselsf/linux-2.6.22.19/include/linux/ioctl.h:4:10: fatal error:
      'asm/ioctl.h' file not found
#include <asm/ioctl.h>
```
The asm/ioctl.h files are located at:

```
$ find . | grep asm/ioctl.h
./build_dir/host/linux-2.6.22.19/user_headers/include/asm/ioctl.h
./build_dir/host/u-boot-2014.10/arch/x86/include/asm/ioctl.h
./build_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/linux-dev/include/asm/ioctl.h
./build_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/uClibc-dev/include/asm/ioctl.h
./staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/include/asm/ioctl.h
```
Which doesn't seem to be included in this `gcc` step:
```
make[3]: Entering directory `/Volumes/Case-sensitive/Entware-ng/package/devel/strace'
CFLAGS="-O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float  -I/Volumes/Case-sensitive/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/linux-mipselsf/linux-2.6.22.19/include  -I/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/opt/include -I/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/include -I/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/usr/include -I/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/include " CXXFLAGS="-O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float  -I/Volumes/Case-sensitive/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/linux-mipselsf/linux-2.6.22.19/include  -I/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/opt/include -I/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/include -I/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/usr/include -I/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/include " LDFLAGS="-L/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/opt/lib -L/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link=/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-uClibc.so.0 -L/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/usr/lib -L/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/lib " /Applications/Xcode.app/Contents/Developer/usr/bin/make -j1 -C /Volumes/Case-sensitive/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/linux-mipselsf/strace-4.13/. CCOPT="-O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float  -I/Volumes/Case-sensitive/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/linux-mipselsf/linux-2.6.22.19/include" ;
cat linux/mips/ioctls_inc0.h linux/mips/ioctls_arch0.h > ioctls_all0.h
gcc -DHAVE_CONFIG_H   -I./linux/mips -I./linux/mips -I./linux -I./linux -I. -I. -I/Volumes/Case-sensitive/Entware-ng/staging_dir/host/include -I/Volumes/Case-sensitive/Entware-ng/staging_dir/host/usr/include -I/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/host/include -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Wsign-compare -Wtype-limits -Wwrite-strings -O2 -I/Volumes/Case-sensitive/Entware-ng/staging_dir/host/include -I/Volumes/Case-sensitive/Entware-ng/staging_dir/host/usr/include -I/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/host/include -I/Volumes/Case-sensitive/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/linux-mipselsf/linux-2.6.22.19/include -DIOCTLSORT_INC=\"ioctls_all0.h\" -c -o ioctlsort0.o ./ioctlsort.c
```
A list of all includes (including duplicates):
**CFLAGS**
-I/Volumes/Case-sensitive/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/linux-mipselsf/linux-2.6.22.19/include
-I/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/opt/include
-I/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/include
-I/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/usr/include
-I/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/include
**CXXFLAGS**
-I/Volumes/Case-sensitive/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/linux-mipselsf/linux-2.6.22.19/include
-I/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/opt/include
 -I/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/include
-I/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/usr/include
-I/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/include
**LDFLAGS**
-L/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/opt/lib
-L/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/lib
-L/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/usr/lib
-L/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/lib
**CCOPT**
-I/Volumes/Case-sensitive/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/linux-mipselsf/linux-2.6.22.19/include
**gcc**
-I./linux/mips
-I./linux/mips
-I./linux
-I./linux
-I.
-I.
-I/Volumes/Case-sensitive/Entware-ng/staging_dir/host/include
-I/Volumes/Case-sensitive/Entware-ng/staging_dir/host/usr/include
-I/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/host/include
-I/Volumes/Case-sensitive/Entware-ng/staging_dir/host/include
-I/Volumes/Case-sensitive/Entware-ng/staging_dir/host/usr/include
-I/Volumes/Case-sensitive/Entware-ng/staging_dir/target-mipsel_mips32r2_uClibc-1.0.16/host/include
-I/Volumes/Case-sensitive/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/linux-mipselsf/linux-2.6.22.19/include

For the existing file `./staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/include/asm/ioctl.h` I do see a match in the CFLAGS and CXXFLAGS:
`-I/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/include`

Should `gcc` pickup pickup the earlier defined `CFLAGS` include `-I/Volumes/Case-sensitive/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.3.0_uClibc-1.0.16/include`?

**Comment by zyxmon** [comment]
There are no problems compiling entware on debian jessie. Please switch to debian!

**Comment by ProBackup-nl** [comment]
@zyxmon Sorry, I don't want to leave Mac OS X.
