### ISSUE TITLE
Unclear what the relation is with uClibc-ng, would someone please translate changes.ru.txt to english?

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-ng/Entware-ng#454]
I'm struggling with understanding how uClibc-ng is hooked in Entware-ng. And where Entware-ng differs from OpenWrt buildroot toolchain (where there doesn't seem to be any use of uClibc-ng).

Searching for "uclibc-ng" in this repository results with changes.ru.txt:
Выкинул все Uclibc, оставил Uclibc-ng и обновил до 1.0.7 (поменял config - uClibc/config-ng-1.0.7/common поближе к тулчену
Тулчейн с uclibc-ng собирается только при выборе gcc 5.2. Поэтому 5.2 выбрал для всех архитектур (однообразие)

I don't understand the Russian language. Would someone please translate or explain?

**Comment by zyxmon** [comment]
Pleasу do not start new issies, continue your questions in the old ones.
Entware-ng differs from Openwrt - it does not compile kernel & kernel modules and does not build firmware images. The difference in `make tollchain/install` step is related to the old 2.6.22 kernel used in the mipsel feed of entware. There may be some differences in the generated uclibc .config file (mostly from  https://github.com/Entware-ng/Entware-ng/blob/master/toolchain/uClibc/config/common file).
If you will follow our recommendations and will not try to build something related to the kernel the toolchain and packages will be build without problems.

**Comment by ProBackup-nl** [comment]
Could someone give an example of a package that is "related to the kernel"?
