### ISSUE TITLE
ps3netsrv update

### ISSUE THREAD

**Issue by Xa6ep** [Entware-ng/Entware-ng#455]
Please update ps3netsrv. The entware version works little buggy.
Old developer doesn't support it anymore. Aldostools - famous developer on psx scene. He makes many tools for ps3. Now he made updated ps3netsrv.
https://github.com/aldostools/ps3netsvr (don't doubt svr=srv)

**Comment by ryzhovau** [comment]
Looks like Windows optimized port which is not compatible with Entware toolchain.

**Comment by Xa6ep** [comment]
Look at it this please, https://github.com/aldostools/webMAN-MOD/tree/master/ps3netsrv
There is compilled linux and raspberry versions in bin folder. Maybe it can be compiled for entware?
