### ISSUE TITLE
Package request: rs-serve

### ISSUE THREAD

**Issue by helloray** [Entware-ng/Entware-ng#456]
rs-serve is a remoteStorage server written in C for POSIX systems, storing data in system users' home directories.

check https://remotestorage.io/ for more details.

**Comment by ryzhovau** [comment]
Looks like it's not developed [for ~3 years](https://github.com/remotestorage/rs-serve/commits/master).
Are you sure it wasn't abandoned?

**Comment by helloray** [comment]
@ryzhovau , thanks for the reply. It seems it is not actively developed now. Sorry. I will close it.
