### ISSUE TITLE
Package Request: Duplicity/Duply

### ISSUE THREAD

**Issue by spdaly** [Entware-ng/Entware-ng#457]
Would like to get this setup https://www.felixdittgen.de/2014/11/08/backup-your-synology-dsm-5-1-encrypted-to-remote-server-with-duply-and-duplicity/ using opkg.

Includes: http://duplicity.nongnu.org/, http://duply.net/ and https://github.com/matthewbentley/duplicity_b2

**Comment by zyxmon** [comment]
Duply is a shell script - just download, unpack and use it. (You may need to edit shebang and install some extra packages like bash).
As for Duplicity - try to install it yourself - https://github.com/Entware-ng/Entware-ng/issues/344
