### ISSUE TITLE
python3 pycrypto

### ISSUE THREAD

**Issue by keiser1080** [Entware-ng/Entware-ng#460]
unable to install pycrypto on python3

`
/opt/bin# opkg install build-essential autoconf libtool pkg-config
/opt/bin# opkg install gcc
/opt/bin# opkg install python3 python3-pip python-cffi
/opt/bin# opkg install libgmp
/opt/bin# ln -s /opt/lib/libgmp.so.10 /opt/lib/libgmp.so
/opt/bin# ./pip3 install pycrypto
...
src/_fastmath.c:36:18: fatal error: gmp.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-openwrt-linux-gnu-gcc' failed with exit status 1
...
`

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-python-modules

**Comment by keiser1080** [comment]
Zyxmon ?

please refer to my post

on the wiki =>There is only symlink libffi.so.6 there. You can create missing link manually

/opt/bin# opkg install libgmp 
/opt/bin# ln -s /opt/lib/libgmp.so.10 /opt/lib/libgmp.so

So the lynk is already done

**Comment by zyxmon** [comment]
You are installing packages that do not exist and do not show headers installation.

**Comment by keiser1080** [comment]
@zyxmon 

you mean libgmp-dev not exsit ? and it's a dependency for pycrypto?

Is there someplace where we can post a package wishlist ?
Can i try to compile the package myself ?

**Comment by zyxmon** [comment]
>> Can i try to compile the package myself ?

You have already tried but have not read the wiki. Just follow wiki steps and use pip3

**Comment by keiser1080** [comment]
@zyxmon 

thanks a lot
It's working now
for those having the same problem.
You have to download the header (replace x86-64 by your arch)

> /opt/bin# wget -qO- http://pkg.entware.net/binaries/x86-64/include/include.tar.gz | tar xvz -C /opt/include
> /opt/bin# opkg install build-essential autoconf libtool pkg-config
> /opt/bin# opkg install gcc
> /opt/bin# opkg install python3 python3-pip python-cffi
> /opt/bin# opkg install libgmp
> /opt/bin# ln -s /opt/lib/libgmp.so.10 /opt/lib/libgmp.so
> /opt/bin# ./pip3 install pycrypto
