### ISSUE TITLE
Where should package daemontools create its /service directory at /opt?

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-ng/Entware-ng#462]
I am trying to package [DJB daemontools](https://cr.yp.to/daemontools.html). DJB daemontools is a collection of tools for managing UNIX services, and has overlaps with `/init.d/`.

For daemontools to operate, it requires a `/service` folder as working directory.

What (and why) is the better location for that `/service` folder?
```
/opt
/opt/etc
/opt/etc/daemontools
```
Or even a totally different location?

**Comment by zyxmon** [comment]
IMHO `/opt/services`

**Comment by ProBackup-nl** [comment]
Stock default RT-N56U + Entware: ```
# ls /opt/services
ls: /opt/services: No such file or directory
```
I will choose `/opt/service` (without s) for the full path.
