### ISSUE TITLE
Package Request: daemon

### ISSUE THREAD

**Issue by arrmo** [Entware-ng/Entware-ng#463]
http://www.libslack.org/daemon/

This is a cool little command - daemonizes a program, but unlike daemonize it monitors and restarts the program if it exits for some reason. That's a key difference ... :-).

Thanks!

**Comment by ryzhovau** [comment]
Looks like it was abandoned 6 years ago. I'm sure there's something newer alternative.

**Comment by arrmo** [comment]
I admit, not that I have found - but I'd be fine with it if there is a newer version! FYI, still seems to be active in Ubuntu (and I use it there also),
http://manpages.ubuntu.com/manpages/zesty/man1/daemon.1.html

Thanks!
