### ISSUE TITLE
"opkg install pyload" installs so many packages

### ISSUE THREAD

**Issue by digimon04** [Entware-ng/Entware-ng#464]
My router is AC68U with Entware-NG. I found that "opkg install pyload" will also install a large amount of other packages including:

`python-curl python python-light python-base zlib libffi libbz2 python-ctypes python-pydoc python-multiprocessing python-codecs python-sqlite3 libsqlite3 python-logging python-gdbm libgdbm python-email python-distutils python-xml libexpat python-compiler python-db libdb47 libxml2 python-openssl libopenssl python-decimal python-unittest python-ncurses libncurses libncursesw libcurl`

Are they all necessary? I am facing memory error when using or installing other packages such as Transmission. I reckon it is related to pyload install.

Any help is appreciated.

**Comment by zyxmon** [comment]
>> Are they all necessary?

Yes, they are nessesary.

>>  I am facing memory error when using or installing other packages 

It is quite different - if you have problems with installation - use a larger hdd or a flash drive, if you have problems with running - do not run pyload and transmission simultaneously
