### ISSUE TITLE
Package request - Zoneminder

### ISSUE THREAD

**Issue by MrDini123** [Entware-ng/Entware-ng#465]
Hi,

That would be great, if I Can install Zoneminder directly on my NAS (ARMv5), from the entware-ng repo. It is a really nice, open-source webcam management software.

https://zoneminder.com/

Thanks!

Ps: the entware-ng uses uClibc, uClibc-ng, or glibc on the ARM boxes?

**Comment by ryzhovau** [comment]
Requires mysql, ffmpeg, V4L and so on. IMHO, it's too heavy for embedded systems.

**Comment by zyxmon** [comment]
https://github.com/ZoneMinder/ZoneMinder#building-from-source-is-discouraged

Building from source is discouraged

PS entware-ng uses glibc on arm.

**Comment by MrDini123** [comment]
Yes, it has a lot of dependancie, I am continously compile theese packages for a week ago... But I hoped, You Can do it better. Because the main system on the nas has uClibc, where the polkit compile (for example) is a bit hard...

Okay, thank you!

**Comment by zyxmon** [comment]
@MrDini123 - you can try to compile Entware version (glibc).
The best way to do it - https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources
You can also try native compilation - https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-(native-compilation) - but in this case you'll need to build cmake (and may be some other developers tools).
