### ISSUE TITLE
rsync: Please support -X and -A as per default

### ISSUE THREAD

**Issue by h4711** [Entware-ng/Entware-ng#466]
Please support the rsync options for extended attributes and ACLs (-X and -A). These are disabled per default and missing in the rsync binary in the repository.

Rationale: There are other packages in the repository that support that, like attr. So this would help to rsync files including their extended attributes or would help in backing up some linux machine to a NAS with Entware-ng.

**Comment by zyxmon** [comment]
@h4711 what feed (arch) are you using? I can build rsync for you to test.

**Comment by h4711** [comment]
Thanks, i will be happy to test.

I'm using Entware-ng for Zyxel NAS.

This is my /opt/etc/opkg.conf :
```
src/gz packages http://pkg.entware.net/binaries/armv7
src/gz Mijzelf http://downloads.zyxel.nas-central.org/Users/Mijzelf/Entware-ng/binaries/armv7
dest root /
dest ram /opt/tmp
lists_dir ext /opt/var/opkg-lists
option tmp_dir /opt/tmp

```

**Comment by h4711** [comment]
The Mijzelf repository only contains one integration package to execute /opt/etc/profile from profile and two packages containing kernel modules, but no rsync.

So I'm using http://pkg.entware.net/binaries/armv7

**Comment by zyxmon** [comment]
@h4711 `opkg install http://pkg.entware.net/binaries/armv7/test/rsync_3.1.2-1a_armv7soft.ipk` to test.
Please report.

**Comment by h4711** [comment]
Thanks!

This works.

-X successfully transferred the user attribute
-A tried to transfer the ACL and correctly reported, that it is not support by the target fs

Adding both, -X and -A, would be helpful anyway, as I will try to get Zyxel to enable ACLs in their kernel (and their may exist systems that have it enabled already).
