### ISSUE TITLE
 tclsh8.5 Can't find a usable init.tcl

### ISSUE THREAD

**Issue by qbox4u** [Entware-ng/Entware-ng#467]
Trying to **make** an webdot and Graphviz from http://www.graphviz.org/
but fails on the install of tcl

[~] #  find / -name '*tclsh8*'
/share/MD0_DATA/.qpkg/Entware-ng/bin/tclsh8.5
[~] #  /share/MD0_DATA/.qpkg/Entware-ng/bin/tclsh8.5
application-specific initialization failed: Can't find a usable init.tcl in the                                              following directories:
    /opt/lib/tcl8.5 /share/MD0_DATA/.qpkg/Entware-ng/lib/tcl8.5 /share/MD0_DATA/                                             .qpkg/lib/tcl8.5 /share/MD0_DATA/.qpkg/Entware-ng/library /share/MD0_DATA/.qpkg/                                             library /share/MD0_DATA/.qpkg/tcl8.5.18/library /share/MD0_DATA/tcl8.5.18/librar                                             y
This probably means that Tcl wasn't installed properly.

% ^C

**Comment by zyxmon** [comment]
@qbox4u  Confirmed. What is your feed (architecture)? I can make a package for you to test!

**Comment by qbox4u** [comment]
Model:TS-459 Pro II
Instruction Set	64-bit
Current QNap firmware version: 4.2.2
Basic clean installation ........

The issue occured at my make for Webdot 
PS: you also need to add manually an symlink in /opt/bin !!!!
tclsh -> /share/MD0_DATA/.qpkg/Entware-ng/bin/tclsh8.5*


ANOTHER COMBINED ISSUE BUT WITH GCC, THEREFORE I ADD THE FULL INFO


[~] # more /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 28
model name      : Intel(R) Atom(TM) CPU D525   @ 1.80GHz
stepping        : 10
microcode       : 0x107
cpu MHz         : 1795.437
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
bogomips        : 3590.87
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 28
model name      : Intel(R) Atom(TM) CPU D525   @ 1.80GHz
stepping        : 10
microcode       : 0x107
cpu MHz         : 1795.437
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
bogomips        : 3590.87
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 28
model name      : Intel(R) Atom(TM) CPU D525   @ 1.80GHz
stepping        : 10
microcode       : 0x107
cpu MHz         : 1795.437
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
bogomips        : 3590.87
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 28
model name      : Intel(R) Atom(TM) CPU D525   @ 1.80GHz
stepping        : 10
microcode       : 0x107
cpu MHz         : 1795.437
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
bogomips        : 3590.87
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:


Installed http://pkg.entware.net/binaries/other/Entware-ng_0.97.qpkg

compiling graphviz issue

download http://www.graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.38.0.tar.gz

[~] #  uname -a
Linux EUV001 3.4.6 #1 SMP Wed Nov 2 02:01:20 CST 2016 x86_64 GNU/Linux
[~] # cat /proc/version
Linux version 3.4.6 (root@BuildServer36) (gcc version 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)) #1 SMP Wed Nov 2 02:01:20 CST 2016
[~] # uname -m
x86_64
[~] # file /sbin/init
/sbin/init: symbolic link to ../bin/busybox



[~] # opkg update
Downloading http://pkg.entware.net/binaries/x86-64/Packages.gz.
Updated list of available packages in /opt/var/opkg-lists/packages.
[~] # opkg upgrade
[~] # opkg list_installed
ar - 2.26.1-1
binutils - 2.26.1-1
busybox - 1.24.2-1
bzip2 - 1.0.6-2
coreutils - 8.23-2
coreutils-install - 8.23-2
entware-opt - 222108-5
file - 5.25-1
findutils - 4.6.0-1
gawk - 4.1.4-1
gcc - 5.4.0-1
ldconfig - 2.23-5
ldd - 2.23-5
libacl - 20160519-1
libattr - 20160302-1
libbfd - 2.26.1-1
libbz2 - 1.0.6-2
libc - 2.23-5
libgcc - 5.4.0-5
libiconv-full - 1.11.1-3
libintl-full - 0.19.6-2
liblzma - 5.2.2-1
libmagic - 5.25-1
libncursesw - 6.0-1b
libopcodes - 2.26.1-1
libpthread - 2.23-5
librt - 2.23-5
libssp - 5.4.0-5
libstdcpp - 5.4.0-5
locales - 2.23-5
make - 4.2.1-1
nano - 2.7.0-1
objdump - 2.26.1-1
opkg - 9c97d5ecd795709c8584e972bfdf3aee3a5b846d-12
sed - 4.2.2-1
tar - 1.29-2
tcl - 8.5.18-1
terminfo - 6.0-1b
xz - 5.2.2-1
xz-utils - 5.2.2-1
zlib - 1.2.8-1
[~] # more /opt/bin/gcc_env.sh
#!/bin/sh
export LDFLAGS="-Wl,-rpath=/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-linux-x86-64.so.2 -L/opt/lib"
export CFLAGS="-O2 -pipe -march=x86-64-a -mtune=cortex-a9 -fno-caller-saves -mfloat-abi=soft "
[~] # cp /share/MD0_DATA/Web/graphviz-2.38.0.tar.gz  /share/MD0_DATA/.qpkg/Entware-ng/lib
[~] # wget -qO- http://pkg.entware.net/binaries/x86-64/include/include.tar.gz | tar xvz -C /opt/include
[~] # cd /share/MD0_DATA/.qpkg/Entware-ng/lib
[/share/MD0_DATA/.qpkg/Entware-ng/lib] # tar -xvf graphviz-2.38.0.tar.gz
[/share/MD0_DATA/.qpkg/Entware-ng/lib] # cd graphviz-2.38.0

*********************** This goes wrong ***********************
[/share/MD0_DATA/.qpkg/Entware-ng/lib/graphviz-2.38.0] # source /opt/bin/gcc_env.sh
[/share/MD0_DATA/.qpkg/Entware-ng/lib/graphviz-2.38.0] # ./configure --prefix=/opt
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /opt/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... config/install-sh -c -d
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/share/MD0_DATA/.qpkg/Entware-ng/lib/graphviz-2.38.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
[/share/MD0_DATA/.qpkg/Entware-ng/lib/graphviz-2.38.0] #

*********************** End of This goes wrong ***********************
When repeating with an new ssh but not adding .....  source /opt/bin/gcc_env.sh, 
the error cannot create executables is eliminated
[/share/MD0_DATA/.qpkg/Entware-ng/lib/graphviz-2.38.0] # PATH=/opt/bin:$PATH
[/share/MD0_DATA/.qpkg/Entware-ng/lib/graphviz-2.38.0] # ./configure --prefix=/opt 
[/share/MD0_DATA/.qpkg/Entware-ng/lib/graphviz-2.38.0] # make
[/share/MD0_DATA/.qpkg/Entware-ng/lib/graphviz-2.38.0] # make install

make[5]: Entering directory '/share/MD0_DATA/.qpkg/Entware-ng/lib/graphviz-2.38.0/cmd/dot'
(cd /opt/bin; if test -x dot; then for i in neato twopi fdp circo osage patchwork sfdp; do rm -f $i; ln -s dot $i; done; fi;)
if test "x" = "x"; then if test -x /opt/bin/dot; then if test -x /sbin/ldconfig; then /sbin/ldconfig 2>/dev/null; fi; /opt/bin/dot -c; else /opt/bin/dot_static -c; fi; fi
/bin/sh: line 1: 13168 Segmentation fault      /opt/bin/dot -c
make[5]: *** [Makefile:1180: install-exec-hook] Error 139

Perhaps it would be nice to have webdot and graphviz also available as an opkg, but i would still remain with the question why these error's occur

**Comment by qbox4u** [comment]
by the way
I am unfortunately aso missing several other libs as required in dependancy's
http://www.graphviz.org/Download_source.php

previously i used  (the eliminated) ipkg and was able to make the full graphviz version with options etc
could  you perhaps also check for the additional packages????
example.. cairo. etc etc
Sorry if this is too much to ask from my side

**Comment by zyxmon** [comment]
@qbox4u - your feed is x64 (or x86-64 - that is the same).
Here is fixed tcl for you to check
http://pkg.entware.net/binaries/x86-64/test/tcl_8.5.18-1a_x86-64.ipk
(I cannot check because I've swithced to Entware-3x on my intel NAS).
Please - report.

As for missing libraries - all are optional, not required - http://www.graphviz.org/Download_source.php . You can leave your tickets asking to add libs (one ticket per lib).
As I can guess - you are going to compile graphiz - in this case you can also compile missing libraries.
FYI - here is an instruction for native compilation - https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-(native-compilation) but the preferred way is crosscompilation - https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources

**Comment by qbox4u** [comment]
hy zyxmon
*i checked the provided link, and it seems to work*
*no error's generated.*
*excellent support** thanks*

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/entware-packages/commit/c36df6577268d425cef76c8d6748f02394af33af
