### ISSUE TITLE
Could not find libpng in the pkg-config search path

### ISSUE THREAD

**Issue by qbox4u** [Entware-ng/Entware-ng#470]
Feed is x64 (or x86-64).
[~] # opkg update
[~] # opkg install libpng
     Package libpng (1.2.56-1) installed in root is up to date.
[~] # source /opt/bin/gcc_env.sh
[~] #  ./configure --prefix=/opt

during ./configure --prefix=/opt  of  cairo-1.14.8 we bail out with the error

checking for cairo's PNG functions feature...
configure: WARNING: Could not find libpng in the pkg-config search path
checking whether cairo's PNG functions feature could be enabled... no
configure: error: recommended PNG functions feature could not be enabled

**Comment by zyxmon** [comment]
Please read the wiki and install (unpack) headers.
We do not provide support for native compilation and recommend to crosscompile packages.

**Comment by qbox4u** [comment]
Hy zyxmon
it is probably due to my lack of experience, but  Package libgd (2.1.1-1) installed in root is up to date
whenever i compile  graphviz-2.38.0, this library is missing
plugin libraries:
  dot_layout:    Yes (always enabled)
  neato_layout:  Yes (always enabled)
  core:          Yes (always enabled)
  devil:         No (missing library)
  _**gd:**            **No (missing library)**_ 

Compiling graphviz-2.38.0 with the latest  libgd-2.2.3 locally enables the library however
https://github.com/libgd/libgd/releases/download/gd-2.2.3/libgd-2.2.3.tar.xz

 plugin libraries:
  dot_layout:    Yes (always enabled)
  neato_layout:  Yes (always enabled)
  core:          Yes (always enabled)
  devil:         No (missing library)
  _**gd:**            **Yes**_

It puzzles me ^_^
Has this to do with the outdated '''Wed 14 January 2015'''' Package libgd (2.1.1-1) of opkg??

********* My make ************
cp /share/MD0_DATA/Web/libgd-2.2.3.tar.xz  /share/MD0_DATA/.qpkg/Entware-ng/lib
cd /share/MD0_DATA/.qpkg/Entware-ng/lib
tar -xvf libgd-2.2.3.tar.xz
cd libgd-2.2.3
source /opt/bin/gcc_env.sh
./configure --prefix=/opt --disable-werror
make
make install

**Comment by zyxmon** [comment]
Have you unpacked the headers? 
Have you installed libs?
Do you use the script setting environment variables for compilation?

If you have done it - you may need to patch graphviz sources so the libs are found!
