### ISSUE TITLE
Dislocker fuse: device not found, try 'modprobe fuse' first

### ISSUE THREAD

**Issue by TotalDay** [Entware-ng/Entware-ng#471]
Arch: mipsel

Dislocker error after entered password

>  fuse: device not found, try 'modprobe fuse' first

+libfuse +libpolarssl have been installed

lsmod shows fuse module (loaded ok)

**Comment by zyxmon** [comment]
You should use kernel module fuse.ko from your firmware or you firmware manufacturer.
Kernel modules cannot be part of Entware.
