### ISSUE TITLE
update shadowsocks-libev to 2.5.6

### ISSUE THREAD

**Issue by steve3d** [Entware-ng/Entware-ng#472]
shadowsocks-libev-2.4.5 seems outdated a long time ago. please update to current 2.5.6 version. 

https://github.com/shadowsocks/shadowsocks-libev/releases

thanks.

**Comment by ryzhovau** [comment]
Done.

**Comment by ryzhovau** [comment]
oops.

**Comment by ryzhovau** [comment]
Please, send this issue to [upstream](https://github.com/openwrt/packages/tree/master/net/shadowsocks-libev) and update will arrive to Entware in the next month.
