### ISSUE TITLE
Package Request:  Java JRE

### ISSUE THREAD

**Issue by latenitetech** [Entware-ng/Entware-ng#473]
Hi, newbie here, hoping this is a reasonable request.  I'm looking for a Java JRE package to run on my Asus RT-AC68U router running AsusWRT-Merlin.  I'm wanting to run Streambaby, (a video streaming application for Tivo), which requires a Java JRE.  I don't think the version is terribly important as it's a pretty old app.  I'm using jre1.8.0_111 on my Windows PC and it's working fine, but an older JAVA version would likely be fine as well.  Thanks for your consideration.

**Comment by zyxmon** [comment]
Oracle JRE is not available for mipsel - that is one of the most popular feeds.
So no JRE in Entware is planned.

**Comment by ryzhovau** [comment]
To clarify: JRE is can be present by jamvm+classpath, but it's too old and too slow, so we decided to to put the into repository.
