### ISSUE TITLE
Package request: mod_dav_svn

### ISSUE THREAD

**Issue by serge-sb** [Entware-ng/Entware-ng#476]
This apache module is needed to access SVN repos via http(s) protocol. As you can see here ([Apache Subversion](https://subversion.apache.org/packages.html)) this module is installed separately for some oses. Entware's apache or subversion-libs lacks support for this module, so it could be released as a separate one. As it is for Debian, Red Hat Linux or Ubuntu, for example.

Many thanks in advance.

**Comment by zyxmon** [comment]
Dub - https://github.com/Entware-ng/Entware-ng/issues/415

**Comment by serge-sb** [comment]
Zyxmon, I've seen that issue and it is not a duplicate. JANogueira asked to change subversion-server package configuration. Here in this issue I ask to add these modules as a standalone package. As it is done for some mentioned OSes. So there would be no desync with OpenWRT.

**Comment by zyxmon** [comment]
@serge-sb if you know how to build required module separately just test it and make a PR.

**Comment by serge-sb** [comment]
@zyxmon if I could do that, I would've done. That's why I've posted this package request issue.

**Comment by zyxmon** [comment]
@serge-sb just google and find out that there is a special configuration option for subversion building to compile mod_dav_svn. It cannot be compiled as standalone binary.

**Comment by serge-sb** [comment]
Yes, there is an option to compile apache with or without svn support. But these modules can be installed from standalone packages for Centos (yum install mod_dav_svn), Debian (apt-get install libapache2-svn), Red Hat (yum install mod_dav_svn), Ubuntu (apt-get install libapache2-svn) and probably OpenBSD (pkg_add ap2-subversion). Somehow these modules were compiled into standalone package.
