### ISSUE TITLE
Package request: unison 2.48.3

### ISSUE THREAD

**Issue by pensionado** [Entware-ng/Entware-ng#477]
This would allow for dual side sync with remote computer (QNAP in my case). Have 2.40.1, but is outdated.

**Comment by zyxmon** [comment]
This is the 4th request for unison. Please use search function to read comments on previous requests.

You can use native compilation (read the wiki) to compile ocaml, fnd use ocaml to compile unison.

**Comment by dugwood** [comment]
Tested on a Synology NAS:

Compile ocaml:
https://github.com/Entware-ng/Entware-ng/issues/446#issuecomment-316628232

Then compile Unison:
```
wget http://www.seas.upenn.edu/~bcpierce/unison//download/releases/stable/unison-2.48.4.tar.gz
tar -xvzf unison-2.48.4.tar.gz
cd src
make UISTYLE=text NATIVE=false
cp unison /opt/bin
```
(Note that you can see `/bin/sh: line 1: etags: command not found`, but it's no big deal, as you should see `make[1]: [Makefile:347: tags] Error 127 (ignored)` right after it).

**Comment by ryzhovau** [comment]
> Tested on a Synology NAS:

It's useless for cross-compilation Buildoot we using.

**Comment by dugwood** [comment]
@ryzhovau, I'm sorry but I don't understand your comment (even if you meant `Buildroot` I think), as you said: https://github.com/Entware-ng/Entware-ng/issues/307#issuecomment-224236284

Hence I assume that we won't ever see a cross-compilation of OCaml, right?

**Comment by ryzhovau** [comment]
> Hence I assume that we won't ever see a cross-compilation of OCaml, right?

Right.
