### ISSUE TITLE
fontconfig - 2.12.1-1 - fontconfig  /usr/share/fonts: No such file or directory

### ISSUE THREAD

**Issue by qbox4u** [Entware-ng/Entware-ng#478]
Hy zyxmon

Probably i am mistaking, but  fontconfig needs with opkg in an QNap apparently an additional path
defined 
changing 
[/opt/share/fonts] # which fc-list
/opt/bin/fc-list
[/opt/share/fonts] # fc-list : file
[/opt/share/fonts] # fc-cat
/usr/share/fonts: No such file or directory
/root/.local/share/fonts: No such file or directory
/root/.fonts: No such file or directory
[/opt/share/fonts] #

changing **temporary** fonts.conf was getting it running, but is no final solution
part... Font directory list
change 
        <dir>/usr/share/fonts</dir>
to
	<dir>/opt/share/fonts</dir>

**Comment by zyxmon** [comment]
Thanks for reporting!
Fixed in https://github.com/Entware-ng/entware-packages/commit/4f6fbc393346f96517a00f03afc028c22aa56245

Will be available in repo with next openwrt sync (in few days).

**Comment by qbox4u** [comment]
Thanks

PS: This is finally my first version of an working graphviz configure/make/
make-install sequence

https://www.mediawiki.org/wiki/Setup_QNap_TS459_PRO_II_for_install_graphviz_with_Entware-ng

I tested this on my other QNap_TS459_PRO_II.

Not the QNap_TS459_PRO+ running qbox4u.com
