### ISSUE TITLE
wrong password after /opt/bin/passwd

### ISSUE THREAD

**Issue by myxa781** [Entware-ng/Entware-ng#479]
after change password via /opt/bin/passwd can't login via putty 2 dropbear 
system android 4.4.2

**Comment by zyxmon** [comment]
Please switch to Entware-3x and create tickets there
https://github.com/Entware-for-kernel-3x/Entware-ng-3x

Alternative Entware-3x install is used for android - http://forums.zyxmon.org/viewtopic.php?f=5&t=5399 (Russian).
