### ISSUE TITLE
Package request php7-*

### ISSUE THREAD

**Issue by ajjjjjjjj** [Entware-ng/Entware-ng#48]
PHP7 brings double performance compared to 5.x branches which is critical factor for running scripts on power optimized cpus in routers.

**Comment by ryzhovau** [comment]
No plans to add PHP7 to repo. Current PHP5 packages (and bunch of dependent packages) are ported from OpenWrt trunk.

You may [ask OpenWrt devs](https://github.com/openwrt/packages/issues) to add PHP7. We'll add them to Entware after OpenWrt.
