### ISSUE TITLE
apache do not list modules

### ISSUE THREAD

**Issue by eliz82** [Entware-ng/Entware-ng#480]
I installed Apache from Entware NG and configured after reading this https://wiki.openwrt.org/doc/howto/http.apache
Is running fine.

apache2 -M or apache2ctl -M in the shell should list installed modules. All i get is "Syntax OK"

The response should be something like this:
_Loaded Modules:
 core_module (static)
 mpm_prefork_module (static)
 http_module (static)
 so_module (static)
 auth_basic_module (shared)
 cgi_module (shared)
 version_module (shared)
 wsgi_module (shared)
Syntax OK_

http://www.shellhacks.com/en/List-Loaded-Enabled-Apache-Modules

**Comment by ryzhovau** [comment]
Please, send this issue to [upstream](https://github.com/openwrt/packages/tree/master/net/apache) and fix will arrive here in next month.
