### ISSUE TITLE
Cannot install Module on synology

### ISSUE THREAD

**Issue by ordimans** [Entware-ng/Entware-ng#481]
Hello,

I follow the HOW To to install Entware on my Synology.
Now I had CPAN, and perl 5.18.

I could install XML:Simple without problem.
But for DateTime it fails during installation... I checked logs, first problem is with List:Util which is outdated...
And when i install the last version, it fail with Extern.h....

I think I have a problem with PATH or something like that... Maybe i forgot something ??
But it's very hard to have a PERL on Synology... I thought it was easier....

my CPAN is up-to-date.

Thanks you in advance.

**Comment by zyxmon** [comment]
Use this instructions - https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-perl-modules

**Comment by ordimans** [comment]
Thanks you.
I had a problem with gcc.

Now i installed every module needed. But i have this error when i launch my script 👍 


Can't load '/opt/lib/perl5/5.22/auto/Fcntl/Fcntl.so' for module Fcntl: /opt/lib/perl5/5.22/auto/Fcntl/Fcntl.so: wrong ELF class: ELFCLASS32 at /opt/lib/perl5/5.22/XSLoader.pm line 96.
 at /opt/lib/perl5/5.22/Fcntl.pm line 12.

**Comment by zyxmon** [comment]
@ordimans - you need to make some patches for sources you have used. Google for the solution, it may not be easy.

**Comment by zyxmon** [comment]
@ordimans Have you used the correct headers for your feed. What feed (architecture) are you using?
