### ISSUE TITLE
Feature request on entware-arm7: mpd with NFS and/or SMB enabled

### ISSUE THREAD

**Issue by rodoviario** [Entware-ng/Entware-ng#483]
Is it possible to compile mpd with NFS and/or SMB directory options (NFS:// or SMB://) apart from the local file directory. It will be the missing piece for my home music system... to be able to pull the mp3s from a NFS or SMB share on the same network.

Thxs in advance

**Comment by ryzhovau** [comment]
Too heavy to embedded devices. You can always mount NFS/SMB shares to use it as local sources.

**Comment by rodoviario** [comment]
Well, thaks... I was trying to do so with no luck so far. Anyway the final
setup will have a big harddrive attached to that google tv clone, so it
will not be that important.

2016-12-27 3:16 GMT-04:00 Alexander Ryzhov <notifications@github.com>:
