### ISSUE TITLE
request: perl Device::USB

### ISSUE THREAD

**Issue by immiimmi** [Entware-ng/Entware-ng#484]
I would really appreciate Device::USB on armv5
many thanks

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-perl-modules

**Comment by immiimmi** [comment]
sorry to reopen the issue; 
I was not as lucky as for Net::SSLeay, for which native compilation worked according to https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-perl-modules

therefore I used https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources 
I was able to cross-compile perl-device-usb on a ubuntu for armv5
`make package/perl-device-usb/compile -j4
 make[1] package/perl-device-usb/compile
 make[2] -C feeds/packages/lang/perl host-compile
 make[2] -C package/libs/toolchain compile
 make[2] -C package/libs/gettext-full host-compile
 make[2] -C package/libs/zlib compile
 make[2] -C package/libs/libusb compile
 make[2] -C feeds/packages/libs/gdbm compile
 make[2] -C package/libs/libusb-compat compile
 make[2] -C feeds/packages/libs/libxml2 compile
 make[2] -C feeds/packages/libs/db47 compile
 make[2] -C feeds/packages/lang/perl-file-sharedir-install host-compile
 make[2] -C feeds/packages/lang/perl compile
 make[2] -C feeds/packages/lang/perl-parse-recdescent host-compile
 make[2] -C feeds/packages/lang/perl-inline host-compile
 make[2] -C feeds/packages/lang/perl-inline-c host-compile
 make[2] -C feeds/packages/lang/perl-inline compile
 make[2] -C feeds/packages/lang/perl-parse-recdescent compile
 make[2] -C feeds/packages/lang/perl-inline-c compile
 make[2] -C feeds/packages/lang/perl-device-usb compile`


the problem is now that when I load  Device::USB  on armv5, I get following error
`Undefined subroutine &Device::USB::lib_find_usb_device called at /opt/lib/perl5/5.22/Device
/USB.pm line 93, <DATA> line 1.`

can you give me a hint?
thanks
