### ISSUE TITLE
Problems setting up Synology DSM6 to build and contribute packages

### ISSUE THREAD

**Issue by robacarp** [Entware-ng/Entware-ng#486]
First off, thanks for putting this project together. I had no problems following the Synology setup guide and getting Entware-ng running on my NAS, and I found immediate benefit by installing many packages without issue.

I have a package or two I'd like to contribute to the repository which I'm planning on building on an Arm7 Synology running DSM6. While following the [How to add a package](https://github.com/Entware-ng/Entware-ng/wiki/How-to-add-a-new-package) guide, I ran into some issues which were easy to resolve, and then hit a roadblock. Perhaps I missed some link to build environment setup that would simply solve my issue, but I cannot find it.

Before running `make`, I had to install `make`, `gcc`, and `libc`. I pulled this from [the OpenWrt build system](https://wiki.openwrt.org/about/toolchain). 

Under [Prepare Build Environment](https://github.com/Entware-ng/Entware-ng/wiki/How-to-add-a-new-package#prepare-build-environement), the first task is to `make tools/install`. The config check stage of that make fails with several missing packages. I was able to prune the list quite a bit by installing these packages:

- `patch`
- `perl`
- `file`
- `unzip`

However, I am still left with this message when attempting to `make tools/install`:

```
Build dependency: Please install ncurses. (Missing libncurses.so or ncurses.h)
Build dependency: Please install a static zlib. (Missing libz.a or zlib.h)
Build dependency: Please install the openssl library (with development headers)
Build dependency: Please install the Perl Thread::Queue module
```

`Please install the Perl Thread::Queue module` led me down the path of [Self installation of perl modules](https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-perl-modules) but I found that installing perlbase was sufficient to satisfy the configure check.

Installing the packages: `libncurses`, `zlib`, and `libopenssl` I expected to resolve the `ncurses`, `static zlip`, and `openssl` errors, but they didn't. I suspect I'm missing some configure flags to specify the location of these libraries.

The last thing I attempted was to source `/opt/bin/gcc_env.sh` which I found somewhere on this wiki and contains some linker and compiler flags. This did not change the output of make and I'm left with these errors:

```
Build dependency: Please install ncurses. (Missing libncurses.so or ncurses.h)
Build dependency: Please install a static zlib. (Missing libz.a or zlib.h)
Build dependency: Please install the openssl library (with development headers)
```

I'm happy to follow a link to a more complete build env setup, or submit an update to the wiki if needed.

**Comment by zyxmon** [comment]
You probably need to install dev versions of lib. For debian based distro you need to install

'''
sudo apt-get install autoconf automake bash bison bzip2 cvs diffutils file flex g++ \
gawk gettext git-core gperf groff-base libexpat1-dev libncurses-dev libssl-dev libtool \
libslang2 libxml-parser-perl make patch perl python ruby sed shtool subversion tar \
texinfo unzip zlib1g zlib1g-dev pkg-config gettext libgmp3-dev libmpfr-dev libmpc-dev
'''

You may also need to install  gcc-multilib and libtool-bin.
You''ll also need en_US.UTF-8 locale on your system.
