### ISSUE TITLE
Netdata crashes on Asus RT-N66U

### ISSUE THREAD

**Issue by falbanese** [Entware-ng/Entware-ng#488]
Trying to execute the netdata utility from the netdata_1.4.0-3 package throws a SIGBUS signal:

    admin@RT-N66U:/tmp/home/root# netdata
    16-12-30 13:35:33: INFO: netdata: System has 1 processors.
    16-12-30 13:35:33: INFO: netdata: System supports 32768 pids.
    16-12-30 13:35:33: ERROR: netdata: User 'root' is not present. Ignoring option.
    Bus error

Has been this package tested on my platform ?

**Comment by ryzhovau** [comment]
Fixed at https://github.com/Entware-ng/entware-packages/commit/c879e6ddec3ba4a5f9893657aa6461a581e95598

**Comment by zyxmon** [comment]
netdata does not work in entware-ng for mipsel. Switch to https://github.com/Entware-for-kernel-3x if your firware kernel is 3.x

**Comment by falbanese** [comment]
After ryzhovau's fix, I can start netdata, but it keeps looping trying to accept connections: I reported that on their [page](https://github.com/firehol/netdata/issues/1503).

I use entware-ng on a Asus RT-N66U with Merlin firmware:

    Linux RT-N66U 2.6.22.19 #1 Fri Nov 11 16:42:24 EST 2016 mips GNU/Linux

As you can see, my router is still running a 2.x kernel.

**Comment by ktsaou** [comment]
btw, netdata should work perfectly on 2.x kernels (I use it under 2.6).

**Comment by zyxmon** [comment]
@ktsaou netdata works ok on arm with 2.6.32 and 2.6.36. But it does not work ок on mipsel with 2.6.22!

**Comment by ktsaou** [comment]
The oldest machine I have access to, is 2.6.26, and yes netdata works on that.
Can we trace it somehow? It should be working even on kernel 2.4.
