### ISSUE TITLE
libopenssl-dev to be able to install Net::SSLeay

### ISSUE THREAD

**Issue by moontear** [Entware-ng/Entware-ng#489]
Related to #430, but opening a new issue.

I'm not able to installed Net::SSLeay via Perl CPAN due to `SSLeay.xs:163:25: fatal error: openssl/err.h: No such file or directory`. According to [this ](https://rt.cpan.org/Public/Bug/Display.html?id=105189) and [this ](https://www.experts-exchange.com/questions/28148645/problem-installing-NET-SSLeay-from-CPAN.html) it seems to be solveable by installing openssl-dev / openssl-devel / libssl-dev. Looking at an Ubuntu package for libssl-dev I see exactly the files SSLeay is complaining about: http://packages.ubuntu.com/precise/i386/libssl-dev/filelist.

Here #42 I see a similar request to mine, but I don't understand the reasoning (cross-compilation) for not providing dev packages / sources.

**Comment by zyxmon** [comment]
There are no dev packages in Entware.
We do not provide support  for native compilation if wiki does not help.

**Comment by moontear** [comment]
The Wiki is of great help: https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-perl-modules - it just doesn't help with installation of SSLeay in this case.

Thanks for taking a look at the issue.

**Comment by moontear** [comment]
Where do I find the header files used for compilation of entware packages? [It seems so easy](https://stackoverflow.com/questions/21729975/error-installing-in-netssleay) - it is just source files...
