### ISSUE TITLE
missing perl GD.pm

### ISSUE THREAD

**Issue by qbox4u** [Entware-ng/Entware-ng#490]
funny

The install of perl is an piece of cake, but GD is missing
http://search.cpan.org/~lds/GD-2.56/lib/GD.pm 

The old ipkg was
The Graphical module
[~] # ipkg install perl-gd

whenever you have time for this ^_^

**Comment by ryzhovau** [comment]
It was excluded from [upstream](https://github.com/openwrt/packages/tree/master/lang/perl) for some reason. Please, [send](https://github.com/openwrt/packages/issues) them this issue and fix will arrive here next month.
