### ISSUE TITLE
[BUG] nginx-1.10.1-2_mipselsf throws warning in log file

### ISSUE THREAD

**Issue by graysky2** [Entware-ng/Entware-ng#492]
On a fresh install, /opt/var/log/nginx/error.log is populated with lines like the following on a startup:
```
2017/01/01 11:26:38 [emerg] 13266#0: eventfd() failed (89: Function not implemented)
```

From [googling](https://www.ruby-forum.com/topic/519162), a possible fix might be building without the `--with-file-aio` configure
option.  I am unsure where I can look in the github repo to see how you are building it to know for sure.

1) Can you point me to the build script or file I can inspect to see how you're building?
2) Can you check into the report of the error.log.

**Comment by ryzhovau** [comment]
It's depends on kernel of your system. 
Please, take a look at wiki if you want to rebuild package.
