### ISSUE TITLE
can't install Scrapy

### ISSUE THREAD

**Issue by layeka** [Entware-ng/Entware-ng#493]
pip3 install Scrapy
 In file included from src/lxml/lxml.etree.c:515:0:
    src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
    compilation terminated.
    Compile failed: command 'arm-openwrt-linux-gnueabi-gcc' failed with exit status 1
    creating opt
    creating opt/tmp
    cc -I/usr/include/libxml2 -c /opt/tmp/xmlXPathInit0kdoxtbj.c -o opt/tmp/xmlXPathInit0kdoxtbj.o
    /opt/tmp/xmlXPathInit0kdoxtbj.c:1:26: fatal error: libxml/xpath.h: No such file or directory
    compilation terminated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'arm-openwrt-linux-gnueabi-gcc' failed with exit status 1

**Comment by zyxmon** [comment]
In case you have followed the wiki and unpacked headers you may need to patch Scrapy sources.
