### ISSUE TITLE
Package request: php5-redis/php5-mod-redis

### ISSUE THREAD

**Issue by mihaicristianpetrescu** [Entware-ng/Entware-ng#494]
Hi,

I've installed redis for cache on owncloud but I cannot use redis cache for owncloud because we don't have the php redis module available on entware.
Can you make and add the package?

Thanks!

**Comment by ryzhovau** [comment]
php5 packages will stay without further development, we keep them just for compatibility.

**Comment by mihaicristianpetrescu** [comment]
Can you then make php7-redis/php7-mod-redis?
Thanks!

**Comment by jsetton** [comment]
I have the same question for php7-mod-redis. Would it be possible to add it to the repository?
