### ISSUE TITLE
Package request: mysql-server with InnoDB and query cache support

### ISSUE THREAD

**Issue by mihaicristianpetrescu** [Entware-ng/Entware-ng#495]
Hi,

I've installed mysql-server in order to use it with owncloud, but unfortunately since v7+ they only support InnoDB as a storage engine and I've noticed that the current mysql-package is missing this storage engine.
Can you please make a mysql-server package that contains the InnoDB storage engine and also query cache?

Thanks!

**Comment by zyxmon** [comment]
@mihaicristianpetrescu - ask openwrt maintainer. But I am afraid he has no time for it
https://github.com/openwrt/packages/issues/2506#issuecomment-196914079
