### ISSUE TITLE
lighttpd mod-auth

### ISSUE THREAD

**Issue by mfuentesraffio** [Entware-ng/Entware-ng#497]
Hello, how do I put lighttpd in? Previously I worked on asus rtn-66u and after installing everything on asus rt-ac68 install the module with:
Opkg install lighttpd-mod-auth
And I modified the file lighttpd.conf with:

server.modules += ( "mod_auth" )
auth.backend = "plain"
auth.backend.plain.userfile = "/opt/etc/lighttpd/passwd"
auth.require = (
"" =>
( "method" => "basic",
"realm" => "restricted area",
"require" => "valid-user"
)
)

But it does not work, can anyone help me?

Thank you

**Comment by ryzhovau** [comment]
This is not a help desk, sorry.

**Comment by mfuentesraffio** [comment]
I'm sorry, I do not know where I have to ask these kinds of questions.
Thank you
