### ISSUE TITLE
Package Request: minisign

### ISSUE THREAD

**Issue by john9527** [Entware-ng/Entware-ng#499]
Router support for DNSCrypt is being added either in native firmware or via install scripts.   minisign is the package of choice for the resolvers list verification (dnscrypt-resolvers.csv) which is updated periodically independent of the DNSCrypt code.

https://github.com/jedisct1/minisign

**Comment by ryzhovau** [comment]
OpenWrt guys [took](https://github.com/openwrt/packages/blob/master/net/dnscrypt-proxy/Makefile) `dnscrypt` package from Entware five years ago and still maintain it. They put resolvers list to separate package but there's no any signature verification used. Looks like `minisign` will be useless for us, sorry.
