### ISSUE TITLE
Package upgrade: netatalk 3.x

### ISSUE THREAD

**Issue by ryzhovau** [Entware-ng/Entware-ng#50]
http://forums.zyxmon.org/viewtopic.php?p=13659#p13659 (Russian).
Requested by @tsynik.

**Comment by zyxmon** [comment]
+1 from qnap forum

**Comment by thomkaufmann** [comment]
+1

**Comment by ryzhovau** [comment]
Done. Binaries will arrive soon.

**Comment by tsynik** [comment]
With knife it works ;-) files in /opt/etc [afp.conf extmap.conf] have wrong permissions (should be 644), and init script have illegal option "-c 7". Not tested much, but with basic config and guest authentication I can access share and read / write to it.

**Comment by tsynik** [comment]
Authorization also works, if user can manage /etc/passwd file: AFP ignores /etc/shadow, and use passwords from /etc/passwd.

**Comment by tsynik** [comment]
minor issue with current build:
it have bogus init.d startup script /opt/etc/init.d/S27afpd, which doesn't start after update.
"-с 7" option is not valid anymore. it must be "-d" or "-d -F /opt/etc/afp.conf"
