### ISSUE TITLE
Request: opus-tools: opusenc with flac support

### ISSUE THREAD

**Issue by gorgobacka** [Entware-ng/Entware-ng#500]
Both tools are in your repository: opus-tools and libflac and it's also the newest version.

But I would like to convert FLAC files to OPUS files, but it seems that opusenc does not recognize the installed libflac libraries.

Is the error on my end or is the installed opus-tools not compiled with flac support? If it's the latter, I would like to make a request for this.

It would be really useful for me. Thanks in advance.

**Comment by zyxmon** [comment]
@gorgobacka For some reason openwrt developers disabled flac support - https://github.com/openwrt/packages/blob/master/utils/opus-tools/Makefile#L40

We will enable it after it is enabled in openwrt.

**Comment by gorgobacka** [comment]
Thanks for letting me know. Now I also opened an issues on openwrt: https://github.com/openwrt/packages/issues/3772

**Comment by gorgobacka** [comment]
@zyxmon 
I asked on openwrt and they mentioned that they do not plan to add it to opus-tools, since the same can be archived with ffmpeg. However it seems that your ffmpeg is not compiled with --enable-libopus (you can check with ffmpeg -version). Therefor, I'm still not able to encode files in opus. However, it seems that the openwrt package is compiled with libffmpeg-full by default and it should be possible to encode with opus (as far as they know).

Can you please check, where opus can be enabled that I'm be able encode those files? Since I have no idea where I have to look at.

**Comment by zyxmon** [comment]
@gorgobacka we build ffmpeg with the same options as on openwrt and include opus with full version - https://github.com/Entware-ng/entware-packages/blob/master/multimedia/ffmpeg/Makefile#L436
Your firmware has another ffmpeg, probably built without opus support. Specify the correct path when you want to run entware ffmpeg version.
