### ISSUE TITLE
Package Request:  MariaDB or MySQL 5.5.0 or newer

### ISSUE THREAD

**Issue by infecticide** [Entware-ng/Entware-ng#501]
phpmyadmin will no longer manage MySQL instances earlier than 5.5.0

MariaDB is a fork of MySQL with some extra engine types and it 100% backwards compatible with MySQL.

**Comment by ryzhovau** [comment]
Can't say MariaDB is cross-compilation friendly. 
Please, [ask upstream](https://github.com/openwrt/packages/issues) for MySQL update,

**Comment by zyxmon** [comment]
FYI - https://github.com/openwrt/packages/issues/2506
