### ISSUE TITLE
Package request: imagemagick-svg / librsvg

### ISSUE THREAD

**Issue by moontear** [Entware-ng/Entware-ng#504]
Imagemagick with SVG support would be great. Usually installation is done like so:

`brew reinstall imagemagick --with-libsrvg librsvg --use-rsvg`

After installing SVG you get the following:
```
convert -list format | grep SVG
     MSVG  SVG       rw+   ImageMagick's own SVG internal renderer
      SVG  SVG       rw+   Scalable Vector Graphics (XML 2.9.0)
     SVGZ  SVG       rw+   Compressed Scalable Vector Graphics (XML 2.9.0)
```
and the svg delegate is `svg =>          "rsvg-convert" -o "%o" "%i"`.

Any chance of adding an `imagemagick-svg` package similar to `png`, `jpeg`, and `tiff` we already have? I suppose that `librsvg2` would also be needed?

**Comment by ryzhovau** [comment]
`Imagemagick` package is taken from [upstream](https://github.com/openwrt/packages) with no any changes. Please, ask them for new features.

**Comment by moontear** [comment]
I'm pretty much looking for librsvg, I could compile imagemagick again myself. librsvg would also come from upstream? OpenWRT has the librsvg library here: https://dev.openwrt.org/browser/packages/XOrg/lib/librsvg can't find it on GitHub.
