### ISSUE TITLE
vtun not working

### ISSUE THREAD

**Issue by valz77** [Entware-ng/Entware-ng#506]
vtun - 3.0.4-1 on arm7 doesn't work. Il logs the following error:

`connecting to 192.168.1.1[30598]: Couldn't run up commands: fork() not available`

**Comment by zyxmon** [comment]
please check this one
http://pkg.entware.net/binaries/armv7/test/vtun_3.0.4-2_armv7soft.ipk

**Comment by valz77** [comment]
It works! Thanks.
