### ISSUE TITLE
Package hdparm missing symbols

### ISSUE THREAD

**Issue by koitsu** [Entware-ng/Entware-ng#508]
Issue 100% reproducible on TomatoUSB (tomato-RT-N66U_0511Toastman-RT-AC-VPN.trx, MIPS architecture, Linux kernel 2.6.22).  Ignore the missing sense data line, and instead note the symbol issues:

root@gw:/proc/scsi/usb-storage# hdparm -Tt /dev/sdb

/dev/sdb:
 Timing cached reads:   268 MB in  2.01 seconds = 133.07 MB/sec
hdparm: can't resolve symbol 'munlockall' in lib 'hdparm'.
root@gw:/proc/scsi/usb-storage# hdparm -v /dev/sdb

/dev/sdb:
SG_IO: bad/missing sense data, sb[]:  70 00 05 00 00 00 00 0a 00 00 00 00 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 multcount     =  0 (off)
 readonly      =  0 (off)
 readahead     = 256 (on)
hdparm: can't resolve symbol 'gnu_dev_major' in lib 'hdparm'.

**Comment by zyxmon** [comment]
Thanks for reporting. The updated hdparm_9.50-1a will be available soon. 
Please report after updating.

**Comment by koitsu** [comment]
Will do. Thank you!

**Comment by koitsu** [comment]
Looks good after commit 40f05d3 (the SG_IO sense data error is irrelevant), thanks!

```
root@gw:/tmp/home/root# opkg upgrade
Upgrading hdparm on root from 9.50-1 to 9.50-1a...
Downloading http://pkg.entware.net/binaries/mipsel/hdparm_9.50-1a_mipselsf.ipk.
Configuring hdparm.
root@gw:/tmp/home/root# hdparm -Tt /dev/sdb

/dev/sdb:
 Timing cached reads:   270 MB in  2.01 seconds = 134.33 MB/sec
 Timing buffered disk reads:  80 MB in  3.00 seconds =  26.63 MB/sec
root@gw:/tmp/home/root# hdparm -v /dev/sdb

/dev/sdb:
SG_IO: bad/missing sense data, sb[]:  70 00 05 00 00 00 00 0a 00 00 00 00 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 multcount     =  0 (off)
 readonly      =  0 (off)
 readahead     = 256 (on)
 geometry      = 61035/64/32, sectors = 124999680, start = 0
```
