### ISSUE TITLE
opkg update error: wget: can't handle reloc type 47

### ISSUE THREAD

**Issue by pcuzn** [Entware-ng/Entware-ng#509]
I think I installed entware-ng on my device successfully. When I did opkg update, I got following message:

~ # opkg update
Downloading http://pkg.entware.net/binaries/mipsel/Packages.gz.

wget: can't handle reloc type 47
 Collected errors:
 * opkg_download: Failed to download http://pkg.entware.net/binaries/mipsel/Packages.gz, wget returned 1.

Anyone know how to solve this problem?
screenshot: http://i.imgur.com/OpTHOsn.png

**Comment by zyxmon** [comment]
my guess the environment on your (unknown) device is incompatible with entware. Probably you have LD_LIBRARY_PATH or LD_PRELOAD in it.
Please try to unset these variables and try once more. If this helps you can unset them in `/opt/etc/profile`. There can be other reasons and solutions for your device.

**Comment by pcuzn** [comment]
Right. It has to do with the ld stuff... I tried to unset LD_LIBRARY_PATH and LD_PRELOAD but it still not worked. Actually the installer.sh already unset them for me. Then I removed this part in the installer:

`echo 'Info: Basic packages installation...'
opkg update
opkg install ldconfig findutils
ldconfig > /dev/null 2>&1
[ -f /etc/TZ ] && ln -sf /etc/TZ /opt/etc/TZ`

and it worked fine. Now I can install aria2 1.28 on my device.

I am not familiar with Linux so I can't explain this. Could you tell me what does "ldconfig > /dev/null 2>&1
[ -f /etc/TZ ] && ln -sf /etc/TZ /opt/etc/TZ`" do? (I know it is related to updating ld.cache but I really don't know these bash command)

Additional info: 
my device is HD300A (rtd1073 chip)
installer link: http://pkg.entware.net/binaries/mipsel/installer/installer.sh

**Comment by zyxmon** [comment]
You can google for what ldconfig is for.
My guess is - your firmware /etc/TZ file is binary and is not compatible with some entware binaries.
In this case your solution is here - https://github.com/Entware-ng/Entware-ng/wiki/Using-time-zones and you need to set /opt/etc/TZ file just after normal installation.
