### ISSUE TITLE
"file" executable ends with Segmentation fault

### ISSUE THREAD

**Issue by JGrana01** [Entware-ng/Entware-ng#51]
Executing the "file" command, a correct response if given but then Segmentation fault occurs. It does not matter what type of file examined.

Running on RT-AC88U, armv7, Asuswrt-merlin 380.57_alpha3

**Comment by zyxmon** [comment]
```
[~] # file index_default.html
index_default.html: HTML document, UTF-8 Unicode text, with CRLF line terminators
```
Tested on armv5 (QNAP running firmaware 4.2). No problems.

**Comment by ryzhovau** [comment]
No response.
