### ISSUE TITLE
mkvtoolnix broken

### ISSUE THREAD

**Issue by handfrog** [Entware-ng/Entware-ng#511]
Hi,

I am happily using entware-ng on my Qnap TS-496L and just installed the new mkvtoolnix 9.6.0.
There are shared librarys missing for mkvmerge to run: libboost_regex.so.1.62.0, libboost_filesystem.so.1.62.0 and libboost_system.so.1.62.0. All theseare avaiable in version 1.61.0 but 1.62.0 is needed.
The package boost itself already is available as 1.62.0, but it has no files.

Could you please add boost-regex (1.62.0), boost-filesystem (1.62.0) and boost-system (1.62.0)?

Error messages and opkg info for all packages:
[http://pastebin.com/LDCkT01y](http://pastebin.com/LDCkT01y)

Thanks a lot in advance, you are doing a great job!

handfrog

**Comment by zyxmon** [comment]
The repository has boost 1.62 libs. I am afraid your /opt/lib/opkg/status file is corrupted. May be it happened after some manual packet installation. Remove all boost* blocks from it in any text editor and run `opkg install --force-reinstall mkvtoolnix`. It will fix the problem.

**Comment by zyxmon** [comment]
More info on the issue - https://github.com/Entware-ng/Entware-ng/issues/514#issuecomment-272693101
