### ISSUE TITLE
I did package update myself, is this ok?

### ISSUE THREAD

**Issue by odkrys** [Entware-ng/Entware-ng#512]
I have done squid 4.0 update.
I changed some of feeds files and it worked.
But I don't have confidence.

Make file 

PKG_VERSION:=4.0.17-20170107-r14967
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=http://www.squid-cache.org/Versions/v4/
PKG_MD5SUM:=8ab647dba66b78fe8fc8bc7a63502601
DEPENDS:=+libopenssl +libpthread +librt +libltdl +libstdcpp +libatomic (I added libatomic)

After this, some errors occurred.
so I disabled 3rd hunk of 001-cross_compile.patch and 1st hunk of 100-mime.patch like this.

;@@ -28314,3 +28314,3 @@ else
; $as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
;-as_fn_error $? "cannot run test program while cross compiling
;+_as_fn_error $? "cannot run test program while cross compiling
; See \`config.log' for more details" "$LINENO" 5; }

;@@ -1,20 +1,3 @@
; \.gif$			        image/gif		       silk/image.png			-	image	+download
; \.mime$			www/mime		silk/page_white_text.png	-	ascii	+download
; ^internal-dirup$	-			silk/arrow_up.png

I made ipk file successfully.
Is there any problem?

**Comment by ryzhovau** [comment]
This is not a help desk, sorry.

Please, test package on your own to find out how it's working.

**Comment by vikkr** [comment]
Hi @odkrys 
Can you please let me know how you compiled squid-4. I have tried 4.0.17 on Ubuntu, Debian and MacOS using Openwrt buildtools. It keeps failing in all of them.

**Comment by zyxmon** [comment]
@vikkr - have you read the wiki 
https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources

**Comment by vikkr** [comment]
@zyxmon 
Yes, I can compile everything else, except squid. All versions including 3.5 and 4.0 ends in compile error. Something to do with C++11 support and openssl, I reckon. The compile fails once it enters the ssl directory.

**Comment by odkrys** [comment]
https://drive.google.com/open?id=0B8M42Lfei1mjaU4zMXJTNGJzU2M

makefile, patches, and ipk if you need it. Maybe it seems 4.0 need some more patch.
When I turn off squid, I have to try several times.
/opt/etc/init.d/S22squid stop 
again 
/opt/etc/init.d/S22squid stop 
again 
/opt/etc/init.d/S22squid stop
lol

**Comment by vikkr** [comment]
To shutdown, you can try
/opt/sbin/squid -k shutdown
works for me in 3.5

**Comment by odkrys** [comment]
Yeah, I just run 'killall squid'  ' -';

here is some trick to auto start squid when router reboot.
squid need a permission for /dev/shm.

nano /jffs/scripts/init-start

-----------------------------------------------------------------------------
echo "shm /dev/shm tmpfs nodev,nosuid,noexec 0 0" >> /etc/fstab
-----------------------------------------------------------------------------

nano /jffs/scripts/post-mount

--------------
mount shm
--------------

**Comment by vikkr** [comment]
Hi @odkrys
I tested the build 4.0.17 14967. It's working well, has fixed several issues in 3.5. 

Squid released v 4.0.18 today. Can you please compile and send again? Apologies my openwrt build env is still producing compile errors.

**Comment by odkrys** [comment]
https://drive.google.com/file/d/0B8M42Lfei1mjQTJ4d0dzSjNudEE/view
This is the last, because I am not a developer of this repo.
make sure your entware build tool again.
good luck.
