### ISSUE TITLE
Package Request: pdnsd

### ISSUE THREAD

**Issue by plutoid** [Entware-ng/Entware-ng#513]
hi,

It's very appreciating for adding pdnsd for mips arch!

also I have found as below, the first repo url seems doesn't work any more, it's pity, the other one is its homepage, hope this will help. :)
https://gitorious.org/pdnsd/pdnsd
http://members.home.nl/p.a.rombouts/pdnsd/dl.html

Regards,
Hua

**Comment by plutoid** [comment]
also I have found as below, the first repo url seems doesn't work any more, it's pity, the other one is its homepage, hope this will help. :)
https://gitorious.org/pdnsd/pdnsd
http://members.home.nl/p.a.rombouts/pdnsd/dl.html

**Comment by ryzhovau** [comment]
Duplicate of #408.
