### ISSUE TITLE
shadowvpn source is unavailable

### ISSUE THREAD

**Issue by davygravy** [Entware-ng/Entware-ng#516]
Trying several times, I believe that the source (via github) for shadowvpn is unavailable.

I have successfully built the package with an alternate github source.   I have --not-- tested the binary, and I do not know the history behind the choice of the original github repository:  <<  https://github.com/GFW-Fucker/ShadowVPN.git  >>

In English, that is --quite-- the name!

**Comment by ryzhovau** [comment]
[Original repository](https://github.com/clowwindy/ShadowVPN) was removed according Chinese government regulation. Now this one is removed too for unknown reasons. I'll ask some of Chinese users what to do about that, not sure I'm ready to play those "hide and seek" forever.

**Comment by ryzhovau** [comment]
Thanks for PR. Checked old and new sources which is seems to be the same.
Merged.
