### ISSUE TITLE
package request ... pear

### ISSUE THREAD

**Issue by qbox4u** [Entware-ng/Entware-ng#520]
Hy

Again an request for something generic
php-pear
info at https://pear.php.net/

previously we could use the following to bypass an nasty mediawiki issue
# [/] ipkg update
# [/] ipkg install php-pear
# [/] pear install Mail-1.3.0
# [/] pear install Net_SMTP

i know that for separate modules i need an additional request , but i don't want to 
bulk additional requests  whenever you don't like to accept the basic installer request
for php-pear, other correlated requests are only polluting your side ^_^
(see https://pear.php.net/packages.php)

the use is simple
modify qnap php.ini file ( Applications/Web server/php.ini maintenance)
include_path = ".:/etc/config/php:/opt/share/pear"

Add in mediawiki localsettings.php
$wgSMTP = array(
        'host' => 'ssl://smtp.gmail.com',
        'IDHost' => 'qbox4u.com', ( or whatever side you have )
        'port' => 465,
        'username' => 'qbox4u@gmail.com',
        'password' => 'xxxxxxxxxxxxxxxxx',
        'auth' => true
);
thanks in advance for an reply

My sysinfo
Qnap ts459Pro II
QBox4u.com
Linux EUV001 3.4.6 #1 SMP Wed Dec 14 01:35:35 CST 2016 x86_64 GNU/Linux

**Comment by ryzhovau** [comment]
PHP packages brought from [upstream](https://github.com/openwrt/packages/tree/master/lang) with minimal changes and we won't rework it without heavy reasons, sorry.

Ask upstream for new PHP extensions and we'll add it after next sync.
