### ISSUE TITLE
Sync bind with owrt since changes

### ISSUE THREAD

**Issue by jamesmacwhite** [Entware-ng/Entware-ng#521]
@ryzhovau @zyxmon

I recently asked for the bind package from upstream to have  `--enable-filter-aaaa` enabled by default. This has now been committed to the openwrt/packages source.

https://github.com/openwrt/packages/commit/909209e7531de2ea63f1f298adce985406d8ba08

Would it be possible to sync Entware-ng with this change so the package is built with the option on?

Thanks!

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/Entware-ng/wiki#internals

**Comment by jamesmacwhite** [comment]
@ryzhovau Thanks for the information. Just to confirm, you are referring to this:

> We sync our sources with OpenWrt feeds and update our own packages approx. once per month, catching bugs and adding some enhancements all other time.

Implying on the next sync the changes will be in the bind package?

**Comment by ryzhovau** [comment]
Yes, that's right.

**Comment by jamesmacwhite** [comment]
@ryzhovau Many thanks! I'll await the next scheduled owrt sync.
