### ISSUE TITLE
subversion error on Qnap TS-212

### ISSUE THREAD

**Issue by gverlicchi** [Entware-ng/Entware-ng#523]
On Qnap TS-212 I have installed subversion-server and subversion client. I have created a repository on qnap and i checkout this in local: svn co file:///path_to_repo
I try to add a file throw svn add, but the command is aborted unexpectedly:

path_to_checkout# svn add filename
Aborted

Svn status command show dot folder (path to checkout) whit L
I'm forced to do svn cleanup, but the file not added.

**Comment by zyxmon** [comment]
Try to install file package `opkg install file`

**Comment by gverlicchi** [comment]
File package installed.... Problem resolved. Thank you.
