### ISSUE TITLE
Package update request:   Tor / Dnscrypt-proxy / Cryptsetup

### ISSUE THREAD

**Issue by blackfuel** [Entware-ng/Entware-ng#526]
tor-0.2.9.9
dnscrypt-proxy-1.9.4
cryptsetup-1.7.3

Thank you.

**Comment by cerberii** [comment]
please update tor.  Some reason old version entering race condition and consuming 99% resources.

**Comment by ryzhovau** [comment]
tor 0.2.9.8, cryptsetup 1.7.2, dnscrypt-proxy1.9.1 arrived during month sync. This packages taken from [upstream](https://github.com/openwrt/packages) with no any changes. If you want too see newer versions of this packages, please, ask them for update.
