### ISSUE TITLE
Entware on Qnap TS-212 Init script

### ISSUE THREAD

**Issue by gverlicchi** [Entware-ng/Entware-ng#527]
I installed Entware from Qnapclub Store IT repository.
After installation in /etc/init.d/Entware-ng.sh there are this rows:

/bin/cat /root/.profile | /bin/grep "source" 1>>/dev/null 2>>/dev/null
[ $? -ne 0 ] && /bin/echo "source /opt/etc/profile" >> /root/.profile

If you have an autorun script that add any other source on /root/.profile the entware init script not add his source. First row should be:

/bin/cat /root/.profile | /bin/grep "source /opt/etc/profile" 1>>/dev/null 2>>/dev/null

**Comment by ryzhovau** [comment]
Not related to repo itself, so I'm closing this, sorry.
