### ISSUE TITLE
Package update request : Nginx with ngx_http_gzip_static_module

### ISSUE THREAD

**Issue by Every0ne** [Entware-ng/Entware-ng#528]
Could you compile nginx with the `--with-http_gzip_static_module` option? This would allow to serve gzip pre-compressed assets. Note - in this case nginx **does not** compress anything, it just checks if a file has a .gz'ipped version and serves this one instead. IMHO it's a great feature when it comes to serving webpages from home routers, where the outgoing bandwidth is usually very limited.

**Comment by ryzhovau** [comment]
Please, send this issues to [upstream](https://github.com/openwrt/packages/issues). New package will arrive here in next month.
