### ISSUE TITLE
Samba package update request

### ISSUE THREAD

**Issue by amanzone** [Entware-ng/Entware-ng#529]
Hello and thanks for the outstanding job you're doing.

As far as I can understand the samba-server package does not allow the use of the tdbsam backend (I imagine only the smbpasswd backend is allowed).
Do you think it would be possible to include support for the tdbsam backend?

Thank you in advance your your reply.

Regards,
A.

**Comment by ryzhovau** [comment]
The current SAMBA version was chosen in compromise between it's speed, simplicity and features number. Please, send this issue to [upstream ](https://github.com/openwrt/openwrt/issues) if you wish. If package will be updated there, it will arrive here in next month.
