### ISSUE TITLE
Package Request autojump

### ISSUE THREAD

**Issue by graysky2** [Entware-ng/Entware-ng#53]
Please consider adding a very powerful directory navigator called [autojump](https://github.com/wting/autojump).  All of the depenedencies are already available in this repo.

Thanks!

**Comment by ryzhovau** [comment]
It doesn't support `ash` - a default shell for 99% of small systems.
Python dependency is the second reason against this utility.

Not sure it's handy for embedded systems, sorry.

**Comment by graysky2** [comment]
OK, thank you for checking into the possibility and for the work you on with entware!
