### ISSUE TITLE
Can't invoke busybox binary by itself

### ISSUE THREAD

**Issue by shunjou** [Entware-ng/Entware-ng#530]
Upgraded busybox from 1.24.2-1 to 1.25.1-2 on armv5 device and now encounter error "busybox: applet not found" when invoking the busybox binary as `busybox`. Intended behavior is a print out of version, usage, and all included applets which was present in the previous version. All other applets appear to be functioning fine otherwise.

Is something wrong with the updated binary or is the issue somehow on my end?

**Comment by shunjou** [comment]
I realize this is probably because the synced config from lede has BUSYBOX_DEFAULT_BUSYBOX set to n. I can't imagine the space savings being that significant, so is it possible to revert this to the previous behavior?

**Comment by zyxmon** [comment]
It is setup by CONFIG_BUSYBOX_CONFIG_BUSYBOX variable. Now fixed in https://github.com/Entware-ng/Entware-ng/commit/90c0057b30747cf5e4e260ef76bf13a353ee3e24
