### ISSUE TITLE
Package Request: php7-mod-imap

### ISSUE THREAD

**Issue by jozefp83** [Entware-ng/Entware-ng#534]
Hi
  Could you add the imap support for php?
Thanks

**Comment by patrikx3** [comment]
just so you know, nginx/apache/openvpn/letsenrypt/php even nodejs thoguh old is still cool, but like mail/email/mysql it is a bit too much, a cheap server is better!!! just so you know!
i tried all but i kept nginx/php/openvpn then i am adding my own small server with debian...
mysql is not required.

though jsut php7-mod-imap is cool! you are right!!!

**Comment by ryzhovau** [comment]
No plans to add it, sorry.
