### ISSUE TITLE
Package Request: rclone (update to 1.35)

### ISSUE THREAD

**Issue by AntSanDev** [Entware-ng/Entware-ng#537]
Hi there,

Just wondering if it were possible to update rclone to the last version. It includes the crypt option.

Thanks a lot and keep it up!

**Comment by zyxmon** [comment]
Dublicate - https://github.com/Entware-ng/Entware-ng/issues/380
https://github.com/Entware-ng/Entware-ng/issues/390

We are working now and try native go 1.8 beta version, that supports mips(le)32. I have already tested new rclone  on mipsel router - it works!
