### ISSUE TITLE
Custom DNSCrypt-Proxy Server

### ISSUE THREAD

**Issue by SquirrelCoder** [Entware-ng/Entware-ng#539]
### Package: dnscrypt-proxy

Hello, 

Is it possible to use my own DNSCrypt Proxy server? I have a dnscrypt proxy server, but it's not for public use, and the only person using it, is me, so I wanted to know where can I add the details about my server?

Thanks a lot.

UPDATE1: Okay, So I have found where the resolver list is, `nano /opt/share/dnscrypt-proxy/dnscrypt-resolvers.csv` and I have edited this file and added my own resolver to the list, and added the name I have give to my resolver here `nano /opt/etc/init.d/S09dnscrypt-proxy` , but the service does Not start!

**Comment by ryzhovau** [comment]
Not related to repo, sorry.

**Comment by SquirrelCoder** [comment]
Sorry man, for asking in the wrong repo. :(
Could you please guide me, where I can ask this question?

Thanks.

**Comment by odkrys** [comment]
You can easily edit the csv file in the window network smb.
match the form like others.
Name, DNSSEC validation, No logs, Namecoin, Resolver address, Provider public key
are need.
