### ISSUE TITLE
timezone damaged after install busybox

### ISSUE THREAD

**Issue by cmheia** [Entware-ng/Entware-ng#54]
I Installed Entware-ng on a TomatoUSB with a mipsel router.
After install busybox, 'date -R' always retern with +0000, although I already set to GMT+08:00 from web.
I'm try to download a binary from busybox.net and override /opt/bin/busybox from entware, the problem is gone.

**Comment by zyxmon** [comment]
The way timezone is set is different for different devices. You can try the following procedure:

1. install zoneinfo package. For Europe:

```
opkg install zoneinfo-europe
```

2. Create symlink (for example for Moscow)

```
ln -sf /opt/share/zoneinfo/Europe/Moscow  /etc/localtime 
```

Check that everything works correctly.

3. Create a script, that makes a symlink at boot: /opt/etc/init.d/S00timezone

```
#!/bin/sh

start() {
    ln -sf /opt/share/zoneinfo/Europe/Moscow  /etc/localtime
}
    
stop() {
    rm -rf /etc/localtime
}
    
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 2
        start
    ;;
    *)
    echo "Usage: $0 {start|stop}"
    ;;
esac
```
This works for me on Tomato.

**Comment by cmheia** [comment]
Thanks for your work. I tried it, but it didn't work for me.
I'm tring to find out why by read the makefile.

**Comment by zyxmon** [comment]
For mipsel it may be different. If you have a file /etc/TZ - just copy it to /opt/etc/TZ

If you do not have it, just create it: `echo UCT-8 > /opt/etc/TZ`

**Comment by cmheia** [comment]
It Works! Thanks for your help.
Finally I chose this method.
```
ln -s /etc/TZ /opt/etc/TZ
```

**Comment by ryzhovau** [comment]
It'd definitely worth of separate wiki article.
https://github.com/Entware-ng/Entware-ng/wiki/Using-time-zones
