### ISSUE TITLE
Removing Entware-ng from the QNAP App Center removes /opt symlink in the root

### ISSUE THREAD

**Issue by mmortal03** [Entware-ng/Entware-ng#542]
I manually installed Entware-ng from the qpkg (Entware-ng_0.97.qpkg) by way of the QNAP App Center gear menu and later removed it from within the QNAP App Center. After doing this, the /opt symlink in the root directory of the NAS was removed. I noticed this because, afterwards, I was trying to install Optware-ng into the /opt symlink from a putty session, and it was missing. I also noticed that after re-installing Entware-ng that the symlink was generated again.

### Platform:

QNAP TS-220

**Comment by zyxmon** [comment]
That is correct. This is the same for Optware qpkg and probably other qpkg's, that use /opt. If Optware-ng installer needs /opt - create it or reboot your NAS.
