### ISSUE TITLE
Package update request: youtube-dl

### ISSUE THREAD

**Issue by happyharrysco1** [Entware-ng/Entware-ng#546]
### Package: youtube-dl

please can you update youtube-dl to a more recent release, the current included release no longer works as intended and a fix has already been pushed upstream

thanks in advance

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/entware-packages/commit/c1e57522f030de21b962ac305dbd2d0818ec919e
Binaries will be available soon

**Comment by happyharrysco1** [comment]
many thanks :)
