### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by blade3609** [Entware-ng/Entware-ng#547]
### Package: <name>

For existing package:

- expected behavior: successful compilation of toolchain.
- actual behavior: failed to compile

checking for clock_t... yes
checking for F_SETLKW... yes
checking if mkdir takes one argument... no
*** Configuration arm-openwrt-linux-gnu not supported
Makefile:4065: recipe for target 'configure-gcc' failed
make[3]: *** [configure-gcc] Error 1
make[3]: Leaving directory '/home/user/Entware-ng/build_dir/toolchain-arm_cortex-a9_gcc-6.3.0_-_eabi/gcc-6.3.0-minimal'
Makefile:46: recipe for target '/home/user/Entware-ng/build_dir/toolchain-arm_cortex-a9_gcc-6.3.0_-_eabi/gcc-6.3.0-minimal/.built' failed
make[2]: *** [/home/user/Entware-ng/build_dir/toolchain-arm_cortex-a9_gcc-6.3.0_-_eabi/gcc-6.3.0-minimal/.built] Error 2
make[2]: Leaving directory '/home/user/Entware-ng/toolchain/gcc/minimal'
toolchain/Makefile:81: recipe for target 'toolchain/gcc/minimal/compile' failed
make[1]: *** [toolchain/gcc/minimal/compile] Error 2
make[1]: Leaving directory '/home/user/Entware-ng'
/home/user/Entware-ng/include/toplevel.mk:194: recipe for target 'toolchain/install' failed
make: *** [toolchain/install] Error 2

any ideas?
I even tried an older version of the git.
openwrt toolchain compiles just fine. 

### Platform:

- Ubuntu 64 bit

-

**Comment by zyxmon** [comment]
The buildroot was under heavy development in February. Now there are no compilation problems in Debian Jessie/64. This looks weired 

>> checking if mkdir takes one argument... no

Try to google on this error.

**Comment by blade3609** [comment]
What command do you use to compile? 
When compiling for example with command make toolchain/install 

It does not give me the option to chose which version of some stuff it installs, how do i do that? 

I'll google to issue and see if i find something, ill try it with Debian also again and keep you posted.

**Comment by zyxmon** [comment]
Everything is configured through `make menuconfig` command.

**Comment by blade3609** [comment]
I dont see anywhere i can configure the versioning of for example binutils in the make menuconfig, where is it located?

**Comment by zyxmon** [comment]
@blade3609 - it is in the same place as in openwrt. Please use the sample configs in  configs subfolder. We save the configurations that do compile and are used to build binary repos.

**Comment by blade3609** [comment]
Got it to work man! thanks. The error also didn't return.

now im going to try to compile snmpd with perl support

**Comment by blade3609** [comment]
I changed the Makefile of snmpd .added , CONFIGURE_ARGS += \
        --enable-embedded-perl \
        --enable-shared \

compiled it successfully and installed it on arm.

but i still get Feb 11 01:56:43 snmpd[17070]: /opt/etc/snmp/snmpd.conf: line 19: Warning: Unknown token: perl.

Do you have any ideas?

**Comment by zyxmon** [comment]
Compilation problems solved. Closing.
