### ISSUE TITLE
arm5 bacula 7.4.4 console not working

### ISSUE THREAD

**Issue by saschadd** [Entware-ng/Entware-ng#548]
### Package: bacula

For existing package:

- expected behavior: 
console not really working. console is connecting to director successfully but when i enter any command i get -sh: <command>: not found (example: -sh: list: not found).
- actual behavior: 
It might be already an failure that bconsole command ends up at *user@nas and not just * but maybe i am wrong.

I double checked all config files and bacula is actually working but i am not able to use the console function.

### Platform:
i am using it on nsa325v2 http://zyxel.nas-central.org/wiki/Category:NSA-325 an arm5 device.

**Comment by zyxmon** [comment]
What is the kernel version on your NAS?
You can try to debug the issue with strace (opkg install strace). If you find the call that fails that causes the issue - please report.

**Comment by saschadd** [comment]
cat /proc/version gives me
Linux version 2.6.31.8
gcc version 4.3.2 (sdk3.3-ct-ng-1.4.1)

strace gives me some (no file or directory) and one (function not implemented) errors.
I am not sure if i understand the strace log correct but it looks like bconsole is dying just after connecting.
Would it help if i post the output?

**Comment by zyxmon** [comment]
>> Linux version 2.6.31.8
The kernel version used for armv5 feed is 2.6.32 - this may be the reason of function not implemented errors. You can post the output on http://pastebin.com/index.php (no registration is required) and give a link here. I am closing the issue.

**Comment by saschadd** [comment]
i posted the strace log http://pastebin.com/4PMxLH2Q
