### ISSUE TITLE
Package Request: Numpy, Sklearn and Scipy for Synology NAS x86_64

### ISSUE THREAD

**Issue by PurpleZool** [Entware-ng/Entware-ng#549]
### Package: Scikit-learn( Numpy, Sklearn, matplotlib)

It will be great for ml developing, data analitycs and other weight maths operations support the adding of these libraries giving us the possibility of compute huge matrices in low sized elements I. E. as well to train machine learning algorithms in a low powered device.

- Since newer versions of GCC ( above 4.9 )havent got GCC-ar , GCC-nm and GCC-ranlib it's imposible to compile them  in a native Python at least for us.

### Platform:

- Python 2.7 , Python 3 in a Synology NAS DSM6.

### Thank you for your work, this will be so helpfull for a lot of devs

**Comment by zyxmon** [comment]
binutils has ar, nm and ranlib:

```
~ # opkg files binutils
Package binutils (2.27-1) is installed on root and has the following files:
/opt/bin/addr2line
/opt/bin/objcopy
/opt/bin/ld
/opt/bin/ranlib
/opt/bin/nm
/opt/bin/readelf
/opt/bin/elfedit
/opt/bin/strip
/opt/bin/as
/opt/bin/ld.bfd
/opt/bin/gprof
/opt/bin/strings
/opt/bin/c++filt
/opt/bin/size
```

You can try to build your application using wiki - https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-python-modules

**Comment by zyxmon** [comment]
No response.
