### ISSUE TITLE
Package request: nzbget 16.4

### ISSUE THREAD

**Issue by mcroach** [Entware-ng/Entware-ng#55]
Please update nzbget package to version 16.4 (latest release as of 2015/12/09.

Package: nzbget
Version: 15.0-1
Depends: libc, libssp, librt, libpthread, libxml2, libopenssl, libncurses, libstdcpp
Status: install user installed
Section: net
Architecture: x86-64
Maintainer: Artur Wronowski <arteqw@gmail.com>
MD5Sum: c1eaf9988d48e39d0e62921cf848ca8e
Size: 847115
Filename: nzbget_15.0-1_x86-64.ipk
Conffiles:
 /opt/share/nzbget/nzbget.conf b6e5ff14efe5933a043a8d799c384d3589
Source: feeds/oldports/nzbget
Description: A command-line client/server based binary newsgrabber for nzb-files.

**Comment by zyxmon** [comment]
http://entware.net/binaries/x86-64/test/nzbget_16.4-1_x86-64.ipk

please test and report

**Comment by mcroach** [comment]
Appears to be working as expected on my QNAP TVS-671 (Intel Core i5-4590S, QTS 4.2.0 build 20151118) and picked right up were the older 15.0-1 version left off.

Only issue reported during install was as follows; this particular nzbget.conf file is not supposed to be changed by the user as its a template file for the WebUI; it should be safe to simply overwrite it.

[/tmp] # opkg install ./nzbget_16.4-1_x86-64.ipk
Upgrading nzbget on root from 15.0-1 to 16.4-1...
Configuring nzbget.
Collected errors:
 * resolve_conffiles: Existing conffile /opt/share/nzbget/nzbget.conf is different from the conffile in the new package. The new conffile will be placed at /opt/share/nzbget/nzbget.conf-opkg.

**Comment by zyxmon** [comment]
/opt/share/nzbget/nzbget.conf  is not a template. It is used as a configuration file in startup script. It would be safer not to overwrite it.
