### ISSUE TITLE
Entware installation on Asus N18U (dd-wrt) - localedef problem

### ISSUE THREAD

**Issue by poki123** [Entware-ng/Entware-ng#550]
Hello,

today I tried to install entware, on my Asus N18U router, dd-wrt (v3.0-r31221 std (02/01/17).

**I start as follow (I have internal jffs about 100MB free):**
cd /jffs
mkdir opt
cp -R /opt/* /jffs/opt/
mount -o bind /jffs/opt /opt
wget -O - http://pkg.entware.net/binaries/armv7/installer/entware_install.sh | sh

**almost at the end I got the error:**
cannot map archive header: Invalid argument
locale-archive file was not created, not enough memory? Downloading...
You can download locale sources from http://pkg.entware.net/sources/i18n_glib223.tar.gz
You can add new locales to Entware using /opt/bin/localedef.new

**as I discovered, there is problem with the following arguments:**
/opt/bin/localedef.new -c -f UTF-8 -i en_US en_US.UTF-8
/opt/bin/localedef.new -c -f UTF-8 -i ru_RU ru_RU.UTF-8
(cannot map archive header: Invalid argument)

Is it possible (or how) to solve this problem please?

**Comment by zyxmon** [comment]
This is not a problem. In your case of low memory the locales archive is downloaded and installed in `/opt/usr/lib/locale` folder. If you need to add your own locale you will need to use swap.
