### ISSUE TITLE
Package request: jpillora/Chisel for mips

### ISSUE THREAD

**Issue by gonsalez-ru** [Entware-ng/Entware-ng#551]
### Package: jpillora/chisel

https://github.com/jpillora/chisel

Chisel is a fast TCP tunnel, transported over HTTP. Single executable including both client and server. Written in Go (Golang). Chisel is mainly useful for passing through firewalls, though it can also be used to provide a secure endpoint into your network.

### Platform:
Asus RT-65U router (MIPS)

**Comment by ryzhovau** [comment]
There's only one Golang-based package in MIPS repo, just to show it's an overkill for embedded devices. Too much resources consumed by go-based soft, sorry.
