### ISSUE TITLE
Please provide libusb headers

### ISSUE THREAD

**Issue by hphde** [Entware-ng/Entware-ng#552]
### Package: libusb1

I tried to compile something against libusb but failed because of missing headers. Compiling and installing my own own libusb either ended up with with an internal error in libusb or libpthread. Not being an expert in C/C++ I ended up installing Optware-ng to get it working

### Platform:

Synology armv5 NAS

**Comment by zyxmon** [comment]
We provide all headers - https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-(native-compilation)

**Comment by hphde** [comment]
Thanks for pointing that out. Problem was that there where already at least a *few* headers in `/opt/include`. Maybe it makes sense to place a `README` in that folder that points to the Wiki.

**Comment by zyxmon** [comment]
We do not provide support for native compilation and recommend cross-compilation - https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources

**Comment by hphde** [comment]
Even more so it makes sense to provide a note at a an easy to get spot as described above, no? :)
I tried googling to find includes but did not came across the Wiki above.

**Comment by zyxmon** [comment]
ОК. Next time there will be a message displayed when gcc из installed as a package.

As for me - when I investigate a GitHub project - I always look if there are wiki and/or issues for the project.
