### ISSUE TITLE
Netdata updated to 1.5

### ISSUE THREAD

**Issue by nickwinn** [Entware-ng/Entware-ng#553]
### Package:  netdata

For existing package:
New version of netdata adds the following functionality.

* netdata now runs on FreeBSD and MacOS
* netdata now supports Graphite, OpenTSDB, Prometheus and compatible backends
* netdata now monitors systemd Services
* new plugins: fping, postgres, varnish, elasticsearch, haproxy, freeradius, mdstat, ISC dhcpd, fail2ban, openvpn, NUMA memory, CPU Idle States, gunicorn, ECC memory errors, IPC semaphores, uptime
* improved plugins: netfilter conntrack, mysql/mariadb, ipfs, cpufreq, hddtemp, sensors, nginx, nginx_log, phpfpm, redis, dovecot, containers and cgroups, disk space, apps.plugin, tc (QoS) and almost all internal plugins (memory, IPv4 and IPv6, network interfaces, QoS, etc)
* dozens of new and improved alarms (including performance monitoring alarms for mysql)
* new alarm notifications: messagebird.com, pagerduty.com, pushbullet.com, twilio.com, hipchat, kafka
* dozens more improvements and performance optimizations

### Platform:

- asus ac68u / asus merlin

**Comment by zyxmon** [comment]
We have made a lot of changes to our Entware buildroot. The packages are synced up to 2017.01.26. This update will be available in few days.
We will upgrade Netadata nex month with openwrt - https://github.com/openwrt/packages/blob/master/admin/netdata/Makefile#L11

**Comment by zyxmon** [comment]
Version 1.6 is in the repo.
