### ISSUE TITLE
make tools go-src issue

### ISSUE THREAD

**Issue by giveup** [Entware-ng/Entware-ng#554]
### Package: go-src

> run make tools/install V=s

```
/usr/local/go/src/runtime/proc.go:63 (0x15553)
/usr/local/go/src/runtime/asm_amd64.s:2232 (0x25611)
```
`go tool dist: FAILED: /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/pkg/tool/darwin_amd64/compile -pack -o /var/folders/45/_xlpn3px3j5dgzcnstj87g0h0000gn/T/go-tool-dist-661355163/cmd/go/_go_.a -p main /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/alldocs.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/bootstrap.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/bug.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/build.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/clean.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/context.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/doc.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/env.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/fix.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/fmt.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/generate.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/get.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/go11.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/help.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/list.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/main.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/note.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/pkg.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/run.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/signal.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/signal_unix.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/test.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/testflag.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/tool.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/vcs.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/version.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/vet.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/zdefaultcc.go /Volumes/Entware-dev/Entware-ng/staging_dir/host/go/src/cmd/go/zosarch.go: exit status 2

`
```
make[2]: *** [/Volumes/Entware-dev/Entware-ng/staging_dir/host/go/.built] Error 2
make[2]: Leaving directory `/Volumes/Entware-dev/Entware-ng/tools/go-src'
make[1]: *** [tools/go-src/compile] Error 2
make[1]: Leaving directory `/Volumes/Entware-dev/Entware-ng'
make: *** [tools/install] Error 2
```

> run make tools/go-src/install V=s

```
make[1]: Entering directory `/Volumes/Entware-dev/Entware-ng'
make[2]: Entering directory `/Volumes/Entware-dev/Entware-ng/tools/go-src'
make[2]: Nothing to be done for `install'.
make[2]: Leaving directory `/Volumes/Entware-dev/Entware-ng/tools/go-src'
make[1]: Leaving directory `/Volumes/Entware-dev/Entware-ng'

```

### Platform:
-  armv7.config
- Mac 10.12

**Comment by zyxmon** [comment]
MacOS is not supported. Sorry.
You can try to install go bootstrap binaries for your os to build go-src
https://github.com/Entware-ng/Entware-ng/blob/master/tools/go-bootstrap/Makefile#L17

It is better to disable manually go* in tools and go packages!
