### ISSUE TITLE
SNMPd with perl support

### ISSUE THREAD

**Issue by blade3609** [Entware-ng/Entware-ng#555]
### Package: snmpd

For existing package:

- expected behavior: snmp perl do command to extend SNMP
- actual behavior: perl do command does not work

### Platform:

- armv7

**Comment by zyxmon** [comment]
There is no snmpd package in Entware. If you mean net-snmp package it is build without perl support as in openwrt.

**Comment by blade3609** [comment]
Yes , net-snmp , could you build one with perl support?

**Comment by zyxmon** [comment]
We build packages with the same configurations as in openwrt to make synchronization of 2000+ packages as easy as possible.
