### ISSUE TITLE
minidlna: error while loading shared libraries: libavformat.so.56: cannot open shared object file

### ISSUE THREAD

**Issue by blackfuel** [Entware-ng/Entware-ng#556]
### Platform: ARM

Just a heads up, customers may have issues with a recent upgrade from ffmpeg 2.8.8 to ffmpeg 3.2.2.

My router is RT-AC68U.  I encountered this issue on Sunday (Feb. 12) when I rebuilt the entire Entware-ng repo from source and upgraded the packages on my router.  Initially, when I ran minidlna there was a missing library (libavformat.so.56).  I was able to fix the problem by uninstalling some dependencies and then re-installed minidlna.  Everything works fine now.

Here is the error:
```
minidlna: error while loading shared libraries: libavformat.so.56: cannot open shared object file: No such file or directory
```

How to fix it:
```
opkg remove libffmpegthumbnailer
opkg remove ffmpeg
opkg remove minidlna
opkg install minidlna
```

**Comment by zyxmon** [comment]
>> when I rebuilt the entire Entware-ng repo from source and upgraded the packages on my router.

There are some problems and we have not yet published the new binaries.

>> when I ran minidlna there was a missing library (libavformat.so.56).

Opkg system is not clever enough in such situations.

>> How to fix it:

We usually recommend to `opkg install --force-reinstall <package>` in such cases. This should be done for ffmpeg & libffmpegthumbnailer in this case.
