### ISSUE TITLE
lighttpd (1.4.44-1a) not working for armv5

### ISSUE THREAD

**Issue by stroetgen** [Entware-ng/Entware-ng#557]
### Package: lighttpd

lighttpd - 1.4.44-1a
lighttpd-mod-access - 1.4.44-1a
lighttpd-mod-accesslog - 1.4.44-1a
lighttpd-mod-auth - 1.4.44-1a
lighttpd-mod-authn_file - 1.4.44-1a
lighttpd-mod-cgi - 1.4.44-1a
lighttpd-mod-status - 1.4.44-1a

- expected behavior: 

server starts and serves web pages aber fresh install and fresh config

- actual behavior: 

server listens on port, but does not send any answer; 
the error.log fills with tons of lines:

2017-02-13 21:25:01: (connections.c.1036) accept failed: Function not implemented 38

No problem with previous versions.

### Platform:

QNAP TS-419P
Firmware-Version	4.2.3 Build 20170121
Linux nas1 3.4.6 #1 Sat Jan 21 10:04:08 CST 2017 armv5tel unknown

**Comment by zyxmon** [comment]
>>the error.log fills with tons of lines:

2017-02-13 21:25:01: (connections.c.1036) accept failed: Function not implemented 38

This may be fixed in 1.4.45. The new code that gives this log was rewritten. Openwrt still has 1.4.44 in repo.

**Comment by stroetgen** [comment]
Sorry, I can not confirm. Fresh upgrade to 1.4.45, still:

2017-02-14 14:54:21: (connections.c.1036) accept failed: Function not implemented 38

**Comment by zyxmon** [comment]
@stroetgen let's try once more - `opkg install --force-reinstall lighttpd`.
I have made some changes....

**Comment by stroetgen** [comment]
Excellent, no more problems. Thanks a lot!
