### ISSUE TITLE
Package upgrade request:  From 1.18.7 to 1.19.0 (stable)

### ISSUE THREAD

**Issue by famewolf** [Entware-ng/Entware-ng#56]
As mentioned in the subject this is a request to have the version of aria2 available updated from 1.18.7 to the current stable version of 1.19.0 which was released in June 2015.

aria2 1.19.0
This releases adds SFTP support, and fixes several bugs. SFTP support has been implemented using libssh2. We added several new options. --multiple-interface option is like --interface option, but can take several interfaces. They are used in round-robin manner, and it works like link aggregation. Previously, .netrc search path is fixed under $HOME directory, and cannot be changed. In this release, --netrc-path option has been added to override the search path. The runtime bug concerning getrandom has been fixed in this release. Previously if download failed because checksum error, aria2 exited with error code 1 (unknown error). Now it exits with dedicated error code 32. We fixed long outstanding bug that aria2 crashes when downloading multi-file torrent.

**Comment by ryzhovau** [comment]
The similar PR is on upstream https://github.com/openwrt/packages/pull/1920
The newer version will arrive from upstream after it will updated there.

**Comment by alienx2** [comment]
theres new version: 1.19.3...found latest version here: https://github.com/tatsuhiro-t/aria2/releases/tag/release-1.19.3

**Comment by ryzhovau** [comment]
`aria2` package is looks like abandoned in OpenWrt, so I have to update it manually.
[1.20.0 is out](https://github.com/tatsuhiro-t/aria2/commit/656800948d185f6abb46d5264c1d534df7ada360), I'll wait a few days to new [release tar ball](https://github.com/tatsuhiro-t/aria2/releases), then I'll update `aria2`. Stay tuned.

**Comment by ryzhovau** [comment]
Done.
