### ISSUE TITLE
python3.6 -m pip => pyexpat.cpython-36.so: undefined symbol: XML_SetCommentHandler

### ISSUE THREAD

**Issue by pangretor** [Entware-ng/Entware-ng#560]
Hi,

pip for python3.6 is causing the error "pyexpat.cpython-36.so: undefined symbol: XML_SetCommentHandler".
Similar to https://github.com/Entware-ng/Entware-ng/issues/485 but for 3.6 instead of 3.5.

You can see the stacktrace here:
https://hastebin.com/bulekutoxe.rb

As you can see, it is a fresh python3 install. I didn't have this issue with 3.5.

I tried to find how to "Manually downgrading python3-xml package from archive folder" but couldn't find any info.

Platform: Synology ARMv7

**Comment by ryzhovau** [comment]
Already fixed, binaries will arrive soon.
