### ISSUE TITLE
motion "FFmpeg/Libav not found on computer.  No RTSP support"

### ISSUE THREAD

**Issue by phobiac** [Entware-ng/Entware-ng#561]
### Package: motion

For existing package: motion

- expected behavior: Loading of RTSP streams using install ffmpeg
- actual behavior: motion not able to detect ffmpeg installation

### Platform: armv7

Installed on synology NAS

When attempting to use the motion package to load RTSP streams the above error is given. ffmpeg is installed and correctly runs. I did find [this suggested patch](https://forum.openwrt.org/viewtopic.php?id=56786) for openwrt but I don't have the ability to build and test it.

I'm more than willing to act as a tester if someone with more ability can provide a built package with the suggested patch or point to another way of getting motion to recognize ffmpeg as being installed.

**Comment by zyxmon** [comment]
We will apply these changes after they are accepted in the trunk (openwrt).

**Comment by joelpdb** [comment]
Hi! Is there possibly some update available on the topic? Possibly the motion package could be updated to the latest version? Thanks!

**Comment by ryzhovau** [comment]
Please, ask [upstream](https://github.com/openwrt/packages/) (OpenWrt team) for that.

**Comment by joelpdb** [comment]
Thanks, just did: https://github.com/openwrt/packages/issues/4092
