### ISSUE TITLE
Package request: php-devel, QNAP

### ISSUE THREAD

**Issue by Ewert02** [Entware-ng/Entware-ng#562]
### Package: php-devel, pecl

For new package to be added:
- php5/7-devel, to use **phpize** command. I need to install Oracle Instant Client 12, on our NAS

- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform:
-x86 (i486-openwrt-linux-gnu)

**Comment by zyxmon** [comment]
there are no *dev packages in Entware. All you can do is to install all headers from tar.gz file as described in the wiki.
Crosscompilation it the best way to build packages.

**Comment by juanjullian** [comment]
> All you can do is to install all headers from tar.gz file as described in the wiki.
Crosscompilation it the best way to build packages.

I checked all the wiki but there's no instruction on how to install headers or crosscompilation, could you post a way to compile and install php5-devel?

Thanks

**Comment by zyxmon** [comment]
There are no instaructions on creating specific packages, only general ones. You are to do ii yourself.
