### ISSUE TITLE
OpenSSH server with tcp_wrappers enabled

### ISSUE THREAD

**Issue by Quidagis** [Entware-ng/Entware-ng#563]
### Package: openssh-server

For existing package:

- expected behavior: Compiled with tcp_wrappers enabled 

- actual behavior: No compiled with tcp_wrappers enabled

### Platform:
Tomato Firmware 1.28.0000 MIPSR2-138 K26 USB Mega-VPN on Linksys E4200 v1.

**Comment by zyxmon** [comment]
Packages are build with the same configurations as in openwrt. Please ask Openwrt maintainers to change configuration. We will sync with it in a month.
