### ISSUE TITLE
Unbound Dead

### ISSUE THREAD

**Issue by uihdff** [Entware-ng/Entware-ng#565]
### Platform:
Asus RT-AC88u running Asuswrt Rmerlin 380.65

Installed Entware-NG with instructions on "https://www.hqt.ro/how-to-install-new-generation-entware/.

1. cd /tmp
2. wget -c -O entware-ngu-setup.sh http://goo.gl/hshQkA
3. chmod +x ./entware-ngu-setup.sh
4. ./entware-ngu-setup.sh

Installed on /dev/sda1 on USB drive.

When attempting to check Unbound, the following error occurs.

![check](https://cloud.githubusercontent.com/assets/22044303/23072124/97741b98-f4fe-11e6-82b9-e7bb185890a5.jpg)

Is there diagnostic information about why Entware is having trouble with this service ?

What does dead mean ?

How can you tell when an Entware installed service like Unbound is running ? Should it appear in the output of top or ps ?

**Comment by ryzhovau** [comment]
We can't support scripts which you found somewhere on internet, sorry. Please, see wiki pages to find how to deploy Entware properly.

Looks like you not configured `unbound` before running. Why?

To find out why it's "dead" take a look at `/opt/etc/init.d/S61unbound` to find which arguments passed to unbound at start and try to start it from console with this arguments.

Sure, running daemon should be appear in `ps` output.
