### ISSUE TITLE
Package Request: Suricata

### ISSUE THREAD

**Issue by RMerl** [Entware-ng/Entware-ng#566]
### Package: suricata

For new package to be added:

https://suricata-ids.org/

Suricata is an IPS/IDS, not unlike Snort.  One of its advantages is that it's multi-threaded, so it might provide better performance on a multicore device (like most modern routers).

Cross-compilation seem possible, there's a package available for OpenWRT.

**Comment by ryzhovau** [comment]
Look's too heavy for MIPS: tooks about couple of minutes to start on 64MB RAM device with all available ruleset enabled.

Please, provide a feedback. I'll be glad to see your post on SNB if `suricata` will be handy for us.

**Comment by RMerl** [comment]
I got it up and running on my RT-AC88U, had to disable a few default rules for it to fit in my RAM.  I see a bunch of tls and dns events logged in eve.json, and got one malicious IP logged in fast.log, so basic functionality seems to be working :)

It was far easier to get running than Snort so far.  I'll experiment some more with it.  Thanks!
