### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by 1688pc** [Entware-ng/Entware-ng#569]
ln: ld-linux.so.3: File exists
ln: libc.so.6: File exists
Info: Basic packages installation...
Downloading http://pkg.entware.net/binaries/armv7/Packages.gz.
Updated list of available packages in /opt/var/opkg-lists/packages.
Installing entware-opt (222108-5) to root...
Downloading http://pkg.entware.net/binaries/armv7/entware-opt_222108-5_armv7soft.ipk.
Collected errors:
 * opkg_install_pkg: Package entware-opt sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package entware-opt.
/opt/usr/lib/locale/locale-archive: No such file or directory
Info: Congratulations!
Info: If there are no errors above then Entware-ng was successfully initialized.
Info: Add /opt/bin & /opt/sbin to your PATH variable
Info: Add '/opt/etc/init.d/rc.unslung start' to startup script for Entware-ng services to start
Info: Found a Bug? Please report at https://github.com/Entware-ng/Entware-ng/issues
aa@RT-AC68U-8C58:/tmp/home/root# opkg install libbz2 libdb47 libncursesw libsqlite3 python python-pyopenssl
Installing libbz2 (1.0.6-2) to root...
Downloading http://pkg.entware.net/binaries/armv7/libbz2_1.0.6-2_armv7soft.ipk.
Installing libdb47 (4.7.25.4.NC-5) to root...
Downloading http://pkg.entware.net/binaries/armv7/libdb47_4.7.25.4.NC-5_armv7soft.ipk.
Installing libncursesw (6.0-1c) to root...
Downloading http://pkg.entware.net/binaries/armv7/libncursesw_6.0-1c_armv7soft.ipk.
Installing libsqlite3 (3130000-2) to root...
Downloading http://pkg.entware.net/binaries/armv7/libsqlite3_3130000-2_armv7soft.ipk.
Installing python (2.7.12-2) to root...
Downloading http://pkg.entware.net/binaries/armv7/python_2.7.12-2_armv7soft.ipk.
Installing python-pyopenssl (16.1.0-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-pyopenssl_16.1.0-1_armv7soft.ipk.
Collected errors:
 * opkg_install_pkg: Package libbz2 sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package libbz2.
 * opkg_install_pkg: Package libdb47 sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package libdb47.
 * opkg_install_pkg: Package libncursesw sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package libncursesw.
 * opkg_download: Failed to download http://pkg.entware.net/binaries/armv7/libsqlite3_3130000-2_armv7soft.ipk, wget returned 8.
 * opkg_install_pkg: Failed to download libsqlite3. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package libsqlite3.
 * opkg_download: Failed to download http://pkg.entware.net/binaries/armv7/python_2.7.12-2_armv7soft.ipk, wget returned 8.
 * opkg_install_pkg: Failed to download python. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package python.
 * opkg_install_pkg: Package python-pyopenssl sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package python-pyopenssl.
aa@RT-AC68U-8C58:/tmp/home/root#

**Comment by 1688pc** [comment]
昨天还可以安装的，今天就不能安装了
Yesterday can also be installed, and today can not be installed

**Comment by zyxmon** [comment]
>> Try 'opkg update'.

**Comment by 1688pc** [comment]
opkg update
still the same

**Comment by 1688pc** [comment]
ASUSWRT-Merlin RT-AC68U 380.65-X7.4 Sat Feb 11 08:50:32 UTC 2017
aa@RT-AC68U-8C58:/tmp/home/root# opkg update
Downloading http://pkg.entware.net/binaries/armv7/Packages.gz.
Updated list of available packages in /opt/var/opkg-lists/packages.
aa@RT-AC68U-8C58:/tmp/home/root# wget -O - http://pkg.entware.net/binaries/armv7/installer/entware_install.sh | /bin/sh
--2017-02-24 13:15:39--  http://pkg.entware.net/binaries/armv7/installer/entware_install.sh
Resolving pkg.entware.net... 81.4.123.217
Connecting to pkg.entware.net|81.4.123.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1564 (1.5K) [application/octet-stream]
Saving to: 'STDOUT'

-                               0%[                                                    ]       0  --.-KB/s             Info: Checking for prerequisites and creating folders...
Warning: Folder /opt exists!
Warning: Folder /opt/bin exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/etc/init.d exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/lib/opkg exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/sbin exists!
Warning: If something goes wrong please clean /opt folder and try again.
-                             100%[===================================================>]   1.53K  --.-KB/s   in 0.09s

2017-02-24 13:15:40 (16.4 KB/s) - written to stdout [1564/1564]

Warning: Folder /opt/share exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/tmp exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/usr exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/var/log exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/var/lock exists!
Warning: If something goes wrong please clean /opt folder and try again.
Warning: Folder /opt/var/run exists!
Warning: If something goes wrong please clean /opt folder and try again.
Info: Opkg package manager deployment...
--2017-02-24 13:15:40--  http://pkg.entware.net/binaries/armv7/installer/opkg
Resolving pkg.entware.net... 81.4.123.217
Connecting to pkg.entware.net|81.4.123.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 127488 (125K) [application/octet-stream]
Saving to: '/opt/bin/opkg'

/opt/bin/opkg                 100%[===================================================>] 124.50K  66.1KB/s   in 1.9s

2017-02-24 13:15:43 (66.1 KB/s) - '/opt/bin/opkg' saved [127488/127488]

--2017-02-24 13:15:43--  http://pkg.entware.net/binaries/armv7/installer/opkg.conf
Resolving pkg.entware.net... 81.4.123.217
Connecting to pkg.entware.net|81.4.123.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 142 [application/octet-stream]
Saving to: '/opt/etc/opkg.conf'

/opt/etc/opkg.conf            100%[===================================================>]     142  --.-KB/s   in 0s

2017-02-24 13:15:44 (4.55 MB/s) - '/opt/etc/opkg.conf' saved [142/142]

--2017-02-24 13:15:44--  http://pkg.entware.net/binaries/armv7/installer/ld-2.23.so
Resolving pkg.entware.net... 81.4.123.217
Connecting to pkg.entware.net|81.4.123.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 142752 (139K) [application/octet-stream]
Saving to: '/opt/lib/ld-2.23.so'

/opt/lib/ld-2.23.so           100%[===================================================>] 139.41K  89.8KB/s   in 1.6s

2017-02-24 13:15:46 (89.8 KB/s) - '/opt/lib/ld-2.23.so' saved [142752/142752]

--2017-02-24 13:15:46--  http://pkg.entware.net/binaries/armv7/installer/libc-2.23.so
Resolving pkg.entware.net... 81.4.123.217
Connecting to pkg.entware.net|81.4.123.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1227404 (1.2M) [application/octet-stream]
Saving to: '/opt/lib/libc-2.23.so'

/opt/lib/libc-2.23.so         100%[===================================================>]   1.17M   108KB/s   in 11s

2017-02-24 13:15:58 (108 KB/s) - '/opt/lib/libc-2.23.so' saved [1227404/1227404]

--2017-02-24 13:15:58--  http://pkg.entware.net/binaries/armv7/installer/libgcc_s.so.1.2.23
Resolving pkg.entware.net... 81.4.123.217
Connecting to pkg.entware.net|81.4.123.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39632 (39K) [application/octet-stream]
Saving to: '/opt/lib/libgcc_s.so.1'

/opt/lib/libgcc_s.so.1        100%[===================================================>]  38.70K  50.7KB/s   in 0.8s

2017-02-24 13:15:59 (50.7 KB/s) - '/opt/lib/libgcc_s.so.1' saved [39632/39632]

ln: ld-linux.so.3: File exists
ln: libc.so.6: File exists
Info: Basic packages installation...
Downloading http://pkg.entware.net/binaries/armv7/Packages.gz.
Updated list of available packages in /opt/var/opkg-lists/packages.
Installing entware-opt (222108-5) to root...
Downloading http://pkg.entware.net/binaries/armv7/entware-opt_222108-5_armv7soft.ipk.
Collected errors:
 * opkg_install_pkg: Package entware-opt sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package entware-opt.
/opt/usr/lib/locale/locale-archive: No such file or directory
Info: Congratulations!
Info: If there are no errors above then Entware-ng was successfully initialized.
Info: Add /opt/bin & /opt/sbin to your PATH variable
Info: Add '/opt/etc/init.d/rc.unslung start' to startup script for Entware-ng services to start
Info: Found a Bug? Please report at https://github.com/Entware-ng/Entware-ng/issues
aa@RT-AC68U-8C58:/tmp/home/root# opkg install libbz2 libdb47 libncursesw libsqlite3 python python-pyopenssl
Installing libbz2 (1.0.6-2) to root...
Downloading http://pkg.entware.net/binaries/armv7/libbz2_1.0.6-2_armv7soft.ipk.
Installing libdb47 (4.7.25.4.NC-5) to root...
Downloading http://pkg.entware.net/binaries/armv7/libdb47_4.7.25.4.NC-5_armv7soft.ipk.
Installing libncursesw (6.0-1c) to root...
Downloading http://pkg.entware.net/binaries/armv7/libncursesw_6.0-1c_armv7soft.ipk.
Installing libsqlite3 (3130000-2) to root...
Downloading http://pkg.entware.net/binaries/armv7/libsqlite3_3130000-2_armv7soft.ipk.
Installing python (2.7.12-2) to root...
Downloading http://pkg.entware.net/binaries/armv7/python_2.7.12-2_armv7soft.ipk.
Installing python-pyopenssl (16.1.0-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-pyopenssl_16.1.0-1_armv7soft.ipk.
Collected errors:
 * opkg_install_pkg: Package libbz2 sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package libbz2.
 * opkg_install_pkg: Package libdb47 sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package libdb47.
 * opkg_install_pkg: Package libncursesw sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package libncursesw.
 * opkg_download: Failed to download http://pkg.entware.net/binaries/armv7/libsqlite3_3130000-2_armv7soft.ipk, wget returned 8.
 * opkg_install_pkg: Failed to download libsqlite3. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package libsqlite3.
 * opkg_download: Failed to download http://pkg.entware.net/binaries/armv7/python_2.7.12-2_armv7soft.ipk, wget returned 8.
 * opkg_install_pkg: Failed to download python. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package python.
 * opkg_install_pkg: Package python-pyopenssl sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package python-pyopenssl.
aa@RT-AC68U-8C58:/tmp/home/root#

**Comment by 1688pc** [comment]
![1](https://cloud.githubusercontent.com/assets/14054316/23291594/9417a730-fa94-11e6-8b86-30de52930533.PNG)
![2](https://cloud.githubusercontent.com/assets/14054316/23291602/98bc71c6-fa94-11e6-8901-548f3fe2044d.PNG)
![3](https://cloud.githubusercontent.com/assets/14054316/23291605/9b090ac0-fa94-11e6-9484-324455ddc588.PNG)

**Comment by 1688pc** [comment]
![3](https://cloud.githubusercontent.com/assets/14054316/23291624/b1200818-fa94-11e6-8259-18918405922c.PNG)
![2](https://cloud.githubusercontent.com/assets/14054316/23291628/b6f4ed30-fa94-11e6-8982-b2b4a255ec02.PNG)
![1](https://cloud.githubusercontent.com/assets/14054316/23291635/c2b4440e-fa94-11e6-888c-801bbfd6eee0.PNG)

**Comment by zyxmon** [comment]
Please explain - why do you run installer if you have already entware installed? To run the installer again you need to clean /opt folder.
You download the correct ipk file, it has the correct sha256sum. Your Packages list is corrupt - it is for the previous package list variant. Your packages list file is corrupt! It is not present on the server (it is an old one)!
There are similar problems described here - https://github.com/Entware-ng/Entware-ng/issues/57

Here is some additional info:

```
root@ws880:/tmp/home/root# wget http://pkg.entware.net/binaries/armv7/entware-opt_222108-5_
armv7soft.ipk
Connecting to pkg.entware.net (81.4.123.217:80)
entware-opt_222108-5 100% |******************************************|  2506   0:00:00 ETA
root@ws880:/tmp/home/root# sha256sum  entware-opt_222108-5_armv7soft.ipk
7baebe87a52b25c1767a0f0b99c3281f4ff6146d8663ffff3079543eee20828a  entware-opt_222108-5_armv7soft.ipk
root@ws880:/tmp/home/root# wget http://pkg.entware.net/binaries/armv7/Packages.gz
Connecting to pkg.entware.net (81.4.123.217:80)
Packages.gz          100% |******************************************|   272k  0:00:00 ETA
root@ws880:/tmp/home/root# gunzip Packages.gz
```

Packages file must have

```
Package: entware-opt
Version: 222108-5
Depends: libc, libssp, librt, libpthread, libgcc, libstdcpp, libpthread, librt, ldconfig, findutils, terminfo, locales, opkg
Section: libs
Architecture: armv7soft
Installed-Size: 1780
Filename: entware-opt_222108-5_armv7soft.ipk
Size: 2506
MD5Sum: 4e9e136d64b2ba15e1b6690367278c04
SHA256sum: 7baebe87a52b25c1767a0f0b99c3281f4ff6146d8663ffff3079543eee20828a
Description:  entware-opt is a metapackage to install Entware basic libraries and scripts.
```

**Comment by 1688pc** [comment]
Thank you

**Comment by 1688pc** [comment]
已经安装了entware，然后不成功，然后尝试“opkg更新”后直接安装。
按您提供额外的信息已经找到问题所在，我的网络处于墙中墙，直接下载是缓存在ISP服务器上的旧软件包列表，因为ISP服务器还没有同步更新，挂代理就能下载到新的软件包列表。
非常感谢您的帮助！
