### ISSUE TITLE
* opkg_install_pkg: Package libopenssl sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.

### ISSUE THREAD

**Issue by famewolf** [Entware-ng/Entware-ng#57]
While trying to install aria2 from entware-ng on a qnap TS-212 (arm)

[~] # opkg install aria2
Installing aria2 (1.18.7-1a) to root...
Downloading http://entware.zyxmon.org/binaries/armv5/aria2_1.18.7-1a_armv5soft.ipk.
Installing zlib (1.2.8-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv5/zlib_1.2.8-1_armv5soft.ipk.
Installing libxml2 (2.9.3-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv5/libxml2_2.9.3-1_armv5soft.ipk.
Installing libopenssl (1.0.2d-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv5/libopenssl_1.0.2d-1_armv5soft.ipk.
Configuring zlib.
Configuring libxml2.
Collected errors:
 * opkg_install_pkg: Package libopenssl sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package aria2.
[~] # opkg update
Downloading http://entware.zyxmon.org/binaries/armv5/Packages.gz.
Updated list of available packages in /opt/var/opkg-lists/packages.
[~] # opkg install aria2
Installing aria2 (1.18.7-1a) to root...
Downloading http://entware.zyxmon.org/binaries/armv5/aria2_1.18.7-1a_armv5soft.ipk.
Installing libopenssl (1.0.2d-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv5/libopenssl_1.0.2d-1_armv5soft.ipk.
Collected errors:
 * opkg_install_pkg: Package libopenssl sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package aria2.

**Comment by zyxmon** [comment]
You have not updated packages list. You are given a hint to do it!

```
opkg update
```

It is recommended to run `opkg update` every time you install packages!

**Comment by famewolf** [comment]
If you bother to READ the lines I posted you will see it shows me DOING an opkg update and then getting the error AGAIN.

**Comment by zyxmon** [comment]
Try once more. No problems with libopenssl:

```
[~] # opkg update
Downloading http://entware.zyxmon.org/binaries/armv5/Packages.gz.
Updated list of available packages in /opt/var/opkg-lists/packages.
[~] # opkg install --force-reinstall libopenssl
Removing package libopenssl from root...
Installing libopenssl (1.0.2d-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv5/libopenssl_1.0.2d-1_armv5soft.ipk.
Configuring libopenssl.
[~] # opkg remove --force-depends libopenssl
Removing package libopenssl from root...
[~] # opkg install  libopenssl
Installing libopenssl (1.0.2d-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv5/libopenssl_1.0.2d-1_armv5soft.ipk.
Configuring libopenssl.
```

**Comment by zyxmon** [comment]
Just as a guess. Today approximately at 7:45-7:50 GMT Some of the packages changed at the repo. Index file was changed at 7:51 GMT. The error can be in case you have run `opkg update` at this time (3 hours ago).

**Comment by williclarkam** [comment]
I have the exact same issue, and it's really frustrating, because I have installed I think 20 Times this entware script but this time, it doesn't work.
I always follow this tutorial and everytime it works great except this time
https://github.com/RMerl/asuswrt-merlin/wiki/Entware
these are the errors I get:

```
 * opkg_install_pkg: Package findutils sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package entware-opt.
```

**Comment by zyxmon** [comment]
Have you done opkg update? There are no problems installing nano:

```
[~] # opkg update
Downloading http://pkg.entware.net/binaries/armv7/Packages.gz.
Updated list of available packages in /opt/var/opkg-lists/packages.
[~] # opkg install nano
Installing nano (2.5.0-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/nano_2.5.0-1_armv7soft.ipk.
Installing file (5.25-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/file_5.25-1_armv7soft.ipk.
Configuring file.
Configuring nano.
```

There is a bug in opkg that sometimes happens. In this case try

```
opkg update
opkg install libmagic
opkg install nano
```

**Comment by williclarkam** [comment]
Thanks for the reply, I greatly appreciate it.
Yeah I did a `opkg update` but no luck, for example now nano has been installed but not correctly, when I want to create file e.g. test , I get the bellow error:
`nano: error while loading shared libraries: libmagic.so.1: cannot open shared object file: No such file or directory`
and when I wanted to install `opkg install libmagic` I get the same error all over again 

```
admin@R7000:/tmp/home/root# opkg install libmagic
Installing libmagic (5.25-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/libmagic_5.25-1_armv7soft.ipk.
Collected errors:
 * opkg_install_pkg: Package libmagic sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package libmagic.
```
still no luck, I can't even check the Hashes, when I run the command `sha256sum` , it couldn't be found!
```
admin@R7000:/tmp/home/root# sha256sum
-sh: sha256sum: not found
```

**Comment by zyxmon** [comment]
There are now mismatches. I have tested it with

```
[~] # opkg download libmagic
Downloading http://pkg.entware.net/binaries/armv7/libmagic_5.25-1_armv7soft.ipk.
Downloaded libmagic as ./libmagic_5.25-1_armv7soft.ipk.
[~] # sha256sum ./libmagic_5.25-1_armv7soft.ipk
c30e9892131da8f75e59c99f5bafbb76b900c60ce08e80542113fa5287fec304  ./libmagic_5.25-1_armv7soft.ipk
[~] # zcat /opt/var/opkg-lists/packages |  grep c30e9892131da8f75e59c99f5bafbb76b900c60ce08e80542113fa5287fec304
SHA256sum: c30e9892131da8f75e59c99f5bafbb76b900c60ce08e80542113fa5287fec304
```

Yesterday repo was updated (there was a major change gcc 4.8.5 -> 5.3.0, glibc 2.22->2.23). The ipkf file names are the same, but sha256/md5 are different from the previous ones. May be there is some proxy between you and the repo that serves you the previous versions.

**Comment by williclarkam** [comment]
I greatly appreciate your help Sir.
Yeah exactly, but there is no proxy, I have even erased my nvram before doing this. I have downloaded the latest packages manually using IDM (Internet Download Manager) and check their hashes using Powershell against the `opkg update` database and these were the results:
```

PS C:\Users\ADMIN> Get-FileHash -Algorithm md5 "C:\IDM Downloads\dnscrypt-proxy_1.6.0-2_armv7soft.ipk"

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
MD5             D98B55F4F9F7636AFAA92431887A6F7F                                    


PS C:\Users\ADMIN> Get-FileHash -Algorithm SHA256 "C:\IDM Downloads\dnscrypt-proxy_1.6.0-2_armv7soft.ipk"

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          A283D1A4B3A312262CF79D62A089864CF28EED8E06F2BA980C68941AF0E82A3B     
```

so the MD5 Hash is:  **D98B55F4F9F7636AFAA92431887A6F7F**
and SHA256 Hash is: **A283D1A4B3A312262CF79D62A089864CF28EED8E06F2BA980C68941AF0E82A3B**

but the file I have downloaded from opkg databse from this link 
http://pkg.entware.net/binaries/armv7/Packages.gz
have these hashes:

```
Filename: dnscrypt-proxy_1.6.0-2_armv7soft.ipk
Size: 67505
MD5Sum: efbc749d963024d3e7e0738158cf9a42
SHA256sum: b937bc43a8c1a71a5b19dd6c2d62f7bb62ea0ce885aa893990394f9885a215c8
```

**Comment by zyxmon** [comment]
```
[~] # opkg download dnscrypt-proxy
Downloading http://pkg.entware.net/binaries/armv7/dnscrypt-proxy_1.6.0-2_armv7soft.ipk.
Downloaded dnscrypt-proxy as ./dnscrypt-proxy_1.6.0-2_armv7soft.ipk.
[~] # sha256sum ./dnscrypt-proxy_1.6.0-2_armv7soft.ipk
b937bc43a8c1a71a5b19dd6c2d62f7bb62ea0ce885aa893990394f9885a215c8  ./dnscrypt-proxy_1.6.0-2_armv7soft.ipk
[~] # md5sum ./dnscrypt-proxy_1.6.0-2_armv7soft.ipk
efbc749d963024d3e7e0738158cf9a42  ./dnscrypt-proxy_1.6.0-2_armv7soft.ipk
```

**Comment by williclarkam** [comment]
yours is identical to the database hashes, but again i have downloaded the dnscrypt-proxy package from this link manually 
http://pkg.entware.net/binaries/armv7/Packages.html
still the hashes are the same!!!
what could be the problem? I am lost here!

**Comment by zyxmon** [comment]
May be your provider uses some transparent proxy to reduce traffic. The files cache was not updated from yesterday's repo update. Try another internet connection, download ipk and compare.

**Comment by zyxmon** [comment]
>>  I have downloaded the latest packages manually using IDM (Internet Download Manager)

There are NO downloads in the server logs (before my test) with the user agent different from wget. No downloads with IDM! After my tests there is a single download from Iran that was probably done with IDM.

**Comment by williclarkam** [comment]
Yes Sir, you were completely right, there is something wrong with my Home internet, after I have downloaded the file using Mobile Data, the hashes were identical to yours. but again, with Home Internet the hashes were different! So I am pretty sure, there is something wrong with my Internet.
Finally I had to use a VPN (using the router it self!) to overcome this issue.
I am truly sorry for taking your time and I greatly appriciate your effort.
Thanks again Sir.

**Comment by ARM-MK** [comment]
i probably installed custom package:
`@OpenWrt:/tmp# opkg install busybox_1.24.2-1_brcm63xx.ipk 
Installing busybox (1.24.2-1) to root...
Collected errors:
 * opkg_install_pkg: Package busybox sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package busybox.
`
But get same error...
Next hack help me 
`opkg-key add busybox_1.24.2-1_brcm63xx.ipk
opkg install busybox_1.24.2-1_brcm63xx.ipk 
Installing busybox (1.24.2-1) to root...
Configuring busybox.
`

**Comment by zyxmon** [comment]
@ARM-MK packages from other repositories or for other architectures will not work in entware. brcm63xx is an example.

**Comment by ARM-MK** [comment]
yes, you right. I checked package work uncorrect
