### ISSUE TITLE
Package request: mysql 5.7

### ISSUE THREAD

**Issue by crazyf1** [Entware-ng/Entware-ng#570]
Please add mysql 5.7 to the package repository, I'd like to be able to use my NAS as a database server for my linux  hosts. Many thanks in advance.

**Comment by meffect** [comment]
oh u need 5.7 minimum?

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/Entware-ng/issues/522
https://github.com/Entware-ng/Entware-ng/issues/501
https://github.com/Entware-ng/Entware-ng/issues/222
https://github.com/Entware-ng/Entware-ng/issues/165

**Comment by ryzhovau** [comment]
Just FYI: `mysql` package(s) was replaced by `mariadb`.
