### ISSUE TITLE
Optware-ng <-> Entware-ng merging: Trustware

### ISSUE THREAD

**Issue by alllexx88** [Entware-ng/Entware-ng#573]
Cannot afford to be more/less (un)specific, but I assume that the need to sustain Optware-ng || Entware-ng (and vice versa) separately is soothing now. I believe, a common project, based on the strong sides of the both projects is needed. The need in balance between Optware-ng (<=Optware) fine control, and Entware-ng (<=OpenWRT) object-oriented transparent approach, should give birth to what I'd name "Trustware": a joint force project, where all the tremendous work on the each of them would be naturally summed up. Sufficient experience feels to be accumulated already.

**Comment by alllexx88** [comment]
Please see https://github.com/Optware/Optware-ng/issues/186

**Comment by ryzhovau** [comment]
Please, remind us your Telegram nick.

**Comment by zyxmon** [comment]
You can join the public channel - https://t.me/Entware for it.

**Comment by alllexx88** [comment]
Sorry for such a silly ticket. Wasn't feeling well back then. You're doing a great job maintaining Entware-ng. There're some good patches in Optware-ng, and maybe some good packages missing from Entware-ng (haven't conducted a research, though), so I'd feel sorry to blindly "dump" Optware-ng after all the effort on my side, but I think that a project run by a team is less likely to go dead. Not to mention the regularly inherited patches from OpenWRT. Heard some while ago that there was a trust issue: people from the Western world reluctant to use Entware-ng, in favor of the old Optware (and perhaps Optware-ng). I'm not familiar with the current state of affairs, so that's a random rumbling, but I just feel it'd be good to have a project that's trusted by both East, and West.
P.S. Just re-installed Telegram (PC crashed a while ago): my nick is same as here: alllexx88
