### ISSUE TITLE
Entware Package Permissions

### ISSUE THREAD

**Issue by uihdff** [Entware-ng/Entware-ng#575]
1) Should Entware and packages be installed while logged in as admin ?

2) When running top, is it normal to see Entware package daemons running under the admin account ?

3) Is it possible to have Entware packages run under non-admin user accounts ? Or is this a feature a package has to specifically support ?

**Comment by zyxmon** [comment]
1. Yes. Use root/admin account to install packages
2. Yes, some daemons may use other accounts.
3. It depends on the package. You have more control on user accounts in Entware-3x, alternative installation - https://github.com/Entware-for-kernel-3x/Entware-ng-3x/wiki/General-installation-notes
