### ISSUE TITLE
Package request: CryFS/gocryptfs

### ISSUE THREAD

**Issue by schnappijedi** [Entware-ng/Entware-ng#576]
Hi there,

Great job with Entware-ng. Works great with Tomato and no longer run/need a linux server as a result of what can do with Entware-ng alone on a router.

Am making a package request for CryFS (https://www.cryfs.org/) and or gocryptfs (https://nuetzlich.net/gocryptfs/). Both are based off EncFS and more or less successors to it. EncFS is available as a package but has issues and limitations. First it isn't secure based on an audit (https://defuse.ca/audits/encfs.htm). That being said it is secure enough for me and network attached storage devices on a Entware-ng device. Biggest issue though is that it has has a file name limit (of about 190).

CryFs and gocryptfs both improve on the security of EncFS (think CryFs does better job since it hides directory tree but both appear good) and most importantly the file name limit applies to neither.

**Comment by meffect** [comment]
sounds awesome

**Comment by zyxmon** [comment]
cryfs was added today to entware-3x repos.
https://github.com/Entware-for-kernel-3x/rtndev-3x/tree/master/cryfs

After entware-ng tests it will be added to entware-ng

**Comment by ryzhovau** [comment]
Done for non-MIPS platforms.

**Comment by ryzhovau** [comment]
Done for MIPSEL too.
