### ISSUE TITLE
bind-server named.conf small error

### ISSUE THREAD

**Issue by schnappijedi** [Entware-ng/Entware-ng#577]
### Package: bind-server

The db.root location in the named.conf file (/opt/etc/bind/named.conf) needs to be changed to point to:
/opt/etc/bind/db.root

The default is /etc/bind/db.root which obviously won't work since Entware-ng is installed in /opt.

**Comment by zyxmon** [comment]
Done - https://github.com/Entware-ng/entware-packages/commit/86f6adfb6433e9864253a0831489f96a829b4065
Binary package will have these changes after the next sync. No PKG_RELEASE change applied.
