### ISSUE TITLE
Package request: GIT with support for git-instaweb

### ISSUE THREAD

**Issue by simonbost** [Entware-ng/Entware-ng#578]
### Package: Git

For existing package:

- expected behavior: I would setup gitweb (https://git-scm.com/docs/gitweb) so I can set-up access to GIT repositories via Web page in read-only mode
- actual behavior: when run git-instaweb to set up gitweb, following information is returned: "fatal: git was built without support for git-instaweb (NO_PERL=YesPlease)"

### Platform:

I am using ARM7 router (ASUS RT-AC68U)

**Comment by ryzhovau** [comment]
`git` was taken from [upstream](https://github.com/openwrt/packages/tree/master/net/git) with no changes. Please, Ask OpenWrt guys to modify this package.

**Comment by simonbost** [comment]
Well, the link you gave, points Makefile containing changes required to have the gitweb working. Looking on changes made to Makefile, I noticed that on 23rd October 2016 they have added the change (https://github.com/openwrt/packages/commit/536dea0c6589a78a25087f54f0bfe929848ccfc3). It's over 4 months since October so when the package will be available via opkg?
