### ISSUE TITLE
Package request: gitolite (or older gitosis)

### ISSUE THREAD

**Issue by simonbost** [Entware-ng/Entware-ng#579]
### Package: Gitolite

For new package to be added:

- Gitolite allows you to setup git hosting on a central server, with fine-grained access control and many more powerful features. (http://gitolite.com/gitolite/index.html).
- It is open source and not abandoned (http://gitolite.com/gitolite/index.html#license). 

### Platform:

- I use ARM7 device (ASUS RT-AC68U)

**Comment by ryzhovau** [comment]
Closed with the same reason as https://github.com/Entware-ng/Entware-ng/issues/578
