### ISSUE TITLE
vsftpd TLS support

### ISSUE THREAD

**Issue by def0def0** [Entware-ng/Entware-ng#580]
### Package: vsftpd

Hello,

I installed Entware-ng on Synology NAS (armv7) to be able to deploy non-factory ftpd. After installing vsftpd (vsftpd-ext was the only available) and modifying the config file vsftpd returns:
"500 OOPS: SSL: ssl_enable is set but SSL support not compiled in"

If I read https://github.com/Entware-ng/entware-packages/blob/master/net/vsftpd/Makefile correctly, the TLS support should be compiled. What am I doing wrong?

Regards,
Tomas

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/rtndev/blob/master/vsftpd-ext/Makefile
No. There are other ftp servers in Entware.

**Comment by def0def0** [comment]
Thanks for the response. Could you please tell me, which one has TLS support? I tried proftpd too, but I got "unknown configuration directive" when using "TLSEngine on" and also with "LoadModule" when trying to load TLS module.

**Comment by zyxmon** [comment]
@def0def0 - https://github.com/Entware-ng/Entware-ng/issues/671
Binary package will be available in few days
