### ISSUE TITLE
Python3: Requests package version 2.13.0 throwing exception on get()

### ISSUE THREAD

**Issue by programatix** [Entware-ng/Entware-ng#581]
### Package: Python3
Starting from python package "requests" version 2.13.0, whenever requests.get() is called, an exception is thrown with the message,
`('Connection aborted.', OSError(89, 'Function not implemented'))`

- expected behavior: No error
- actual behavior: Error
`('Connection aborted.', OSError(89, 'Function not implemented'))`

**Comment by zyxmon** [comment]
Probably it is related to the old kernel of your firmware. I have tested it on a modern router running 3.x kernel with entware-3x. No error:

```
>>> requests.get('https://api.github.com/user', auth=HTTPBasicAuth('user', 'pass'))
<Response [401]>
>>>
```
