### ISSUE TITLE
Report bug: transmission-web can't work in Chrome 56 and Safari mobile

### ISSUE THREAD

**Issue by JeremyPeng** [Entware-ng/Entware-ng#586]
### Package: <transmission-web 2.92+git-4 x86-64>

- expected behavior: 
It should be able to work properly in iOS10’s safari and chrome 56

- actual behavior: 
1. Only appear a web UI, without any seed-related lists and content, in iPhone7 iOS10 Safari
2. The seed list appears repeatedly and will gradually increase, in Windows 10 Chrome 56

- Repair method:
I downlad transmission 2.92(14714)'s web folder and replaced it.
Everything is back to normal.

Hope to be able to re-release the package to fix this problem.

### Platform:
QNAP TS-453A QTS 4.2.3

**Comment by zyxmon** [comment]
Please report this bug upstream - https://github.com/openwrt/packages/issues
