### ISSUE TITLE
perl-Crypt-SSLeay

### ISSUE THREAD

**Issue by uihdff** [Entware-ng/Entware-ng#587]
### Package: Crypt/SSLeay.pm

For new package to be added:

- Does Entware have this package with a different name or is it included with an existing package ?
- I'm trying to install shirkdog's Pulledpork for Snort, but the Crypt/SSLeay.pm module is missing

     [https://github.com/shirkdog/pulledpork/issues/253](url)

### Platform:

- Asus RT-AC88U running Asuswrt-Rmerlin 380.65

**Comment by zyxmon** [comment]
Entware does not have this package.
Try this - https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-perl-modules to install it.

**Comment by zyxmon** [comment]
More info (quote) from QNAP forum

>>For those trying to install Net::SSLeay this CPAN line worked for me o conf makepl_arg 'LIBS="-L/opt/lib -lcrypto -lssl"'
>>
>>(you have to 'opkg install libopenssl' beforehand)
