### ISSUE TITLE
lm-sensors cannot open shared object file

### ISSUE THREAD

**Issue by arma-gast** [Entware-ng/Entware-ng#588]
### Package: lm-sensors
- expected behavior:
After installation, when running `sensors` command expected to see cores temperature.

- actual behavior:
Command outputs:
`sensors: error while loading shared libraries: libsensors.so.4: cannot open shared object file: No such file or directory`

### Platform:
x64

**Comment by arma-gast** [comment]
One more thing. After installation I cant find pwmconfig, fancontrol and other scripts. Is it possible to rebuild package from https://github.com/groeck/lm-sensors?

**Comment by ryzhovau** [comment]
This package was take form [upstream](https://github.com/openwrt/packages/tree/master/utils/lm-sensors) with no changes. Please, ask OpenWrt guys to improve it. We'll sync once per month and renewed package came here quite soon.

**Comment by zyxmon** [comment]
@ryzhovau 
Package is fixed via https://github.com/Entware-ng/entware-packages/commit/91c7bd04630293c363031f6531a3265e38c322e4 - thanks for reporting.
As for ` pwmconfig`, `fancontro` - these are shell scripts - you can unpack them from sources archive and edit for entware (/etc -> /opt/etc and similar changes).

**Comment by arma-gast** [comment]
Thanks for fix, as for scripts already done so.
