### ISSUE TITLE
Package request: cvs-1.11.23

### ISSUE THREAD

**Issue by pauldrt** [Entware-ng/Entware-ng#589]
### Platform: x86_64
QNAP TVS-EC880 Entware-ng 0.96 
Have legacy CVS database that we want to move to the QNAP to retain history, branches, tags.
Entware already has SVN and GIT.

**Comment by ryzhovau** [comment]
With all respect to CVS and what it gives us in past, it's obsolete.
I see no sense to add software, [abandoned since 2008](https://ftp.gnu.org/non-gnu/cvs/source/).
