### ISSUE TITLE
how can i enable php phar ?

### ISSUE THREAD

**Issue by yangyao** [Entware-ng/Entware-ng#59]
i use a php framework(laravel) that require php phar extension .
is there has way to enable it ? 
i found phar was disabled in configire with 
'--disable-phar'

**Comment by ryzhovau** [comment]
Please, follow https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources

Just fix `feeds/lang/php5/Makefile` before compiling `php5`.
