### ISSUE TITLE
Request to update ipset4 package to most recent version

### ISSUE THREAD

**Issue by Xentrk** [Entware-ng/Entware-ng#590]
### Package: <name>
ipset4 for arml7
For existing package:
ipset4
- expected behavior: ...
Most recent version
- actual behavior: ...
Version on entware is old and not able to support ipset functions on dd-wrt. Specifically, the malware-block and privacy-filter scripts written by swetoast on snbforums.com. I was able to get an xt_set.ko from a forum posting on dd-wrt that got the scripts working on dd-wrt. dd-wrt builds do not include ipset and there are several forums where people are looking for it. Having an updated version on entware would solve the problem.
For new package to be added:

- make sure there's no similar package already added,
- describe killer features of new package,
- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform:

- please, tell us what feed and\or devices are you using.
D-Link 880L running dd-wrt
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by zyxmon** [comment]
You can install Entware-3x and use the new ipset on your router
https://github.com/Entware-for-kernel-3x
