### ISSUE TITLE
Upgrade rrdtool

### ISSUE THREAD

**Issue by Wojtus11** [Entware-ng/Entware-ng#591]
### Package: rrdtool

Could you please consider upgrading rrdtool to latest version?

Version available with Entware-ng is 1.2.30 from 2009. 
Latest one is 1.6.0 from 2016.

Ready-made scripts available on internet fail due missing features. As manual from 1.2.30 is not available with package, it's hard to fix and edit scripts.

### Platform:
QNAP TS-212P (armv5)

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/entware-oldpackages-ports/blob/master/rrdtool/Makefile#L7
