### ISSUE TITLE
Bug in Tor 0.2.9.8 (git-01ab67e38b358ae9)

### ISSUE THREAD

**Issue by monosoul** [Entware-ng/Entware-ng#592]
### Package: Tor 0.2.9.8 (git-01ab67e38b358ae9)
- expected behavior: 
Tor starting succesfully.
- actual behavior: 
Tor failing to start with next error:
`Mar 12 10:06:46.000 [err] tor_assertion_failed_(): Bug: src/common/compat_time.c:359: monotime_coarse_get: Assertion r == 0 failed; aborting. (on Tor 0.2.9.8 01ab67e38b358ae9)
Mar 12 10:06:46.000 [err] Bug: Assertion r == 0 failed in monotime_coarse_get at src/common/compat_time.c:359. (Stack trace not available) (on Tor 0.2.9.8 01ab67e38b358ae9)
`

This issue seems to be fixed already in tor project: https://bugs.torproject.org/21035

### Platform: MIPS
Device: **Asus RT-N66U**
Firmware: **Asuswrt-Merlin 380.65_2**

**Comment by monosoul** [comment]
Btw, most recent stable tor version is **0.2.9.10**. Are you accepting PRs to `entware-packages`? I could update tor's makefile myself and send PR.

**Comment by ryzhovau** [comment]
This package was taken from [upstream](https://github.com/openwrt/packages/tree/master/net/tor) with no changes. Please, send PR to OpenWrt guys and fixed package will arrive here in next sync.
