### ISSUE TITLE
mediatomb: error loading libavformat.so.56

### ISSUE THREAD

**Issue by RogueScholar** [Entware-ng/Entware-ng#593]
### Package: mediatomb

I'm admittedly a Linux neophyte, but it appears at first glance that with mediatomb being dependent on ffmpeg, when ffmpeg was updated recently then mediatomb also required recompiling but wasn't

After install of mediatomb package on armv7 entware-ng Netgear R7000, all attempts to invoke program generate the following message: "mediatomb: error while loading shared libraries: libavformat.so.56: cannot open shared object file: No such file or directory"

**Comment by zyxmon** [comment]
opkg system is not clever enough in some cases. You need to force-reinstall some packages.
My guess is you need to run `opkg install --force-reinstall libffmpegthumbnailer`. If it does not help - you can reinstall all packages with libraries with `opkg list-installed|grep -v "libc "|sed 's/ - .*$//'|grep lib|grep -v libpthread|grep -v libgcc|xargs -n 5 opkg --force-reinstall install`.
