### ISSUE TITLE
Can't install on AC66U with DD-WRT

### ISSUE THREAD

**Issue by neheb** [Entware-ng/Entware-ng#595]
Log: 

root@DD-WRT:/opt# wget -O - http://pkg.entware.net/binaries/mipsel/installer/ins
taller.sh | sh
Connecting to pkg.entware.net (81.4.123.217:80)
Info: Creating folders...
Info: Deploying opkg package manager...
Downloading /opt/bin/opkg... success!
Downloading /opt/etc/opkg.conf... success!
Downloading /opt/etc/profile... success!
Downloading /opt/etc/init.d/rc.func... success!
Downloading /opt/etc/init.d/rc.unslung... success!
Info: Basic packages installation...
Segmentation fault
Segmentation fault

Congratulations! If there are no errors above then Entware-ng is successfully initialized.

Found a Bug? Please report at https://github.com/Entware-ng/Entware-ng/issues

Type 'opkg install <pkg_name>' to install necessary package.

root@DD-WRT:/opt# opkg
Segmentation fault

I have no idea why it's segfaulting. DD-WRT build is latest from March 4.

**Comment by zyxmon** [comment]
What is your device/architecture?

There is bug in the latest DD-WRT with busybox 1.26.2 - wget downloads corrupted files that cannot be run. Please suggest firmware developpers the following patch (from busybox mail list) to fix it - https://github.com/Entware-ng/Entware-ng/commit/6b829b35c2553c3a97d5d12c0d53bce5dfb60040 or to rollback to busybox 1.25.1!

You can check if the bug is present by downloading large ipk files from our repo on a router and checking the length.

**Comment by zyxmon** [comment]
BTW - since the latest DD-WRT firmwares use 3.x or 4.x kernels I strongly recommend to install Entware-3x - https://github.com/Entware-for-kernel-3x/Entware-ng-3x
But first you must solve wget froblem with firmware.  Once Entware-3x is installed it will use its own wget binary.

**Comment by neheb** [comment]
DD-WRT also includes curl. Potential workaround...

**Comment by zyxmon** [comment]
opkg binary needs working wget.

**Comment by neheb** [comment]
replaced and adjusted all occurances of wget in the install.sh file with curl. opkg no longer segfaults.

I ended up installing 3x like you mentioned. Got these errors:

Downloading http://entware-3x.zyxmon.org/binaries/mipsel/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/packages
Package ext-ui-lighttpd version 0.2-1 has no valid architecture, ignoring.
Package ext-ui-lighttpd-7 version 0.2-1 has no valid architecture, ignoring.
Package ext-ui-nginx version 0.2-1 has no valid architecture, ignoring.
Package ext-ui-nginx-7 version 0.2-1 has no valid architecture, ignoring.
Package libndm version 1.1.0-1a has no valid architecture, ignoring.
Installing entware-opt (1.0-4) to root...
Downloading http://entware-3x.zyxmon.org/binaries/mipsel/entware-opt_1.0-4_mipsel-3x.ipk
Collected errors:
 * parse_from_stream_nomalloc: Missing new line character at end of file!
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for entware-opt:
 *      zoneinfo-asia *         zoneinfo-europe *       terminfo *      locales * 
 * opkg_install_cmd: Cannot install package entware-opt.
Package ext-ui-lighttpd version 0.2-1 has no valid architecture, ignoring.
Package ext-ui-lighttpd-7 version 0.2-1 has no valid architecture, ignoring.
Package ext-ui-nginx version 0.2-1 has no valid architecture, ignoring.
Package ext-ui-nginx-7 version 0.2-1 has no valid architecture, ignoring.
Package libndm version 1.1.0-1a has no valid architecture, ignoring.
Unknown package 'opkg'.
Collected errors:
 * parse_from_stream_nomalloc: Missing new line character at end of file!
 * opkg_install_cmd: Cannot install package opkg.
cp: can't stat '/opt/etc/passwd.1': No such file or directory
cp: can't stat '/opt/etc/group.1': No such file or directory
cp: can't stat '/opt/etc/shells.1': No such file or directory
Info: Congratulations!
Info: If there are no errors above then Entware-3x was successfully initialized.
Info: Add /opt/bin & /opt/sbin to your PATH variable
Info: Add '/opt/etc/init.d/rc.unslung start' to firmware startup script for Entware-3x services to start

This is an alternative Entware-3x installation. We recomend to install and setup Entware version of ssh server
and use it instead of a firmware supplied one. You can install dropbear or openssh as an ssh server

**Comment by zyxmon** [comment]
opkg uses wget do get index file and packages. It failes. You can get/build static wget that works and add the path with working wget first in a list.

**Comment by ryzhovau** [comment]
> where can i find a working wget static for entware?

Not sure we going to provide it, sorry. Static `wget` not "for Entware" only, it can be built on any other build system unless it works on MIPSEL.

**Comment by zyxmon** [comment]
>> where can i find a working wget static for entware?

Just search for wget for armv7.
Here is a statically linked busybox for armv7 that I have build some time ago for Android users -
http://pkg.entware.net/binaries/armv7/experimental/busybox
One can manually put it on usb storage and modify install script that will install a working copy of Entware on DD-WRT. Please add busybox or wget-nossl or wget package to initial installation and make sure that /opt/bin comes first in the PATH.

**Comment by hpetitti** [comment]
Please, let me know how can I install Entware on my WRT1200AC using busybox.
Thanks (a lot) in advance,
HP

**Comment by hpetitti** [comment]
Hi folks, 
I just resolved seg fault by coping binaries by hand.
Now I can run opkg update, and drops the following error:
  # opkg update
  Downloading http://entware-3x.zyxmon.org/binaries/armv7/Packages.gz
  Updated list of available packages in /opt/var/opkg-lists/packages
  Collected errors:
   * parse_from_stream_nomalloc: Missing new line character at end of file!_

It seems like wget is downloading corrupt files. So,  PLEASE @zyxmon, @p3x-robot let us know how can we solve this issue by using your statically linked wget in your custom busybox.
Thanks in advance,
HP

**Comment by zyxmon** [comment]
Please contact firmware manufacturer to fix wget problem or temporary install working wget and install wget in entware.

**Comment by BrainSlayer** [comment]
maybe entware should simply fix the webserver Downloading /opt/etc/profile... Connecting to pkg.entware.net (81.4.123.217:80)
wget: error getting response: Invalid argument

**Comment by ryzhovau** [comment]
@BrainSlayer, we rolled back to 1.25.1 after this regression, so it's up to you.

You can reproduce it with any 64KB+ file served by nginx.

**Comment by BrainSlayer** [comment]
i can't reproduce it with any other webserver. nginx returns a header which is unsupported by wget as it seems. since this busybox version is now in dd-wrt since more than 6 months, its clearly caused by entware

**Comment by BrainSlayer** [comment]
Downloading /opt/etc/profile... Connecting to pkg.entware.net (81.4.123.217:80)
wget: error getting response: Invalid argument

**Comment by BrainSlayer** [comment]
upgraded now to busybox 1.27 this works as well.

**Comment by ryzhovau** [comment]
Thanks.

We rolled back from 1.26.2 to 1.25.1 not because of `wget` only, there was some other regressions, such as seg.faults in shell scripts.

I hope 1.27 is fine.

**Comment by BrainSlayer** [comment]
so far it works
