### ISSUE TITLE
A Request and Query

### ISSUE THREAD

**Issue by Aeres-u99** [Entware-ng/Entware-ng#596]
### Package: <w3m>
   I love this one and truly want to use on my android 

For existing package:
lynx , elinks
- expected behavior: lynx www.google.com should connect to google ; but it is shoing Alert:Unable to connect to remote host
cant access start file
- actual behavior: ...

For new package to be added:

- make sure there's no similar package already added,
- describe killer features of new package,
- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform:

- please, tell us what feed and\or devices are you using. I am Using Android 4.4.2 , lgd686
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by zyxmon** [comment]
lynx work ok in entware in normal linux environment. Android is very special - many standard linux files needed normally are missing and should be added manualy. The best discussion on using entware on android is here (Russian) - http://4pda.ru/forum/index.php?showtopic=745536
