### ISSUE TITLE
rclone v1.36

### ISSUE THREAD

**Issue by jheyneman** [Entware-ng/Entware-ng#598]
### Package: rclone v1.36

There have been significant updates made to rclone to increase stability and add features over v1.35 which is currently available through Entware-ng.  I currently use rclone on my QNAP TS-563 for mounting Amazon Cloud Drive. 

Changelog:
http://rclone.org/changelog/

Download:
http://rclone.org/downloads/

Thanks!

**Comment by zyxmon** [comment]
Done
