### ISSUE TITLE
Request for pigz

### ISSUE THREAD

**Issue by Kalofin** [Entware-ng/Entware-ng#599]
I like to have **pigz** - a multi-threaded version of gzip  available in entware-ng. We have a QNAP Appliance with multi-core processors, which can speed up gzip compression of large chunks of data.

See: http://zlib.net/pigz/

Cheers,
  Kalofin

**Comment by zyxmon** [comment]
Added via https://github.com/Entware-for-kernel-3x/rtndev-3x/commit/148d559e51d3922829a879a8249f3c12b5490879
pigz will be soon in Entware-ng also
