### ISSUE TITLE
Asterisk11.22.0-2 RTP error

### ISSUE THREAD

**Issue by realby1** [Entware-ng/Entware-ng#600]
### Package: asterisk11	11.22.0-2

For existing package:
- expected behavior: ...
- actual behavior: 
When you try to call, you get an: ERROR[1612][C-00000000]: rtp_engine.c:259 ast_rtp_instance_new: No RTP engine was found. Do you have one loaded?
I found a solution to this problem using recompiling http://forums.asterisk.org/viewtopic.php?f=1&t=86518 , but I do not have the compilation skills. Also from this article I realized that the previous compiled versions may not have this error. Then where can I find previous versions of Asterisk packages?

### Platform: MIPS Asus RT-N16 DD-WRT

**Comment by zyxmon** [comment]
Please report bugs if any upstream - https://github.com/openwrt/telephony/issues
We build asterisk with the same modules and configuration as in openwrt. There are 100+ asterisk modules in entware/openwrt. May be you need to install one of them.

**Comment by zyxmon** [comment]
No responce. Closing. There is a package in Entware that may help " This package provides support for 'Secure RTP' in Asterisk11."
