### ISSUE TITLE
Apache gone wrong (?)

### ISSUE THREAD

**Issue by serge-sb** [Entware-ng/Entware-ng#601]
### Package: apache 2.4.25-1

For existing package:

- expected behavior: start and stop normally
- actual behavior:

About starting: service starts only after LogLevel is set to 'notice' in https.conf (or any other than there is after package installation)

About stopping: service does not stop normally at all. Seems, that the /opt/var/log/httpd.pid is created with bad pid in it. If I write actual pid there, service stops correctly.

### Platform:

ASUS RT-N56U B1

### Note

Problem started when I upgraded packages (opkg update, opkg upgrade). Previously apache was 2.2.something version.

**Comment by zyxmon** [comment]
The "LogLevel" bug was reported in openwrt in 2011 - https://forum.openwrt.org/viewtopic.php?id=31549
We will try to find and fix pid bug. You can use another script to stop apache before this bug is fixed.
BTW we recommend nginx or lighttpd for embedded devices usually.

**Comment by serge-sb** [comment]
Thanks. I need apache for svn. Actually I was trying to build the ipk package for myself (finally I want to build the ipk with svn support). Before installing it I've done opkg update/upgrade from entware repository. And stuck with what I wrote in the issue.

**Comment by zyxmon** [comment]
@serge-sb - my recomendations for your hardware.
1. Install Padavan firmware
2. Install Entware-3x - https://github.com/Entware-for-kernel-3x/Entware-ng-3x/wiki or (Russian) http://forums.zyxmon.org/viewtopic.php?f=5&t=5399
3. Install debian (chroot environment) - http://forums.zyxmon.org/viewtopic.php?f=5&t=5484
4. Install apache, svn, etc in debian

There are also other methods to install debian chroot.

**Comment by zyxmon** [comment]
Fixed in https://github.com/Entware-ng/entware-packages/commit/3ccae64a8058813170e857b86c66b72a58f75f7d
