### ISSUE TITLE
rtorrent 0.9.7

### ISSUE THREAD

**Issue by NubeRoja** [Entware-ng/Entware-ng#602]
### Package: rtorrent 0.9.7

Version 0.9.7+ has a built-in daemon mode disabling the user interface, so you can only control it via XMLRPC. [https://github.com/rakshasa/rtorrent/wiki/Daemon_Mode](url)
In an embedded device is a essential mode, no need to install screen or dtach to daemonize rtorrent and so make it lighter yet

Thanks!

### Platform: RT-AC56U

**Comment by zyxmon** [comment]
Please ask it upstream - https://github.com/openwrt/packages/blob/master/net/rtorrent/Makefile
We will sync with openwrt after it is upgraded there.
