### ISSUE TITLE
packages do not autostart

### ISSUE THREAD

**Issue by lug-gh** [Entware-ng/Entware-ng#603]
### Package: mysql-server AND zabbix-proxy

For existing package:

- expected behavior: it starts automatically
- actual behavior: it doesn't

### Platform: QNAP TS-421 (armv5)

I installed entware-ng on the qnap and then I installed mysql-server and zabbix-proxy via opkg

The problem is, these packages do not run on startup.
I've tried multiple things like https://wiki.qnap.com/wiki/Running_Your_Own_Application_at_Startup but as it turns out entware-ng destroys this method.

When I check if mysql is up I do it like this:
`/opt/etc/init.d/S70mysqld check`
 Checking mysqld...              alive.

But there is no mysqld process running, no service is using port 3306 and if I do
`mysql -uadmin -p` OR `mysql -uroot -p` I get this error message:
`Can't connect to local MySQL server through socket '/opt/var/run/mysqld.sock' (2)`

The services only run if I type `mysqld` and `zabbix_proxy` manually

**Comment by zyxmon** [comment]
mysql daemon requires initial setup before the first run. Have you done the initial setup?
Please check if daemons can be run from ssh console by running `/opt/etc/init.d/S70mysqld start`?
Your question is very hardware specific - please post it here - https://forum.qnap.com/viewforum.php?f=351

**Comment by lug-gh** [comment]
Yes i have done the initial setup, I've forgot to mention that.
`/opt/etc/init.d/S70mysqld start` prints this: `Starting mysqld...              already running.`

But why is this hardware specific?

**Comment by zyxmon** [comment]
There is another mysql (from firmware) running on QNAP. You need to rewrite mysql startup script for QNAP. This show that it is hardware specific. Other devices do not have mysql from firmware running.

**Comment by lug-gh** [comment]
Ok I just noticed I dont even need mysql for zabbix-proxy .. :)
so there's just one question left, which should not be hardware specific.
how do i stop the zabbix service? opkg install zabbix-proxy does not create a file under /opt/etc/init.d

do i have to create one by myself?

**Comment by zyxmon** [comment]
>> do i have to create one by myself?

Yes. Some services do not have startup files. You can share your startup file - so we can include it in future package versions.
PS I am afraid you need entware mysql daemon running for zabbix.
