### ISSUE TITLE
Update request: Deluge 1.3.14

### ISSUE THREAD

**Issue by gibxxi** [Entware-ng/Entware-ng#604]
Package: Deluge 1.3.14
For existing package: 1.3.13

Existing 1.3.13 package crashes randomly or when adding torrents, rendering Deluge unusable. Fixed in latest update (1.3.14).

http://dev.deluge-torrent.org/ticket/2941

Platform: QNAP / Entware-ng (NAS)

**Comment by tomduijf** [comment]
+1

**Comment by zyxmon** [comment]
Done.

**Comment by gibxxi** [comment]
Thankyou zyxmon. :)
