### ISSUE TITLE
mpg123 arm7 1.22 not work on tomatousb R6300v2

### ISSUE THREAD

**Issue by comicfans** [Entware-ng/Entware-ng#606]
### Package: mpg123

For existing package:

- expected behavior:   mpg123 should load alsa and null audio output plugin, and play audio
- actual behavior: mpg123 shows no output plugin loaded and can not play audio (to any output plugin)

mpg123 can decode mp3 to file  with no problem, just can not load output plugin correctly. 
verbose shows that libltdl load plugin failed.

with latest mpg123 1.24.0, this problem resolved and mpg123 can play audio normally.
changelog shows that 1.24.0 use dlopen instead of libltdl.  
mpg123 1.24.0 add a "libout123.so" which is needed at runtime

### Platform:
device : netgear R6300v2  (using entware-ng armv7)
firmware:  tsynik moded tomatousb (usb audio module added)

**Comment by zyxmon** [comment]
We build this package the same way as in openwrt. Please ask upstream to upgrade package to 1.24
https://github.com/openwrt/packages/issues
