### ISSUE TITLE
rtorrent cannot connect to SSL tracker (https)

### ISSUE THREAD

**Issue by deartonym** [Entware-ng/Entware-ng#607]
### Package: rtorrent

I have installed and upgraded the rtorrent/rutorrent package using rutorrent-easy-install from Entware on an Asus router AC68U

It runs correctly on most BT trackers. However, when I turn to some Private Trackers that require a ssl connection by https, the rtorrent cannot connect to them.

BTW, the deluge can connect to the PTs that require a ssl connection.

Is it some bug that I can fix by my side?

Thanks.

**Comment by dafart** [comment]
In order to have it working correctly you need to install ssl certificates (so install the package ca-certificates and it will work)
Greetings,

Daf

**Comment by zyxmon** [comment]
`opkg install ca-certificates`
