### ISSUE TITLE
Amule fails to start

### ISSUE THREAD

**Issue by thuantran** [Entware-ng/Entware-ng#608]
Amule fail to start with following error:
amuled -f -c /opt/var/amule
amuled: error while loading shared libraries: libbfd-2.26.1.so: cannot open shared object file: No such file or directory

Looks like it needs to be recompile with latest libbfd.

Please tell me when it's up.

Thanks and best regards.

**Comment by zyxmon** [comment]
It looks like you have not run 

```
opkg update
opkg upgrade
```

before package installation. If it does not help, please update all libraries running

```
opkg list-installed|grep -v "libc "|sed 's/ - .*$//'|grep lib|grep -v libpthread|grep -v libgcc|xargs -n 5 opkg --force-reinstall install
```

opkg system is not alway clever enough to update all needed files.

**Comment by thuantran** [comment]
Does not fixed the problem for me after what I have done what you told me:

ASUSWRT-Merlin RT-AC56U 380.65-4 Wed Mar 29 04:39:47 UTC 2017
admin@RT-AC56U-84E0:/tmp/home/root# opkg update
Downloading http://entware.zyxmon.org/binaries/armv7/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/packages
admin@RT-AC56U-84E0:/tmp/home/root# opkg upgrade
admin@RT-AC56U-84E0:/tmp/home/root# opkg list-installed|grep -v "libc "|sed 's/
- .*$//'|grep lib|grep -v libpthread|grep -v libgcc|xargs -n 5 opkg --force-rein
stall install
Removing package libbfd from root...
Removing package libcryptoxx from root...
Removing package libcurl from root...
Removing package libevent2 from root...
Removing package libexpat from root...
Installing libbfd (2.27-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libbfd_2.27-1_armv7soft.ipk
Installing libcryptoxx (5.6.3-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libcryptoxx_5.6.3-1_armv7so                                                                                                                                                                                                                                                                                           ft.ipk
Installing libcurl (7.52.1-2) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libcurl_7.52.1-2_armv7soft.                                                                                                                                                                                                                                                                                           ipk
Installing libevent2 (2.0.22-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libevent2_2.0.22-1_armv7sof                                                                                                                                                                                                                                                                                           t.ipk
Installing libexpat (2.2.0-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libexpat_2.2.0-1_armv7soft.                                                                                                                                                                                                                                                                                           ipk
Configuring libcurl.
Configuring libbfd.
Configuring libexpat.
Configuring libevent2.
Configuring libcryptoxx.
Removing package libiconv-full from root...
Removing package libintl-full from root...
Removing package libmagic from root...
Removing package libncurses from root...
Removing package libncursesw from root...
Installing libiconv-full (1.11.1-3) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libiconv-full_1.11.1-3_armv                                                                                                                                                                                                                                                                                           7soft.ipk
Installing libintl-full (0.19.8.1-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libintl-full_0.19.8.1-1_arm                                                                                                                                                                                                                                                                                           v7soft.ipk
Installing libmagic (5.25-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libmagic_5.25-1_armv7soft.i                                                                                                                                                                                                                                                                                           pk
Installing libncurses (6.0-1c) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libncurses_6.0-1c_armv7soft                                                                                                                                                                                                                                                                                           .ipk
Installing libncursesw (6.0-1c) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libncursesw_6.0-1c_armv7sof                                                                                                                                                                                                                                                                                           t.ipk
Package libncursesw (6.0-1c) installed in root is up to date.
Configuring libiconv-full.
Configuring libintl-full.
Configuring libncursesw.
Configuring libncurses.
Configuring libmagic.
Removing package libopenssl from root...
Removing package libpng from root...
Removing package libreadline from root...
Removing package librt from root...
Removing package libssp from root...
Installing libopenssl (1.0.2k-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libopenssl_1.0.2k-1_armv7so                                                                                                                                                                                                                                                                                           ft.ipk
Installing libssp (6.3.0-6) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libssp_6.3.0-6_armv7soft.ip                                                                                                                                                                                                                                                                                           k
Installing librt (2.23-6) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/librt_2.23-6_armv7soft.ipk
Installing libpng (1.2.57-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libpng_1.2.57-1_armv7soft.i                                                                                                                                                                                                                                                                                           pk
Installing libreadline (7.0-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libreadline_7.0-1_armv7soft                                                                                                                                                                                                                                                                                           .ipk
Package librt (2.23-6) installed in root is up to date.
Package libssp (6.3.0-6) installed in root is up to date.
Configuring libssp.
Configuring librt.
Configuring libopenssl.
Configuring libpng.
Configuring libreadline.
Removing package libstdcpp from root...
Removing package libwxbase from root...
Removing package zlib from root...
Installing libstdcpp (6.3.0-6) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libstdcpp_6.3.0-6_armv7soft                                                                                                                                                                                                                                                                                           .ipk
Installing libwxbase (2.8.12-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/libwxbase_2.8.12-1_armv7sof                                                                                                                                                                                                                                                                                           t.ipk
Installing zlib (1.2.11-1) to root...
Downloading http://entware.zyxmon.org/binaries/armv7/zlib_1.2.11-1_armv7soft.ipk
Package zlib (1.2.11-1) installed in root is up to date.
Configuring zlib.
Configuring libstdcpp.
Configuring libwxbase.
admin@RT-AC56U-84E0:/tmp/home/root# amuled -f -c /opt/var/amule
amuled: error while loading shared libraries: libbfd-2.26.1.so: cannot open shared object file: No such file or directory

As I told you this is because of lifbfd has been updated to version 2.26 without recompiling amule. So I tried to reinstall amule package and that fixed it for me. I have all these packages installed long ago, maybe that's why and you should have increase the amule - 2.3.2-1 to amule - 2.3.2-2 for libbfd update?

**Comment by thuantran** [comment]
Got different error now:
```
 2017-04-01 21:18:52: Initialising aMuleD SVN compiled with wxBase v2.8.12
 2017-04-01 21:18:52: Checking if there is an instance already running...
 2017-04-01 21:18:52: No other instances are running.
 2017-04-01 21:18:52: ListenSocket: Ok.
 2017-04-01 21:18:52: Loading temp files from /mnt/<FSDfsdfsf>
 2017-04-01 21:18:52: All PartFiles Loaded.
 2017-04-01 21:18:52: amuled: OnInit - starting timer

Terminated after throwing an instance of 'std::bad_alloc'
        what(): std::bad_alloc
        backtrace:
[2] ?? in /opt/lib/libstdc++.so.6[0x40815058]

Aborted
```
