### ISSUE TITLE
GCC and architecture mismatch

### ISSUE THREAD

**Issue by SkyCrawl** [Entware-ng/Entware-ng#609]
### Package: gcc

When I try to configure certain software for compilation (`./configure --prefix=<prefix>`), the command fails and the log says:

```
configure:2958: gcc -o conftest -g   conftest.c  >&5
configure:2962: $? = 0
configure:2969: ./conftest
./conftest: error while loading shared libraries: libgcc_s.so.1: wrong ELF class: ELFCLASS32
```

Not sure what changed but recently, the very same command for the very same software (and version) worked.

### Platform:

__NAS__  
Brand: QNAP  
Model: TS-251  
Firmware: QTS 4.2.4
`uname -m`: `x86_64`

I have checked with `find / -name "libgcc_s.so.1"` and `objdump -a <library>`. The only ELF32 instance of that library seems to be:
```
$ objdump -a /lib/libgcc_s.so.1

/lib/libgcc_s.so.1:     file format elf32-i386
/lib/libgcc_s.so.1

```

So, I think the mystery is why the configure command finds `/lib/libgcc_s.so.1` instead of all other instances of the affected library (which I've confirmed to be `elf64-x86-64`). The following information may be useful to find out:

```
$ echo $PATH
/opt/bin:/opt/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin
$ echo $LDFLAGS
(empty)
```

If any more information is needed, I'll happily provide it.

I have also searched the affected `configure` script for `/lib` and the results didn't seem to contain anything harmful or related. Nevertheless, I can provide it if needed.

**Comment by zyxmon** [comment]
Entware does not use libraries from `/lib` folder. It uses `/opt/lib`.
My recommendation for your NAS and firmware - remove Entware-ng and install Entware-3x.

Please read the wiki on gcc in Entware - https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-(native-compilation)
