### ISSUE TITLE
Update net-snmp from openwrt-packages

### ISSUE THREAD

**Issue by sorano** [Entware-ng/Entware-ng#613]
### Package: libnetsnmp

For existing package:

- expected behavior: Newer release (5.7.3-4): https://github.com/openwrt/packages/commit/ec6712feada38dd05f77aaa8833b9630d4908a76
- actual behavior:
opkg info libnetsnmp | grep Version
Version: 5.7.3-2a
 

### Platform:

- please, tell us what feed and\or devices are you using.
mips

**Comment by zyxmon** [comment]
If netsnmp was updated in openwrt - it will be updated in entware.

**Comment by sorano** [comment]
@zyxmon 

Yeah, that's what I thought as well. 

However openwrt was updated 28th Feb, but entware is not updated yet. That is why I have waited until now. 

I thought entware packages were synced once a month? When is the next sync coming up?

**Comment by zyxmon** [comment]
Done - https://github.com/Entware-ng/entware-packages/blob/master/net/net-snmp/Makefile
