### ISSUE TITLE
How do I remove?

### ISSUE THREAD

**Issue by halcy0n9001** [Entware-ng/Entware-ng#614]
Silly question, how do I remove this if I no longer want it after installing with the easy set-up script?

Thanks,

**Comment by zyxmon** [comment]
What is "this" you are going to remove?
To remove a package run `opkg remove <package_name>`.
To remove entware that was setup with a script - remove the contents of /opt folder.

**Comment by halcy0n9001** [comment]
Sorry,
I meant the packages installed using "opkg install rtorrent-easy-install" (https://github.com/Entware-ng/Entware-ng/wiki/Using-Rtorrent)

Do I just remove them individually using opkg, or is there a script to remove them?

**Comment by zyxmon** [comment]
`opkg remove rtorrent-easy-install --autoremove`

**Comment by halcy0n9001** [comment]
Thanks :)
