### ISSUE TITLE
Flask

### ISSUE THREAD

**Issue by kharlashkin** [Entware-ng/Entware-ng#618]
Планируется ли добавление [Flask](https://github.com/pallets/flask) в репозитории Entware?

Маршрутизатор Asus rt-n16, прошивка dd-wrt big, подключил usb-флешку, установил python2.7 и python-pip.

Пробовал установить с помощью "pip install flask" - вываливается ошибка:
`Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xdf4af0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/flask/`

**Comment by kharlashkin** [comment]
> Пробовал установить с помощью "pip install flask" - вываливается ошибка:
`Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xdf4af0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/flask/`
Как оказалось проблема у провайдера была.
Сейчас так:
`    Complete output from command python setup.py egg_info:
    /opt/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: invalid command 'egg_info'
`

**Comment by zyxmon** [comment]
Не планируем. Вы инструкции по установке прочли?
https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-python-modules

Пред установкой нужно выполнить `pip install --upgrade pip setuptools`

**Comment by kharlashkin** [comment]
Прошу прощения, уже нашел проблему всё установилось, работает.
