### ISSUE TITLE
Request for Mosh 1.3!

### ISSUE THREAD

**Issue by MacDragon** [Entware-ng/Entware-ng#619]
### Package: Mosh

Mosh 1.2 has a major issue when running on busybox that causes clients to frequently not be able to connect when connection message is cut off, my mac laptop never succeeds in connecting to router, but some other clients do, and I believe this has been fixed in 1.3 so would request it be updated on the feed to latest version.

### Platform: Asus AC3200 router with tomato.

**Comment by RogueScholar** [comment]
I've got the same experience with the current build. The Chrome extension and JuiceSSH on Android (my primary reason for experimenting with mosh in the first place) never receive the handshake on UDP, no matter how I tinker with the config. It would be great if 1.3 resolved these issues.

**Comment by zyxmon** [comment]
Done - https://github.com/Entware-ng/entware-oldpackages-ports/blob/master/mosh/Makefile#L11
Package is in the binary repo now.

**Comment by MacDragon** [comment]
Thanks, is now indeed working to router when launch with option -no-ssh-pty added in 1.3
