### ISSUE TITLE
Bitlbee doesn't work at all.

### ISSUE THREAD

**Issue by rodoviario** [Entware-ng/Entware-ng#62]
I installed, edited its configuration. It can be started (but no restarted), it can be stopped. It doesn't show when you list processes with ps. If you try to run it... it says "segmentation fault"

**Comment by ryzhovau** [comment]
I see no way to bring back `bitlbee` to life. As soon as it proven as broken, I'll remove it from repo.

**Comment by rodoviario** [comment]
Thanks men.
May be in the archives, an old version. I will try and report if it works.
