### ISSUE TITLE
php7-fpm bug

### ISSUE THREAD

**Issue by Pbroc** [Entware-ng/Entware-ng#620]
### Package: php7-fpm

Package create wrong .conf file named `php7-fpm.conf`, needs to be `php-fpm.conf`
(The init script needs to be changed to reflect that too).

Then, I get Fastcgi error with nginx, using socket:

`[error] 17169#0: *3 FastCGI sent in stderr: "Unable to open primary script: /opt/share/nginx/html/index.php (No such file or directory)" while reading response header from upstream, client: 192.168.1.16, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/opt/var/run/php7-fpm.sock:", host: "192.168.1.14:5465"`

So for that last error, I don't really know if it's due to root permissions inside Asustor "system" or if it's the package, but I try a lot of solutions I find online, nothing is working.

**Comment by zyxmon** [comment]
>> Package create wrong .conf file named php7-fpm.conf, needs to be php-fpm.conf

This comes from openwrt - Package create wrong .conf file named php7-fpm.conf, needs to be php-fpm.conf - please report bug upstream. Perhaps it is not a bug. It is done to distinguish php5 and php7.
