### ISSUE TITLE
Package request speedtest-cli

### ISSUE THREAD

**Issue by dgalimov** [Entware-ng/Entware-ng#621]
Please add speedtest-cli package - it is small command line package for testing internet speed using speedtest.net servers

https://github.com/sivel/speedtest-cli

Platform: ASUS RT-N56U, mipsel, but I think it may also be good to add it to other platforms as well.

**Comment by zyxmon** [comment]
It is a python script. You can install it yourself.

**Comment by TCB13** [comment]
@dgalimov just run:

```
opkg install python python-pip
pip install speedtest-cli
```
