### ISSUE TITLE
Can't find dnscrypt-proxy-common.conf

### ISSUE THREAD

**Issue by uihdff** [Entware-ng/Entware-ng#622]
### Package: dnscrypt-proxy

For existing package:

- expected behavior: To be able to configure use of TCP. There appears to be a new version of dnscrypt-proxy that is no longer configured in the S09dnscrypt-proxy file.

[https://github.com/jedisct1/dnscrypt-proxy/issues/610]

- actual behavior: Can't find dnscrypt-proxy-common.conf file

**Comment by ryzhovau** [comment]
Please, use `S09dnscrypt-proxy` start scripts with any options you need, including custom config file. 
Please, refer to `dnscrypt-proxy` manual for details.

**Comment by uihdff** [comment]
Thank you.
