### ISSUE TITLE
Entware-ng can not init when startup on QTS 4.3.3.0154 (2017/04/13)

### ISSUE THREAD

**Issue by 0xcb49** [Entware-ng/Entware-ng#623]
After upgrade QTS to 4.3.3.0154 (2017/04/13) entware can not start when nas startup. The commands installed by entware can not found as well.

**Comment by zyxmon** [comment]
There may be 2 reasons 
1. You have installed 32 version manually
2. https://forum.qnap.com/viewtopic.php?f=351&t=130320
