### ISSUE TITLE
rtorrent: error while loading shared libraries

### ISSUE THREAD

**Issue by ferrvittorio** [Entware-ng/Entware-ng#628]
Hi,
seems as I cannot  launch rtorrent, I get a 
```
[~] # rtorrent
rtorrent: error while loading shared libraries: libxmlrpc_server.so.3: cannot open shared object file: No such file or directory
```
I tried to install to QNAP TS 212 via entware-ng

Thanks

**Comment by zyxmon** [comment]
You probably need to reinstall some packages. I cannot be more specific with no information from what have you done with opkg system.
