### ISSUE TITLE
Please add package expect for sending commands

### ISSUE THREAD

**Issue by shenoyh** [Entware-ng/Entware-ng#629]
### Package: expect

For new package to be added:

- make sure there's no similar package already added: "opkg list expect" is not showing it.
- describe killer features of new package,: Great to login to routers and switches from cron and other automated scripts and perform tasks unattended. This package will enable sending username/password followed by configuration commands. This package requires tcl which is already present in the entware-ng repo and so should be an easy add.
- make sure it's open source and not abandoned (at least for last 5 years or so),: Yes standard open source package on all major linux variants.
https://sourceforge.net/projects/expect/
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.: Not Applicable.

### Platform:

- please, tell us what feed and\or devices are you using.: Would like to use it on ddwrt. Should be helpful for other openwrt users as well.

- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by ryzhovau** [comment]
Please, try `empty` utility first.

**Comment by shenoyh** [comment]
ok, good empty works ok for my needs now. Still in the future would like expect if at all possible since it has more features and better known all around and several existing scripts can be ported in.
