### ISSUE TITLE
nano is now broken

### ISSUE THREAD

**Issue by YasharF** [Entware-ng/Entware-ng#63]
Here is what I got when trying to run it, and then tried to remove and reinstall it and still didn't work:

/tmp/home/root# nano
/tmp/mnt/sdb/entware/bin/nano: can't load library 'libmagic.so.1'
:/tmp/home/root# opkg remove nano
Removing package nano from root...
Not deleting modified conffile /opt/etc/nanorc.
:/tmp/home/root# opkg install nano
Installing nano (2.4.2-1c) to root...
Downloading http://entware.zyxmon.org/binaries/mipsel/nano_2.4.2-1c_mipselsf.ipk.
Configuring nano.
:/tmp/home/root# nano
/tmp/mnt/sdb/entware/bin/nano: can't load library 'libmagic.so.1'

**Comment by YasharF** [comment]
It is a dependency issue.  I manually installed libmagic and then nano loaded fine:

:/tmp/home/root# opkg install libmagic
Installing libmagic (5.25-1) to root...
Downloading http://entware.zyxmon.org/binaries/mipsel/libmagic_5.25-1_mipselsf.ipk.
Configuring libmagic.
:/tmp/home/root# nano

**Comment by YasharF** [comment]
So here is the change that I think broke it:
https://github.com/Entware-ng/entware-packages/commit/78d2acd2ac9f1fe281e3611dc8075c951eeb9ec1

**Comment by zyxmon** [comment]
file package depends on libmagic - https://github.com/Entware-ng/entware-packages/blob/master/libs/file/Makefile

nano will crash without full file package install on editing some files. I do not understand why libmagic is not installed with file package. You are the second one to report this issue.

**Comment by YasharF** [comment]
Checking:

```
:/tmp/home/root# file -v
file-5.25
magic file from /opt/share/misc/magic
:/tmp/home/root# opkg whatdepends file
Root set:
  file
What depends on root set
        nano 2.4.2-1c   depends on file
:/tmp/home/root# opkg whatdepends libmagic
Root set:
  libmagic
What depends on root set
        file 5.25-1     depends on libmagic
```

**Comment by YasharF** [comment]
I found a clue on when this broke.  My stratup scrpts execute `opkg update` and `opkg upgrade` and put the output in a log file in /opt/var/logs.  On September 29, 2015 everything was fine, but something changed between Sep 29th and Nov 30th, since the Nov 30th opkg update/upgrades broke something.   Here is what I have in my logs:
```
Upgrading nano on root from 2.4.2-1b to 2.4.2-1c...
Downloading http://entware.zyxmon.org/binaries/mipsel/nano_2.4.2-1c_mipselsf.ipk.
Installing file (5.25-1) to root...
Downloading http://entware.zyxmon.org/binaries/mipsel/file_5.25-1_mipselsf.ipk.
libmagic was autoinstalled and is now orphaned, removing.
Removing package libmagic from root...
Configuring file.
Configuring nano.
Finished OPKG upgrade on: Nov_30_2014_16_00_29
```

**Comment by ryzhovau** [comment]
Looks like Entware -> Entware-ng upgrade issue.

**Comment by ryzhovau** [comment]
Can't reproduce that after Entware -> Entware-ng upgrade:
```
admin@RT-N66U:/tmp/mnt/OPT# wget -qO - http://entware.wl500g.info/binaries/entware/installer/entware_install.sh | sh
Info: Creating folders...
Info: Opkg package manager deployment...
…
Bug? Please report at https://github.com/Entware/entware/issues
admin@RT-N66U:/tmp/mnt/OPT# opkg install nano
Installing nano (2.4.2-1) to root...
Downloading http://entware.wl500g.info/binaries/entware/nano_2.4.2-1_entware.ipk.
Installing libncurses (5.9-2) to root...
Downloading http://entware.wl500g.info/binaries/entware/libncurses_5.9-2_entware.ipk.
Installing terminfo (5.9-2) to root...
Downloading http://entware.wl500g.info/binaries/entware/terminfo_5.9-2_entware.ipk.
Configuring terminfo.
Configuring libncurses.
Configuring nano.
admin@RT-N66U:/tmp/mnt/OPT# wget -qO - http://entware.zyxmon.org/binaries/mipsel/installer/upgrade.sh | sh
This script will upgrade existing Entware packages to Entware-ng.
…
Configuring libmagic.
Configuring file.
Configuring nano.
…
admin@RT-N66U:/tmp/mnt/OPT# opkg install ldd
Installing ldd (1.0.9-1) to root...
Downloading http://pkg.entware.net/binaries/mipsel/ldd_1.0.9-1_mipselsf.ipk.
Configuring ldd.
admin@RT-N66U:/tmp/mnt/OPT# ldd `which nano`
        libz.so.1 => /opt/lib/libz.so.1 (0x2aac0000)
        libmagic.so.1 => /opt/lib/libmagic.so.1 (0x2aae4000)
        libncursesw.so.6 => /opt/lib/libncursesw.so.6 (0x2ab14000)
        libgcc_s.so.1 => /opt/lib/libgcc_s.so.1 (0x2ab84000)
        libc.so.1 => /opt/lib/libc.so.1 (0x2abaa000)
        ld-uClibc.so.1 => /opt/lib/ld-uClibc.so.0 (0x2aaa8000)
```

**Comment by YasharF** [comment]
It looks like it worked fine after after Entware -> Entware-ng upgrade; but it broke when Nano 2.4.2-1b upgrade to 2.4.2-1c happened.

I don't remember when I did the Entware -> Entware-ng upgrade but here are my data points:

- On Sep 29th, OPKG pulled Nano 2.4.2-1 from Entware (not Entware-ng)
- nano 2.4.2-1 to 2.4.2-1b upgrade isn't logged so it was a manual run probably when I did the Entware -> Entware-ng upgrade
- My Nov 30th OPKG update/upgrade autorun did a nano 2.4.2-1b to 2.4.2-1c upgrade using Entware-ng

The 2.4.2-1b to 2.4.2-1c is what ended up marking libmagic as orphaned by error and that would be somewhere after or including the following commit:

https://github.com/Entware-ng/entware-packages/commit/058544ef4a1546f9b53b8461a634c7b625dbb03c#diff-afb2071394cd3b548dfebdcc5ee89598

**Comment by ryzhovau** [comment]
Looks like nothing we can do about that. I hope this issues will stay in past.

Thanks for the info, anyway!

**Comment by YasharF** [comment]
I agree, I don't think there is much to do here.  I suspect it is a bug in OPKG, and you may end up getting others bringing the same issue up.  For other users to solve it I think the prefered way is to remove nano and file and then reinstall nano, or just to manually install libmagic.

It looks like the opkg bug is: If both package A and B depend on package C, and only Package A and C are installed.  Changing A's dependency to B may result in C being marked as orphaned and being removed even though B gets installed as part of A's upgrade and B will be depending on C.  I will try to see if this bug is documented somewhere or if it needs to be submitted to opkg maintainers.

==================================================
Just for reference, I figure out how to reproduce it:
copy nano_2.4.2-1b_mipselsf.ipk from http://entware.zyxmon.org/binaries/mipsel/archive/ to /opt/tmp
-  opkg remove nano
-  opkg remove file
-  opkg remove libmagic
-  cd /opt/tmp
-  opkg install ./nano_2.4.2-1b_mipselsf.ipk
- opkg upgrade

and bingo! ```opkg upgrade``` will upgrade nano to 2.4.2-1c from entware.zyxmon.org/binaries/mipsel/ and says libmagic is not needed and removes it.  However, ```opkg depends``` says file still depends on libmagic, so the marking as orphaned is a bug probably in opkg upgrade (imo)


```
:/tmp/mnt/sdb/entware/usr# cd /opt/tmp
:/tmp/mnt/sdb/entware/tmp# opkg install ./nano_2.4.2-1b_mipselsf.ipk
Installing nano (2.4.2-1b) to root...
Installing libmagic (5.25-1) to root...
Downloading http://entware.zyxmon.org/binaries/mipsel/libmagic_5.25-1_mipselsf.ipk.
Configuring libmagic.
Configuring nano.
:/tmp/mnt/sdb/entware/tmp# opkg upgrade
Upgrading nano on root from 2.4.2-1b to 2.4.2-1c...
Downloading http://entware.zyxmon.org/binaries/mipsel/nano_2.4.2-1c_mipselsf.ipk.
Installing file (5.25-1) to root...
Downloading http://entware.zyxmon.org/binaries/mipsel/file_5.25-1_mipselsf.ipk.
libmagic was autoinstalled and is now orphaned, removing.
Removing package libmagic from root...
Configuring file.
Configuring nano.
:/tmp/mnt/sdb/entware/tmp# nano
/tmp/mnt/sdb/entware/bin/nano: can't load library 'libmagic.so.1'
:/tmp/mnt/sdb/entware/tmp# opkg depends nano
nano depends on:
        libc
        libssp
        libncursesw
        zlib
        file
:/tmp/mnt/sdb/entware/tmp# opkg depends file
file depends on:
        libc
        libssp
        libmagic
:/tmp/mnt/sdb/entware/tmp# opkg remove nano
Removing package nano from root...
Not deleting modified conffile /opt/etc/nanorc.
:/tmp/mnt/sdb/entware/tmp# opkg remove file
Removing package file from root...
:/tmp/mnt/sdb/entware/tmp# opkg install nano
Installing nano (2.4.2-1c) to root...
Downloading http://entware.zyxmon.org/binaries/mipsel/nano_2.4.2-1c_mipselsf.ipk.
Installing file (5.25-1) to root...
Downloading http://entware.zyxmon.org/binaries/mipsel/file_5.25-1_mipselsf.ipk.
Installing libmagic (5.25-1) to root...
Downloading http://entware.zyxmon.org/binaries/mipsel/libmagic_5.25-1_mipselsf.ipk.
Configuring libmagic.
Configuring file.
Configuring nano.
```

**Comment by ryzhovau** [comment]
Great investigation! Could you spend five more minutes to [add a ticket](https://dev.openwrt.org/newticket) for upstream?

**Comment by YasharF** [comment]
done: https://dev.openwrt.org/ticket/21427
