### ISSUE TITLE
Update Package Request : please build zsh with --enable-regex and --enable-pcre

### ISSUE THREAD

**Issue by neskweek** [Entware-ng/Entware-ng#630]
### Package: zsh
Hello

- expected behavior: be able to use some Oh My Zsh plugins and themes like powerlevel9k

- actual behavior: 
when starting zsh with powerlevel9k I get this error :  

> /root/.oh-my-zsh/custom/themes/powerlevel9k/powerlevel9k.zsh-theme:29: failed to load module: zsh/regex
> /root/.oh-my-zsh/custom/themes/powerlevel9k/powerlevel9k.zsh-theme:29: -regex-match not available for regex

The problem is that the operator **=~** is not supported with the actual build
reference : 
https://github.com/robbyrussell/oh-my-zsh/issues/227

Simple test : 
>\# [[ "$remote" =~ "github" ]]
zsh: failed to load module: zsh/regex
zsh: -regex-match not available for regex

Thank you
Best regards

**Comment by zyxmon** [comment]
We build zsh with the same configuration as openwrt. We will ad these options after openwrt adds them.
