### ISSUE TITLE
Request for Zerotier 1.2.2

### ISSUE THREAD

**Issue by songshupine** [Entware-ng/Entware-ng#631]
### Package: Zerotier 1.2.2

For existing package:

- expected behavior: fixed many bugs.
- actual behavior: ...

For new package to be added:

- make sure there's no similar package already added,
- describe killer features of new package,
- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform:

- please, tell us what feed and\or devices are you using.
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by zyxmon** [comment]
This version is available in Entware-3x only - https://github.com/Entware-for-kernel-3x/entware-packages-3x/blob/master/net/zerotier/Makefile
kernel headers are too old for the current toolchain in Enware-ng.

**Comment by meoso** [comment]
If we are stuck at Kernel 2.6.x do we have to stay Entware-NG?

**Comment by zyxmon** [comment]
Yes
