### ISSUE TITLE
How to script starting rng-tools

### ISSUE THREAD

**Issue by uihdff** [Entware-ng/Entware-ng#633]
### Package: rng-tools

For existing package:

- expected behavior: Install and run from script in init.d
- actual behavior: Installs, but does not appear to run. Is there a startup script for this daemon ?

### Platform: Asuswrt-Merlin 380.65

- Asus RT-AC88U

**Comment by zyxmon** [comment]
Not all packages have stratup scripts. You can suggest such a script - if it is universal we will add it to the package.

**Comment by uihdff** [comment]
@zyxmon ,

Thanks for the quick response.

I request a startup script be created, since if you can't get it running, there's no reason to attempt installing it.
