### ISSUE TITLE
Pandom

### ISSUE THREAD

**Issue by uihdff** [Entware-ng/Entware-ng#634]
### Package: Pandom

For new package to be added:

https://ncomputers.org/pandom

### Platform: Asuswrt-Merlin 380.65

- Asus RT-AC88U

**Comment by ryzhovau** [comment]
Is there any killer features comparing to `rng-tools`?

**Comment by uihdff** [comment]
@ryzhovau ,

There's doesn't seem to be any current interest in showing how to get it running on a system running Entware-NG packages.

# How to script starting rng-tools #633 

rng-tools may be downloadable via Entware-NG, but there's no startup script to get it running.
