### ISSUE TITLE
Package update request: zerotier

### ISSUE THREAD

**Issue by meoso** [Entware-ng/Entware-ng#636]
### Package: zerotier

For existing package:

- expected behavior: upgrade to v 1.2.4
- actual behavior: v 1.1.4

### Platform: Synology 410j ARMv5

- https://pkg.entware.net/binaries/armv5/Packages.html
- https://pkg.entware.net/binaries/armv5/zerotier_1.1.14-4_armv5soft.ipk
- https://www.zerotier.com/download.shtml
- 1.2.4 *may* have ARM issues; as per download page -- possibly why this hasn't been updated.

**Comment by zyxmon** [comment]
Dublicate - https://github.com/Entware-ng/Entware-ng/issues/631
