### ISSUE TITLE
Package Upgrade: shadowsocks-libev from 2.6.1 to 3.0.6

### ISSUE THREAD

**Issue by smounives** [Entware-ng/Entware-ng#639]
shadowsocks-libev-2.6.1 seems outdated a long time ago. please update to current 3.0.6 version.

https://github.com/shadowsocks/openwrt-shadowsocks
the openwrt [upstream](https://github.com/openwrt/packages/blob/master/net/shadowsocks-libev/Makefile) seems outdated too.

thanks.

**Comment by odkrys** [comment]
https://github.com/hqvv/openwrt-udns

libudns library will be need to compile shadowsocks-libev.

**Comment by joopdorresteijn** [comment]
+1 waiting for this one!  (shadowsocks-libev) Thanks

**Comment by zyxmon** [comment]
Please report upstream. We will update package after it is updated in openwrt - https://github.com/openwrt/packages/tree/master/net/shadowsocks-libev

**Comment by joopdorresteijn** [comment]
@zyxmon Upstream has updated the package!
https://github.com/openwrt/packages/issues/4191

**Comment by zyxmon** [comment]
We will update entware package on the next sync with openwrt.

**Comment by joopdorresteijn** [comment]
Thanks, how often does this sync happen? (no pressure, just curious)

**Comment by zyxmon** [comment]
We sync once a month or two months usually. This package was updated https://github.com/Entware-ng/entware-packages/blob/master/net/shadowsocks-libev/Makefile and will be available in binary repos soon.

**Comment by smounives** [comment]
Thanks!!!

**Comment by mdeng1024** [comment]
It seems 3.0.6 build is broken. Missing ss-server and ss-local in the package

**Comment by joopdorresteijn** [comment]
@mdeng1024 We have switched to ss-redir, 3.0.6 works fine for us.

**Comment by mdeng1024** [comment]
@joopdorresteijn thanks for the tip. I am running a SS server to my home network. if I am not wrong, ss-redir can only be used as client?

**Comment by vkedwardli** [comment]
Encountered the same problem as @mdeng1024, seems [this is not the first time](https://github.com/Entware-ng/Entware-ng/issues/39) the `ss-server` is missing?

Currently I'm using 
```
wget http://pkg.entware.net/binaries/armv7/archive/shadowsocks-libev_2.6.1-1_armv7soft.ipk
opkg --force-downgrade install shadowsocks-libev_2.6.1-1_armv7soft.ipk
```

as workaround

**Comment by odkrys** [comment]
hey guys. using this until fixing.
and simple-obfs is there if you need it.

https://drive.google.com/open?id=0B8M42Lfei1mjaEU0OFU1SjRxeEk

**Comment by shounak-de** [comment]
@joopdorresteijn How do you use `ss-redir` as `ss-server`? Can you point me to any documentation? TIA.

**Comment by joopdorresteijn** [comment]
I'm not. I'm using ss-redir to replace ss-local.

On 27 June 2017 03:26:34 GMT+08:00, redhat27 <notifications@github.com> wrote:
>@joopdorresteijn How do you use `ss-redir` as `ss-server`? Can you
>point me to any documentation? TIA.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Entware-ng/Entware-ng/issues/639#issuecomment-311157541

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xiao99xiao** [comment]
After 2 months and ss-local & ss-server are still not included.

According to here:
https://github.com/openwrt/packages/issues/4435
The openwrt seems has updated, so will Entware-ng in the next sync ?

**Comment by zw963** [comment]
after update to 3.0.6, speed is very slow in asus `AC-66U (mips)` .
see #739

**Comment by la88962** [comment]
您好:
我是用Asus RT-3200 Asuswrt-Merline 配置了Entware-arm
想安装shadowsocks-libev ss-server
但並arm v7庫裡並沒有shadowsocks-libev ss-server!
因為我不想擦Tomato(因為某些原因!)
求大神指點及幇忙
能否給我解決方法
小弟感激不盡

**Comment by zyxmon** [comment]
@la88962 - please write in English.
We do not provide detailed manuals on specific package usage. Search forums or other sites for guides on shadowsocks-libev.

**Comment by mdeng1024** [comment]
@la88962 please refer to @odkrys comments, you can download and try his custom built

**Comment by odkrys** [comment]
http://blog.naver.com/sky100301/220921764151

Written in Korean.
There are latest shadowsocks-libev, simple-obfs, kcptun, shadowsocksr-libev for armv7 devices.
I will keep them up to date.

**Comment by xiao99xiao** [comment]
@zyxmon I'll do the translation for @la88962, for the related part :

He installed Entware-arm (Now Entware-ng) on Asus RT-3200 router. After installing shadowsocks-libev from Entware-ng he couldn't found the ss-server.

Below is my own opinion:

Shadowsocks-libev in the upstream Openwrt got splitted into 6 packages. During that change, Entware-ng synced once with Openwrt packages and happened to receive a broken Shadowsocks-libev config, which results in the missing of ss-server and ss-local. 

Entware-ng needs to update the config to fix this problem.

Commit https://github.com/Entware-ng/Entware-ng/commit/a60b6419b832d76c238f024b71399c32a5ba3ac9 fixed it only for mipsel, **leaving armv5, armv7, x86, x64 still broken.**

Personally I was using armv5 so I couldn't even use @odkrys 's custom build.

**Comment by zyxmon** [comment]
For test (tha same version as mipsel)

**Comment by zyxmon** [comment]
For tests (the same version as mipsel)
http://pkg.entware.net/binaries/armv7/test/
http://pkg.entware.net/binaries/armv5/test/

**Comment by la88962** [comment]
Thank you for the great god to help,Can work now,Thank you
