### ISSUE TITLE
urbackupsrv can't start

### ISSUE THREAD

**Issue by daredevel** [Entware-ng/Entware-ng#641]
### Package: urbackup-server - 2.1.19-1

- expected behavior: 
urbackupsrv up & running

- actual behavior: 
After latest updates, urbackup server can't start.

[~] # cat /var/log/urbackup.log
2017-05-01 09:30:52: ERROR: Unable to change user, probably because process uid is not root. Errno: 0

[~] # urbackupsrv run
2017-05-01 09:54:28: ERROR: Unable to change logfile ownership
2017-05-01 09:54:28: ERROR: Unable to change user, probably because process uid is not root. Errno: 0

[~] # ll /var/log/urbackup.log
-rw-rw-rw-    1 admin    administ       204 May  1 09:54 /var/log/urbackup.log

[~] # qnaphub_tool --firmware_version
FW=14 04 15 03 4F 00 01 03

[~] # opkg list-installed
entware-opt - 222108-5
findutils - 4.6.0-1
ldconfig - 2.23-6
libc - 2.23-6
libcurl - 7.53.1-1
libgcc - 6.3.0-6
libopenssl - 1.0.2k-1
libpthread - 2.23-6
librt - 2.23-6
libssp - 6.3.0-6
libstdcpp - 6.3.0-6
locales - 2.23-6
opkg - 2011-04-08-9c97d5ec-17a
terminfo - 6.0-1c
urbackup-server - 2.1.19-1
zlib - 1.2.11-1

Please, let me know if you need more info.

Thanks for you work.

**Comment by zyxmon** [comment]
1. For latest qnap firmwares entware-3x is recommended - https://github.com/Entware-for-kernel-3x/Entware-ng-3x/wiki/Install-on-QNAP-NAS
2. New version requires `-u` switch that should be added to startup script `/opt/etc/init.d/S60urbackups-server` . For Entware-3x alternative install edit it and add it to ARGS - `ARGS="run -u root --daemon"`. For Entware-ng or standard Entware3x try to replace root with admin.
