### ISSUE TITLE
Who compiles the dnscrypt-proxy package ?

### ISSUE THREAD

**Issue by uihdff** [Entware-ng/Entware-ng#642]
### Package: dnscrypt-proxy

For existing package:

- actual behavior: The developer for dnscrypt-proxy has a new installer for Linux/arm platforms.

[https://github.com/jedisct1/dnscrypt-proxy-installer](url)

However it has a dependence on adding and modifying files in the /lib directory, which is on a read only file system. How does the Entware-NG version of dnscrypt-proxy operate without a read/write dependence on the /lib directory ?

For new package to be added: N/A

### Platform: Asus RT-AC88U running Asuswrt-Merlin 380.65

**Comment by zyxmon** [comment]
Our package is based on upstream version https://github.com/openwrt/packages/tree/master/net/dnscrypt-proxy
We have added a small postinst script
https://github.com/Entware-ng/entware-packages/blob/master/net/dnscrypt-proxy/Makefile#L116

Do you have problems with package usage?

**Comment by uihdff** [comment]
I would request dnscrypt-proxy be updated to support the dnscrypt-proxy.conf file instead of having to use command-line options with separate S09dnscrypt-proxy files.

https://github.com/jedisct1/dnscrypt-proxy/wiki/Configuration
