### ISSUE TITLE
Package Request: Snort

### ISSUE THREAD

**Issue by uihdff** [Entware-ng/Entware-ng#644]
### Package: Snort

For existing package:

- Current available Entware-NG version is 2.9.7.2-4

For new package to be added:

- Please update Snort to current version (now 3.0)

### Platform: armv7

- Asus RT-AC88U running Asuswrt-Merlin 380.65

**Comment by zyxmon** [comment]
Please report upstream. We will updated snort after it is updated in openwrt.
