### ISSUE TITLE
[Synology DSM 6] rc.local no longer executed during startup

### ISSUE THREAD

**Issue by adamrothman** [Entware-ng/Entware-ng#645]
As of DSM 6 (I think; not exactly sure when this changed), `/etc/rc.local` is no longer executed during startup. That makes the [instructions on the wiki](https://github.com/Entware-ng/Entware-ng/wiki/Install-on-Synology-NAS) out of date: the script never executes so `/volume1/@entware-ng/opt` is never mounted to `/opt`.

The simplest workaround on recent versions of DSM 6 is to use the Task Scheduler to create a triggered task (running on boot-up) that does the mounting. I have tested this personally and it works fine. See https://forum.synology.com/enu/viewtopic.php?t=116174 for more discussion on the issue.

I am happy to update the wiki accordingly but I wasn't sure whether it was cool for me to just go in there and start changing things.

### Platform:

- Synology RS2416+
- DSM 6.1.1-15101 Update 1

**Comment by ericgrancher** [comment]
In DSM 6.0, /etc/rc.local is still used, so it must be as of 6.1?

**Comment by adamrothman** [comment]
Possible. In any case it is broken on the latest DSM.

**Comment by ryzhovau** [comment]
Not related to repo itself, so I'm closing this.

**Comment by adamrothman** [comment]
I have updated the wiki accordingly.
