### ISSUE TITLE
Package Request: Sieve 

### ISSUE THREAD

**Issue by alex9434** [Entware-ng/Entware-ng#646]
### Package: dovecot-mysql

For existing package: 

- expected behavior: Sieve support
- actual behavior: doveconf: Fatal: Error in configuration file /opt/etc/dovecot/dovecot.conf: protocols: Unknown protocol: sieve

Please add sieve support for Dovecot (e.g. as seperate package)

### Platform
- Asus routner

**Comment by zyxmon** [comment]
We build packages with the same configuration as in openwrt. Some plugins may be missing.
