### ISSUE TITLE
pcap: syntax error in filter expression: syntax error

### ISSUE THREAD

**Issue by liquidwax** [Entware-ng/Entware-ng#648]
### Package: knockd

For existing package:

- expected behavior: Starts knockd daemon
- actual behavior:
stderr:
pcap: syntax error in filter expression: syntax error
waiting for child processes...
closing...

### Platform:
Entware-ng arm mounted at /opt on Asus RT-AC56U & RT-AC68U running DD-WRT v3.0-r31870M kongac (04/16/17)

**Comment by zyxmon** [comment]
I have just check knockd on a similar hardware running tomato firmware.
After adding `-i xxx` parameter to `ARGS` in `/opt/etc/init.d/S05knockd` knockd starts OK. The default interface is `eth0`, you should change it for firmwares that have different interfaces.
Please try to google before reporting here.
