### ISSUE TITLE
No valid architecture warning while updating

### ISSUE THREAD

**Issue by matteodelv** [Entware-ng/Entware-ng#65]
Hi everyone!  
I just bought a QNAP TS-131 Nas and successfully installed Entware through App Center, using the file provided. It works really well and I already installed some packages like `nano`, `nmap` and others...  
  
While I'm using `opkg` over SSH, I get a lot of warnings about wrong architecture...
Is there a way to get rid of these warnings or a way to solve this incompatibility issue?
My QNAP is arm7-based and I think I'm using the correct package listing...  
  
Here is my opkg.conf:  
> src/gz packages http://pkg.entware.net/binaries/armv7
> dest root /
> dest ram /opt/tmp
> lists_dir ext /opt/var/opkg-lists
> option tmp_dir /opt/tmp

And this is what I get doing a simple `opkg update`:
> \# opkg update
> Package fetchmail version 6.3.26-1a has no valid architecture, ignoring.
> Package fetchmail-nossl version 6.3.26-1a has no valid architecture, ignoring.
> Package libradiusclient-ng version 0.5.6-1 has no valid architecture, ignoring.
> Package libwxbase version 2.8.12-1 has no valid architecture, ignoring.
> Package oidentd version 2.0.8-2 has no valid architecture, ignoring.
> Package openswan version 2.6.43-2 has no valid architecture, ignoring.
> Package proftpd version 1.3.5a-1 has no valid architecture, ignoring.
> Package psmisc version 22.21-2 has no valid architecture, ignoring.
> Package pyload version 0.4.9-20151216-1 has no valid architecture, ignoring.
> Package pyopenssl version 0.13.1-1 has no valid architecture, ignoring.
> Package python-curl version 7.19.5.3-1 has no valid architecture, ignoring.
> Package pyxdg version 0.25-2 has no valid architecture, ignoring.
> Package radiusclient-ng version 0.5.6-1 has no valid architecture, ignoring.
> Package streamripper version 1.64.6-1 has no valid architecture, ignoring.
> Package subversion-client version 1.9.3-1 has no valid architecture, ignoring.
> Package subversion-libs version 1.9.3-1 has no valid architecture, ignoring.
> Package subversion-server version 1.9.3-1 has no valid architecture, ignoring.
> Package tftpd-hpa version 5.2-1 has no valid architecture, ignoring.
> Package tftp-hpa version 5.2-1 has no valid architecture, ignoring.
> Package time version 1.7-2 has no valid architecture, ignoring.
> Package unfs3 version 0.9.22-3 has no valid architecture, ignoring.
> Package vtun version 3.0.3-2 has no valid architecture, ignoring.
> Package weechat version 1.3-3 has no valid architecture, ignoring.
> Package wput version 0.6.2-2 has no valid architecture, ignoring.
> Package wview version 5.21.5 has no valid architecture, ignoring.
> Package xmail version 1.27-1b has no valid architecture, ignoring.
> Downloading http://pkg.entware.net/binaries/armv7/Packages.gz.
> Updated list of available packages in /opt/var/opkg-lists/packages.

Thank you so much!

**Comment by zyxmon** [comment]
This is my misteked. Thanks for reporting!

**Comment by JGrana01** [comment]
I see similar warnings on a Asus RT-88u running Asuswrt-Merlin. 
Thanks Jjg 



Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by zyxmon** [comment]
The warnings belong to the previously downloaded package list. Next time you run `opkg update` there will be no warnings.

**Comment by matteodelv** [comment]
@zyxmon Thank you so much for your fast reply and fix! Now everything works as expected! ;)

**Comment by kes31** [comment]
I see this warning for x68_64.
Greetings Kes31.

**Comment by mcandre** [comment]
No matter how many times I run `opkg update`, `opkg install gcc` and `opkg list | grep gcc` think that gcc has "no valid architecture".

I'm using OpenWRT 12.09 attitude adjustment in Docker with `echo 'src/gz packages http://pkg.entware.net/binaries/x86-64' >> /etc/opkg.conf` to add the entware repository to OpenWRT's opkg.

**Comment by ngoonee** [comment]
Thanks @mcandre that's what I was looking at as well. Fortunately the full entware install isn't too big for my router, so I don't mind maintaining two opkg roots. Just use /opt/bin/opkg when needed.

**Comment by zyxmon** [comment]
Here is my post (Russian) on using Entware with lede/openwrt
http://www.zyxmon.org/2017/08/16/ustanavlivaem-entware-na-ledeopenwrt/
