### ISSUE TITLE
libgmp package does not install gmp.h

### ISSUE THREAD

**Issue by bprager** [Entware-ng/Entware-ng#650]
### Package: libgmp

- expected behavior: I installed libgmp: 
`sudo opkg list-installed | grep gmp`
`libgmp - 6.1.2-1`
- actual behavior: for linking this library the header file needs to be available, but it's not installed:
` ls /opt/include/gmp*`
`ls: /opt/include/gmp*: No such file or directory`

### Platform:
` uname -a`
`Linux QNAP 3.4.6 #1 SMP Thu Apr 13 04:31:17 CST 2017 x86_64 GNU/Linux`

**Comment by zyxmon** [comment]
Header files should be installed manually - https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-(native-compilation)
Please not we give no support for native compilation. Use crosscompilation to build binaries.
