### ISSUE TITLE
perlbase for XML::LibXML

### ISSUE THREAD

**Issue by jorens** [Entware-ng/Entware-ng#652]
### Package: perlbase XML-LibXML

http://search.cpan.org/~shlomif/XML-LibXML-2.0129/

I tried to compile myself on my platform (x64 QNAP), but couldn't get it to work. Entwares libxml2 version 2.9.4 is not supported (blacklisted) in XML-LibXML-2.0129.

### Platform:

x64 on QNAP 469-L

**Comment by zyxmon** [comment]
we do not support native compilation, sorry.

**Comment by zyxmon** [comment]
@jorens - BTW XML-LibXML documentation states that "only versions 2.6.16 and higher are supported". 2.9.4 is higher then 2.6.16!

**Comment by jorens** [comment]
Thank you for the quick answer.

2.9.4 fails: here a quotation from the XML-LibXML Makefile.PL:

\# We keep track of the valid versions by keeping a blacklist of intervals
\# of working and not working versions where Ma.Mi.Pt <= X.Y.Z is of the same
\# state."
...
\# [2,6,16,1], \# first version to pass all tests
[2,6,18,1], \# up to 2.6.18 all ok
[2,6,19,0], \# broken c14n
[2,6,20,0], \# broken schemas
[2,6,24,1], \# all tests pass
[2,6,25,0], \# broken XPath
[2,6,32,1], \# tested, works ok
[2,7,1,0], \# broken release, broken utf-16
[2,7,6,1], \# tested, ok
[2,7,8,1], \# tested, ok
[2,9,3,1], \# schema regression
[2,9,4,0], \# schema regression
