### ISSUE TITLE
Не получается расшарить принтер через CUPS из Entware на OpenWrt Chaos Calmer

### ISSUE THREAD

**Issue by ilya-fedin** [Entware-ng/Entware-ng#653]
У меня Raspbery Pi с OpenWrt Chaos Calmer 15.05 (раньше был полноценный Linux, но MicroSD начала помирать, пришлось очень уменьшить раздел и поставить OpenWrt) и Samsung ML-1210
Раньше всегда расшаривал принтер через CUPS, дабы печатать с андроидов. Но на OpenWrt только p910nd, а принтер юзает GDI, разумеется под андроид ни одна программа не умеет в GDI. Я поставил Entware-ng, поставил cups, добавил принтер, поставил галочку "Разрешить совместный доступ", но в статусе так и пишется "нет совместного доступа". Я уже не знаю, что оно от меня хочет. Не подскажите, в чем проблема?
Если написал непонятно, поясню: проблема в том, что я ставлю галку на расшаривание, а оно не расшаривает все равно.
Ничего, что я на русском?

**Comment by zyxmon** [comment]
1. Насколько мне известно, самсунги отлично расшариваются через p910nd. Попробуйте. Может с андроидом проблема - не знаю.
2. cups в entware ЕМНИП настраивается без галочек, руками.

Если в openwrt нет cups проще собрать пакет, чем прикручивать к openwrt весь Entware.

**Comment by ilya-fedin** [comment]
@zyxmon я сделал еще "проще". Поставил debootstrap - работает на ура :)
Entware-ng я тоже не удалил, использую Deluge из него. Работает тоже на 5+.

**Comment by zyxmon** [comment]
Вам лучше поставить Entware-3x вместо Entware-ng. https://github.com/Entware-for-kernel-3x/Entware-ng-3x
Там кстати есть debootstrap в виде пакета, который упрощает установку debian и совместное использование debian и entware.
Если возникнет необходимость переустановить - переходите на Entware-3x.
