### ISSUE TITLE
Generate signatures file for compatibility with LEDE

### ISSUE THREAD

**Issue by MikeKlem** [Entware-ng/Entware-ng#654]
### Package: packages repo

For existing package: packages repo

- expected behavior: 
downloads [Packages.sig] signature file
- actual behavior:# opkg update
Downloading http://pkg.entware.net/binaries/x86-64/Packages.gz
Updated list of available packages in /var/opkg-lists/packages
Downloading http://pkg.entware.net/binaries/x86-64/Packages.sig
Signature file download failed.
Remove wrong Signature file.
Downloading http://downloads.lede-project.org/releases/17.01.0/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_core
Downloading http://downloads.lede-project.org/releases/17.01.0/targets/x86/64/packages/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.0/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_base
Downloading http://downloads.lede-project.org/releases/17.01.0/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.0/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_luci
Downloading http://downloads.lede-project.org/releases/17.01.0/packages/x86_64/luci/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.0/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_packages
Downloading http://downloads.lede-project.org/releases/17.01.0/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.0/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_routing
Downloading http://downloads.lede-project.org/releases/17.01.0/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.0/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_telephony
Downloading http://downloads.lede-project.org/releases/17.01.0/packages/x86_64/telephony/Packages.sig
Signature check passed.
Collected errors:
 * opkg_download: Failed to download http://pkg.entware.net/binaries/x86-64/Packages.sig, wget returned 8

### Platform:
LEDE Project

**Comment by zyxmon** [comment]
Entware was not designed for openwrt/lede. You can install entware on lede, but in this case you can use /opt/bin/opkg binary that does not require signatures.
