### ISSUE TITLE
WRT1900ACS v1 dd-wrt brainslayer build 31924 can't install entware

### ISSUE THREAD

**Issue by pizzulicchio** [Entware-ng/Entware-ng#655]
I have just flashed my WRT1900ACS v1 with the latest brainslayer build 👍 (31924 )
I have formatted a new usb key in ext2  but starting the installer i'm ahving this issue.

root@WRT1900ACS:/opt# wget -O - http://pkg.entware.net/binaries/armv7/installer/entware_install.sh | sh
Connecting to pkg.entware.net (81.4.123.217:80)
Info: Checking for prerequisites and creating folders...
Warning: Folder /opt exists!
Info: Opkg package manager deployment...
Connecting to pkg.entware.net (81.4.123.217:80)
wget: error getting response: Invalid argument
chmod: /opt/bin/opkg: No such file or directory
Connecting to pkg.entware.net (81.4.123.217:80)
Connecting to pkg.entware.net (81.4.123.217:80)
Connecting to pkg.entware.net (81.4.123.217:80)
wget: error getting response: Invalid argument
Connecting to pkg.entware.net (81.4.123.217:80)
wget: error getting response: Invalid argument
Info: Basic packages installation...
sh: /opt/bin/opkg: not found
sh: /opt/bin/opkg: not found
Connecting to pkg.entware.net (81.4.123.217:80)
wget: error getting response: Invalid argument
Info: Congratulations!
Info: If there are no errors above then Entware-ng was successfully initialized.
Info: Add /opt/bin & /opt/sbin to your PATH variable
Info: Add '/opt/etc/init.d/rc.unslung start' to startup script for Entware-ng services to start
Info: Found a Bug? Please report at https://github.com/Entware-ng/Entware-ng/issues

This is my config: 

root@WRT1900ACS:/opt# uname -a
Linux WRT1900ACS 3.18.51 #131 SMP Sun Apr 30 20:34:24 CEST 2017 armv7l DD-WRT

root@WRT1900ACS:/opt# busybox ash
BusyBox v1.26.2 (2017-05-02 01:16:56 CEST) built-in shell (ash)

**Comment by zyxmon** [comment]
>> wget: error getting response: Invalid argument

It looks like wget from firmware does not like arguments and cannot download files.

>> BusyBox v1.26.2 (2017-05-02 01:16:56 CEST) built-in shell (ash)

Busybox 1.26.2 has another bug in wget - https://github.com/Entware-ng/Entware-ng/issues/595
Please check if this bug is fixed before trying to install entware.
