### ISSUE TITLE
latest python packages including compiled library files

### ISSUE THREAD

**Issue by jsetton** [Entware-ng/Entware-ng#656]
### Package: python/python3

It appears that since the last update, the python packages are now including the compiled library files while the original source library files were included before. I couldn't find any information explaining this change. This is preventing some development tools such pylint from working properly.

python - 2.7.13-5
python3 - 3.6.1-1

### Platform:
QNAP TS-469L
Linux 3.4.6 x86_64 GNU/Linux

**Comment by zyxmon** [comment]
This change was introduce by openwrt after many requests to speedup execution. The information can be found upstream - https://github.com/openwrt/packages

**Comment by jsetton** [comment]
@zyxmon Thanks for pointing me in the right direction.

So based on the merged [pull request](https://github.com/openwrt/packages/pull/4130) related to this change, it looks like the source files were moved into a separate package. Any chance that package could be available in entware-ng?

**Comment by zyxmon** [comment]
There are no separate packages with sources.
