### ISSUE TITLE
pip3 - no module, two pip in system

### ISSUE THREAD

**Issue by dittohead** [Entware-ng/Entware-ng#657]
### Package: python-pip3

For existing package:
try to run _pip3 install %package_name%_

- expected behavior: pip3 install %package name"

- actual behavior: 

> Traceback (most recent call last):
>   File "/opt/bin/pip3", line 7, in <module>
>     from pip import main
>   File "/__init__.py", line 21, in <module>
>   File "/__init__.py", line 62, in <module>
>   File "/__init__.py", line 29, in <module>
> ModuleNotFoundError: No module named 'urllib3'

on force delete and **opkg install python3-pip3** got two pip3

- python3-pip - 9.0.1 - Python 3.6 pip module
- python3-pip - 8.1.2-1a

### Platform:
mi mini
mipsel

**Comment by zyxmon** [comment]
Something was broken in the latest python3 package.
To solve the problem one can download and install urllib3 and pip tar.gz archives manually. Install them by running `python3 setup.py install`. pip starts to work:

```
# pip3 install --upgrade setuptools
Collecting setuptools
  Downloading setuptools-35.0.2-py2.py3-none-any.whl (390kB)
    100% |████████████████████████████████| 399kB 139kB/s
Collecting packaging>=16.8 (from setuptools)
  Downloading packaging-16.8-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from setuptools)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Collecting six>=1.6.0 (from setuptools)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 202kB/s
Installing collected packages: six, pyparsing, packaging, appdirs, setuptools
Successfully installed appdirs-1.4.3 packaging-16.8 pyparsing-2.2.0 setuptools-35.0.2 six-1.10.0
```

**Comment by zyxmon** [comment]
May be @commodo will have a look on the issue?

**Comment by dittohead** [comment]
Cool, it works! Thank you!

**Comment by commodo** [comment]
@zyxmon 
[curious] is this specific to Entware ?
or do I have a chance of reproducing on LEDE/OpenWrt ?

**Comment by zyxmon** [comment]
@commodo 

>> is this specific to Entware ?

It should not be specific. In entware wi change installation paths. Everything else should be as in openwrt/lede.  Current python3 version of python3 is 3.6.1 - https://github.com/Entware-ng/entware-packages/blob/master/lang/python3/files/python3-version.mk

**Comment by commodo** [comment]
ack 
will check

**Comment by commodo** [comment]
On LEDE trunk it worked for me.

Had to edit  `/etc/opkg/distfeeds.conf` to enable the reboot_packages feed.

Then
```
opkg update
opkg install python3-pip
```

**Comment by zyxmon** [comment]
@commodo - can you install or update python packages with python3-pip after installation?

**Comment by commodo** [comment]
ah ; found it ; 
i get the err too

will check

**Comment by zyxmon** [comment]
@commodo just after pip & setuptools were made part of python (2.x and 3.x)  (no separate Makefiles) pip stopped to work. To make pip work one needed to run `pip install --upgrade pip setuptools`. It works now for python 2 and stopped working for python 3.

**Comment by commodo** [comment]
so, problem seems to be related to the bytecode generation for pip3 package
seems some bytecodes are not properly generated;
as quick/temp fix, i've changed pip3 to ship with just py source files

the root cause seems to be in `lede/build_dir/target-x86_64_musl/Python-3.6.1/install-pip/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py`

line `from .packages.ssl_match_hostname import CertificateError`
which is just a wrapper for `from ssl import CertificateError`

i don't know why the files in `lede/build_dir/target-x86_64_musl/Python-3.6.1/install-pip/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/packages/ssl_match_hostname `  were not compiled as the others in the pip3 build dir
