### ISSUE TITLE
Package request: Bacula-server and Bacula-client

### ISSUE THREAD

**Issue by chc88** [Entware-ng/Entware-ng#66]
Hello, Is it possible to add the Bacula system to this repo?

Thanks in advance and happy holidays

**Comment by zyxmon** [comment]
I've already compiled bacula several months ago. I had no response for a long time. Makefile is lost. I'll try to redo my previous efforts later.

**Comment by chc88** [comment]
Thanks, I noticed your post on the Qnap forum. I have also replied on that post.

**Comment by zyxmon** [comment]
what is you architecture (feed) - armv5,v7,intel?
I'll compile bacula for testing. I hope you will help me to split ipk into sub-packages, make init scripts and determine config files that should not be overwritten with upgrade/reinstall.

**Comment by chc88** [comment]
I have intel x86-32. 
The NAS I will be trying to install Bacula is an Synology DS415Play.
Currently I already have Bacula running on a Synology DS212j (arm)

Back then I created this manual http://forum.synology.com/enu/viewtopic.php?f=39&t=55414

Inits scripts and configs will not be a problem as I already have a working system, which needs to be updated from Bacula 5 to 7.

**Comment by zyxmon** [comment]
http://pkg.entware.net/binaries/x86-32/test/bacula_7.2.0-1_x86-32.ipk
this is a test package. The configuration file is a little different from the previous one and can be found in /opt/etc/bacula/scripts/bacula_config file. SQLite3 is currently used as a DB.
I was told that some scripts should be fixed (for the previous bacula build). If you need configuration or some other changes - please report.

**Comment by chc88** [comment]
When I look in the bacula_config file it looks correct for most options. Things like openssl for encryption of connections/backups are in my opinions a nice-feature, but not necessary at this point.

One point which would be "nice" is to change the following option
 Install config files:     /opt/etc
It would be better to have the config-files in /opt/etc/bacula (as the folder is created anyway and this way it would not clutter the etc-folder)

Currently setting up some real dir/fd/sd-configs to check a backup.

**Comment by zyxmon** [comment]
http://pkg.entware.net/binaries/x86-32/test/bacula_7.2.0-2_x86-32.ipk
In this version config files are in /opt/etc/bacula folder. These files are marked as configuration files and will not be overwritten during upgrade!

**Comment by chc88** [comment]
Thanks zyxmon.

The sample configs work out of the box, so that is very nice. 

The initial create_bacula_database did not work correctly. So I had to manually create the initial bacula.db. Creation of the tables did work afterwards make_sqlite3_tables.

Backup of the catalog is not yet working, there are 2 backup methods:
1) make_catalog_backup.pl MyCatalog => this gives an error about some missing file
2) make_catalog_backup=> this gives an error about some a wrong reference to the sqlite3 executable.
The backups I will look further into and report back.

Ofcourse there were a lot of folder-changes compared to my previously self-compiled version so my old configs need some reworking.

There are 3 start/stop/restart/status scripts in:
- /opt/etc/bacula/scripts/bacula-ctl-dir
- /opt/etc/bacula/scripts/bacula-ctl-fd
- /opt/etc/bacula/scripts/bacula-ctl-sd

These do NOT work out of the box, due to incompatible ps-versions and different paths.
I'll rework these and submit when acceptable.

**Comment by chc88** [comment]
I attached the 3 changed bacula-ctl-*  files, I changed the commands which used ps to determine if the process still existed.
Also the Bacula test command has been added.

For the backups;
1) to fix the perl-based backup;
- I had to install Perl, CPAN and the strict-module. I used entware-ng to install these items, there is a Synology package for Perl but I have not tried this one for now.
2)  to fix the sh-based backup;
- there were some incorrect 
[make_catalog_backup.zip](https://github.com/Entware-ng/Entware-ng/files/73533/make_catalog_backup.zip)
references from the cross-compiling I guess. My current file is attached.

**Comment by zyxmon** [comment]
Thank you for the fixes.
As for perl strict module it is in perlbase-essential package. Perl in openwrt (and in entware) is splitted into 100+ small packages. I recomend to install all perlbase* packages with `opkg list | grep perlbase- | sed 's/ - .*//' | xargs opkg install`

**Comment by zyxmon** [comment]
bacula is in arm & intel repos.

**Comment by chc88** [comment]
Thanks!

**Comment by d1nd141** [comment]
Hi,
is it possible for you to make an upgrade package?
Actually 9.0.6 is out on bacula page.
Thanks for the great work!
