### ISSUE TITLE
Package request: mpd

### ISSUE THREAD

**Issue by untiefe** [Entware-ng/Entware-ng#660]
**Package:** mpd

**Web site:** https://www.musicpd.org/

**Make sure there's no similar package already added:**
I couldn't find anything mpd related in the repository

**Describe killer features of new package:**
Music Player Daemon (MPD) is a flexible, powerful, server-side application for playing music. Through plugins and libraries it can play a variety of sound files while being controlled by its network protocol.

**Make sure it's open source and not abandoned (at least for last 5 years or so):**
GPLed - and last release is only a few days old

**Please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms:**
mpd is written in C++

**Platform:**
I'd like to use it on my NAS to stream music on the USB output

**Please, tell us what feed and\or devices are you using:**
QNAP TS-210

**Be ready to check issue-related changes or it will be closed after 30 days with "no response" status:**
I'll do - even though I don't fully understand what issue-related changes are - but I'll watch this closely and help as far as I can.

**Comment by zyxmon** [comment]
Repository already has two variants of mpd - full and mini.
