### ISSUE TITLE
package request: cpdup

### ISSUE THREAD

**Issue by rikmnet** [Entware-ng/Entware-ng#662]
### Package: <name>

cpdup

- describe killer features of new package,

-a file copy utility, standard on some distros, that will optionally erase files on target that are not on source
-complements rsync, may be faster in some circumstances, useful for keeping backups in sync
-code here on github

### Platform: 

ds1815

**Comment by ryzhovau** [comment]
Original `cpdup` was abandoned in 2008 and local fork is just [couple of patches](https://github.com/drizzt/cpdup/commits/master) upon it. 

Not sure I want to add it, sorry. Please, find some modern alternative.
