### ISSUE TITLE
upgrade.sh

### ISSUE THREAD

**Issue by fdge** [Entware-ng/Entware-ng#663]
### Package: upgrade.sh
[3/4] Deploying Entware-ng opkg package manager...
Downloading /opt/bin/opkg... success!
Downloading /opt/etc/opkg.conf... success!
Downloading /opt/etc/profile... success!
Downloading /opt/etc/init.d/rc.func... success!
Downloading /opt/etc/init.d/rc.unslung... success!
[4/4] Installing new versions of packages...
/opt/bin/opkg: line 1: syntax error: unexpected "("
/opt/bin/opkg: line 1: syntax error: unexpected "("
Done. Found a bug? Please report us at
https://github.com/Entware-ng/Entware-ng/issues

### Platform:
RT-AC3100

**Comment by zyxmon** [comment]
There is no upgrade.sh package.
My guess - you are installing entware for the wrong architecture. You should use armv7 feed for entware-ng or entware-3x depending on your firmware.
