### ISSUE TITLE
Package Request: minidnla upgraded to 1.2.0 released May 25,2017

### ISSUE THREAD

**Issue by ZacWolf** [Entware-ng/Entware-ng#664]
### Package: minidnla

For existing package:
upgrade to version 1.2.0 release May 25, 2017

**Comment by zyxmon** [comment]
We upgrade packages when syncing with upstream. Ask openwrt developers to upgrade it.

**Comment by ZacWolf** [comment]
Sorry to ask, but can ya point me in the right direction to do so?

**Comment by ZacWolf** [comment]
Nevermind, I found it.  Thanks!

**Comment by ZacWolf** [comment]
OK, I've worked with the OpenWRT folks to upgrade their upstream to the new version, how long does that take before the new package builds in Entware? Do I need to request something special for that to happen? THANKS!

**Comment by zyxmon** [comment]
Openwrt version is still 1.1.6 - https://github.com/openwrt/packages/blob/master/multimedia/minidlna/Makefile

We sync entware with openwrt approximately once a month or two - https://github.com/Entware-ng/Entware-ng/wiki/Changelog
The latest sync (binary packages were uploaded)  was yesterday.
You need not reopen the issue. You can add posts to the closed issue. minidlna in entware wil be upgraded sooner or later regardless of the issue status.

**Comment by ALEXYAL** [comment]
MiniDLNA still 1.1.6...
