### ISSUE TITLE
Segmentation Fault on ARMv7 Processor rev 4 (v7l)

### ISSUE THREAD

**Issue by seanmccully** [Entware-ng/Entware-ng#665]
### Package: entware_install.sh

For existing package:

- expected behavior: installer finished without error
- actual behavior: 

root@dd-wrt:/opt# wget -O - http://pkg.entware.net/binaries/armv7/installer/entware_install.sh | sh
Connecting to pkg.entware.net (81.4.123.217:80)
-                    100% |********************************************************************************************************************************************|  1564   0:00:00 ETA
Info: Checking for prerequisites and creating folders...
Warning: Folder /opt exists!
Info: Opkg package manager deployment...
Connecting to pkg.entware.net (81.4.123.217:80)
opkg                  39% |*******************************************************                                                                                     | 50680   0:00:01 ETA
Connecting to pkg.entware.net (81.4.123.217:80)
opkg.conf            100% |********************************************************************************************************************************************|   142   0:00:00 ETA
Connecting to pkg.entware.net (81.4.123.217:80)

Connecting to pkg.entware.net (81.4.123.217:80)
libc-2.23.so           1% |*                                                                                                                                           | 13032   0:01:33 ETA
Connecting to pkg.entware.net (81.4.123.217:80)
libgcc_s.so.1        100% |********************************************************************************************************************************************| 39632   0:00:00 ETA
Info: Basic packages installation...
Segmentation fault
Segmentation fault
Connecting to pkg.entware.net (81.4.123.217:80)
wget: error getting response: Resource temporarily unavailable
Info: Congratulations!
Info: If there are no errors above then Entware-ng was successfully initialized.
Info: Add /opt/bin & /opt/sbin to your PATH variable
Info: Add '/opt/etc/init.d/rc.unslung start' to startup script for Entware-ng services to start
Info: Found a Bug? Please report at https://github.com/Entware-ng/Entware-ng/issues

### Platform:
Netgear Nighthawk R9000

# cat /proc/cpuinfo 
model name	: ARMv7 Processor rev 4 (v7l)
processor	: 0
BogoMIPS	: 100.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0xc0f
CPU revision	: 4

**Comment by zyxmon** [comment]
It looks like you are using dd-wrt firmware with broken wget - https://github.com/Entware-ng/Entware-ng/issues/595
It downloads corrupted binaries that segfault.
