### ISSUE TITLE
can entware-ng install kmod-ipt-tproxy?

### ISSUE THREAD

**Issue by hdstar2009** [Entware-ng/Entware-ng#666]
### Package: <name>
kmod-ipt-tproxy
For existing package:
a package will use tproxy but i find my router kernel doesn't include this.
When I use openwrt in a MTK7620 router, I can opkg install kmod-ipt-tproxy.
I dont know if i can install a mod under the entware-ng?
- expected behavior: ...
- actual behavior: ...

For new package to be added:
kmod-ipt-tproxy
- make sure there's no similar package already added,
- describe killer features of new package,
- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform:
armv7
- please, tell us what feed and\or devices are you using.
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by zyxmon** [comment]
Entware is a universal repo. Kernel modules are device and firmware specific. Ask your firmware builder for this module.
