### ISSUE TITLE
Module calendar Asterisk11

### ISSUE THREAD

**Issue by Rom1985** [Entware-ng/Entware-ng#667]
**Package:** asterisk11-res-calendar
Hello. Asterisk11-res-calendar does not contain modules for accessing calendars. For example(connection module):
for iCalenda - res_calendar_icalendar.so
for CalDAV - res_calender_caldav.so
for Microsoft Exchange Server - res_calendar_exchange.so
for Microsoft Exchange Web Services - res_calendar_ews.so

In the archive only a common integration module - res_calendar.so
Do you plan to add a calendar connection module?
Without other modules, you can not connect calendars.

**Platform:** Asus RT-N56U

**Comment by zyxmon** [comment]
We buld asterisk with the same configuration as in openwrt. Please ask this question upstream.
