### ISSUE TITLE
Package Request: gerbera (replace mediatomb)

### ISSUE THREAD

**Issue by sinni800** [Entware-ng/Entware-ng#668]
Since mediatomb is now abandoned, things are moving towards "gerbera", a mediatomb fork intending to continue mediatomb.

This means pretty much that everyone should migrate

**Comment by ryzhovau** [comment]
[Release notes](https://github.com/v00d00/gerbera/releases) sounds promising. I hope mediadomb successor is far more stable and not dying on every step.

**Comment by zyxmon** [comment]
gerbera requires libupnp 1.8 or higher. Firstly we need to upgrade this lib (from packages) and check that it does not break packages that use it (mpd, djmount ...).

**Comment by ryzhovau** [comment]
`libupnp-1.8` is a separate library. I've added it to repo.

**Comment by ryzhovau** [comment]
As for me, I found Gerbera WebUI buggy as it was in Mediatomb. It's not working in modern FF and/or Edge. IE show it only in IE7 compatibility mode.

* pro: Youtube feature potentially working,
* contra: `ffmpegthumbnailer` not supported.

@sinni800, please, provide a feedback.

**Comment by sinni800** [comment]
The development of Gerbera is still ongoing, I wouldn't be surprised if they manage to repair the UI in a while. 

Mediatomb is definitely not going to fix it though... Maybe we should wait a little bit and see how development of Gerbera is progressing?
