### ISSUE TITLE
Package request: libsqlite3-dev

### ISSUE THREAD

**Issue by chc88** [Entware-ng/Entware-ng#67]
Hello, Is it possible to add more dev-versions of packages? These are used frequently when building larger applications.

Thanks in advance and happy holidays

**Comment by ryzhovau** [comment]
No. Entware (as OpenWrt upstream) will not going to support native compilation.

**Comment by zyxmon** [comment]
@chc88 - https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-%28native-compilation%29

**Comment by chc88** [comment]
zyxmon, thanks for that page I did not find that.
