### ISSUE TITLE
package request: cmake

### ISSUE THREAD

**Issue by Nick-Msk** [Entware-ng/Entware-ng#672]
### Package: cmake

For new package to be added:

- make sure there's no similar package already added: true
- describe killer features of new package: to build, for ex: mysql, clang

### Platforms:

- Arm 7 (Synology DS116), Mips (Asus AC68U)
- I'm ready to check.

**Comment by stefaang** [comment]
cmake can be made on target: 

* opkg install gcc
* source /opt/bin/gcc_env.sh
* wget https://cmake.org/files/v3.9/cmake-3.9.0.tar.gz
* tar zxvf cmake-3.9.0 && cd cmake-3.9.0
* export CXX_FLAGS="$CFLAGS $LDFLAGS"
* ./bootstrap
* make
* make install

**Comment by Nick-Msk** [comment]
Failed with 

_/var/services/homes/skelet/code/source/cmake/CMake/Source/CursesDialog/form/CURSES_INCLUDE_PATH
   used as include directory in directory /var/services/homes/skelet/code/source/cmake/CMake/Source/CursesDialog/form
CURSES_INCLUDE_PATH (ADVANCED)_

It looks like curses.h is required, but it doen't exists on device.
