### ISSUE TITLE
pkg.entware.net - SSL certificate is not trusted in Google Chrome

### ISSUE THREAD

**Issue by jamesmacwhite** [Entware-ng/Entware-ng#673]
Thought I should let you know, Google Chrome (Version 58.0.3029.110 64-bit) is flagging the pkg.entware.net domain as invalid/not trusted SSL `(NET::ERR_CERT_AUTHORITY_INVALID)`. It appears Google Chrome does not like the CA the cert is signed by.

I came across this information which explains why this is the case:

https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html

Interestingly, Mozilla did take similar action, but testing in Firefox 53, the cert is trusted.

Thought you should know!

**Comment by ryzhovau** [comment]
HTTPS is disabled for now. Thanks for report.

**Comment by IanNorris** [comment]
Is there an ETA for when HTTPS will work again? Downloading binaries or scripts over https is a really bad idea.

**Comment by ryzhovau** [comment]
Most of busybox-based embedded system doesn't support HTTPS at all so there was no any plans to support it.
