### ISSUE TITLE
Package request: rdiff-backup (stable!)

### ISSUE THREAD

**Issue by FabianF95** [Entware-ng/Entware-ng#674]
Currently Entware-ng provides rdiff-backup in version 1.3.3. However, this version is the developer/unstable version. I have severe problems running my backup with this version, it seems to be impossible to get it running.

The stable version is 1.2.8. Could you please add this package or replace it?

### Platform:

QNAP TS-459 PRO

**Comment by zyxmon** [comment]
Try to install 1.2.8 from archive subfolder
