### ISSUE TITLE
libpng 1.6.x breaks Package rrdtool

### ISSUE THREAD

**Issue by kvic-z** [Entware-ng/Entware-ng#675]
### Package: rrdtool 1.2.30-3a

After upgraded to libpng 1.6.x, rrdtool fails to load. It complains libpng12.so.0 not found. 

Temporary fix: downgrade to previous version of libpng (v1.2.x) fixed the issue.

Long term fix: a recompile of rrrdtool required?

### Platform: 

Tested only on armv7 softfloat

**Comment by zyxmon** [comment]
No need to downgrade!
Just run `opkg install --force-reinstall rrdtool`. Opkg system is not clever enough to do it.
