### ISSUE TITLE
Nmap missing scripting support

### ISSUE THREAD

**Issue by hoxia** [Entware-ng/Entware-ng#678]
### Package: nmap

Nmap appears to have been compiled without scripting support, possibly due to missing or disabled liblua dependency.

This can be observed by attempting to run one of these commands:
```
# nmap -sC
Nmap 7.40 ( https://nmap.org )
Usage: nmap [Scan Type(s)] [Options] {target specification}
[...]
SEE THE MAN PAGE (https://nmap.org/book/man.html) FOR MORE OPTIONS AND EXAMPLES
Scantype C not supported

# nmap --script
nmap: unrecognized option '--script'
See the output of nmap -h for a summary of options.
```

Also, --help output is missing the "SCRIPT SCAN" section present on nmap built with scripting support.

Would it be possible to build the current package, or an additional package, with scripting support?

### Platform:
armv7 (others not tested)

**Comment by zyxmon** [comment]
We build packages with options from openwrt. In case openwrt developers will add scripting, we will also add scripting.

**Comment by hoxia** [comment]
@zyxmon Didn't know this, thanks. I'll send this their way.
