### ISSUE TITLE
opkg <any_command> crashes router or ends with 'Killed'

### ISSUE THREAD

**Issue by diman82** [Entware-ng/Entware-ng#679]
### Package: opkg

For existing package:

- expected behavior: finish command
- actual behavior: command end with 'Killed'

For new package to be added:

- make sure there's no similar package already added,
- describe killer features of new package,
- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform:

- I'm using Netgear R7000 with DD-WRT installed.
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by zyxmon** [comment]
Probably the same problem as here - https://github.com/Entware-ng/Entware-ng/issues/595
wget downloaded corrupted opkg.

**Comment by diman82** [comment]
But router also crashes if I manually download the package (*.ipk file) and run the command like that:
opkg install /opt/var/to_install/tmux_2.3-1_armv7-3x.ipk
No wget is involved in this..

**Comment by zyxmon** [comment]
Your installation was corrupted during installation or opkg upgrade. opkg binary is corrupted and libs it uses.

**Comment by diman82** [comment]
So.. Are you suggesting to reinstall Entware (the newer version: https://github.com/Entware-for-kernel-3x/Entware-ng-3x )? Also, where is the install script for this version, I couldn't find it
Or prior to re-installation DD-WRT firmware developers should fix the problem described in: [https://github.com/Entware-ng/Entware-ng/issues/595](url)
