### ISSUE TITLE
bash has no job control

### ISSUE THREAD

**Issue by achampion** [Entware-ng/Entware-ng#68]
Intel x86_64: QNAP x53.
Version 4.3.42.1 of bash has no job control, i.e Ctrl-Z doesn't work for interactive shells.
$ jobs
bash: jobs: command not found

**Comment by zyxmon** [comment]
fixed  in https://github.com/Entware-ng/entware-packages/commit/dd7a3b87a65dc5a2365d2d8ba1174538d9a51bb8
