### ISSUE TITLE
/opt/usr/bin/ss-local: can't load library 'libsodium.so.17'

### ISSUE THREAD

**Issue by mzhboy** [Entware-ng/Entware-ng#680]
mipsel:
shadowsocks-libev load 'libsodium.so.17' which is not exist in '/opt/lib'
package libsodium use 'libsodium.so.18' instead,
I have to make a hard link for 'libsodium.so.17' to slove this problem

**Comment by ryzhovau** [comment]
As long as you are using `ss-local`, I presume you took that from archive folder. So it's an old package, linked against old `libsodium`.
