### ISSUE TITLE
minidlna stopped working after upgrade to libpng

### ISSUE THREAD

**Issue by njascgil** [Entware-ng/Entware-ng#687]
### Package: minidlna

- expected behavior: should start in daemon or interactive mode
- actual behavior: does not start and reports the following:
`/opt/bin/minidlna: can't load library 'libpng12.so.0'`

This started happening after upgrading libpng to version 1.6.29-2 using opkg update/upgrade. Minidlna was running just fine before this update. While updating I got the following info:

```
Upgrading libpng on root from 1.2.57-1 to 1.6.29-2...
Downloading http://pkg.entware.net/binaries/mipsel/libpng_1.6.29-2_mipselsf.ipk
Removing obsolete file /opt/lib/libpng12.so.0.
Removing obsolete file /opt/lib/libpng12.so.0.57.0.
Removing obsolete file /opt/lib/libpng.so.3.
Removing obsolete file /opt/lib/libpng.so.3.57.0.
```

### Platform:

- Asus RT-N56U (original version) running latest Padavan firmware downloaded from http://rt-n56u.soulblader.com/files/current/

**Comment by zyxmon** [comment]
You need to reinstall minidlna with: `opkg install --forcereinstall minidlna`.

**Comment by njascgil** [comment]
Thanks! The idea of reinstalling minidlna was great!
That exact command line didn't work and neither did `opkg install --force-reinstall minidlna`.
Then I tried the following:
```
opkg remove --autoremove minidlna
opkg install minidlna
```
And it worked!
