### ISSUE TITLE
Package Request: Bacula-FD < 7.x OR Bareos-FD

### ISSUE THREAD

**Issue by AwrThiel** [Entware-ng/Entware-ng#690]
### Package: <name>

Is there a way to get the bacula-fd older than 7.x because deamons in that version won't interact with Bareos-director Servers ? 
If that's not possible, is it then possible to get a package for baroes-fd ?
I know it's a dublicate of issue 172 and 185 but still interesting.

Kind regards
Michael

### Platform:
QNAP TS879U-RP with firmware 4.3.3.0210
Linux NAS 4.2.8 #x86_64 GNU/Linux

**Comment by zyxmon** [comment]
Previous builds can be found in archive subfolder - http://pkg.entware.net/binaries/x86-64/archive/

**Comment by AwrThiel** [comment]
Hi zyxmon, thanks for responding. 
I've seen the archive directory during my searches, but the oldest version of bucula there is 7.2.x,
To interact with Bareos-Director, I'm searching for a 5.x-version of the bacula file deamon or a bareos file deamon.

Kind regards
Michael

**Comment by guillemlc** [comment]
I would like to see full support for Bareos in Qnap. I am about to make a decision in order to buy QNAP equipment and for the moment the lack of Bareos support is making me look at other options.

**Comment by AwrThiel** [comment]
After the bacula-fd <-> bareos-dir thing doesn't work (because of the version problems ... see above), I switched from my bareos-dirctor to a bacula-director.
