### ISSUE TITLE
Package update request: SNORT

### ISSUE THREAD

**Issue by aherbjornsen** [Entware-ng/Entware-ng#695]
### Package: Snort

For existing package:

Current Snort package is 2.9.7.2 which is end of life (03/17).
Could this be updated to current release 2.9.9.0?

### Platform: armv7l

RT-AC3200 running Entware-ng on Tomato Shibby

**Comment by zyxmon** [comment]
Please ask upstream - https://github.com/openwrt/packages/blob/master/net/snort/Makefile
We will upgrade snort after openwrt.
