### ISSUE TITLE
IP address blocked from accessing pkg.entware.net?

### ISSUE THREAD

**Issue by adamrothman** [Entware-ng/Entware-ng#698]
I can't reach pkg.entware.net at all from my home IP. Ping/HTTP return no response and `opkg update` hangs indefinitely. I _can_ load pages through a proxy (I tried https://hide.me/en/proxy). Based on issues #292 and #597 it seems like maybe my IP address (which I'm happy to provide privately) has been blocked? If that is the case, could you please explain why? I am not running any kind of script that accesses the index on a regular/frequent schedule or might be mistaken for a DDoS.

**Comment by zyxmon** [comment]
We temporary block ip's downloading a lot of packages. Please try to connect later.

**Comment by adamrothman** [comment]
That's the thing though. My server doesn't download packages automatically – I have to issue the command myself. The last time I did it was probably over a month ago. If my IP was blocked, it was done in error. I would like to try to figure out why/how so it doesn't happen again.

**Comment by adamrothman** [comment]
@zyxmon I am happy to provide my IP address through a private channel. It would be useful to know (for both of us, I think) when and for how long I was blocked since, as I said, the last time I even connected to the index was weeks ago. Seems like something isn't working the way it should be.

**Comment by zyxmon** [comment]
blocked ip list is empty now. You have some other problem.

**Comment by adamrothman** [comment]
OK, thanks for letting me know. Must be something on my end.
