### ISSUE TITLE
Upgrade Request: miniDLNA 1.1.6 to 1.2.0

### ISSUE THREAD

**Issue by ALEXYAL** [Entware-ng/Entware-ng#699]
### Package: <miniDLNA>

1.2.0 - Released 17-May-2017
--------------------------------
- Add libavformat > 57 compatibility. 
- Add TiVo Bonjour discovery support using Avahi for Bolt. 
- Improve Samsung BD-J5500 support. 
- Add quirk to fix video playback on Hyundai TVs. 
- Add non-destructive update rescan support. 
- Enhance bookmark support to work with Kodi. 

Thanks!

**Comment by ryzhovau** [comment]
Duplicate of #664
