### ISSUE TITLE
Package shadowsocks-libev: missing ss-local and ss-server binaries

### ISSUE THREAD

**Issue by kvic-z** [Entware-ng/Entware-ng#701]
### Package: shadowsocks-libev 2.6.1-1

Built from Entware-ng source will have ss-local and ss-server binaries. The ipk available from the repository does not include these two binaries. Are they removed by design?

ss-server performance is superb on 800MHz Cortex A-9. Please include ss-local and ss-server.

### Platform:

Checked armv7softfloat.

**Comment by zyxmon** [comment]
Current version of shadowsocks-libev is 3.0.6. As one can see from openwrt makefile - https://github.com/openwrt/packages/blob/327c325d30e07cec1c54bc9ab9258adfbb691b87/net/shadowsocks-libev/Makefile#L74 binaries installed are ss-local ss-redir ss-tunnel ss-server
We will add them with next sync,

**Comment by kvic-z** [comment]
Great news! Cant' wait for v3 upgrade.

**Comment by xiao99xiao** [comment]
@zyxmon Pardon me but the ss-server & ss-local are critical for some people like me and the missing status has been lasting for almost 3 months. Is there any other way to get this fixed? (No offense
