### ISSUE TITLE
Package Request - PHP 7.x

### ISSUE THREAD

**Issue by KSHHDK** [Entware-ng/Entware-ng#702]
### Package: <PHP 7.x>

Killer features of new package:
Faster and more reliable than PHP 5.6.30

### Platform:

For an ASUSTOR NAS Server AS5104T.
And I'm more than ready to check issue-related changes

**Comment by zyxmon** [comment]
PHP 7 is in the repo from February - https://github.com/Entware-ng/Entware-ng/wiki/Changelog
