### ISSUE TITLE
Make world fails on "C++ style comments are not allowed in ISO C90"

### ISSUE THREAD

**Issue by faircreek** [Entware-ng/Entware-ng#704]
If you follow https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources, you will get several failures on  "C++ style comments are not allowed in ISO C90", and when you tmp fix it then you will get the same error a bit later, is there a way to turn off ISO C90 compiler setting on a global level or per package level?

Cheers Olof

PS: I'm using the armv7.config

**Comment by zyxmon** [comment]
There is no `make world` command in the wiki. Please follow wiki instructions.
Everything compiles correctly on debian jessie 64 bit.

**Comment by faircreek** [comment]
I'm sorry, but what is the point with a issue system if  closing stuff that is clearly are valid. I clarified in #705 .

**Comment by ryzhovau** [comment]
Should we change our build environment to reproduce this error? I think, no. Sorry.

**Comment by faircreek** [comment]
No, but I'm simply looking for a setting, this has to do with stricter
settings in regards to warnings errors in gcc. You will sooner or later get
this error, and keeping this ticket open will let other people how use
later releases of Ubuntu contribute to a solution. Closing it is not a wise
move in my view since the problem is there its just so that you can't
reproduce it, so let others come up with solutions. I'm currently working
on a fix.

**Comment by zyxmon** [comment]
@faircreek   If you want some help - post build output on pastebin. My guess you have this error in building tools or some other prerequisites. Compliler flags for packages are setup on per package basis. The same compiler (toolchain) is used for building packages on different distros.
If you have the same bugs when you build openwrt packages - report to lede/openwrt developers.
