### ISSUE TITLE
Package: asterisk11 - 11.25.1-1 error

### ISSUE THREAD

**Issue by vadimdr** [Entware-ng/Entware-ng#706]
### Package: asterisk11 - 11.25.1-1

3 packages were upgraded 2weeks ago:
asterisk11 - 11.22.0-2 -> 11.25.1-1
asterisk11-res-xmpp - 11.22.0-2 -> 11.25.1-1
asterisk11-chan-motif - 11.22.0-2 -> 11.25.1-1

The version asterisk11 - 11.22.0-2 worked just fine. After upgrade to 11.25.1-1, asterisk11 stopped working, constantly throwing "Illegal instruction" error and exiting. Reverting back to asterisk11 - 11.22.0-2 solves the issue.

Asterisk is being used in my x86-64 QNAP NAS device with entware-ng installed. (Linux nas 4.2.8 #1 SMP Mon Jul 3 07:22:40 CST 2017 x86_64 GNU/Linux)

**Comment by dataforce-troy** [comment]
Getting the same issue here. 
Trying to run asterisk11-11.25.1-1 on x86_64 QNAP TS-469L.

CPU:  Intel(R) Atom(TM) CPU D2701   @ 2.13GHz
Kernel: #1 SMP Mon Jul 3 05:45:46 CST 2017 (version 3.4.6)

**Comment by zyxmon** [comment]
Please check if this version is fixed
http://pkg.entware.net/binaries/x86-64/test/asterisk11/asterisk11_11.25.1-1a_x86-64.ipk
Other recompiled and probably fixed asterisk modules are here
http://pkg.entware.net/binaries/x86-64/test/asterisk11/

**Comment by dataforce-troy** [comment]
Good man!

It is now working.

**Comment by zyxmon** [comment]
Fixed via https://github.com/Entware-ng/entware-telephony/commit/45760bcd19c41faeadcb5f9ba093b35cd7259ca1
