### ISSUE TITLE
Package request: libffi-dev

### ISSUE THREAD

**Issue by liguiz** [Entware-ng/Entware-ng#708]
### Package: libffi-dev

For existing package: python module paramiko

there are package for paramiko https://github.com/NucleaPeon/OpenWRT-Python3-Utils
but it's only for bulding.

try to compile libffi source code,I didn't make it.

### Platform:armv7l

PHICOMM K3

**Comment by zyxmon** [comment]
There are no dev packages in Entware. Please read thw wiki, how to compile python packages nativly or with crosscompiler.
