### ISSUE TITLE
Package request: kcptun 20170525-1

### ISSUE THREAD

**Issue by joopdorresteijn** [Entware-ng/Entware-ng#709]
### Package: kcptun 20170525-1

Upstream source: https://github.com/xtaci/kcptun

- There is no kcp tunnel software represent for the repository at presence.
- The kcptun allows to obfuscate by routing through encrypted tunnel. This is important for countries with oppressive internet censorship. My test I found it actually improved my bandwidth by 1200% for my home network.
- 

### Platform:
ARMv7 with Shibby Tomato / AdvancedTomato v1.28 

Thank you so much!

**Comment by odkrys** [comment]
for armv7
https://drive.google.com/open?id=0B8M42Lfei1mjZy01SThZVEtLZUk

**Comment by ryzhovau** [comment]
`kcptun` is written in GO, so I'm not sure it will be handy for embedded devices.
Please, find some ligtweight alternative.

**Comment by odkrys** [comment]
I agree with ryzhovau in part.
My ac1900p router (dual core 1.4ghz) cpu usage easily reaching 100% of total 200% with youtube ~30k speed. It's enough to play 4k video.
If you just want 5mbps speed for 1080p, I guess there is no problem even mips :o.

**Comment by joopdorresteijn** [comment]
Thanks! It runs fine on my router. 6%cpu at peak

On 2017년 7월 10일 오후 7시 50분 22초 GMT+08:00, odkrys <notifications@github.com> 작성함:
>for armv7
>https://drive.google.com/open?id=0B8M42Lfei1mjZy01SThZVEtLZUk
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Entware-ng/Entware-ng/issues/709#issuecomment-314083240

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ryzhovau** [comment]
Closing for now.
