### ISSUE TITLE
[BUG] Syncthing cant get free port

### ISSUE THREAD

**Issue by Generator** [Entware-ng/Entware-ng#711]
## expected behavior 
out-of-the-box ready to use
## actual behavior
syncthing ends with `FATAL: get free port (GUI): listen tcp 127.0.0.1:0: errno -9`

### Platform:

- Tested on WNR3500v2 with TomatoUSB v140
```
$ uname -a
Linux WNR3500L 2.6.22.19 #2 Thu May 4 21:28:28 CEST 2017 mips GNU/Linux
```

## Notes
Also tested the official release of Syncthing (v0.14.32) with same issue
`syncthing -home=/opt/etc/syncthing/ -no-browser -no-restart -gui-address=0.0.0.0:8384`
with or without `-gui-address=`

**Comment by zyxmon** [comment]
Your kernel is very old.
