### ISSUE TITLE
Package Request: Wireguard

### ISSUE THREAD

**Issue by ma7dy** [Entware-ng/Entware-ng#715]
### Package: Wireguard

WireGuard is an extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography. It aims to be faster, simpler, leaner, and more useful than IPSec, while avoiding the massive headache. It intends to be considerably more performant than OpenVPN. WireGuard is designed as a general purpose VPN for running on embedded interfaces and super computers alike, fit for many different circumstances.

### Platform:
- Qnap 

https://github.com/WireGuard/WireGuard

**Comment by ryzhovau** [comment]
There's a bunch of extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography, and some of then already added.

I see no sense to add them all, so please, tell about killer features of this solution.

**Comment by paway** [comment]
# killer features as:
- Minimal Attack Surface
- High Performance
- Well Defined & Thoroughly Considered
- Cryptographically Sound
- Simple & **super**Easy-to-use
it's well designed and has a good chance to replace ipsec and openvpn.
check it out <https://www.wireguard.com/>
# Platform:
- arm

**Comment by thinrope** [comment]
Hello,
I am not still clear how easy it is, but wireguard is available both on LEDE and OpenWRT:
e.g. https://github.com/openwrt/packages/tree/master/net/wireguard

While it is still under very active development/fast-release, it is generally stable and backward compatible (so far there has been only one protocol change introducing interoperability issues).

**Comment by zyxmon** [comment]
https://www.wireguard.com/install/#kernel-requirements
 >> WireGuard requires Linux ≥3.10, with the following configuration options...

Entware is usually installed on hardware running 2.6 kernel.
