### ISSUE TITLE
alternative entware for 2.6 kernel

### ISSUE THREAD

**Issue by amurabito** [Entware-ng/Entware-ng#716]
hello, 

in entware 3x, there is mention of alternative entware. 

https://github.com/Entware-for-kernel-3x/Entware-ng-3x/wiki/General-installation-notes
> We call alternative Entware installation the case when /opt/etc/passwd and /opt/etc/group are real files (not symlinks).

Does entware-ng have alternative installation as well? I have been searching for it this morning, and haven't been able to find it. 

I have an r7000 / arm kernel on 2.6. ( 2.6.36.4brcmarm)

I would like as much flexibility as possible, and prefer the alternative install if its possible for 2.6

**Comment by jamesmacwhite** [comment]
This project should be fine for you. Entware-3x is better for routers running Kernel 3.x/4.x based firmware.

Note the toolchains used in this project for ARMv7:

https://github.com/Entware-ng/Entware-ng/wiki#internals

**Comment by zyxmon** [comment]
@amurabito - there is an experimental lib for armv7 android - http://www.zyxmon.org/2016/04/17/entware-ng-na-android/ (Russian). It was not updated for a long time. You can try to manually make alternative install with it (add hold flag for libc in opkg).
I do not recommend it and give no waranty it will work.
