### ISSUE TITLE
Package request: unoconv

### ISSUE THREAD

**Issue by juhuujo** [Entware-ng/Entware-ng#721]
I like to have unoconv - universal file converter (supported from libre office) available in entware-ng. I have a QNAP 251A and want to install a well seed dms (data management system).
regards
Jochen

**Comment by zyxmon** [comment]
It is just a python script. You can try to install it yourself. In case you need some extra python modules - use this - https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-python-modules
