### ISSUE TITLE
Package Update: ffmpeg with libmp3lame for ARMv7

### ISSUE THREAD

**Issue by johnnybainguyen** [Entware-ng/Entware-ng#723]
Package: ffmpeg
- expected behavior: Convert media file to mp3 using codec libmp3lame
- actual behavior: libmp3lame isn't compiled with the current settings.  

Platform: ARMv7
- Currently using RT5300 with merlin with entware-ng

Side Notes:
Doing a little code reading and because CONFIG_SOFT_FLOAT is set, it does not compile with libmp3lame support.  Is there a reason for this?  Is it because the platform doesn't support compilation with libmp3lame?

----- Code Start in question (Makefile in ffmpeg) ----
ifeq ($(BUILD_VARIANT),full)
	FFMPEG_CONFIGURE+= \
		$(if $(CONFIG_PACKAGE_libopus),--enable-libopus)
  ifeq ($(CONFIG_SOFT_FLOAT),y)
	FFMPEG_CONFIGURE+= \
		--enable-small \
		\
		$(if $(CONFIG_PACKAGE_shine),--enable-libshine)
  else
	FFMPEG_CONFIGURE+= \
		--enable-small \
		--enable-gpl \
		\
		$(if $(CONFIG_PACKAGE_lame-lib),--enable-libmp3lame) \
		$(if $(CONFIG_PACKAGE_libx264),--enable-libx264)
  endif
endif
---- Code End ----

(Note I do have coding knowledge but I dont know much about compiling with makefile or setting up a system capable of doing so)  Much help would be appreciated.

**Comment by zyxmon** [comment]
We use Makefile from openwrt. We use softfloat for routers without hard-float support and dd-wrt.
There is a fork with hardfloat support for arm routers with 3x kernel - http://forums.zyxmon.org/viewtopic.php?p=16708#p16708 (Russian) 
Repo is here - http://cortex-a15.zyxmon.org/binaries/cortex-a15-3x/
English discussion is on SNB forum.

**Comment by johnnybainguyen** [comment]
Reading the forum and Voxel said in the following post "Thus, this assembly is not compatible with Cortex-A9-based devices"  and he says it multiple times throughout the post.  

I'm currently using ASUS RT5300  that uses "Broadcom BCM47094 @1.4GHz SoC (ARM Cortex A9)".  So I dont think I can use this repository.  I tried installing it anyways to see if it works, it doesn't =(

**Comment by johnnybainguyen** [comment]
Can I get this issue reopened?

**Comment by zyxmon** [comment]
Just write here without reopening.

**Comment by johnnybainguyen** [comment]
Okay.  I'm still trying to figure out if my router supports hard float.  Is there a specific place where I can check?

I've tried looking up the broadcom website and lookup up the chipset, but no luck.

**Comment by zyxmon** [comment]
My guess your router does not support hardfloat, but your firmware kernel has float emulation support.

**Comment by johnnybainguyen** [comment]
My guess is that libmp3lame codec requires hard float support which is why the .config for ARMv7 has it disabled.  So the original coder instead used libshine as the mp3 encoder for soft float CPUs. 

The problem now is the setting in armv7.config doesn't have the libshine library enabled to be compiled with ffmpeg:
"# CONFIG_PACKAGE_shine is not set" - (in armv7.config)

So finally when it does a check on the variable CONFIG_PACKAGE_shine, it doesn't enable it.
"$(if $(CONFIG_PACKAGE_shine),--enable-libshine)" - (in Makefile ffmpeg)

As of now, the entware ffmpeg package does not include mp3 encoding support.  

Can someone please compile ffmpeg with mp3 encoding support either using libshine or libmp3lame?

Probably just need to add the line 
"CONFIG_PACKAGE_shine=y" to the armv7.config

**Comment by johnnybainguyen** [comment]
I'm guessing people might need this in the future to use Youtube-dl with ffmpeg when they want to convert the video files to mp3.  I dont think people care if it uses libmp3lame or libshine.

**Comment by zeroconcept** [comment]
Well, i am using youtube-dl and came across with this error which ffmpeg doesn't support libmp3lame.
I am glad that you guys working on this 👍
