### ISSUE TITLE
Package request: mplayer

### ISSUE THREAD

**Issue by Ak-911** [Entware-ng/Entware-ng#726]
Hi,

i'm very happy if you can add this package : "**mplayer**" !
i'm using Synology 6.1 on : **ARMv7** : 

processor	: 0
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 2655.84
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x4
CPU part	: 0xc09
CPU revision	: 1

processor	: 1
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 2655.84
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x4
CPU part	: 0xc09
CPU revision	: 1

Hardware	: Marvell Armada 380/381/382/383/384/385/388 (Device Tree)
Revision	: 0000

Thanks in advance, and big up to the team for maintain many binaries (very usefull 👍 )
Many thanks for your work from France ;-)

**Comment by ryzhovau** [comment]
To heavy for embedded devices, sorry.
