### ISSUE TITLE
Package request: rrdtool7

### ISSUE THREAD

**Issue by maforshaw** [Entware-ng/Entware-ng#729]
Package: rrdtool3 and/or rrdtool7
Platform: x86-64

Entware-ng currently has packages rrdtool1 and rrdtool for versions 1.0 and 1.2

The minimum supported RRDtool version is 1.3 so the software I am using doesn't work with anything earlier.

Please can we have a new package for version 1.3 or higher? I believe the newest stable release is 1.7.

Source: https://oss.oetiker.ch/rrdtool/download.en.html

Thank you.

**Comment by zyxmon** [comment]
https://github.com/Entware-ng/entware-oldpackages-ports/blob/master/rrdtool/Makefile#L7

This is the reason for old versions.
