### ISSUE TITLE
Package request: nodejs

### ISSUE THREAD

**Issue by axfree** [Entware-ng/Entware-ng#73]
Could you please add nodejs?

- Homepage
https://nodejs.org/en/

- Source code
https://nodejs.org/dist/v4.2.4/node-v4.2.4.tar.gz

**Comment by thomkaufmann** [comment]
+1

**Comment by templarundead** [comment]
+1

**Comment by zyxmon** [comment]
node is in repo. 
the name of the package is either node or node_legacy depending on the feed. mipsel version is still under some tests.

**Comment by ryzhovau** [comment]
MIPS binaries added. Please note:
* it requires A LOT of RAM on any simple operation:
```
pmap -d pidof node | grep mapped
mapped: 55540K    writeable/private: 44736K    shared: 4K
```
* `npm` uses `$HOME` directory. That can cause troubles on small system, where `$HOME` resides in tmpfs (part of RAM).
* HTTPS support seems to be broken. To make `npm` work switch to HTTP by:
```
set registry http://registry.npmjs.org
```

**Comment by thomkaufmann** [comment]
Wow, thanks!

**Comment by willin** [comment]
@ryzhovau https://nodejs.org/dist/v7.6.0/node-v7.6.0.tar.gz

**Comment by ryzhovau** [comment]
@willin, https://github.com/openwrt/packages/tree/master/lang/node

**Comment by LucasIcarus** [comment]
@ryzhovau Any plan upgrade node to the latest LTS v8.x ?

**Comment by zyxmon** [comment]
some new node versions are incompatible with softfloat used in Entware. We will try to upgrade node with upstream upgrade - https://github.com/openwrt/packages/blob/master/lang/node/Makefile
