### ISSUE TITLE
Package request: Home Assistant

### ISSUE THREAD

**Issue by mediix** [Entware-ng/Entware-ng#731]
### Package: home assistant

https://home-assistant.io/

### Platform:
I'm running Tomato Shibby on a LinksysE3200, Broadcom BCM5357 chip rev 1 pkg 10.

**Comment by zyxmon** [comment]
It is a python3 application that requires a lot of other python3 components - https://github.com/home-assistant/home-assistant/blob/dev/requirements_all.txt
There are now only few python3 packages in the repo. But still you can try to install it yourself https://github.com/Entware-ng/Entware-ng/wiki/Self-installation-of-python-modules
