### ISSUE TITLE
xmail not setting pid directory

### ISSUE THREAD

**Issue by yoyoma2** [Entware-ng/Entware-ng#732]
### Package: <xmail>

For existing package: xmail

- xmail should start up
- xmail startup script waits forever for pid file to appear
- xmail stop script also fails because pid file is missing from script's expected location

Fixed by setting XMAIL_PID_DIR in the xmail startup script.  See patch.

[patch.txt](https://github.com/Entware-ng/Entware-ng/files/1206979/patch.txt)

This seems to have been reported before and closed without fixing in "Can't stop XMail 1.27 #27".

### Platform:

Linux DD-WRT 3.10.94 #5330 SMP Sat Jan 2 06:04:55 CET 2016 armv7l DD-WRT

**Comment by yoyoma2** [comment]
It seems that the xmail startup script lives somewhere else and is patched as it is copied over to Entware-ng
by the existing patch below.  The two lines added in patch.txt above simply need to be added to the existing patch file below by someone with a build environment.

https://github.com/Entware-ng/entware-oldpackages-ports/blob/master/xmail/patches/510-xmail-start-script.patch

**Comment by zyxmon** [comment]
fixed via https://github.com/Entware-for-kernel-3x/entware-oldpackages-ports-3x/commit/5fa06d32f07d664c301a50e61c5aeea28831b813

Entware-ng will receive this fix soon.
