### ISSUE TITLE
Package request : strongswan-mod-forecast

### ISSUE THREAD

**Issue by dulemis** [Entware-ng/Entware-ng#733]
### Package: strongswan-mod-forecast

This is a part of Strongswan, not existing in Entware. It would be nice to add this feature , as it makes routing multicast and/or broadcast over VPN possible. This could obviously be well used for clients browsing Windows network shares, or different streaming clients like Plex.

**Comment by zyxmon** [comment]
Please ask upstream to add this module.
https://github.com/openwrt/packages/blob/master/net/strongswan/Makefile

**Comment by dulemis** [comment]
Thanks, I will!
I can see that it says Strongswan 5.5.3, but in Entware 5.5.2 is only available. How often is Entware updated from upstream?

**Comment by zyxmon** [comment]
We update entware every month or two months. This summer there is a delay.
I hope we will have time to update entware early in autumn.

**Comment by dulemis** [comment]
I got the following response from upstream
"strongswan-mod-forecast exists for LEDE (both master and 17.01), and for OpenWrt snapshots."

**Comment by dulemis** [comment]
I got the following response from upstream
"strongswan-mod-forecast exists for LEDE (both master and 17.01), and for OpenWrt snapshots..
This is an Entware problem, they seem to be using an outdated clone of this repo. Please take it up with them. I bumped strongswan to 5.5.3 in 960006b in May, and added strongswan-mod-forecast in 475be1d in October 2016 (!)."
