### ISSUE TITLE
nginx-extras 1.13.0 HTTP/2 mode not working

### ISSUE THREAD

**Issue by OvalII** [Entware-ng/Entware-ng#735]
### Package: nginx-extras 1.13.0

- expected behavior: works with http2 mode as well
- actual behavior: pages not loaded on Safari, ERR_SPDY_COMPRESSION_ERROR on Chrome

### Platform:
QNAP HS-251
http://pkg.entware.net/binaries/x86-64/Packages.html

**Comment by OvalII** [comment]
https://forum.nginx.org/read.php?21,275904,275910#msg-275910

**Comment by OvalII** [comment]
nginx-extras 1.13.5 still not working http2 :(

**Comment by ryzhovau** [comment]
Just checked via [this tool](https://tools.keycdn.com/http2-test), works fine.
Both on Chrome and Firefox showed test page without any issues.

**Comment by OvalII** [comment]
Yes, test passed ok. But site won’t loads :(
