### ISSUE TITLE
Package request: ShadowsocksR-libev

### ISSUE THREAD

**Issue by 275761919** [Entware-ng/Entware-ng#736]
### Package: ShadowsocksR-libev

For existing package:
- shadowsocks-libev: has no ability to obfuscate protocol

### Platform:
- ARM V7

**Comment by ryzhovau** [comment]
Not sure I want to add another obfuscating and/or GFC-breaking VPN solution. This is an endless story.
Sorry, it's out of project goal.

**Comment by wqtty** [comment]
@ryzhovau 
you are no living in China so you don't know the terrible suppression of "free Internet".
the old shadowsocks algorithm was not enough to get through the GFW,(see http://ieeexplore.ieee.org/document/8048116/?reload=true#full-text-section), so we need  to do obfuscating, which shadowsocks-libev is really good at.
So, please reconsider this.
We REALLY need it.

**Comment by ryzhovau** [comment]
I'm not a magician who can break a spell of terrible "suppression" of free Internet for you, sorry. It's up to your local laws which I have no reason to break. 

Also, not sure I have a time to play this endless game with GFW. This is 4th or 5th request. `shadowsocks-libev` was the long-living solution, but if it become useless, I just remove it as previous ones.

This is OpenWrt-based repo where you can add any package you want. You should ask local guys to add it.

**Comment by ryzhovau** [comment]
Or we can solve it that way: Ok, we'll do it last time, but if `shadowsocksr-libev` become useless, no any other anti-GFW solution will be added in future.

**Comment by wqtty** [comment]
Thank you for the reply, I have learned how to add package by myself in the past several days, so you can ignore this.
