### ISSUE TITLE
Package update: netdata 1.6 to 1.7

### ISSUE THREAD

**Issue by chrisob** [Entware-ng/Entware-ng#738]
Hi team,

I'd like to request that the netdata-1.6.0 package be updated to v1.7.

From the author of netdata: "There have been too many fixes since v1.6".
This may potentially solve some issues I've seen with netdata on embedded devices...

Thank you!

**Comment by chrisob** [comment]
@diizzyy Are you the package maintainer?  Is this something you'd be able to help with?

**Comment by diizzyy** [comment]
@chrisob 
Hmm? https://github.com/openwrt/packages/tree/master/admin/netdata
I'm not affiliated with entware-ng in any way.

**Comment by chrisob** [comment]
Ah, sorry about that then! I saw your name in the Makefile and just assumed it belonged to entware.

**Comment by chrisob** [comment]
@zyxmon Daniel has already updated netdata to 1.7 in OpenWRT's packages, would an Entware maintainer be able to port his changes?

**Comment by zyxmon** [comment]
@chrisob - I know we are late with entware & openwrt sync this time. I hope packages will be updated in September.

**Comment by zyxmon** [comment]
Done - https://github.com/Entware-ng/entware-packages/blob/master/admin/netdata/Makefile
Binaries will be awailable in few days.

**Comment by chrisob** [comment]
Since the above-mentioned update, netdata is now **missing entirely** from the mipsel package list: http://pkg.entware.net/binaries/mipsel/Packages.html.  

Even the 1.6 package is missing now.  

Are you able to either add the new 1.7 package, or re-add the 1.6 version?  Thank you.

**Comment by zyxmon** [comment]
>> netdata is now missing entirely from the mipsel package
It does not work for mipsel. If you use mipsel device, switch to entware-3x if your kerenl is 3.x or later. You'll have netdata and other applications missing in entware-ng. 
You can also try to install old netdata package from archive folder.

**Comment by chrisob** [comment]
@zyxmon 
> It does not work for mipsel. 

Are you able to elaborate why?

**Comment by zyxmon** [comment]
Because of the toolchain based on 2.6.22 kernel.
