### ISSUE TITLE
shadowsocks-libev very slow after update to 3.xx.

### ISSUE THREAD

**Issue by zw963** [Entware-ng/Entware-ng#739]
Hi, I use entware in my ASUS routes, AC-66U.

after update to shadowsocks 3.0.6. (original shadowsocks-libev split into seperate packages)
, i install only following needed three package:

shadowsocks-libev-config
shadowsocks-libev-ss-redir
shadowsocks-libev-ss-tunnel

(Addtionally, we need install rng-tool or haveged to make ss-tunnel work correct.)

it worked, as a forward transparent proxy. but, very very slow now.
(previous old version is worked quite well, but, I don't remember that version all)

I can confirm the problem is happen in client, previous old version, Youtube in my Android
phone speed is very well, but, when update to new version, Youtube only can open page,
almost could not play normally, But, if use shadowsocks android client, speed is very quickly
as usual.

So, I think maybe some issue happen for newest version,Please give me a link of old shadowsocks entware package, I want to tried it again for speed

Following is some info:

```sh
admin@RT-AC66U-20F0:/tmp/home/root# uname -a
Linux RT-AC66U-20F0 2.6.22.19 #1 Sun Jul 16 12:57:03 EDT 2017 mips ASUSWRT-Merlin
```
`shadowsocks-libev` version:  3.0.6
`haveged` version: 1.9.1-5 is installed  for resolve following warn info when run `ss-tunnel`.

```sh
admin@RT-AC66U-20F0:/tmp/mnt/sda1/entware/etc/init.d# ss-tunnel -c /opt/etc/shadowsocks.json -b 127.0.0.1 -l 1082 -L 8.8.4.4:53 -u -vvv
 2017-08-12 19:03:29 INFO: initializing ciphers... rc4-md5
 2017-08-12 19:03:29 INFO: This system doesn't provide enough entropy to quickly generate high-quality random numbers
Installing the rng-utils/rng-tools or haveged packages may help.
On virtualized Linux environments, also consider using virtio-rng.
The service will not start until enough entropy has been collected.
 2017-08-12 19:03:29 INFO: UDP relay enabled
```

Thanks

**Comment by smounives** [comment]
![image](https://user-images.githubusercontent.com/9267814/29240486-0e0c82b6-7f99-11e7-841c-677f9d79195d.png)
seems everything is good for me.

**Comment by zw963** [comment]
@smounives ,  my connect speed only 140kp - 160kb.

anyone could help give some link about old shadowsocks-libev and dependent packages

**Comment by zw963** [comment]
@smounives , That speed is tested in firefox for Android.

But, if use Youtube Android App directly, same url, same quality,
youtube keep buffering, and not play.

**Comment by zw963** [comment]
I can confirm the reason make Youtube app can not play is: the speed.

several years ago, I use squid as forward proxy,  obviously, squid is too
weight for this simple purpose, it speed is not ideally, almost same as
current situation.

when I switch to shadowsocks, same remote VPS, the effect is improve a lot.

**Comment by yicong2007** [comment]
You can use the following link to get the old 2.6.1 version:
[http://pkg.entware.net/binaries/mipsel/archive/shadowsocks-libev_2.6.1-1_mipselsf.ipk](http://pkg.entware.net/binaries/mipsel/archive/shadowsocks-libev_2.6.1-1_mipselsf.ipk)

**Comment by zw963** [comment]
I deploy shadowsocks-libev 2.6.1 with OpenSSL 1.0.2k 26 Jan 2017 version to
my router, server version keep 3.0.8
```sh
$: /usr/bin/ss-server -u --fast-open -c /etc/shadowsocks/config.json
```
It now worked, after a short time test. (within firefox browser for andorid, use pc mode),
I see Connection speed is up, 700-1200+ kbps. but for Youtube app, after short time test,
still keep caching ... maybe caused by other problem.

anywhy, I need more time do test to exclude others network issue.

Thanks

**Comment by zw963** [comment]
Hi, sorry for confuse, for recent days, seem like Youtube app speed is ideal for me.

I think that should be a network issue.

For avoid this happen again, I create a issue to Asuswrt merlin project for support tproxy 
kernel module, that is done for now.

Thanks very much.
