### ISSUE TITLE
Package request: icu4c

### ISSUE THREAD

**Issue by axfree** [Entware-ng/Entware-ng#74]
Could you please add icu4c?

- Home page
http://site.icu-project.org

- Source code
http://download.icu-project.org/files/icu4c/52.1/icu4c-52_1-src.tgz

- Corresponding ubuntu packages
root@neo:~# apt-cache search libicu
icu-devtools - Development utilities for International Components for Unicode
**libicu-dev - Development files for International Components for Unicode**
**libicu52 - International Components for Unicode**
libicu52-dbg - International Components for Unicode

**Comment by ryzhovau** [comment]
ICU is a set of C/C++ and Java libraries. How you going to use it?

**Comment by axfree** [comment]
I only need C library at the moment for use with node-icu-charset-detector.
https://github.com/mooz/node-icu-charset-detector

I tried to compile it using Entware's gcc on QNAP x86 NAS, but failed with these errors:

<pre>
...
make[2]: Leaving directory '/share/CACHEDEV1_DATA/Download/src/icu/source/data'
Unpacking ./in/icudt52l.dat and generating out/tmp/icudata.lst (list of data files)
LD_LIBRARY_PATH=../lib:../stubdata:../tools/ctestfw:$LD_LIBRARY_PATH  ../bin/icupkg -d ./out/build/icudt52l --list -x \* ./in/icudt52l.dat -o out/tmp/icudata.lst
../bin/icupkg: /lib/libc.so.6: version `GLIBC_2.7' not found (required by ../lib/libicutu.so.52)
../bin/icupkg: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by ../lib/libicutu.so.52)
Makefile:462: recipe for target 'out/tmp/icudata.lst' failed
make[1]: *** [out/tmp/icudata.lst] Error 1
make[1]: Leaving directory '/share/CACHEDEV1_DATA/Download/src/icu/source/data'
Makefile:141: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 2
</pre>

QNAP's built in libc is rather old (it's 2.6.1). I also filed a request to QNAP to upgrade their libc. For now, please add support for icu4c in Entware-ng.

Thanks.

**Comment by ryzhovau** [comment]
Please, refer to [OpenWrt Buildoot](https://wiki.openwrt.org/doc/howto/build) docs to see how to add a new packages. I see no sense to add `icu4c` to repo.
