### ISSUE TITLE
Package Request: deluge-console

### ISSUE THREAD

**Issue by newdietpi** [Entware-ng/Entware-ng#740]
Hi,

Is there a package for deluge-console?

https://dev.openwrt.org/browser/packages/net/deluge/Makefile?rev=20178

**Comment by zyxmon** [comment]
Your link is 7 years old. There is deluge package for all platforms but mipsel in the repo.
deluge segfaults on mips.
If you can use entware-3x for your device - there is a working deluge for all feeds there.

**Comment by newdietpi** [comment]
I see deluge and deluge web but not deluge console.

Is it possible to use deluge thin client?

**Comment by zyxmon** [comment]
Just try to use it. It is in /opt/bin dir.
