### ISSUE TITLE
Package description: cpio

### ISSUE THREAD

**Issue by bayonne** [Entware-ng/Entware-ng#743]
### Package: cpio

opkg info cpio

The description seems to be that of aspell and not that of the copy and archival tool named cpio.

Package: cpio
Version: 2.12-1
Depends: libc, libssp, librt, libpthread
Status: unknown ok not-installed
Section: utils
Architecture: x86-64
MD5Sum: 86ce75b2df03752f0e671b9bf132a145
Size: 99508
Filename: cpio_2.12-1_x86-64.ipk
Description: GNU cpio does a superior job of suggesting possible replacements for
 a misspelled word than just about any other spell checker out there for
 the English (and some other) language.

### Platform: x86_64

**Comment by zyxmon** [comment]
Fixed via https://github.com/Entware-ng/rtndev/commit/44956ec4bf3e777c0586cae26c80778574cd3b9e
Binary will be fixed with next sync.
