### ISSUE TITLE
Autoconf incorrectly defining presence of accept4() on Asus N66U

### ISSUE THREAD

**Issue by chrisob** [Entware-ng/Entware-ng#747]
### Package: netdata

For existing package:

- expected behavior: Package is built expecting that the system does not have an `accept4()` call
- actual behavior: Package is built assuming that `accept4()` exists, which it does not

### Platform:

The system call `accept4()` is not present, which causes issues with the netdata package running on Asus-merlin firmware on an N66U.  

As discovered [here](https://github.com/firehol/netdata/issues/2591#issuecomment-323595951), Asus-merlin does not have an `accept4()' system call, but when building the netdata package, autoconf incorrectly assumes that this system call exists.  

Is it possible to expect that `accept4()` does not exist, or will this break other packages that do not implement it if it's missing?

**Comment by ryzhovau** [comment]
We can't provide compatibility with all existent kernel 2.6.x, sorry.
You can [recompile](https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources) this package with appropriate `configure` variables.
