### ISSUE TITLE
make V=99 failed on archlinux 201708

### ISSUE THREAD

**Issue by debiansid** [Entware-ng/Entware-ng#748]
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at ./bin/automake.tmp line 3938.
make[3]: *** [Makefile:51: /home/storage/Entware-ng/build_dir/host/automake-1.15/.configured] Error 255
make[3]: Leaving directory '/home/storage/Entware-ng/tools/automake'
make[2]: *** [tools/Makefile:129: tools/automake/compile] Error 2
make[2]: Leaving directory '/home/storage/Entware-ng'
make[1]: *** [tools/Makefile:125: /home/storage/Entware-ng/staging_dir/target-arm_cortex-a9_glibc-2.23_eabi/stamp/.tools_compile_yyyyyyyyyyyyyynyyyyyyyyyyyyyyyyyyny] Error 2
make[1]: Leaving directory '/home/storage/Entware-ng'
make: *** [/home/storage/Entware-ng/include/toplevel.mk:208: world] Error 2

**Comment by debiansid** [comment]
I want compile package for my Netgear R7000 which is running DD-WRT,but looks like build host does not work on my arch Linux. 
Btw I can compile LEDE on it.

**Comment by debiansid** [comment]
I copied automake1.15.1 into entware-ng ,it works for now

**Comment by ryzhovau** [comment]
We can't support any existent Linux distros, so it's up to you, sorry.
Please, use Debian or Ubuntu.
