### ISSUE TITLE
Package update: redis 3.2.9 -> 4.0.1

### ISSUE THREAD

**Issue by argakon** [Entware-ng/Entware-ng#749]
Hello!
Can you please update redis to 4.0? Pretty cool things like async deletes, new cache eviction algo and redis uses less memory.
New redis got [modules](https://redis.io/modules) support. Can you build ReJSON, redis-timerseries modules? Actually exists one more interesting module - RediSearch, but for now only a preview version, so... may be later.

**Comment by zyxmon** [comment]
Done.
Binaries will be available in few days.
