### ISSUE TITLE
Issue with time() in gcc.

### ISSUE THREAD

**Issue by achampion** [Entware-ng/Entware-ng#75]
Programs that call time() in gcc just SEGVs:

    --- test.c ---
    #include <time.h>
    #include <stdio.h>
    int main()
    {
        time_t t = time(0)
        printf("%d", t);
        return 0;
    }
    $ gcc -g test.c
    $ a.out
    Segmentation fault
    $ gdb a.out
    (gdb) run
    0x00007ffff7df053e in ?? () from /lib64/ld-linux-x86-64.so.2
    (gdb) backtrace
    #0  0x00007ffff7df053e in ?? () from /lib64/ld-linux-x86-64.so.2
    #1  0x0000000000400605 in main () at test.c:5
    (gdb) frame 1
    #1  0x0000000000400605 in main () at test.c:5
    5           time_t t = time(0);

Am I missing something?
This is on a QNAP x86_64 intel machine.
Interestingly, calling time(0) in gdb works fine.

    (gdb) print time(0)
    $2 = 1451921634

Any help appreciated.

**Comment by zyxmon** [comment]
It loooks like you have not read the wiki and used environment variable for gcc 
https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-%28native-compilation%29

```
#include <time.h>
#include <stdio.h>
int main()
{
    time_t t = time(0);
    printf("%d", t);
    return 0;
}
$ gcc_env.sh
$ gcc -g $CFLAGS $LDFLAGS test.c
$ a.out
1451941739
```

**Comment by achampion** [comment]
I knew I was likely missing something basic - thank you.
