### ISSUE TITLE
Upgrade kernel to 4.4.80

### ISSUE THREAD

**Issue by debiansid** [Entware-ng/Entware-ng#750]
### Platform:
Netgear R7000 armv7

How to upgrade to 4.4.80

**Comment by zyxmon** [comment]
Entware is not a firmware. Please use Entware-3x - https://github.com/Entware-for-kernel-3x
Are there some kernel 4.x syscalls that speed up userspace applications compared to kernel 3.x ?
What package requires new kernel and cannot be build using 3x toolchain?

**Comment by debiansid** [comment]
Here is why 
https://github.com/jamesmacwhite/ipset-netgear-r7000-dd-wrt
I want to use same kernel as Kong build for R7000

**Comment by zyxmon** [comment]
In this case you'll need to build modified entware yourself.
Entware is a universal repository and runs on many devices. It cannot take into account some specific kernels.
Entware-3x has a new ipset, try it first. It runs on common kernels 3.x or higher.
Entware-ng has an old ipsel for 2.6 kernels - you can also try it.

**Comment by debiansid** [comment]
Got it. I have tried 3.x, but the package I compiled on it cannot be installed on R7000, Entware-ng was good. I have no idea why.
