### ISSUE TITLE
Shadowsocks-libev 3.0.6-1 -> 3.0.8

### ISSUE THREAD

**Issue by MercuryhgJiang** [Entware-ng/Entware-ng#753]
### Package: Shadowsocks-libev

Package: Shadowsocks-libev
Version 3.0.8 released

### Platform: armv7softfloat.

please add 4 binaries files ss-local ss-redir ss-tunnel ss-server.

**Comment by kvic-z** [comment]
The latest package 3.0.6-1 from Entware-ng (armv7softfloat) still does not carry **ss-server** and **ss-local**. I checked the Makefile. Believe the root cause is missing **server** and **local** in the following line:

        $(INSTALL_BIN) $(PKG_BUILD_DIR)/src/ss-{redir,tunnel} $(1)/opt/bin

**Comment by zyxmon** [comment]
Done.
Binaries will be available in few days.

**Comment by smounives** [comment]
@zyxmon Please upgrade to 3.1.1, thanks!
