### ISSUE TITLE
Shadowsocks-libev packages >= 3.0.6-2 only enabled in mipsel

### ISSUE THREAD

**Issue by op8867555** [Entware-ng/Entware-ng#755]
### Platform: armv7 (or other platform except mipsel)

Hi there,
a60b6419b832d76c238f024b71399c32a5ba3ac9 enabled latest shadowsocks packges (`shadowsocks-libev-config`, `shadowsocks-libev-ss-local`, `shadowsocks-libev-ss-redir`, `shadowsocks-libev-ss-rules`, `shadowsocks-libev-ss-server`, `shadowsocks-libev-ss-tunnel`) in mipsel.config, but others still have the old `shadowsocks-libev` package only. Is there any reason for this? 

BTW, I built `shadowsocks-libev-ss-server` for armv7 and I can comfirm it works as expected on a synology ds216j.

**Comment by zyxmon** [comment]
Version 3.0.8 will available for all feeds in few days.
