### ISSUE TITLE
Package request: Clang

### ISSUE THREAD

**Issue by Nick-Msk** [Entware-ng/Entware-ng#757]
### Package: **clang**

Improved c/c++ compiler.  Better than gcc. Primary on macos. 

### Platform:     Arm 7 (Synology DS116)

I tried to build it witl cmake, but without success. 

Error when building libLTO:

_/opt/bin/ld: failed to set dynamic section sizes: Memory exhausted
collect2: error: ld returned 1 exit status
make[2]: *** [tools/lto/CMakeFiles/LTO.dir/build.make:268: lib/libLTO.so.6.0.0svn] Error 1
make[1]: *** [CMakeFiles/Makefile2:14196: tools/lto/CMakeFiles/LTO.dir/all] Error 2
make: *** [Makefile:152: all] Error 2_

Device has 1GB real memory. 
I increased swap +=6GB but get the same error.  

_user@nserv:/volume1/homes/user/code/source/clang/builddir$ swapon
NAME              TYPE      SIZE   USED PRIO
/dev/sda2         partition   2G 291.1M   -1
/volume1/swap.swp file        4G   140K   -2_

**Comment by Nick-Msk** [comment]
upd: build is done using `-D CMAKE_BUILD_TYPE="Release"`

but **make install** 
_CMake Error at tools/llvm-split/cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/volume1/homes/skelet/code/source/clang/builddir/bin/llvm-split" to
  "/usr/local/bin/llvm-split".
Call Stack (most recent call first):
  tools/cmake_install.cmake:87 (include)
  cmake_install.cmake:66 (include)_

**Comment by Nick-Msk** [comment]
upd: 

now it's installed, but really not working

_skelet@nserv:~/code/tests$ cat hello.c
#include <stdio.h>
int             main(void){
        printf("Hello, World!\n");
}
skelet@nserv:~/code/tests$ clang --version
clang version 6.0.0 (https://github.com/llvm-mirror/clang.git 9b13d907c509a53fd938dcc777bb7dd097cea4c0) (https://github.com/llvm-mirror/llvm.git 707fb1cf0ca99d98c59f1ae87b7e0ff9b2dd0c8b)
Target: armv7l-unknown-linux-gnueabi
Thread model: posix
InstalledDir: /usr/local/bin
skelet@nserv:~/code/tests$ which clang
/usr/local/bin/clang
skelet@nserv:~/code/tests$ clang hello.c -o hello
hello.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated._

Even if set CFLAGS - it's useless: 

_skelet@nserv:~/code/tests$ echo $CFLAGS

skelet@nserv:~/code/tests$ export CFLAGS=-I/opt/include
skelet@nserv:~/code/tests$ clang hello.c -o hello
hello.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated._

**Comment by TCB13** [comment]
+1 here!

**Comment by zyxmon** [comment]
Please ask upstream for clang. We will port it to entware.

**Comment by Nick-Msk** [comment]
opkg update
Downloading http://pkg.entware.net/binaries/armv7/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/packages
:~$ opkg list | grep -i clang
