### ISSUE TITLE
libexpat1-dev

### ISSUE THREAD

**Issue by Janpopan** [Entware-ng/Entware-ng#76]
or an other Solution to get XML::Simple in perl an qnap armv5

**Comment by zyxmon** [comment]
There are no dev packages in entware and openwrt. You can try native compiling using this guide
https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-%28native-compilation%29

There is XML::Parser package in Openwrt that can be easily built. Can you substitute XML::Simple with XML-Parser?
