### ISSUE TITLE
Package Request: Byobu

### ISSUE THREAD

**Issue by rodoviario** [Entware-ng/Entware-ng#760]
### Package: <name>Byobu

For new package to be added:
- make sure there's no similar package already added,
Its an improved version of tmux / screen

- describe killer features of new package,
easy for the newbies

- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform: AsusWrt-Merlin

- please, tell us what feed and\or devices are you using.
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by kernhanda** [comment]
+1 for this

**Comment by zyxmon** [comment]
byoby is a set of shell, perl & python scripts. It looks like a lot of manual modifications should be made for embedded linux to run byobu properly.
You can install byobu manually and try yourself. Compilation is not needed.
If you successed, please publish your modifications - we will embed them into ipk.
