### ISSUE TITLE
Package pixelserv-tls: new Version Kk released

### ISSUE THREAD

**Issue by kvic-z** [Entware-ng/Entware-ng#770]
### Package: pixelserv-tls

New version v35.HZ12.Kk. 

GitHub source for this release: https://github.com/kvic-z/pixelserv-tls/tree/v35.HZ12.Kk 

Please update Entware-ng Makefile as below to turn on support for pthread in pixelserv-tls:
```
diff --git a/pixelserv-tls/Makefile b/pixelserv-tls/Makefile
index 8d6ba3f..ab8d639 100644
--- a/pixelserv-tls/Makefile
+++ b/pixelserv-tls/Makefile
@@ -38,8 +38,8 @@ endef
 
 define Build/Compile
        $(TARGET_CC) \
-               $(TARGET_CPPFLAGS) -DDROP_ROOT -DIF_MODE \
-               $(TARGET_LDFLAGS) -lssl -lcrypto \
+               $(TARGET_CPPFLAGS) -DDROP_ROOT -DIF_MODE -DUSE_PTHREAD \
+               $(TARGET_LDFLAGS) -lssl -lcrypto -lpthread \
                $(PKG_BUILD_DIR)/util.c \
                $(PKG_BUILD_DIR)/socket_handler.c \
                $(PKG_BUILD_DIR)/pixelserv.c \
```

Thanks

**Comment by ryzhovau** [comment]
[Done](https://github.com/Entware-ng/rtndev/commit/84cd0311162c5077ff984c7d0d41cd6eb929f96a). Binaries will arrive in next week as long as we are in the middle of monthly update.
