### ISSUE TITLE
Entware install don't match AS_NAS_ARCH variable ... search uname

### ISSUE THREAD

**Issue by FRYYYYYY** [Entware-ng/Entware-ng#771]
### Package: entware-ng-0.97.2

Installation of the package via ASUSTOR appstore or apk download is not possible.
I using the latest ASUSTOR ADM 3.0.1 - with 3.0.0 it was also not possible.

The error message at ADM's logfile:

"Entware install don't match AS_NAS_ARCH variable ... search uname"

Output of uname -m is: i686

### Platform:

- ASUSTOR 204T with ADM 3.0.1R9J2

**Comment by zyxmon** [comment]
Asustor packages are not parts of Entware project. 
Please contact package manufacturer or use install script.
