### ISSUE TITLE
nsd4.1.13 can not compile 

### ISSUE THREAD

**Issue by debiansid** [Entware-ng/Entware-ng#773]
### Package: <name>
nsd
For existing package:

- expected behavior: ... compiled and running 
- actual behavior: ...
stopped at 
```
checking for SSL... configure: error: Cannot find the SSL libraries in /home/storage/Entware-ng/staging_dir/target-arm_cortex-a9_glibc-2.23_eabi/usr
```
the right place should be 
`staging_dir/target-arm_cortex-a9_glibc-2.23_eabi/opt/include/openssl/`

where I can make change in Makefile?

thanks

**Comment by debiansid** [comment]
```
ifeq ($(BUILD_VARIANT),ssl)
        CONFIGURE_ARGS += \
                --with-ssl="$(STAGING_DIR)/opt"
```
ok, I found it. and every /usr in Makefile should be replaced by /opt

**Comment by herrold** [comment]
@debiansid usually with most auto-tools, this is abstracted tp $(PREFIX), rather than an hard-coded /opt

**Comment by debiansid** [comment]
Not all packages are checked by compiling, I guess
