### ISSUE TITLE
Package Request: Telegram-cli

### ISSUE THREAD

**Issue by alienx2** [Entware-ng/Entware-ng#774]
Package: Telegram-cli

This is useful for send message to yourself or your friend using bash script or via telnet/SSH.

can be like example:
- Away from home/office router
- can receive alert/status/report message from router
- notification system

Platform: Asuswrt-merlin MIPS and Arms
Hardware: Asus RT-AC88U & Asus RT-AC66U
link: https://github.com/vysheng/tg

example script: https://blog.mypapit.net/2015/09/a-bash-script-for-sending-telegram-messages-in-linux.html

**Comment by zyxmon** [comment]
Just use it - https://github.com/Entware-ng/rtndev/tree/master/telegram-cli
It was add in Entware (not Entware-ng) some time ago.
