### ISSUE TITLE
Don't work Apache

### ISSUE THREAD

**Issue by sasa1978** [Entware-ng/Entware-ng#775]
### Platform: ASUS AC88U + Merlin 380.67

1. Install Entware: entware-setup.sh

2. opkg update, opkg upgrade

3. opkg install mc apache

4. httpd.conf > # Group nogroup

5. ./S80apache start

6. In Log>
This function has not been implemented on this platform: AH03312: apr_thread_pool_create() with 16 threads failed

6. If i try to get a page: Server return 500 error

Log In Attach

**Comment by sasa1978** [comment]
[error_log.log](https://github.com/Entware-ng/Entware-ng/files/1340692/error_log.log)

**Comment by zyxmon** [comment]
This is upstream bug - https://github.com/openwrt/packages/issues/4840
Let's wait for a fix. You can try an old version from archive before the fix is available.
