### ISSUE TITLE
mkvtoolnix looking for previous version boost libraries

### ISSUE THREAD

**Issue by shawnhicks** [Entware-ng/Entware-ng#776]
### Package: mkvtoolnix - 12.0.0-1
For existing package:

- expected behavior: ...
finds 1.65.0-1 boost libraries
- actual behavior: ...
[~] # ldd `which mkvmerge`
        linux-vdso.so.1 (0x00007ffd9f2fd000)
        libstdc++.so.6 => /opt/lib/libstdc++.so.6 (0x00007f8ae6bf3000)
        libintl.so.8 => /opt/lib/libintl.so.8 (0x00007f8ae69e9000)
        libmagic.so.1 => /opt/lib/libmagic.so.1 (0x00007f8ae67ca000)
        libz.so.1 => /opt/lib/libz.so.1 (0x00007f8ae65b4000)
        libmatroska.so.6 => /opt/lib/libmatroska.so.6 (0x00007f8ae62ed000)
        libebml.so.4 => /opt/lib/libebml.so.4 (0x00007f8ae60c8000)
        libiconv.so.2 => /opt/lib/libiconv.so.2 (0x00007f8ae5de3000)
        libboost_regex.so.1.64.0 => not found
        libboost_filesystem.so.1.64.0 => not found
        libboost_system.so.1.64.0 => not found
        libFLAC.so.8 => /opt/lib/libFLAC.so.8 (0x00007f8ae5b72000)
        libogg.so.0 => /opt/lib/libogg.so.0 (0x00007f8ae596b000)
        libvorbis.so.0 => /opt/lib/libvorbis.so.0 (0x00007f8ae5740000)
        libm.so.6 => /opt/lib/libm.so.6 (0x00007f8ae542f000)
        libgcc_s.so.1 => /opt/lib/libgcc_s.so.1 (0x00007f8ae5218000)
        libc.so.6 => /opt/lib/libc.so.6 (0x00007f8ae4e7d000)
        /opt/lib/ld-linux-x86-64.so.2 (0x00007f8ae6f72000)
        librt.so.1 => /opt/lib/librt.so.1 (0x00007f8ae4c75000)
        libpthread.so.0 => /opt/lib/libpthread.so.0 (0x00007f8ae4a57000)

For new package to be added:

- make sure there's no similar package already added,
- describe killer features of new package,
- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform:
qnap ts870 firmware 4.3.3.0299 - Entware-3x 0.98std

- please, tell us what feed and\or devices are you using.
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by shawnhicks** [comment]
mkvtoolnix release 16.0.0 is available, maybe an update is in order?

**Comment by zyxmon** [comment]
Please do not duplicate issues in Entware-3x and Entware-ng.
Opkg is not always clever enough in upgrades. Just remove mkvtoolnix and reinstall it

```
opkg remove --autoremove mkvtoolnix
opkg install mkvtoolnix
```

If it does not help, reinstall appropriate boots libs using `--force-depends` flag.

**Comment by shawnhicks** [comment]
Is this because even though mkvtoolnix (12.0.0-1) was recompiled for the later boost libraries, the revision wasn't incremented? i.e. -1 to -2

**Comment by ryzhovau** [comment]
> Is this because even though mkvtoolnix (12.0.0-1) was recompiled for the later boost libraries, the revision wasn't incremented? i.e. -1 to -2
Yes. On one hand, revision incremented only if some patches/configuration package changed in LEDE/OpenWrt. On the other hand, `opkg` is too stupid to track re-linked binaries.

**Comment by shawnhicks** [comment]
Thanks for the info. I looked at the package indexes and control files. It appears that the currently installed packages status are stored in /opt/lib/opkg/info, control files contain "Installed-Size:" attributes. I'm sure it would be more reliable to store either of the checksum attributes, but why shouldn't opkg compare installed size and version to select upgrades? I'm frustrated that the opkg tool is "not always clever enough" and "too stupid"; this shouldn't be a problem. It especially shouldn't be a problem I've run into more than once. 
My entware-3x opkg version (-v) is 0.1.8 (4 years old) and opkg list shows 2011-04-08-9c97d5ec-17a, but I found the latest version is 0.3.5 (4 months old). It's possible these issues have been corrected, but I couldn't find anything definitive in the mailing list archive. Is the latest opkg version available for entware-3x?

**Comment by zyxmon** [comment]
I have already tried the new opkg binary. It is not compatible with the old one and requires a lot of changes inluding buildroot scripts. New opkg is used in openembedded and yoktoproject.
There is also opkg fork in lede now. Probably some bugs are fixed there. But it looks like it has the same "stupidness" as the opkg in entware. Probably we will switch to lede version in future.
