### ISSUE TITLE
Package: strongswan-mod-forecast

### ISSUE THREAD

**Issue by dulemis** [Entware-ng/Entware-ng#777]
Refering to an old, closed issue.

I've recently upgraded to Strongswan 5.6.0 via Entware (opkg), however still the forecast-plugin is missing.
On the openwrt Gitbuh they told me following:

This is an Entware problem, they seem to be using an outdated clone of this repo. Please take it up with them. I bumped strongswan to 5.5.3 in 960006b in May, and added strongswan-mod-forecast in 475be1d in October 2016 (!).

**Comment by zyxmon** [comment]
There were some  problems adding it. I'll keep the issue open, probably it will be added later.

**Comment by dulemis** [comment]
Hi, thank you! Are able to specify later? :)

**Comment by dulemis** [comment]
Alternately, maybe you could assist me in finding the right version for mt Netgear R6250? (ARMv7 Processor rev 0 (v7l)?

From Openwrt github:
Maybe you can add one of the arm package targets from https://downloads.lede-project.org/snapshots/packages/ to /etc/opkg/customfeeds.conf. You'll have to figure out which ones are compatible with your device.

Or you could simply use LEDE instead of Entware.

**Comment by zyxmon** [comment]
1. May be later.
2. If you can install lede instead of firmware - you can use openwrt packages that strongly depend on libc from firmware.

**Comment by dulemis** [comment]
Why maybe? It exists in upstream, so what's the problem with Entware?
