### ISSUE TITLE
Rclone Dropbox auth error

### ISSUE THREAD

**Issue by glemag** [Entware-ng/Entware-ng#778]
Rclone, v1.37, since Dropbox shutted down Auth 1 at 28 September get an error with Token in Rclone like: 

Folowing Auth link https://www.dropbox.com/1/oauth2/authorize?client_id=XXXXXXXXXXXXXX&response_type=code

I got a code: EajdoXXXXXXXXXXXXXBfwPaYynYYYYYYsQ8-epM85Lc

And paste to rclone result, got an error:

**2017/10/05 08:59:46 Failed to configure token: invalid character 'E' looking for beginning of value**

How to fix it?

**Comment by zyxmon** [comment]
You should ask rclone support on it. Version 1.37 supports dropbox v2 api as I can see from rclone github pages.

**Comment by glemag** [comment]
They said that they fixed it in 1.38. When we can get updated package?
