### ISSUE TITLE
malformed /opt/bin/ldd (x87-64)

### ISSUE THREAD

**Issue by mcandre** [Entware-ng/Entware-ng#784]
### Package: ldd

For existing package:

- expected behavior: `/opt/bin/ldd --help` => Some usage message
- actual behavior: `ash: /opt/bin/ldd: not found`

### Platform:

* Latest entware install sh for x86-64
* OpenWRT 12.09
* Docker 17.09.0-ce

ls confirms that the ldd binary was placed there in /opt/bin, by `opkg install ldd`. Strangely, readelf reports that /opt/bin/ldd is in fact not an ELF binary!

```console
# ls -Ahl /opt/bin/ldd
-rwxr-xr-x    1 root     root        5.6K Sep 25 14:26 /opt/bin/ldd

# readelf -d /opt/bin/ldd
readelf: Error: Not an ELF file - it has the wrong magic bytes at the start
```

**Comment by zyxmon** [comment]
ldd is a script.
