### ISSUE TITLE
Entware-ng apache server

### ISSUE THREAD

**Issue by gnankov** [Entware-ng/Entware-ng#786]
### Package: Entware-ng apache 2.4.27

For existing package:

- expected behavior: When you install, start and try it from browser Firefox - expected to see the very simple: "It works!" page.
- actual behavior: Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at webmaster@dummy-host.example.com to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.
Additionally, a 400 Bad Request error was encountered while trying to use an ErrorDocument to handle the request.

For new package to be added:

- Connection to Tomcat using ajp workers balancer jk_mode module pre-installed and pre-loaded.

### Platform:

- QNAP TS-451 Firmware 4.3.3.xxx

**Comment by zyxmon** [comment]
Entware is a universal repo. You need to adopt some packages for your hardware/firmware. The same package cannot somtimes у run on a nas, router, android box without changing configuration.

**Comment by gnankov** [comment]
First I installed manually Entware-ng_0.97.qpkg on QNAP TS-451.
Then using shell on QNAP I installed apache: opkg install apache
This is supposed to bring all ADOPTED packages for the particular QNAP Firmware, isn't it?
The default configuration I checked was pretty straightforward and simple, and the "It works" page was already there. 
It just does not work. What package I need to adopt for QNAP TS-451 Firmware 4.4.4 that you are referring of? There is something wrong in that particular version of apache server 2.4.27 compiled for QNAP TS-451 Firmware 4.3.3

**Comment by zyxmon** [comment]
>> This is supposed to bring all ADOPTED packages for the particular QNAP Firmware, isn't it?

No. The packages are the same for different devices. The same for qnap, synology and other....
90% of packages work out of the box. Some need adoptation - add users, groups. Add missing binaries. Cange some pathes in config, etc...As for Qnap - I recomend Entware-3x. Entware-ng was desighned for devices with 2.6 kernel.

**Comment by gnankov** [comment]
Good to know. Thank you.
Regards.
