### ISSUE TITLE
zerotier not working on tomato

### ISSUE THREAD

**Issue by halfu** [Entware-ng/Entware-ng#788]
### Package: zerotier

For existing package:

- expected behavior: 
`zerotier-cli join 'netID'` should join a private network.
- actual behavior: 

> ERROR: unable to configure virtual network port: could not open TUN/TAP device: No such file or directory
200 join OK

It actually got an IP address from zerotier server,  but had problems setup the TUN/TAP device.

**Comment by zyxmon** [comment]
Tomato by Shibby has tun.ko kernel module. My guess - you need to setup your tun/tap interface.
