### ISSUE TITLE
Package request: httpry

### ISSUE THREAD

**Issue by tenwx** [Entware-ng/Entware-ng#789]
### Package: httpry

For existing package:

- expected behavior: HTTP logging and information retrieval tool
- actual behavior: Just tcpdump

The source code is located here:

https://github.com/jbittel/httpry.git

### Platform:

Asus RT-AC68U

**Comment by ryzhovau** [comment]
Binaries will arrive soon.

**Comment by ryzhovau** [comment]
Damn! As long as it doesn't support HTTPS, it's quite useless.

Not sure it will be handy for Entware, sorry.
