### ISSUE TITLE
Package update request: dnsmasq-full

### ISSUE THREAD

**Issue by kpschaper** [Entware-ng/Entware-ng#790]
### Package: dnsmasq-full

The current version is 2.77 but a lot of vunerablillties / exploids have been found by Google.
https://security.googleblog.com/2017/10/behind-masq-yet-more-dns-and-dhcp.html

These have been patched in version 2.78!

### Platform: 

I'm currently using Entware-ng on a Qnap armv5 nas!

**Comment by zyxmon** [comment]
>> I'm currently using Entware-ng on a Qnap armv5 nas!

I strongly recommned Entware-3x for qnap nases. It already has dnsmasq 2.78.

**Comment by kpschaper** [comment]
I upgraded to Entware-3x, Thanks!
