### ISSUE TITLE
TEE mode on iptables doesnt work, maybe need to update to latest?

### ISSUE THREAD

**Issue by itay-sho** [Entware-ng/Entware-ng#794]
### Package: iptables/ xtables-addon

- expected behavior: duplicate packets using TEE should work
- actual behavior: it doesn't :( 
when trying:
iptables -t mangle -A PREROUTING -s <some ip> -j TEE --gateway <other_ip>
the result is:
iptables: No chain/target/match by that name.

looking on the web it seems like kind of familiar problem, when most of the people gave up on that config

For new package to be added: according to a post I read, maybe adding xtables-addon would fix it, another thing that might cause a problem is most recent iptable version on the package manager.

### Platform:
I am using mispel-based router (xiaomi mi router 3)

**Comment by zyxmon** [comment]
You need a corresponding netfilter module in your firmware for such commands to work. These modules cannot be part of entware.
