### ISSUE TITLE
ssldump help!

### ISSUE THREAD

**Issue by xietian1** [Entware-ng/Entware-ng#795]
### Package: ssldump

For existing package:
I want to use it on my wifi router AC1750. However, none of existing packages can work on the router.

### Platform:
AC1750 (mips_24kc) LEDE platform

If possible, I'm willing to get the Makefile if you don't have time to generate the package for me. Thanks!

**Comment by ryzhovau** [comment]
We do not provide personal support, sorry.

**Comment by zyxmon** [comment]
You can install on your router Entware-3x. It has mips feed. Entware-ng has only mipsel feed.
Entware-3x is here - https://github.com/Entware-for-kernel-3x/Entware-ng-3x
mips repo is here - http://entware-3x.zyxmon.org/binaries/mips/
Instruuctions (Russian, for ARM router) for Entware-3x installation on LEDE is here - http://www.zyxmon.org/2017/08/16/ustanavlivaem-entware-na-ledeopenwrt/
