### ISSUE TITLE
Help installation libcurl-devel

### ISSUE THREAD

**Issue by Jorman** [Entware-ng/Entware-ng#797]
Hi, I know that there's no dev package on Entware but I ask (if possible) if some can help me to compile libcurl-dev on a qnap system x86-64, actually I've Entware-ng on it.

A brief story, the new versions of Jackett need libcurl-dev so I've to compile it, but the very first obstacle is the package, what I need? I search on google libcurl devel x86-64 source but I'm not very sure that I found the right package

Any help on start?

**Comment by zyxmon** [comment]
You do not need dev packages. Please read - https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-(native-compilation)

**Comment by Jorman** [comment]
Sorry but I'm not so able to understand the possibility you link to me. I don't know if you mean this one
https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources or others info.

Is possible any help?
