### ISSUE TITLE
Compiling hardfloat binaries on Synology Diskstation

### ISSUE THREAD

**Issue by gbaderg** [Entware-ng/Entware-ng#803]
### Package: gcc

For existing package: gcc 
Trying to compile "sox" using `export CFLAGS="-O2 -pipe -march=armv7-a -mtune=cortex-a9 -fno-caller-saves -mfloat-abi=hard "`

- expected behavior:   can compile with support for HF hardfloat processing using -mfloat-abi=hard
- actual behavior:  using "hard" throws error message during configure. "soft" and "softfp" for -mfloat-abi run successfully.
configure: error: C compiler cannot create executables ---> See `config.log' for more details:
```
configure:3703: gcc -O2 -pipe -march=armv7-a -mtune=cortex-a9 -fno-caller-saves -mfloat-abi=hard   -Wl,-rpath=/opt/lib -
Wl,--dynamic-linker=/opt/lib/ld-linux.so.3 -L/opt/lib conftest.c  >&5
/opt/bin/ld: error: /opt/tmp/ccwXFvJD.o uses VFP register arguments, a.out does not
/opt/bin/ld: failed to merge target specific data of file /opt/tmp/ccwXFvJD.o
collect2: error: ld returned 1 exit status
```

### Platform:

- please, tell us what feed and\or devices are you using.
armv7l
Synology DS216play | STM STiH412 | Dual Core | 2 | Yes | Monaco | DDR3 1 GB

**Comment by zyxmon** [comment]
Entware is built with softfloat option to be compatible with broadcom arm routers. You need to rebuild and reinstall ALL entware without this option.
