### ISSUE TITLE
Package Request: Emacs 

### ISSUE THREAD

**Issue by fiskhandlarn** [Entware-ng/Entware-ng#805]
### Platform:

- QNAP 4.3.3

Latest version is not important, if that makes anything easier.

**Comment by zyxmon** [comment]
dublicate of https://github.com/Entware-ng/Entware-ng/issues/229

**Comment by fiskhandlarn** [comment]
Sorry for the duplicate. Is this still true for earlier versions than 23.4 mentioned in https://github.com/Entware-ng/Entware-ng/issues/229?
