### ISSUE TITLE
modprobe: module nfsd not found

### ISSUE THREAD

**Issue by lug-gh** [Entware-ng/Entware-ng#807]
### Package: nfs-kernel-server

Hi, i've installed entware-ng on my ddwrt router (netgear r7000)
I wanted to to a nfs share, so i install nfs-kernel-server and utils

I created my shares in /opt/etc/exports but when I do `/opt/etc/init.d/S57nfs-kernel-server start`

I get these errors: 
```
Starting NFS server
modprobe: module nfsd not found
modprobe: failed to load module nfsd: No such file or directory
mount: mounting rpc_pipefs on /opt/var/lib/nfs/rpc_pipefs failed: No such device
mount: mounting nfsd on /proc/fs/nfsd failed: No such device
/opt/etc/init.d/S57nfs-kernel-server: line 78: can't create /proc/fs/nfsd/max_block_size: nonexistent directory
rpc.nfsd: Unable to access /proc/fs/nfsd errno 2 (No such file or directory).
Please try, as root, 'mount -t nfsd nfsd /proc/fs/nfsd' and then restart rpc.nfsd to correct the problem
```

So i tried to do this "fix" but it doesnt work "mount: mounting nfsd on /proc/fs/nfsd failed: No such device"

Edit: `lsmod | grep 'nfs'` is empty

**Comment by zyxmon** [comment]
Does your firware have appropriate kernel modules? You may need to specify full path to *.ko in startup script if it has modules,

**Comment by lug-gh** [comment]
How to I get to know this?
I am not really deep into linux kernel modules etc., especially not custom builds.
Is this something you need to know? https://www.dd-wrt.com/wiki/index.php/NFS

**Comment by zyxmon** [comment]
>> How to I get to know this?

Ask DD-WRT support. Kernel modules should be supplied by firmware builder.
