### ISSUE TITLE
nodejs  Illegal instruction

### ISSUE THREAD

**Issue by mir355** [Entware-ng/Entware-ng#808]
admin@R6300V2-B99D:/tmp/mnt/sda1/tools# opkg install node
Installing node (v6.11.2-3) to root...
Downloading http://pkg.entware.net/binaries/armv7/node_v6.11.2-3_armv7soft.ipk
Installing libopenssl (1.0.2l-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/libopenssl_1.0.2l-1_armv7soft.ipk
Installing zlib (1.2.11-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/zlib_1.2.11-1_armv7soft.ipk
Installing libuv (1.11.0-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/libuv_1.11.0-1_armv7soft.ipk
Configuring zlib.
Configuring libopenssl.
Configuring libuv.
Configuring node.
admin@R6300V2-B99D:/tmp/mnt/sda1/tools# node
Illegal instruction
admin@R6300V2-B99D:/tmp/mnt/sda1/tools# node -v
v6.11.2
admin@R6300V2-B99D:/tmp/mnt/sda1/tools# file /opt/bin/node
/opt/bin/node: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /opt/lib/ld-linux.so.3, for GNU/Linux 2.6.32, stripped
admin@R6300V2-B99D:/tmp/mnt/sda1/tools# ldd node
        libz.so.1 => /opt/lib/libz.so.1 (0x400a2000)
        libcrypto.so.1.0.0 => /opt/lib/libcrypto.so.1.0.0 (0x400fd000)
        libssl.so.1.0.0 => /opt/lib/libssl.so.1.0.0 (0x4022c000)
        libdl.so.2 => /opt/lib/libdl.so.2 (0x40281000)
        librt.so.1 => /opt/lib/librt.so.1 (0x40294000)
        libstdc++.so.6 => /opt/lib/libstdc++.so.6 (0x402ab000)
        libm.so.6 => /opt/lib/libm.so.6 (0x403f1000)
        libgcc_s.so.1 => /opt/lib/libgcc_s.so.1 (0x404a5000)
        libpthread.so.0 => /opt/lib/libpthread.so.0 (0x40045000)
        libc.so.6 => /opt/lib/libc.so.6 (0x404c0000)
        /opt/lib/ld-linux.so.3 (0x400ca000)

**Comment by zyxmon** [comment]
Please uninstall node and install node_legacy. There are two node versions in the armv7 repo - node does not work for broadcom chipset you have.
