### ISSUE TITLE
Package Request : CUPS Filter package

### ISSUE THREAD

**Issue by davigre** [Entware-ng/Entware-ng#81]
Can include CUPS Filters package?

The source code can be download from:

[CUPS Filter Source Code](http://www.openprinting.org/download/cups-filters/)

And the repository are on 

[CUPS Filter Repository](http://bzr.linuxfoundation.org/loggerhead/openprinting/cups-filters/changes)

The reason is to implement pdf -> raster filter in CUPS

Thanks.

**Comment by davigre** [comment]
I found that [CUPS](http://www.openprinting.org/download/cups-filters/) filter for openwrt are on package:

[Printing packages for OpenWrt](https://github.com/FranciscoBorges/openwrt-printing-packages)

I think this will help.

Thank you.

**Comment by futurechild** [comment]
I would also like to request the cups-filter package

**Comment by futurechild** [comment]
I managed to create packages for cups-filters (and dependencies qpdf, libijs, poppler).
The compiled binaries for armv7 and makefiles are included in the zip file.
I'm sure these makefiles could use improvement, but as they work for me (on my rt-ac68u) I am sure someone with more experience will be able to provide said improvement

[entware-ng_cups-filters.zip](https://github.com/Entware-ng/Entware-ng/files/134935/entware-ng_cups-filters.zip)

**Comment by futurechild** [comment]
I seem to have forgotten to include the sbin directory, so a new makefile and binary are made.

I found pdf processing fails when ghostscript/fontconfig is trying to find matching fonts.
I think this has to do with the configuration of fontconfig .
Pdf's without text, .jpg, .txt . ps and .pcl files are printed.

[cups-filters.zip](https://github.com/Entware-ng/Entware-ng/files/138355/cups-filters.zip)

**Comment by ryzhovau** [comment]
Done. Binaries will arrive soon.
