### ISSUE TITLE
Please update mkvtoolnix

### ISSUE THREAD

**Issue by BuSHari** [Entware-ng/Entware-ng#811]
### Package: MKVtoolnix 12.0

Hi,

Can you please update the package mkvtoolnix to the latest version (Version 18.0)?

Thanks,
Idan

**Comment by zyxmon** [comment]
We have updated Entware-3x - https://github.com/Entware-for-kernel-3x/rtndev-3x/blob/master/mkvtoolnix/Makefile
Entware-ng will be updated soon.

**Comment by BuSHari** [comment]
Great! thank you...
