### ISSUE TITLE
rdiff-backup: returns '$version' and not the actual version

### ISSUE THREAD

**Issue by chrisgraf** [Entware-ng/Entware-ng#812]
Package: rdiff-backup
Version: 1.3.3-1
Depends: libc, libssp, librt, libpthread, python, librsync, openssl-util
Status: install user installed
Architecture: x86-64
Installed-Time: 1484847754

- expected behavior: 'rdiff-backup --version' should return the version of the program
- actual behavior: 'rdiff-backup --version' returns '$version'

This is important to fix, because using rdiff-backup remotely compares both versions using the version string. The error msg I get is:
"
Server may work, but there is a version mismatch:
Local version: 1.3.3
Remote version: $version

In general, an attempt is made to guarantee compatibility only between
different minor versions of the same stable series.  For instance, you
should expect 0.12.4 and 0.12.7 to be compatible, but not 0.12.7
and 0.13.3, nor 0.13.2 and 0.13.4.

Warning: Local version 1.3.3 does not match remote version $version.
"

**Comment by zyxmon** [comment]
Fixed via - https://github.com/Entware-for-kernel-3x/entware-oldpackages-ports-3x/commit/0869d1cffcfc71fbfb3841eea27911b0df1be467
Will be fixed in Entware-ng also!
