### ISSUE TITLE
Package request: fatrace

### ISSUE THREAD

**Issue by TomParis01** [Entware-ng/Entware-ng#813]
Package: fatrace
Link: https://launchpad.net/fatrace
License: GNU GPL v3
Latest release: 2016-04-25
My Platform: QNAP TS-251 (Intel x86-64)
Testing: I got the binary running with no problem at all on my TS-251. Can obviously only confirm for my system.
Killer features:

This little tool combines the power of iotop with the knowledge which files are actually accessed. Great tool to find out which process opens / writes / closes which file exactly.

Even greater tool to find out which process prevents the HDD from spinning down and because of which file

**Comment by zyxmon** [comment]
1. I strongly recommend to use Entware-3x, not Entware-ng on your TS-251
2. fatrace was added to Entware-3x and will be soon in binary repo. https://github.com/Entware-for-kernel-3x/rtndev-3x/tree/master/fatrace
3. fatrace requires kernel support. It does not run even on lede router with 4.9 kernel. It runs on qnap. I do not think we will add fatrace to Entware-ng because it is used mainly for routers.

Here is ftrace output from armv7 qnap nas
```
fatrace
sh(13848): O /mnt/ext/opt/bluetooth/usr/sbin/hcitool
hcitool(13848): R /mnt/ext/opt/bluetooth/usr/sbin/hcitool
hcitool(13848): R /mnt/ext/opt/bluetooth/usr/sbin/hcitool
hcitool(13848): O /mnt/ext/opt/bluetooth/usr/lib/libbluetooth.so.3.5.0
hcitool(13848): R /mnt/ext/opt/bluetooth/usr/lib/libbluetooth.so.3.5.0
hcitool(13848): R /mnt/ext/opt/bluetooth/usr/lib/libbluetooth.so.3.5.0
hcitool(13848): R /mnt/ext/opt/bluetooth/usr/lib/libbluetooth.so.3.5.0
hcitool(13848): C /mnt/ext/opt/bluetooth/usr/lib/libbluetooth.so.3.5.0
unknown(13848): C /mnt/ext/opt/bluetooth/usr/sbin/hcitool
sh(13849): O /mnt/ext/opt/bluetooth/usr/sbin/hcitool
sh(13849): R /mnt/ext/opt/bluetooth/usr/sbin/hcitool
hcitool(13849): RO /mnt/ext/opt/bluetooth/usr/lib/libbluetooth.so.3.5.0
hcitool(13849): R /mnt/ext/opt/bluetooth/usr/lib/libbluetooth.so.3.5.0
hcitool(13849): R /mnt/ext/opt/bluetooth/usr/lib/libbluetooth.so.3.5.0
hcitool(13849): C /mnt/ext/opt/bluetooth/usr/lib/libbluetooth.so.3.5.0
unknown(13849): C /mnt/ext/opt/bluetooth/usr/sbin/hcitool
hal_daemon(2651): CO /share/CACHEDEV1_DATA
hal_daemon(2651): CO /share/CACHEDEV1_DATA
hal_daemon(2651): CO /share/CACHEDEV1_DATA
..................
```
