### ISSUE TITLE
rtorrent - very high memory usage after upgrading to 0.9.6

### ISSUE THREAD

**Issue by kevin201** [Entware-ng/Entware-ng#82]
I've just upgraded to 0.9.6/0.13.6 from my original installation of 0.8.6, which has been running faultlessly for the last 4 years. Now when I start up the 1500 odd torrents that I am running, the memory usage goes up to about 600MB. (900MB, 90% total) and uses all the swap file. Before it was around 200MB.

As a consequence, it cannot fork a process to move/link files, and the machine becomes very unstable/slow to respond.

Is there something that I can do to reduce the memory usage, other than reduce the number of torrents?

I have reduced the number of torrents down to 600 temporarily. The memory usage has gone down to ~ 400MB but I am still getting occasional "Event 'event.download.finished' failed: ExecFile::execute(...) Fork failed" errors.

Can I downgrade to 0.9.3/13.3, or even back to 0.8.6/12.6?

Might it be a similar problem to here: https://github.com/rakshasa/rtorrent/issues/191

I'd really appreciate any help - I've been working on this upgrade for some days now, and I don't want to lose the ability to seed that many torrents if I can avoid it.

**Comment by ryzhovau** [comment]
I think it's better to send this issue to @rakshasa. 

> Can I downgrade to 0.9.3/13.3, or even back to 0.8.6/12.6?

[See how](https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources) to compile Entware packages. You may downgrade rtorrent/libtorrent versions at `feeds/packages/net/rtorrent/Makefile` and `feeds/packages/libs/libtorrent/Makefile` accordingly and make your own personal downgraded build. 

Not sure downgraded versions will be suitable for everyone, so there is no reason for me to put them in repo.

**Comment by kevin201** [comment]
Thank you.
