### ISSUE TITLE
util-linux compile error

### ISSUE THREAD

**Issue by earthGavinLee** [Entware-ng/Entware-ng#822]
### Platform: mipsel

/media/gavin/Datapart/OpenWRT/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-5.4.0_uClibc-1.0.17/include/paths.h:61:0: note: this is the location of the previous definition
 #define _PATH_SHELLS "/etc/shells"
 ^
sys-utils/eject.c: In function 'eject_scsi':
sys-utils/eject.c:618:51: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
                                         io_hdr.sbp[12] == 0x3a))
                                                   ^
sys-utils/eject.c:618:51: warning: dereferencing 'void *' pointer
sys-utils/eject.c:618:51: error: void value not ignored as it ought to be
Makefile:9317: recipe for target 'sys-utils/eject-eject.o' failed
make[5]: *** [sys-utils/eject-eject.o] Error 1
make[5]: Leaving directory '/media/gavin/Datapart/OpenWRT/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/util-linux-2.30.1'
Makefile:11721: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/media/gavin/Datapart/OpenWRT/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/util-linux-2.30.1'
Makefile:4906: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/media/gavin/Datapart/OpenWRT/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/util-linux-2.30.1'
Makefile:717: recipe for target '/media/gavin/Datapart/OpenWRT/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/util-linux-2.30.1/.built' failed
make[2]: *** [/media/gavin/Datapart/OpenWRT/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/util-linux-2.30.1/.built] Error 2
make[2]: Leaving directory '/media/gavin/Datapart/OpenWRT/Entware-ng/package/utils/util-linux'
package/Makefile:109: recipe for target 'package/utils/util-linux/compile' failed
make[1]: *** [package/utils/util-linux/compile] Error 2
make[1]: Leaving directory '/media/gavin/Datapart/OpenWRT/Entware-ng'
/media/gavin/Datapart/OpenWRT/Entware-ng/include/toplevel.mk:207: recipe for target 'package/utils/util-linux/compile' failed
make: *** [package/utils/util-linux/compile] Error 2

**Comment by zyxmon** [comment]
We do not have this error when debian 8/x64 is used as a host system. Try to use Debian for building entware.
