### ISSUE TITLE
Is Entware-ng working on MIPS (not MIPSEL) eg. AR7161 (WNDR3700v2)?

### ISSUE THREAD

**Issue by obiwan-bartek** [Entware-ng/Entware-ng#827]
Hi,
Is Entware-ng working on MIPS (not MIPSEL) eg. AR7161 (WNDR3700v2)? I followed the instructions for mipsel but with no luck. I get "opkg: Permission Denied".

**Comment by zyxmon** [comment]
Entware-ng does not have mips feed. It is not working on mips.
Entware-3x has mips feed - https://github.com/Entware-for-kernel-3x
Binary repos are here http://entware-3x.zyxmon.org/binaries/
