### ISSUE TITLE
Package request: gcc for mipsel

### ISSUE THREAD

**Issue by shunjou** [Entware-ng/Entware-ng#828]
### Package: gcc

A request for gcc for mipsel (#138) was made over a year ago but never followed up on. I am submitting a new request since I saw that Entware-ng-3x has gcc in its mipsel repo.

### Platform: mipsel

I am using the built in Entware-ng install on a rt-n56u running latest padavan firmware build. If not possible to add gcc to mipsel feed for Entware-ng, what would be the best recommended method to transition to Entware-ng-3x?

Thanks.

**Comment by zyxmon** [comment]
Just install Entware-3x on your n56u. The installation for Padavan firmware is discriped in Russian here - http://forums.zyxmon.org/viewtopic.php?f=5&t=5399
