### ISSUE TITLE
Request for comment

### ISSUE THREAD

**Issue by decoderman** [Entware-ng/Entware-ng#829]
### Non Entware shell script application: [AB-Solution](https://www.ab-solution.info/) ad-blocker
I would like to use the Entware environment to place AB-Solution into for the benefit of consistent system wide paths.
Additionally, the next version of AB-Solution will use one of the web servers. Moving all AB-Solution files to Entware would make sense, to have it all under one structure. Note that the used web server files are in its default place, this request for comment is only is for AB-Solution files.

### Proposed file/folder structure for AB-Solution within Entware
Config files: /opt/etc/absolution/
Shell scripts: /opt/share/absolution/
Hosts files, white and blacklists: /opt/var/cache/absolution/
Dnsmasq log files: /opt/var/log/dnsmasq.log*
Symlink in /opt/bin to main shell script:
ln -s /opt/share/absolution/ab-solution /opt/bin/ab-solution

Would this be acceptable or should I use a differing structure?

**Comment by zyxmon** [comment]
It looks normal.
