### ISSUE TITLE
Problem compiling new package

### ISSUE THREAD

**Issue by kevin201** [Entware-ng/Entware-ng#83]
Hi,
Followed the instructions, installed OpenWRT, Entware-ng, 

as per:
https://github.com/Entware-ng/Entware-ng/wiki/Compile-packages-from-sources

ran the following successfully:

make tools/install
make toolchain/install
make target/compile

tried to compile rtorrent 

make feeds/packages/net/rtorrent/compile -j1 V=s

and got this:

$ make feeds/packages/net/rtorrent/compile -j1 V=s
make[1]: Entering directory '/home/kevin/Entware-ng'
make[1]: *** No rule to make target 'feeds/packages/net/rtorrent/compile'.  Stop.
make[1]: Leaving directory '/home/kevin/Entware-ng'
/home/kevin/Entware-ng/include/toplevel.mk:184: recipe for target 'feeds/packages/net/rtorrent/compile' failed
make: *** [feeds/packages/net/rtorrent/compile] Error 2

What have I missed out?

**Comment by zyxmon** [comment]
```
make package/rtorrent/compile V=s
```

**Comment by kevin201** [comment]
make[1]: *** No rule to make target 'package/rtorrent/compile'.  Stop.

**Comment by zyxmon** [comment]
Have you installed feeds

```
./scripts update -a
./scripts install -a
```

Run menuconfig and check if rtorrent is present in packages list and selected [*] or [M].

**Comment by kevin201** [comment]
./scripts/feeds update -a
./scripts/feeds install -a

Yes I did, but I ran them in the openwrt directory. Now I've run them in the Enware-ng directory it is compiling. (Doesn't matter now, but don't know how to run menuconfig)

**Comment by zyxmon** [comment]
FYI If you have compiled tollchain with changed uclibc confuguration your packages may be incompatible with the stock Entware-ng installation.
