### ISSUE TITLE
Package-Request: Bubbleupnpserver

### ISSUE THREAD

**Issue by T-Lancer** [Entware-ng/Entware-ng#830]
### Package: BubbleUPnPServer

https://www.bubblesoftapps.com/bubbleupnpserver/

currently already availaible on optware-ng repos.  However optware-ng does not work with my router running DD-WRT.  Or the installation is more complex.  Entware-ng worked out of the box.

### Key features:

stream DLNA services to Chromecast or compatible devices.

### Platform:

ARMv7 soft float and hard float (For TP-Link Archer C9 running ARM Cortex A9)

**Comment by zyxmon** [comment]
This is java application. There is no java 7 or 8 in openwrt now.
