### ISSUE TITLE
Package-Request: openJDK 7

### ISSUE THREAD

**Issue by T-Lancer** [Entware-ng/Entware-ng#831]
Package: openJDK 7

currently already availaible on optware-ng repos. However optware-ng does not work with my router running DD-WRT. Or the installation is more complex. Entware-ng worked out of the box.

Key features:
Run Java applications directly on the used hardware. 

Platform:
ARMv7 soft float and hard float (For TP-Link Archer C9 running ARM Cortex A9)

**Comment by zyxmon** [comment]
Java is very slow on many embedded devices. 
Probably sometimes openwrt will add JDK or entware developers will.
