### ISSUE TITLE
Please update wiki with instructions for using on openwrt/Lede 

### ISSUE THREAD

**Issue by ngoonee** [Entware-ng/Entware-ng#832]
I'm using Lede (currently on a Xiaomi Mi Wifi 3G). Previously was using asuswrt-merlin with entware and very happy with it (both Huawei WS880 routers are still running that).

Was disappointed with the package selection on Lede (no syncthing or rsnapshot) so I managed to get entware's packages using the following steps (e.g. for rsnapshot):-

1. Create /opt (required to install entware)
mkdir /opt

2. Install entware-ng (MIPS version)
wget -O - http://pkg.entware.net/binaries/mipsel/installer/installer.sh | sh

3. Run the install opkg using /opt/bin/opkg
/opt/bin/opkg install rsnapshot

4. Run rsnapshot using /opt/bin/rsnapshot

Could this be updated to the wiki? Also, since Lede is using opkg itself (and in fact as far as I can tell entware-ng is derived from openwrt's work) is there a more direct way than maintaining a separate set of binaries in /opt (for e.g. could users add a feed to /etc/pkg/customfeeds.conf?)

**Comment by zyxmon** [comment]
I think wiki has enough information on installation. I have written a short post (Russian) on using entware with lede - http://www.zyxmon.org/2017/08/16/ustanavlivaem-entware-na-ledeopenwrt/
If someone translates it into English, I can add url to this translation in wiki.
I strongly recommend Entware-3x for modern lede firmwares.

**Comment by ngoonee** [comment]
@zyxmon thanks, the guide looks similar to what I've done except for including /etc/profile. Why Entware-3x though, this is the first I've heard of it.

**Comment by zyxmon** [comment]
Entware-ng is designed to support old devices with kernel 2.6.22. It has some limitations because of old kernel.
Entware-3x is for devices with kernel 3.x. It has more packages and newer versons of some packages.
