### ISSUE TITLE
 FFMPEG https

### ISSUE THREAD

**Issue by hchr** [Entware-ng/Entware-ng#835]
### Package: libffmpeg-full - 3.2.7-3

- expected behavior:
When using youtube-dl it should be able to use https links.

- actual behavior:
youtube-dl https://somelink/at/here
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled

**Comment by zyxmon** [comment]
My guess is - it is an issue with youtube-dl. Try to update it manually. ffmpeg is used to convert downloaded media.
