### ISSUE TITLE
fsck.ext4: error while loading shared libraries: libext2fs.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by jamieburchell** [Entware-ng/Entware-ng#836]
### Package: e2fsprogs

- expected behavior:

fsck.ext4 works

- actual behavior:

fsck.ext4: error while loading shared libraries: libext2fs.so.2: cannot open shared object file

I'm getting this error all of a sudden.

I confirmed with opkg that the mentioned library was already installed.

I removed the library and installed again and fsck.ext4 worked as expected.

However, I've just run in to the same issue again. I'm thinking (but I'm not certain) that a reboot might "break" things but haven't been able to test this. It could also be the result of a new firmware update.

### Platform:

QNAP TS-228 ARM v7

http://pkg.entware.net/binaries/armv7/Packages.html

**Comment by zyxmon** [comment]
This sometimes happens after `opkg update; opkg upgrade` because opkg system is not clever enough. I have published a trick to solve this problem, that reinstalls all libs. I have already given a link to this solution to you.

**Comment by jamieburchell** [comment]
As I already said, I already reinstalled the libext2fs library to fix the issue, but the problem happened again at a later date.

**Comment by zyxmon** [comment]
I have no problems with e2fsprogs in Entware-3x on TS-128 used to check armv7 repo.
 Please install ldd and check dependencies - 

```
/share/CACHEDEV1_DATA/.qpkg/Entware-3x/root # ldd /opt/sbin/fsck.ext4
        libext2fs.so.2 => /opt/lib/libext2fs.so.2 (0xb6f63000)
        libcom_err.so.0 => /opt/lib/libcom_err.so.0 (0xb6f51000)
        libblkid.so.1 => /opt/lib/libblkid.so.1 (0xb6f07000)
        libuuid.so.1 => /opt/lib/libuuid.so.1 (0xb6ef4000)
        libe2p.so.2 => /opt/lib/libe2p.so.2 (0xb6edd000)
        libdl.so.2 => /opt/lib/libdl.so.2 (0xb6eca000)
        libgcc_s.so.1 => /opt/lib/libgcc_s.so.1 (0xb6eaf000)
        libc.so.6 => /opt/lib/libc.so.6 (0xb6d71000)
        /opt/lib/ld-linux.so.3 (0xb6fb3000)
```

This is from Entware-3x. Please also check package versions. Ensure - there is no LD_LIBRARY_PATH and LD_PRELOAD in your environment. Check if there is no other fsch.ext4 on your system that is called. The information you provide is not enouph to reproduce the bug. Please switch to Entware-3x. I do not use Entware-ng on my QNAP devices any more.

**Comment by jamieburchell** [comment]
I have been using Entware-ng for years on my TS-212 (and later TS-228) - it's only the last week or so where I've run in to this issue on 2 separate occasions running fsck.ext4. I have not seen Entware-3x yet, I'll have a look at moving over to it another time.

Apologies for opening the issue in the wrong place originally; I did not see the note. The various opkg/ipkg/optware/entware/entware-ng/entware-3x names confuse me.
