### ISSUE TITLE
Git package missing templates directory

### ISSUE THREAD

**Issue by gmerrall** [Entware-ng/Entware-ng#837]
The git templates  template directory is not populated which causes issues when creating git repositories. Normally when you run "git init --bare" a number of files are copied over including the contents of the 'template' directory which typically contains sample scripts.

Perform the following steps on a regular box with git installed

$ strings `which git` | grep /templates
share/git-core/templates
$ ls /usr/share/git-core/templates/
branches	description	hooks		info
If this is done with a Entware-ng-3x install

$ strings `which git` | grep /templates
/opt/share/git-core/templates
$ ls /opt/share/git-core/templates
<empty directory>
Expected result is the template files should be present

You can also do the same action by running 'git init --bare' and observe different results.

**Comment by zyxmon** [comment]
Please - report upstream.
https://github.com/openwrt/packages
