### ISSUE TITLE
ENTWARE-NG  Asus Gt-Ac5300  Major issue

### ISSUE THREAD

**Issue by stevef9432203** [Entware-ng/Entware-ng#838]
Hi, tried to install Arm7 entware-ng on Asus Gt-Ac5300. As you probably now
ASUS has a /opt directory in the root_fs  so installer is unusable.

Is the /opt prefix path hard coded in the Entware utils or possibly able to change
with an Env Var?

steve_a_foster@yahoo.com

**Comment by zyxmon** [comment]
`/opt` directory is hardcoded in Entware. Merlin added Entware-ng installation script for his firmware.
Please read - https://github.com/Entware-ng/Entware-ng/issues/772
You can create simlinks to install Entware-ng or Entware-3x.
