### ISSUE TITLE
Samba (package request)

### ISSUE THREAD

**Issue by dduck669** [Entware-ng/Entware-ng#839]
Samba 3.5 or 3.6
Is possible to have a full samba implementation (not samba_multicall). I need to join it to an existing domain.
I'm using DDWRT on an Armv7 device (asus rt-ac68u)

Thank you

**Comment by zyxmon** [comment]
We build samba exactly the same way as openwrt/lede. Changing packages leeds to the haos.

**Comment by zyxmon** [comment]
I do not think multicall binary makes the difference. You can install Entware-3x on ac68u. Entware-3x has Samba4x (4.7.3 now) that is built without multicall.

**Comment by zyxmon** [comment]
I am afraid your router does not support Entware-3x. Your kernel is too old....
