### ISSUE TITLE
rTorrent user can't access 'id' program. Some functionality will be unavailable.

### ISSUE THREAD

**Issue by kevin201** [Entware-ng/Entware-ng#84]
A small error that occurs every time the rutorrent page is started.

This line appears in the rtorrent.log:
sh -c /opt/bin/id -u ; /opt/bin/id -G ; echo ~ 

but there is no "--- Success ---" entry following, signifying failure.

When run in the console:
\# sh -c "id -u ; id -g ; echo ~"
0
0
/share/homes/admin

Any pointers would be much appreciated.

**Comment by ryzhovau** [comment]
`opkg install coreutils-id`

**Comment by kevin201** [comment]
When run in the console:
```
# sh -c "id -u ; id -g ; echo ~"
0
0
/share/homes/admin
```
That is to say, it works in the console. Coreutils-id is already installed:

    # opkg list-installed | grep coreutils-id
    coreutils-id - 8.23-2

**Comment by ryzhovau** [comment]
> That is to say, it works in the console.

So, if it works from console and won't works from script, then something wrong with environment. Check `$PATH` for both cases.

**Comment by kevin201** [comment]
I did have a look at share/www/rutorrent/php/settings.php and checked that:

      $id = getExternal('id');
      $req = new rXMLRPCRequest(
      new rXMLRPCCommand("execute_capture",array("sh -c",$id." -u ; ".$id." -g ; echo ~ ")));

was using the right result. I hard code the path to id too. Same problem.

**Comment by ryzhovau** [comment]
Works for me, tried on two different routers.
Closing for now.

**Comment by kevin201** [comment]
I'm using this on an Intel QNAP TS-459Pro+. rtorrent is running using the admin (root) user. I don't know how to fault find any further but I don't know what functionality is being lost anyway so I'll leave this closed.
