### ISSUE TITLE
lftp 4.8.2 segmentation fault

### ISSUE THREAD

**Issue by vicelversa** [Entware-ng/Entware-ng#844]
### Package: lftp - 4.8.2-2

lftp on version 4.8.2 (and possibility 4.8.1) encounters segmentation faults during various operations and cannot complete transfers. Requesting to revert to older version until fix is released.

see:
https://github.com/lavv17/lftp/issues/393
https://github.com/lavv17/lftp/issues/400

### Platform:

x86-64 Packages
QNAP TS-451+
-Firmware ver: 4.3.4.0435

**Comment by zyxmon** [comment]
1. Please report upstream. You can always install old version from archive repo folder
2. I strongly recommend to switch to Entware-3x for your NAS.

BTW There is 4.8.3 release on lftp site. I can make a test package for testing. Please reply here if you will test it.

PS To report bugs upstream use - https://github.com/openwrt/packages

**Comment by vicelversa** [comment]
Thank you for the prompt reply, willing to test 4.8.3 package. Also thanks for the instructions on reporting upstream!

**Comment by zyxmon** [comment]
`opkg install http://pkg.entware.net/binaries/x86-64/test/lftp_4.8.3-1_x86-64.ipk` - to test (x64)
Please report.

**Comment by vicelversa** [comment]
Thank you very much! I just test various operations and no more segmentation faults.  Everything is working as expected on this version.

**Comment by zyxmon** [comment]
Thanks for tests. We are updating lftp in repo before upstream
https://github.com/Entware-ng/entware-packages/commit/253b9a1a8f224e21c2b183045ecf648845617cad
