### ISSUE TITLE
dnsmasq-full 2.78-6 is missing DHCP server functionality (regression)

### ISSUE THREAD

**Issue by petterjohanolsen** [Entware-ng/Entware-ng#845]
### Package: dnsmasq-full 2.78-6

- expected behavior: dnsmasq-full should include DHCP server (2.77-12 works as expected)
- actual behavior: when dnsmasq option "dhcp-range" is specified in /opt/etc/dnsmasq.conf, dnsmasq quits with the following error:

dnsmasq: unsupported option (check that dnsmasq was compiled with DHCP/TFTP/DNSSEC/DBus support) at line xxx of /opt/etc/dnsmasq.conf

### Platform: x86_64 (QNAP 4.3.4, TS-453S Pro)

Package feed: http://pkg.entware.net/binaries/x86-64

**Comment by petterjohanolsen** [comment]
A temporary workaround is to install a previous version:

`opkg install http://pkg.entware.net/binaries/x86-64/archive/dnsmasq-full_2.77-12_x86-64.ipk --force-downgrade`

**Comment by zyxmon** [comment]
1. I strongly recommend to use Entware-3x, not Entware-ng on your NAS.
2. I tried to run dnsmasq on TS-253B with dhcp server enabled, but got `dnsmasq: failed to bind DHCP server socket: Address already in use`, because of dhcp server in firmware.
3. I've tried dnsmasq on an arm NAS running QTS 4,3,4 with dhcp server enabled with no problems.

Please switch to Entware-3x and give more details how to run dnsmasq on your NAS here - https://github.com/Entware-for-kernel-3x/Entware-ng-3x/issues

**Comment by zyxmon** [comment]
We have tested dnsmasq on Entware-ng (mipsel) - it starts without problem. Probably something wrong with x64 build. As for Entware-3x and x64 -
` dnsmasq -v
Dnsmasq version 2.78  Copyright (c) 2000-2017 Simon Kelley
Compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth no-DNSSEC no-ID loop-detect inotify`.
Entware-ng uses toolchain based on 2.6 linux kernels. Some new syscalls are absent. Some new packages fail to compile on Entware-ng or may have runtime problems. The best solution is to switch to Entware-3x. If there is still a bug - it will be easier to solve it for Entware-3x.

**Comment by mackowiakp** [comment]
OK, but it worked in previous version of Entware package. Is it possible do downgrade dnsmasq to previous version?

**Comment by petterjohanolsen** [comment]
Looks like DHCP is not compiled in for the x64 version:
```
[~] # uname -a
Linux qnap 4.2.8 #1 SMP Sat Dec 30 06:25:19 CST 2017 x86_64 GNU/Linux

[~] # dnsmasq -v
Dnsmasq version 2.78  Copyright (c) 2000-2017 Simon Kelley
Compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN no-DHCP no-Lua TFTP conntrack ipset auth no-DNSSEC no-ID loop-detect inotify
```
@mackowiakp: see my previous post for how to manually downgrade. It will be lost after automatic upgrade, though.

**Comment by mackowiakp** [comment]
Yep. I downgrade dnsmasq to the version taken from http://entware.zyxmon.org/binaries/x86-64/archive/ and now it works OK. From my point of view - problem solved

**Comment by zyxmon** [comment]
The issue is fixed in Entware-ng. There was no issue in Entware-3x.
Repo will be reindexed in 10 minutes.
