### ISSUE TITLE
Compiling my own packages

### ISSUE THREAD

**Issue by kevin201** [Entware-ng/Entware-ng#85]
Is there any more help available anywhere for compiling packages? I have set up a ubuntu system on virtualbox, installed openwrt and entware-ng, obtained and installed the feeds and can compile the individual packages as they currently exist.

I'm trying to downgrade rtorrent and libtorrent to previous versions, available from rtorrent.net/downloads. I have changed the Makefiles to (I think) point to the correct location:

    PKG_NAME:=rtorrent
    PKG_VERSION:=0.9.3
    PKG_SOURCE_URL:=http://rtorrent.net/downloads/
    PKG_SOURCE:=rtorrent-0.9.3.tar.gz

    PKG_NAME:=libtorrent
    PKG_VERSION:=0.13.3
    PKG_SOURCE_URL:=http://rtorrent.net/downloads
    PKG_SOURCE:=libtorrent-0.13.3.tar.gz

But running package/rtorrent/compile V=s results in several errors and fails.

````
configure.ac:22: error: possibly undefined macro: AM_PATH_CPPUNIT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
	  
configure: WARNING: unrecognized options: --disable-nls, --disable-instrumentation, --with-zlib

/home/kevin/Entware-ng/build_dir/target-x86_64_glibc-2.22/libtorrent-0.13.3/missing: Unknown `--is-lightweight' option
configure: WARNING: 'missing' script is too old or missing

/home/kevin/Entware-ng/include/toplevel.mk:184: recipe for target 'package/rtorrent/compile' failed
make: *** [package/rtorrent/compile] Error 2
````

Not really sure where to go from here. I'm quite pleased with my progress so far, but would appreciate any assistance, or pointers to more information.

**Comment by ryzhovau** [comment]
You may take old patches for libtorrent/rtorrent from here.

https://dev.openwrt.org/browser/packages/libs/libtorrent/patches?rev=37591

**Comment by kevin201** [comment]
That's useful, thanks. I put in the patches to libtorrent and it was going quite well until:

```
cp -fpR /home/kevin/Entware-ng/build_dir/target-x86_64_glibc-2.22/libtorrent-0.13.3-git/ipkg-install/usr/lib/libtorrent.so.* /home/kevin/Entware-ng/build_dir/target-x86_64_glibc-2.22/libtorrent-0.13.3-git/ipkg-x86-64/libtorrent/usr/lib/
cp: cannot stat '/home/kevin/Entware-ng/build_dir/target-x86_64_glibc-2.22/libtorrent-0.13.3-git/ipkg-install/usr/lib/libtorrent.so.*': No such file or directory
Makefile:71: recipe for target '/home/kevin/Entware-ng/bin/x86-64-glibc/packages/libtorrent_0.13.3-git-6fb96e38f166a1189c1b9af2a6e95bf569a81d4b-1_x86-64.ipk' failed
make[2]: *** [/home/kevin/Entware-ng/bin/x86-64-glibc/packages/libtorrent_0.13.3-git-6fb96e38f166a1189c1b9af2a6e95bf569a81d4b-1_x86-64.ipk] Error 1
make[2]: Leaving directory '/home/kevin/Entware-ng/feeds/packages/libs/libtorrent'
package/Makefile:191: recipe for target 'package/feeds/packages/libtorrent/compile' failed
make[1]: *** [package/feeds/packages/libtorrent/compile] Error 2
make[1]: Leaving directory '/home/kevin/Entware-ng'
/home/kevin/Entware-ng/include/toplevel.mk:184: recipe for target 'package/rtorrent/compile' failed
make: *** [package/rtorrent/compile] Error 2

```

**Comment by ryzhovau** [comment]
`.../ipkg-install/usr/lib/...`

Please replace `/usr` to `/opt` in Makefile.

**Comment by kevin201** [comment]
Yes, many thanks. 

libtorrent appears to work now, but rtorrent Makefile and patches are for 0.8.6, not 0.9.3. Without them I get the "--is-lightweight" error:

    /home/kevin/Entware-ng/build_dir/target-x86_64_glibc-2.22/rtorrent-norpc/rtorrent-0.9.3/missing: Unknown `--is-lightweight' option

and with them I get:
```
Applying ./patches/100-fix-cross_compile.patch using plaintext: 
patching file scripts/common.m4
Hunk #1 FAILED at 184.
Hunk #2 FAILED at 199.
2 out of 2 hunks FAILED -- saving rejects to file scripts/common.m4.rej
Patch failed!  Please fix ./patches/100-fix-cross_compile.patch!
```

**Comment by ryzhovau** [comment]
You may see history for SVN files using links above.
Pick up patches, matching desired rtorrent/libtorrent version.

**Comment by kevin201** [comment]
Yes, I'm sorry for being so stupid, but I'm afraid I couldn't see any other versions there. It's been quite a steep learning curve for me, and I'm obviously not there yet!

**Comment by ryzhovau** [comment]
* libtorrent revisions - https://dev.openwrt.org/log/packages/libs/libtorrent?rev=37591
* rtorrent revisions - https://dev.openwrt.org/log/packages/net/rtorrent?rev=37591

**Comment by kevin201** [comment]
I don't know quite how, but I literally just stumbled across this:

- https://dev.openwrt.org/browser/packages/net/rtorrent?rev=40537#patches

which appears to be what I was looking for. So I'm off to try it now...

**Comment by ryzhovau** [comment]
`rtorrent` and `libtorrent` code always developed together and depended between each other very tightly, so every `rtorrent` version can be compiled with (the one) appropriate `libtorrent` version only. The error above is raised form misfit between rtorrent/libtorrent version. Logging routines was heavily reworked at some moment of developing rtorrent/libtorrent version. 

Please, find out what rtorrent/libtorrent can be compiled together.

**Comment by kevin201** [comment]
Success! It has now compiled. Thank you for steering me down the right track. I now have 28 .ipk files in the bin/x32-64/packages directory.

Last question: What is the command to use to install from a local package?

**Comment by ryzhovau** [comment]
`opkg install ./file.ipk`

**Comment by kevin201** [comment]
Thank you.
