### ISSUE TITLE
Package pixelserv-tls twice listed in available packages

### ISSUE THREAD

**Issue by decoderman** [Entware-ng/Entware-ng#850]
### Package: pixelserv-tls
- expected behavior: For "opkg update" only the latest stable version is expected to be listed.
- actual behavior: Previous and current package is listed:
pixelserv-tls - 2.0.1-1 - pixelserv-tls is a tiny bespoke webserver for adblock with HTTP/1.1 and HTTPS support
pixelserv-tls - V35.HZ12.Kk-1

This double-listing causes the package not to update when running "opkg upgrade" or 
"opkg update && opkg upgrade"

### Workaround: 
"opkg remove pixelserv-tls", then "opkg install pixelserv-tls". This then installs the first listed package, which is pixelserv-tls - 2.0.1-1

### Platform:
- ARM, MIPSEL on Asus wireless routers

### Note:
After "opkg remove pixelserv-tls" then "opkg install pixelserv-tls" and then "opkg update" only the latest version is listed in the available packages.

**Comment by ryzhovau** [comment]
`opkg` package manager consider V35.HZ12.Kk is newer than 2.0.1 and I too:) So, it's up @kvic-z.

**Comment by decoderman** [comment]
That is an unfortunate outcome. Is there a workaround you guys can build in or does @kvic-z have to resubmit with a new version name such as V4.0?

**Comment by zyxmon** [comment]
>> opkg package manager consider V35.HZ12.Kk is newer than 2.0.1 

Probably opkg considers these are different packages. Thу dirty  solution is -
1) open `/opt/lib/opkg/status` file on the router with the text editor and delete "section" with `pixelserv-tls - V35.HZ12.Kk-1`
2) install with `opkg install pixelserv-tls` command

**Comment by decoderman** [comment]
For most users of AB-Solution this is beyond their understanding. I'd have to push an AB-Solution update to automatically do that for them. That would also be a hack and I have to be careful as some run the pixelserv beta version. Anything else you could do on your end?
