### ISSUE TITLE
Apply to add  V2Ray 

### ISSUE THREAD

**Issue by zhneghuaiyu** [Entware-ng/Entware-ng#852]
### Package: <V2Ray >

For new package to be added:
https://github.com/v2ray/v2ray-core
the newest software to break the Great Wall

### Platform:
arm v7  and miples

**Comment by ryzhovau** [comment]
Please, see [this comment](https://github.com/Entware-ng/Entware-ng/issues/736#issuecomment-346318544)ю

**Comment by zhneghuaiyu** [comment]
THERE IS NO LAW ABOUT BAN SITES IN CHINA.  THEY DO WHAT THEY WANT AND NEED WITHOUT LAW.
IN RUSSIA THERE IS LAW FOR BANING SITES , AND EVERY BANED SITE WILL DISPLAY ORDER Court。
IN CHINA IT'S DIFFERENT

**Comment by zyxmon** [comment]
@zhneghuaiyu you can download mipel or arm version of V2Ray from GitHub.
V2Ray is a go program. It is rather heavy for embedded systems.
We have
1. shadowsocks-libev + simple-obfs 
2. shadowsocksR-libev 
in Entware.

**Comment by zhneghuaiyu** [comment]
thank you very much 
i need to delete it so that no trouble for me
