### ISSUE TITLE
wifi wpa-suplicant

### ISSUE THREAD

**Issue by dr04** [Entware-ng/Entware-ng#859]
### Package: <wpa-suplicant>
пожалуста подскажите как в консоли подключиться к сети wifi wpa2
wpa-suplicant пакет у меня не находит
For existing package:
WPA-suplicant
- expected behavior: ...
- actual behavior: ...

For new package to be added:

- make sure there's no similar package already added,
- describe killer features of new package,
- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform:
MIPSEL (DIR-320)
- please, tell us what feed and\or devices are you using.
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by ryzhovau** [comment]
We do not provide personal support, sorry.
