### ISSUE TITLE
 Package request "iptables-persistent"

### ISSUE THREAD

**Issue by LeftPinkie** [Entware-ng/Entware-ng#861]
### Package: iptables-persistent

New package request for iptables-persistent
platform: x86-64
purpose: to make iptables persistent after reboots.

**Comment by zyxmon** [comment]
>> This is a very simple script that restores the file /etc/iptables/rules.v4 as the active ruleset at system boot. 

You can write your own script for your device to restore iptables rules. It is (1) simple, (2) may be firmware specific.
