### ISSUE TITLE
Asking for usb-net-cdc-ether and usb-net-rndis support for MIPSEL

### ISSUE THREAD

**Issue by Maxfive** [Entware-ng/Entware-ng#865]
Hello. Please help to setup 3g support for RNDIS WIFI 3G MODEM.

### Package: kmod-usb-net-rndis and kmod-usb-net-cdc-ether
It is impossible to use RNDIS-based modem as WAN-connection. New cdc-ether device is present but there is no interface for connecting (system shows status: network interface is not active). Probably system does not have driver for such device like kmod-usb-net-rndis or kmod-usb-net-cdc-ether drivers.

### Platform:
Device name: Asus N56U

**Comment by zyxmon** [comment]
There are no kmod packages in Entware. They are device specific.
Entware is a universal repo.
