### ISSUE TITLE
Subversion and QNAP TS-231

### ISSUE THREAD

**Issue by Scotobaza** [Entware-ng/Entware-ng#868]
I apologize if this question is not for you, but QNAP Support couldnt help and sent me to you. I use QNAP NAS TS-231 and I needed Subversion. Everything works, but I cant make it run after reboot. I tried all the possible options that I found, including through qpkg.conf. The script itself, if you run it manually, works

**Comment by zyxmon** [comment]
There is no startup script for subversion server in entware-package. You are to write your own.
It should be placed in /opt/etc/init.d folder and named S..... (filename must start with capital S).

There are a lot of such script examples in Entware.
How do you start subversion manually? 

PS You can ask your questions on qnap forum next time - https://forum.qnap.com/viewforum.php?f=351

**Comment by Scotobaza** [comment]
#!/bin/sh
(sleep 10; svnserve -d -r /share/repo_path ) &

**Comment by zyxmon** [comment]
Try this one (/opt/etc/init.d/S79svnserve)

```
#!/bin/sh

ENABLED=yes
PROCS=svnserve
ARGS="-d -r /share/repo_path"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func


```
Of coarse you need chmod+x this file.
Test it with `/opt/etc/init.d/S79svnserve start`
Reboot to test it is OK.
