### ISSUE TITLE
nginx: [emerg] getgrnam("nobody") failed in /opt/etc/nginx/nginx.conf:2

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware-ng/Entware-ng#870]
### Package: nginx

For existing package:

- expected behavior:
$ /opt/etc/init.d/S80nginx start
Nginx started.
- actual behavior:
$ /opt/etc/init.d/S80nginx start
nginx: [emerg] getgrnam("nobody") failed in /opt/etc/nginx/nginx.conf:2

### Platform:
mipsel

**Comment by ProBackup-nl** [comment]
`getgrnam` is short for "get group name". In short the error tells that the group name "nobody" does not exist.

You can have a look at:
`$ cat /etc/group`
and see that there is no line starting with "`nobody:x:`". That is why this error occurred.

When /etc/group lists a line starting with "`nogroup:x:`", you might wish to start nginx using that group.

Edit the nginx configuration by:
`$ nano /opt/etc/nginx/nginx.conf`
and change the line:

    user  nobody;

to:

    user  nobody nogroup;

**Comment by ProBackup-nl** [comment]
Or create a new `nobody` group?

**Comment by zyxmon** [comment]
Create a new group if you firmware supports it, or use an existing one in config. It is your choise. This is device and firmware specific and is not a part of Entware.
