### ISSUE TITLE
Question: Is there a built-in mechanism to backup my entware-ng configuration and all installed packages?

### ISSUE THREAD

**Issue by rfgamaral** [Entware-ng/Entware-ng#876]
I have installed entware-ng on my Synology NAS but I need to recreate the volumes on all disks and start over. I'm trying to find the best way to backup entware-ng configuration, all installed packages (and their config/data files) so that I can restore everything.

Question: Is there a built-in mechanism to backup/restore mechanism within entware-ng or I'm out of luck? Any other recommendations to make this process any less painful?

**Comment by zyxmon** [comment]
No. Just backup the full /opt folder.
