### ISSUE TITLE
ruby - gem

### ISSUE THREAD

**Issue by stevebovy** [Entware-ng/Entware-ng#877]
### Package: gem

For existing package:

admin-280@RT-AC66U_B1:/tmp/home/root# gem install rake
ERROR:  Loading command: install (LoadError)
        failed to load encoding (Windows-31J)
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

### Platform:

Linux RT-AC66U_B1 2.6.36.4brcmarm #1 SMP PREEMPT Wed Jan 31 17:32:52 CST 2018 armv7l GNU/Linux

**Comment by zyxmon** [comment]
The same was reported upstream - https://github.com/openwrt/packages/issues/3454
Ruby was splitted into 56 packages in openwrt (and in Entware). You may need some of them and probably other packages like ca-certificates.
Run `opkg list ruby*` for ruby packages list.

**Comment by stevebovy** [comment]
Thanks !
