### ISSUE TITLE
mosquitto init.d support

### ISSUE THREAD

**Issue by serhatozkara** [Entware-ng/Entware-ng#881]
### Package: mosquitto-ssl mosquitto-nossl
- expected behavior: mosquitto should be run as a daemon (init.d script badly needed)
- actual behavior: mosquitto doesn't start and when mosquitto command manually issued, gives the output (main conf file /opt/etc/mosquitto.conf file disregarded):
```
1518716364: mosquitto version 1.4.14 starting
1518716364: Using default config.
1518716364: Opening ipv4 listen socket on port 1883.
1518716364: Opening ipv6 listen socket on port 1883.
1518716364: Warning: Address family not supported by protocol
1518716364: Error: Invalid user 'mosquitto'.
```

### Platform:

DD-WRT v3.0-r34929M std running on TP-Link Archer C7 v2

**Comment by zyxmon** [comment]
Please make a PR to add startup script.
We cannot test all packages and add all startup scripts.

**Comment by serhatozkara** [comment]
This is the first time I'm using entware. If I could make an init script for it, i would gladly do so and create a PR :)

**Comment by zyxmon** [comment]
Most of the scripts look like this one - https://github.com/Entware-ng/entware-oldpackages-ports/blob/master/amule/files/S57amuled

**Comment by serhatozkara** [comment]
OK, I've created the S80mosquitto under init.d with the following content:

```
#!/bin/sh

ENABLED=yes
PROCS=mosquitto
ARGS="-c /opt/etc/mosquitto/mosquitto.conf"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
```
mosquitto defaults to running under mosquitto:mosquitto user. Can we change that behaviour with the init script? If yes, i think this startup script is ready to commit. If not, default conf file should be modified to run under root user (not good) or mosquitto:mosquitto user and group should be created when installing mosquitto packages. Thanks for the heads up.

**Comment by zyxmon** [comment]
> mosquitto defaults to running under mosquitto:mosquitto user.

Adding users and groups is firmware dependent. This may be the reason there is no startup script that should be universal.

**Comment by serhatozkara** [comment]
Hmm I didn't know about that. But as all (most?) processes run under root in a router environment, running it as root user shouldn't be a problem. (AFAIK) 
This is the the default conf:
https://github.com/eclipse/mosquitto/blob/master/mosquitto.conf

> # When run as root, drop privileges to this user and its primary 
> # group.
> # Leave blank to stay as root, but this is not recommended.
> # If run as a non-root user, this setting has no effect.
> # Note that on Windows this has no effect and so mosquitto should 
> # be started by the user you wish it to run as.
> #user mosquitto

It should run under root user as default if not defined in conf file otherwise. But it's not running under root user by default and complains about mosquitto user when used in entware. Something is not right definitely.
