### ISSUE TITLE
http://pkg.entware.net/binaries/armv7/libopenssl_1.0.2n-1_armv7soft.ipk

### ISSUE THREAD

**Issue by hdsyl0211** [Entware-ng/Entware-ng#884]
http://pkg.entware.net/binaries/armv7/libopenssl_1.0.2n-1_armv7soft.ipk

update

libopenssl_1.1.0-*_armv7soft.ipk

**Comment by hdsyl0211** [comment]
root@OpenWrt:~# curl -v https://ourbits.club
* ssl_handshake returned - PolarSSL: (-0x7780) SSL - A fatal alert message was r    eceived from our peer
curl: (35) ssl_handshake returned - PolarSSL: (-0x7780) SSL - A fatal alert mess    age was received from our peer

**Comment by zyxmon** [comment]
Cannot confirm

```
# /opt/bin/curl -v https://ourbits.club
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
> GET / HTTP/1.1
> Host: ourbits.club
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 302 Moved Temporarily
< Date: Thu, 22 Feb 2018 13:07:13 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=dd3838c999e4cd77b49a8cec645a5dedb1519304833; expires=Fri, 22-Feb-19 13:07:13 GMT; path=/; domain=.ourbits.club; HttpOnly; Secure
< Location: https://ourbits.club/login.php
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 3f122aca0f012330-FRA
< 

```

**Comment by hdsyl0211** [comment]
3q，I am openwrt cc 15.05




| |
50中学
邮箱：syl0211@126.com
|

签名由 网易邮箱大师 定制

On 02/22/2018 21:09, zyxmon wrote:

Cannot confirm

# /opt/bin/curl -v https://ourbits.club
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
> GET / HTTP/1.1
> Host: ourbits.club
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 302 Moved Temporarily
< Date: Thu, 22 Feb 2018 13:07:13 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=dd3838c999e4cd77b49a8cec645a5dedb1519304833; expires=Fri, 22-Feb-19 13:07:13 GMT; path=/; domain=.ourbits.club; HttpOnly; Secure
< Location: https://ourbits.club/login.php
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 3f122aca0f012330-FRA
<

**Comment by hdsyl0211** [comment]
sorry，I am working hard on my English.   entware  ：
curl -V：lbcurl 7.57  libopenssl 1.0.2n，but I want  libcurl 7.57 libmtbedtls 2.6.0




| |
50中学
邮箱：syl0211@126.com
|

签名由 网易邮箱大师 定制

在2018年02月22日 21:27，hdsyl0211 写道：
3q，I am openwrt cc 15.05




| |
50中学
邮箱：syl0211@126.com
|

签名由 网易邮箱大师 定制

On 02/22/2018 21:09, zyxmon wrote:

Cannot confirm

# /opt/bin/curl -v https://ourbits.club
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
> GET / HTTP/1.1
> Host: ourbits.club
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 302 Moved Temporarily
< Date: Thu, 22 Feb 2018 13:07:13 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=dd3838c999e4cd77b49a8cec645a5dedb1519304833; expires=Fri, 22-Feb-19 13:07:13 GMT; path=/; domain=.ourbits.club; HttpOnly; Secure
< Location: https://ourbits.club/login.php
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 3f122aca0f012330-FRA
<
