### ISSUE TITLE
New Package Request: DNSCrypt Proxy

### ISSUE THREAD

**Issue by elsieholmes** [Entware-ng/Entware-ng#886]
### Package: ![jedisct1/dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy)

For new package to be added:
To replace now abandoned dnscrypt-proxy 1.9.5 that sucks.
This one is open-source, written in Golang and has the following killer features:

- DNS traffic encryption and authentication. Supports DNS-over-HTTPS (DoH) and DNSCrypt.
- DNSSEC compatible
- DNS query monitoring, with separate log files for regular and suspicious queries
- Pattern-based local blocking of DNS names and IP addresses
- Time-based filtering, with a flexible weekly schedule
- Transparent redirection of specific domains to specific resolvers
- DNS caching, to reduce latency and improve privacy
- Local IPv6 blocking to reduce latency on IPv4-only networks
- Load balancing: pick a set of resolvers, dnscrypt-proxy will automatically measure and keep track of their speed, and balance the traffic across the fastest available ones.
- Cloaking: like a HOSTS file on steroids, that can return preconfigured addresses for specific names, or resolve and return the IP address of other names. This can be used for local development as well as to enforce safe search results on Google, Yahoo and Bing.
- Automatic background updates of resolvers lists
- Can force outgoing connections to use TCP; useful with tunnels such as Tor.

### Platform:
RT-AC66U running AsusWRT - Merlin

**Comment by zyxmon** [comment]
Golang binaries are usually too heavy for embedded devices.

**Comment by elsieholmes** [comment]
And you definitely dgaf that entware relies on **external**  storage units with at least 8 GB of capacity...

**Comment by elsieholmes** [comment]
Pathetic

**Comment by Marco-vW** [comment]
Running dnscrypt-proxy v2 since it's early alphas for a few months now on a RT-AC68U without any noticable performance impact. It does reserve quite a large amount of virtual address space but it actually uses (v2.0.2 at the time of writing) around 4Mb of physical memory. So apparently GoLang isn't really memory efficient when it comes to reserving space, but the actual addressed physical memory footprint is wat less then I expected.

**Comment by zyxmon** [comment]
I have compiled dnscrypt-proxy2 for entware-3x. I do те think that binary is different from the official one. It has different size. Probably I'll upload test packages for testing after the new repo is released.
