### ISSUE TITLE
sorry，I am working hard on my English.   entware  ： curl -V：lbcurl 7.57  libopenssl 1.0.2n，but I want  libcurl 7.57 mtbedtls 2.6.0

### ISSUE THREAD

**Issue by hdsyl0211** [Entware-ng/Entware-ng#887]
sorry，I am working hard on my English.   entware  ：
curl -V：lbcurl 7.57  libopenssl 1.0.2n，but I want  libcurl 7.57 mtbedtls 2.6.0

**Comment by zyxmon** [comment]
Please - ask upstream (openwrt).
