### ISSUE TITLE
please update zerotier to new release,thanks

### ISSUE THREAD

**Issue by blackantt** [Entware-ng/Entware-ng#888]
### Package: <name>

For existing package: zerotier

- expected behavior: ...  update
- actual behavior: ...     lowest version now

For new package to be added:

- make sure there's no similar package already added,
- describe killer features of new package,
- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform:

- please, tell us what feed and\or devices are you using.
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by zyxmon** [comment]
Please ask upstream. This version is ported from openwrt - https://github.com/openwrt/packages/blob/master/net/zerotier/Makefile#L9

**Comment by blackantt** [comment]
the link you gave is v1.2.4 , but in entware it is v1.1.14

**Comment by zyxmon** [comment]
zerotier 1.2.4 is ready and will be soon in binary repos. mipsel version will not be upgraded because of https://github.com/Entware-ng/entware-packages/blob/master/net/zerotier/Makefile#L6
