### ISSUE TITLE
Buildroot / Toolchain Compile error

### ISSUE THREAD

**Issue by AkiraNorthstar** [Entware-ng/Entware-ng#89]
Hello!
During build the target toolchain i've got following error:
[entware-ng.txt](https://github.com/Entware-ng/Entware-ng/files/89977/entware-ng.txt)

By the way - Nice work!

Best regrads
Christian

**Comment by zyxmon** [comment]
Try to install libc-dev-bin if you use debian based distro.

**Comment by AkiraNorthstar** [comment]
My distro is fedora 23 x86_64 and i use the openwrt pre requierments list.
[dnf.txt](https://github.com/Entware-ng/Entware-ng/files/90232/dnf.txt)
The glibc-devel packages are installed for both arches (x86_64 and i686).
Any idea to solve this behavior?

**Comment by zyxmon** [comment]
install rpcgen - I do not know where is it in fedora

**Comment by AkiraNorthstar** [comment]
rpcgen is in the glibc-common package, that is also installed by glibc-devel.

ldd /entware-ng.git/staging_dir/toolchain-arm_xscale_gcc-4.8.5_glibc-2.22_eabi/bin/rpcgen returns:
Not dynamicly linked
sh /entware-ng.git/staging_dir/toolchain-arm_xscale_gcc-4.8.5_glibc-2.22_eabi/bin/rpcgen returns:
Cannot execute binary file
file /entware-ng.git/staging_dir/toolchain-arm_xscale_gcc-4.8.5_glibc-2.22_eabi/bin/rpcgen returns:
ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 2.6.32, not stripped

**Comment by zyxmon** [comment]
This is normal. staging_dir/host/bin/rpcgen is build for host architecture.

**Comment by AkiraNorthstar** [comment]
any other idea to solve it?

**Comment by zyxmon** [comment]
give the full log of 

```
make package/dsniff/{clean,compile} V=s
```

upload it to pastebin.com

**Comment by AkiraNorthstar** [comment]
make package/dsniff/clean V=s : http://pastebin.com/sHpS4vZQ
make package/dsniff/compile V=s : http://pastebin.com/u6Kvgrab

**Comment by zyxmon** [comment]
My guess is that your PATH variable setup by openwrt script is different from from the PATH in Debian. May be @ryzhovau will remember some problems with rpcgen we had a year or more ago.
The binary ....staging_dir/toolchain-arm_xscale_gcc-4.8.5_glibc-2.22_eabi/bin/rpcgen should not be called.

**Comment by AkiraNorthstar** [comment]
Ok - i will try!

**Comment by zyxmon** [comment]
Try to modify Makefile for dsniff. Replace

```
PATH="$(TOPDIR)/staging_dir/host/bin:$(TARGET_PATH)" \
```

with

```
export PATH="$(TOPDIR)/staging_dir/host/bin:$(TARGET_PATH)" \
```

If you do not need dsniff - just disable it in menuconfig. AFAIR it is the only package that need this hack with PATH

**Comment by AkiraNorthstar** [comment]
Ok... strange!
dsniff compiles if build with "make -j4" and it doesn't compile with regular "make" (single cpu).
libxml2 doesn't compile with "make -j4" but with "make" (single cpu)
At the moment the build runs and actually libsane compiles.

**Comment by ryzhovau** [comment]
Parallel build (-jx) sometimes causes similar problems. 
Closing for now.
