### ISSUE TITLE
smstools3

### ISSUE THREAD

**Issue by kille72** [Entware-ng/Entware-ng#892]
### Package: <smstools3 3.1.21-1>

3.1.15-3 works great
3.1.21-1 starts but not work

### Platform:
Tomato ARM

**Comment by zyxmon** [comment]
We cannot fix it without more details.
Please give more details. Try to run it with strace and upload output to pastebin....

**Comment by zyxmon** [comment]
One of the possible reasons can be change in sendsms script. The previous version used chown, the last one uses chgrp. Is there chgrp busybox applet in Tomato?
The previous version installed sms2html, sms2unicode, unicode2sms scripts, the last one does not install them. There are also changes in smsd daemon of coarse.

**Comment by pedro0311** [comment]
I'll upload strace log in a moment.

But first problem I see in 3.1.21-1 is:

`# ./smsd
Cannot open config file /etc/smsd.conf for read: No such file or directory`

It should check in /opt/etc/ of course.

The same in strace log: [https://pastebin.com/EyDRRWbg](https://pastebin.com/EyDRRWbg)

**Comment by pedro0311** [comment]
BTW: after copying the config file to /etc, smsd starts normally.

**Comment by zyxmon** [comment]
Fixed via https://github.com/Entware/entware-packages/commit/3cea8ee6957c48fbfcd715fc8c901375f5f2c018

Please run `opkg update; opkg upgrade` two times. This will upgrade you to Entware (merged Entware-ng & Entware-3x) and upgrade smstools to smstools3_3.1.21-1a.
