### ISSUE TITLE
Package request: ewf-tools

### ISSUE THREAD

**Issue by skysbsb** [Entware-ng/Entware-ng#893]
### Package: ewf-tools

For existing package:

- expected behavior: needed package to work with Expert Witness Compression Format (EWF) and make E01 images of USB external devices in my QNAP storage.
- actual behavior: 

For new package to be added:

- make sure there's no similar package already added,

- describe killer features of new package,

 Read or write supported EWF formats:
SMART .s01 (EWF-S01)
EnCase .E01 (EWF-E01) and .Ex01 (EWF2-Ex01)
Read-only supported EWF formats:
Logical Evidence File (LEF) .L01 (EWF-L01) and .Lx01 (EWF2-Lx01)
The libewf package contains the following tools:
ewfacquire, which writes storage media data from devices and files to EWF files.
ewfacquirestream, which writes data from stdin to EWF files.
ewfdebug; experimental tool does nothing at the moment.
ewfexport, which exports storage media data in EWF files to (split) RAW format or a specific version of EWF files.
ewfinfo, which shows the metadata in EWF files.
ewfmount, which FUSE mounts EWF files.
ewfrecover; special variant of ewfexport to create a new set of EWF files from a corrupt set.
ewfverify, which verifies the storage media data in EWF files.
ewfaquirestream-mt, C++ 11 multi-threaded version of ewfacquirestream contributed by Bernhard Zach in 2013.

- make sure it's open source and not abandoned (at least for last 5 years or so),
https://github.com/libyal/libewf/ - last update a month ago

- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform:

- please, tell us what feed and\or devices are you using. 
QNAP STORAGE, model TVS-1271U-RP, x86_64

- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.
Ok

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
