### ISSUE TITLE
Package Request: pciutils

### ISSUE THREAD

**Issue by AkiraNorthstar** [Entware-ng/Entware-ng#90]
Please add pciutils as package binary for arm (armv5) and for other arches as well ;-)
The Recpie always exist under: "feeds/packages/utils/pciutils/".
It was not shipped as binary package in the repository under:
http://pkg.entware.net/binaries/armv5/Packages.html

Best regrads,
Christian

**Comment by zyxmon** [comment]
Added to repos for arm and intel feeds
