### ISSUE TITLE
ca-certificates

### ISSUE THREAD

**Issue by AkiraNorthstar** [Entware-ng/Entware-ng#92]
Please update the current ca-certificate with the newer one:
URL : http://ftp.debian.org/debian/pool/main/c/ca-certificates/ca-certificates_20160104.tar.xz
MD5 : d9665a83d0d3ef8176a38e6aa20458e9
The current (ca-certificates-20151214.tar.xz) cannot be downloaded anymore.

King regards,
Christian

**Comment by ryzhovau** [comment]
`ca-certificates` will be updated in the next months, during sync with [upstream](https://dev.openwrt.org/browser/trunk/package/system/ca-certificates).
