### ISSUE TITLE
build-essentials?

### ISSUE THREAD

**Issue by macmpi** [Entware-ng/Entware-ng#93]
Hi,

Would it be possible to have build-essentials on Entware-ng?
I happen to build stuff right from my ARM NAS, and just migrated to Entware-ng.
Would be easier to get that collection in one install.

Thanks for consideration.

**Comment by zyxmon** [comment]
Just install build tools one by one.
Please read wiki before trying to compile
https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-%28native-compilation%29

The best practice is to crosscompile needed binaries

**Comment by macmpi** [comment]
Thanks for the info.
A bit concerned about the beta state of tools & seemingly more complex environment vs optware/ipkg distribution...
Should I be concerned about moving my older projects to Entware-ng, or should it be no brainer recompile & install? I'm reconsidering getting back to optware.
Thanks for hints & recommendations.

**Comment by zyxmon** [comment]
If you did not use native compilation for your projects and crosscompiled your binaries - there should not be real problems.
If you have used native compilation - just consider using crosscompilation for your projects.
If you still want to use native compilation - just try it in Entware. This week - https://github.com/Entware-ng/Entware-ng/wiki/Changelog#january-2016-first-decade
the following development packages were added - autoconf, automake, m4. pkg-config.

**Comment by ryzhovau** [comment]
Our goal is not become an Optware, so there is not chance to see `build-essentials` here just like in Optware.

**Comment by philippetev** [comment]
If the reason behind the decision not to include such meta-package is (possible) comparison with Optware and not a possible convenience for the collective good, then it really doesn't matter what this project will become. Such meta-package will ease the native toolchain installation for everybody, after all, why would anyone build those packages and even write a tutorial about using then, if he/she has no intention to use them...
