### ISSUE TITLE
Continuing rtorrent/libtorrent memory problems

### ISSUE THREAD

**Issue by kevin201** [Entware-ng/Entware-ng#95]
v 0.9.3/13.3 works, but has the same problem with high memory use as 0.9.6/13.6

Trying now to compile 0.8.6/12.6, both downloaded from rtorrent.net/downloads, but getting this error:

[Error.txt](https://github.com/Entware-ng/Entware-ng/files/92744/Error.txt)

Which ends with:

`#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is``currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options`

As always, any pointers would be much appreciated.

**Comment by ryzhovau** [comment]
Links I provided before includes this versions of libtorrent/rtorrent. Not sure I would do the same job twice:( 

Please, pick appropriate revisions from [OpenWrt SVN](https://dev.openwrt.org/log/packages/libs/libtorrent/Makefile?rev=40536).

**Comment by kevin201** [comment]
Thanks. I thought I had chosen the correct versions of the Makefile and patches. (32303/30734) Having spent well over a week on this problem, it is all proving to be much too much trouble. Regretfully, I suspect I will have to give up on Entware and go back to what worked for me.
