### ISSUE TITLE
Subversion error on QNAP TS 253A -- svn: E170000:Unrecognized URL scheme

### ISSUE THREAD

**Issue by wiesel25** [Entware-ng/Entware-ng#98]
# svn checkout http://www.streamboard.tv/svn/oscam/trunk oscam-svn
svn: E170000: Unrecognized URL scheme for 'http://www.streamboard.tv/svn/oscam/trunk'
# svn --version
svn, version 1.9.3 (r1718519)
   compiled Jan  9 2016, 17:21:16 on x86_64-openwrt-linux-gnu

Copyright (C) 2015 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/

The following repository access (RA) modules are available:

* ra_svn : Module for accessing a repository using the svn network protocol.
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme

The following authentication credential caches are available:

* Plaintext cache in /root/.subversion
* GPG-Agent

[/] #

**Comment by ryzhovau** [comment]
`http(s)` schemes are not supported.

**Comment by zyxmon** [comment]
I have added http & https support to subversion

```
opkg update
opkg upgrade
```
